INTERFACE
SUBROUTINE SURFTSTP    (YSURF, KIDIA , KFDIA , KLON  , KLEVS , KCWS, KTILES,&
 & KLEVSN, KLEVO , KLEVI ,  KSTART , KSTEP,&
 & KDHVTSS , KDHFTSS,&
 & KDHVTTS , KDHFTTS,&
 & KDHVTIS , KDHFTIS,&
 & KDHVSSS , KDHFSSS,&
 & KDHVIIS , KDHFIIS,&
 & KDHVWLS , KDHFWLS,&
 & KDHVBIOS, KDHFBIOS, KDHVVEGS, KDHFVEGS,&                  !CTESSEL
 & KVTYPES, &
 & KTVL , KTVH , KVEG , KSOTY,&
 & PSSDP2, PSSDP3, &
 & PTSPHY , PSDOR , PFRTI,&
 & PSST, PUSTRTI , PVSTRTI,&
 & PAHFSTI, PEVAPTI, PSSRFLTI,PSLRFLTI,&
 & PLAT , PANFMVT , PANDAYVT , PMU0,&                        !CTESSEL
 & PCVT, PLAIVT, PLAIL, PLAIH,&                              !CTESSEL
 & PCIL, &
 & PLAILC,  PLAIHC,&
 & LDLAND, LDSICE,LDLICE, LDSI, LDNH, LDOCN_KPP,&
 & PSNM1M  ,PTSNM1M,PASNM1M,PRSNM1M,PWSNM1M,&
 & PAPRS,  PTSKM1M ,PTSAM1M,PTIAM1M,&
 & PWLM1M  ,PWSAM1M,&
 & PTLICEM1M,PTLMNWM1M,PTLWMLM1M,PTLBOTM1M,PTLSFM1M,& 
 & PHLICEM1M,PHLMLM1M,PGEMU,PLDEPTH,LDLAKE,PCLAKE, &
 & PRSFC   ,PRSFL,& 
 & PSLRFL  ,PSSFC   ,PSSFL,& 
 & PCVL    ,PCVH    ,PCUR    ,PWLMX   ,PEVAPSNW,&
 & PUSRF   ,PVSRF   ,PTSRF,& 
 & PZO     ,PHO     ,PHO_INV ,PDO     ,POCDEPTH ,&
 & PUO0    ,PVO0    ,PUOC    ,PVOC    ,PTO0     ,&
 & PSO0    ,PADVT   ,PADVS   ,PTRI0   ,PTRI1    ,&
 & PSWDK_SAVE, PUSTRC ,PVSTRC,&
 & PUSTOKES,PVSTOKES,PTAUOCX ,PTAUOCY ,PPHIOC   ,&
 & PWSEMEAN,PWSFMEAN  ,&
 & LNEMOICETHK, PTHKICE, &
!-DIAGNOSTICS OUTPUT
 & PTSDFL  , PROFD , PROFS,&
 & PWFSD   , PMELT , PFWEV, PENES,&
 & PDIFM   , PDIFT , PDIFS, POTKE,&
 & PRESPBSTR,PRESPBSTR2,PBIOMASS_LAST,&                      !CTESSEL
 & PBIOMASSTR_LAST,PBIOMASSTR2_LAST,&                        !CTESSEL
 & PBLOSSVT, PBGAINVT, &                                     !CTESSEL
 & PLAI    , PBIOM , PBLOSS, PBGAIN, PBIOMSTR, PBIOMSTR2, &  !CTESSEL
!-TENDENCIES OUTPUT
 & PSNE1   , PTSNE1 , PASNE1,&
 & PRSNE1  , PWSNE1 , PTSAE1 , PTIAE1,&
 & PWLE1   , PWSAE1,&
 & PTLICEE1,PTLMNWE1,PTLWMLE1,&        
 & PTLBOTE1,PTLSFE1,PHLICEE1,PHLMLE1,&  
 & PUOE1   , PVOE1  , PTOE1  ,PSOE1,& 
 & PLAIE1  , PBSTRE1, PBSTR2E1,&                             !CTESSEL 
!-DDH OUTPUTS
 & PDHTSS  , PDHTTS , PDHTIS,&
 & PDHSSS  , PDHIIS , PDHWLS,&
 & PDHBIOS , PDHVEGS)                                        !CTESSEL

USE PARKIND1, ONLY : JPIM, JPRB
USE YOS_SURF, ONLY : TSURF
USE ISO_C_BINDING

! (C) Copyright 1993- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!     ------------------------------------------------------------------
!**** *SURFTSTP* - UPDATES LAND VALUES OF TEMPERATURE, MOISTURE AND SNOW.

!     PURPOSE.
!     --------
!          This routine updates the sea ice values of temperature
!     and the land values of soil temperature, skin soil water,
!     moisture in soil layers (in M scaled to the first reservoir depth),
!     snow mass (in M water equivalent), snow temperature, snow density
!     and snow albedo. For temperature, this is done via a forward time
!     step damped with some implicit linear considerations: as if all
!     fluxes that explicitely depend on the variable had only a linear
!     variation around the t-1 value. For moisture: (a) the evaporation
!     of the interception layer is treated implicitely, via a
!     linearization, while the other sources are treated explicitely;
!     (b) The soil transfer is "fully semi-implicit" similar to vertical
!     diffusion. Lower boundary conditons are no heat flux and free
!     drainage.

!**   INTERFACE.
!     ----------
!          *SURFTSTP* IS CALLED FROM *CALLPAR*.
!          THE ROUTINE TAKES ITS INPUT FROM THE LONG-TERM STORAGE:
!     TSA,WL,WSA,SN AT T-1,TSK,SURFACE FLUXES COMPUTED IN OTHER PARTS OF
!     THE PHYSICS, AND W AND LAND-SEA MASK. IT RETURNS AS AN OUTPUT
!     TENDENCIES TO THE SAME VARIABLES (TSA,WL,WSA,SN).

!     PARAMETER   DESCRIPTION                                    UNITS
!     ---------   -----------                                    -----
!     INPUT PARAMETERS (INTEGER):
!    *KIDIA*      START POINT
!    *KFDIA*      END POINT
!    *KLEV*       NUMBER OF LEVELS
!    *KLON*       NUMBER OF GRID POINTS PER PACKET
!    *KLEVS*      NUMBER OF SOIL LAYERS
!    *KCWS        Number of layers to merge at the end for the soil water profile (for > 4layers)
!    *KTILES*     NUMBER OF TILES (I.E. SUBGRID AREAS WITH DIFFERENT 
!                 SURFACE BOUNDARY CONDITION)
!    *KTVL*       VEGETATION TYPE FOR LOW VEGETATION FRACTION
!    *KTVH*       VEGETATION TYPE FOR HIGH VEGETATION FRACTION
!    *KSOTY*      SOIL TYPE                                   (1-7)
!    *KLEVSN*     Number of snow layers  
!    *KLEVI*      Number of sea ice layers (diagnostics)
!    *KLEVO*      NUMBER OF LAYERS OF OCEAN MIXED LAYER MODEL       
!    *KSTART*     FIRST TIMESTEP                                    
!    *KSTEP*      CURRENT TIMESTEP                                  

!     INPUT PARAMETERS (REAL):
!    *PSICE*      .LT.0.5 FOR LATITUDE ROWS WITH NO SEA ICE POINTS
!    *PEPS*       COEFFICIENT FOR TIME FILTER
!    *PTSPHY*     TIME STEP FOR THE PHYSICS                      S
!    *PSDOR*      OROGRAPHIC PARAMETER                         (m)
!    *PFRTI*      TILE FRACTIONS                              (0-1)
!            1 : WATER                  5 : SNOW ON LOW-VEG+BARE-SOIL
!            2 : ICE                    6 : DRY SNOW-FREE HIGH-VEG
!            3 : WET SKIN               7 : SNOW UNDER HIGH-VEG
!            4 : DRY SNOW-FREE LOW-VEG  8 : BARE SOIL
!    *PCIL*         LAND-ICE FRACTION                          (0-1)
!    *PAHFSTI*    SURFACE SENSIBLE HEAT FLUX, FOR EACH TILE    W/M2
!    *PEVAPTI*    SURFACE MOISTURE FLUX, FOR EACH TILE         KG/M2/S
!    *PSSRFLTI*   NET SHORTWAVE RADIATION FLUX AT SURFACE, FOR
!                 EACH TILE                                    W/M2
!    *PSLRFLTI*   NET LONGWAVE  RADIATION AT THE SURFACE, FOR
!                 EACH TILE                                W/M**2
!    *PUO0*       HORIZONTAL VELOCITY OF OCEAN MIXED LAYER MODEL  
!    *PVO0*       HORIZONTAL VELOCITY OF OCEAN MIXED LAYER MODEL  
!    *PTO0*       TEMPERATURE OF OCEAN MIXED LAYER MODEL          
!    *PSO0*       SALINITY OF OCEAN MIXED LAYER MODEL             
!    *PADVT*      TEMPERATURE ADVECTION TERM FOR OCEAN MIXED LAYER MODEL 
!    *PADVS*      SALINITY ADVECTION TERM FOR OCEAN MIXED LAYER MODEL    
!    *PUSTOKES*   X-COMPONENT STOKES DRIFT
!    *PVSTOKES*   Y-COMPONENT STOKES DRIFT
!    *PTAUOCX*    X-COMPONENT SURFACE MOMENTUM FLUX TO OCEANS
!    *PTAUOCY*    Y-COMPONENT SURFACE MOMENTUM FLUX TO OCEANS
!    *PPHIOC*     ENERGY FLUX INTO OCEAN (DIMENSIONAL)
!    *PWSEMEAN*   WINDSEA VARIANCE
!    *PWSFMEAN*   WINDSEA MEAN FREQUENCY

!     INPUT PARAMETERS (LOGICAL):
!    *LDLAND*     LAND/SEA MASK (TRUE/FALSE)
!    *LDSICE*     SEA ICE MASK (.T. OVER SEA ICE)
!    *LDLICE*     LAND ICE MASK (.T. OVER LAND ICE)
!    *LDLAKE*     LAKE MASK (.T. OVER LAKE)
!    *LDSI*       TRUE IF THERMALLY RESPONSIVE SEA-ICE
!    *LDNH*       TRUE FOR NORTHERN HEMISPHERE LATITUDE ROW
!    *LDOCN_KPP*  TRUE IF OCEAN MIXED LAYER GRID                    
!    *PCLAKE*     REAL LAKE COVER 

!     INPUT PARAMETERS AT T-1 OR CONSTANT IN TIME (REAL):
!    *PSNM1M*     SNOW MASS (per unit area)                      kg/m**2
!    *PWSNM1M*    SNOW LIQUID WATER CONTENT (per unit area)      kg/m**2
!    *PTSAM1M*    SOIL TEMPERATURE                               K
!    *PTIAM1M*    SEA-ICE TEMPERATURE                            K
!          (NB: REPRESENTS THE FRACTION OF ICE ONLY, NOT THE GRID-BOX)
!    *PWLM1M*     SKIN RESERVOIR WATER CONTENT                   kg/m**2
!    *PWSAM1M*    SOIL MOISTURE                                m**3/m**3
!    *PTLICEM1M*  LAKE ICE TEMPERATURE                           K
!    *PTLMNWM1M*  LAKE MEAN WATER TEMPERATURE                    K
!    *PTLWMLM1M*  LAKE MIX-LAYER TEMPERATURE                     K
!    *PTLBOTM1M*  LAKE BOTTOM TEMPERATURE                        K
!    *PTLSFM1M*   LAKE SHAPE FACTOR (THERMOCLINE)                -
!    *PHLICEM1M*  LAKE ICE THICKNESS                             m
!    *PHLMLM1M*   LAKE MIX-LAYER THICKNESS                       m
!    *PGEMU*      SIN OF LATITUDE                                -
!    *PLDEPTH*    LAKE DEPTH                                     m
!    *PRSFC*      CONVECTIVE RAIN FLUX AT THE SURFACE          KG/M**2/S
!    *PRSFL*      LARGE SCALE RAIN FLUX AT THE SURFACE         KG/M**2/S
!    *PSLRFL*     NET LONGWAVE  RADIATION AT THE SURFACE         W/M**2
!    *PSSFC*      CONVECTIVE  SNOW FLUX AT THE SURFACE         KG/M**2/S
!    *PSSFL*      LARGE SCALE SNOW FLUX AT THE SURFACE         KG/M**2/S
!    *PCVL*       LOW VEGETATION COVER  (CORRECTED)              (0-1)
!    *PCVH*       HIGH VEGETATION COVER (CORRECTED)              (0-1)
!    *PCUR*       URBAN COVER (PASSIVE)                          (0-1)
!    *PWLMX*      MAXIMUM SKIN RESERVOIR CAPACITY                kg/m**2
!    *PEVAPSNW*   EVAPORATION FROM SNOW UNDER FOREST           KG/M**2/S
!    *POCDEPTH*     OCEAN DEPTH FOR OCEAN MIXED LAYER MODEL    (m)  
!    *PZO*          VERTICAL LAYER FOR OCEAN MIXED LAYER MODEL (m)  
!    *PDO*          VERTICAL LAYER FOR OCEAN MIXED LAYER MODEL (m)  
!    *PUSRF*      LOWEST LEVEL WIND U COMPONENT                   M/S
!    *PVSRF*      LOWEST LEVEL WIND V COMPONENT                   M/S
!    *PTSRF*      LOWEST LEVEL AIR TEMPERATURE                    K
!    *PAPRS*      LOWEST LEVEL AIR PRESSURE                       Pa
!    *POCDEPTH*     OCEAN DEPTH FOR OCEAN MIXED LAYER MODEL    (m)  
!    *PZO*          VERTICAL LAYER FOR OCEAN MIXED LAYER MODEL (m)  
!    *PDO*          VERTICAL LAYER FOR OCEAN MIXED LAYER MODEL (m)  
!     OUTPUT PARAMETERS (TENDENCIES):
!    *PSNE1*      SNOW MASS (per unit area) TENDENCY           kg/m**2/S
!    *PWSNE1*     SNOW LIQUD WATER CONTENT (per unit area) TENDENCY      kg/m**2/S
!    *PTSNE1*     SNOW TEMPERATURE                              K/S
!    *PASNE1*     SNOW ALBEDO                                   -/S
!    *PRSNE1*     SNOW DENSITY                                KG/M**3/S
!    *PTSAE1*     SOIL TEMPERATURE TENDENCY                     K/S
!    *PTIAE1*     SEA-ICE TEMPERATURE TENDENCY                  K/S
!          (NB: REPRESENTS THE FRACTION OF ICE ONLY, NOT THE GRID-BOX)
!    *PWLE1*      SKIN RESERVOIR WATER CONTENT TENDENCY       kg/m**2/s
!    *PWSAE1*     SOIL MOISTURE TENDENCY                   (m**3/m**3)/S
!    *PTLICEE1*   LAKE ICE TEMPERATURE TENDENCY                 K/S
!    *PTLMNWE1*   LAKE MEAN WATER TEMPERATURE TENDENCY          K/S
!    *PTLWMLE1*   LAKE MIX-LAYER TEMPERATURE TENDENCY           K/S
!    *PTLBOTE1*   LAKE BOTTOM TEMPERATURE TENDENCY              K/S
!    *PTLSFE1*    LAKE SHAPE FACTOR (THERMOCLINE) TENDENCY      -/S
!    *PHLICEE1*   LAKE ICE THICKNESS TENDENCY                   m/S
!    *PHLMLE1*    LAKE MIX-LAYER THICKNESS TENDENCY             m/S
!    *PWSAE1M*    SOIL MOISTURE TENDENCY                   (m**3/m**3)/S
!    *PUOE1*      VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
!    *PVOE1*      VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
!    *PTOE1*      TEMPERATURE TENDENCY OF OCEAN MIXED LAYER MODEL  K/S
!    *PSOE1*      SALINITY TENDENCY OF OCEAN MIXED LAYER MODEL  psu/S

!     OUTPUT PARAMETERS (DIAGNOSTIC):
!    *PTSDFL*     UPWARD FLUX BETWEEN SURFACE AND DEEP LAYER   W/M**2
!    *PROFD*      DEEP LAYER RUN-OFF                          kg/m**2/s
!    *PROFS*      SURFACE RUN-OFF                             kg/m**2/s
!    *PWFSD*      WATER FLUX BETWEEN LAYER 1 AND 2            kg/m**2/s
!    *PMELT*      WATER FLUX CORRESPONDING TO SNOW MELT       kg/m**2/s
!    *PFWEV*      EVAPORATION OVER LAND SURFACE               kg/m**2/s
!    *PENES*      SOIL ENERGY per unit area                   J/M**2
!    *PDHTSS*     Diagnostic array for snow T (see module yomcdh)
!    *PDHTTS*     Diagnostic array for soil T (see module yomcdh)
!    *PDHTIS*     Diagnostic array for ice T (see module yomcdh)
!    *PDHSSS*     Diagnostic array for snow mass (see module yomcdh)
!    *PDHIIS*     Diagnostic array for interception layer (see module yomcdh)
!    *PDHWLS*     Diagnostic array for soil water (see module yomcdh)
!    *PDIFM*      VISCOSITY OF OCEAN MIXED LAYER MODEL                
!    *PDIFT*      TEMPERATURE DIFFUSIVITY OF OCEAN MIXED LAYER MODEL  
!    *PDIFS*      SCALAR DIFFUSIVITY OF OCEAN MIXED LAYER MODEL       
!    *POTKE*      TURBULENT KINETIC ENERGY IN THE OCEAN MIXED LAYER   !OCEAN TKE


!     METHOD.
!     -------
!          STRAIGHTFORWARD ONCE THE DEFINITION OF THE CONSTANTS IS
!     UNDERSTOOD. FOR THIS REFER TO DOCUMENTATION. FOR THE TIME FILTER
!     SEE CORRESPONDING PART OF THE DOCUMENTATION OF THE ADIABATIC CODE.

!     EXTERNALS.
!     ----------
!          *SRFT*   COMPUTES THE TEMPERATURE CHANGES BEFORE THE SNOW
!                   MELTING.
!          *SRFWL*  COMPUTES THE SKIN RESERVOIR CHANGES.
!          *SRFWEXC*COMPUTES THE RUN-OFF AND SETS THE COEFFICIENTS OF
!                   THE TRIDIAGONAL MOISTURE SYSTEM OF EQUATIONS.
!          *SRFWDIF*SOLUTION OF THE TRIDIAGONAL MOISTURE SYSTEM OF EQUATIO
!          *SRFWINC*INCRMENTS OF SOIL MOSITURE, COMPUTATION OF DIAGNOSTICS
!          *SRFSN*  COMPUTES SNOW DEPTH CHANGES BEFORE SNOW MELTING.
!          *SRFSML* COMPUTES TEMPERATURE, SKIN RESERVOIR, SOIL WATER
!                   AND SNOW DEPTH CHANGES DUE TO SNOW MELTING.
!          *SRFWNG* CORRECTIONS TO AVOID NEGATIVE SOIL MOISTURE.

!     REFERENCE.
!     ----------
!          SEE SOIL PROCESSES' PART OF THE MODEL'S DOCUMENTATION FOR
!     DETAILS ABOUT THE MATHEMATICS OF THIS ROUTINE.
!     ------------------------------------------------------------------

!     P.VITERBO       E.C.M.W.F.     16/03/93.
!     MODIFIED BY
!     SURFACE TILES   P.VITERBO/ACMB          8/03/99.
!     Surface DDH for TILES P. Viterbo        17/05/2000.
!     J.F. Estrade *ECMWF* 03-10-01 move in surf vob
!     P. Viterbo   *ECMWF* 04-05-24 New argument PENES; change surface units
!     G. Balsamo   *ECMWF* 06-07-03 Add soil type and orographic var. (runoff)
!     V. Stepanenko        08-01-22 Stress components, sea surface temperature
!                                   are added as arguments
!     E. Dutra/G. Balsamo  08-05-01 Add lake tile
!     E. Dutra/G. Balsamo  08-06-08 Add revised snow
!     Y. Takaya    *ECMWF* 08-10-07 Implement an ocean mixed layer model
!     E. Dutra             09-11-16 snow 2009 cleaning 
!     E. Dutra             10/10/2014      net longwave tiled 
!     I. Ayan-Miguez       June 2023 Add object with spatially distributed parameters

IMPLICIT NONE

! Declaration of arguments

TYPE(TSURF)       ,INTENT(INOUT) :: YDSURF
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSSDP2(:,:)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSSDP3(:,:,:)
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVS
INTEGER(KIND=JPIM),INTENT(IN)    :: KCWS
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTART
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN)    :: KTILES
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVSN
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVI
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVTSS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFTSS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVTTS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFTTS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVTIS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFTIS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVSSS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFSSS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVIIS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFIIS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVWLS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFWLS
!CTESSEL specific
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVBIOS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFBIOS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVVEGS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFVEGS
INTEGER(KIND=JPIM),INTENT(IN)    :: KVTYPES
INTEGER(KIND=JPIM),INTENT(INOUT) :: KVEG(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLAT(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PCVT(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSKM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRS(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PLAIVT(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PLAIL(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PLAIH(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PCIL(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PANFMVT(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PANDAYVT(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PRESPBSTR(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PRESPBSTR2(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PBIOMASS_LAST(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PBIOMASSTR_LAST(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PBIOMASSTR2_LAST(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PBLOSSVT(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PBGAINVT(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PLAIE1(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PBSTRE1(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PBSTR2E1(KLON,KVTYPES)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PLAI(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBIOM(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBLOSS(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBGAIN(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBIOMSTR(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBIOMSTR2(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDHBIOS(KLON,KVTYPES,KDHVBIOS+KDHFBIOS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDHVEGS(KLON,KVTYPES,KDHVVEGS+KDHFVEGS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLAILC(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLAIHC(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMU0(KLON)
 !End CTESSEL specific
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVO
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSPHY
INTEGER(KIND=JPIM),INTENT(IN)    :: KTVL(KLON)
INTEGER(KIND=JPIM),INTENT(IN)    :: KTVH(KLON)
INTEGER(KIND=JPIM),INTENT(IN)    :: KSOTY(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSDOR(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRTI(KLON,KTILES)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PUSTRTI(KLON,KTILES)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVSTRTI(KLON,KTILES)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAHFSTI(KLON,KTILES)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PEVAPTI(KLON,KTILES)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSSRFLTI(KLON,KTILES)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSLRFLTI(KLON,KTILES)
LOGICAL           ,INTENT(IN)    :: LDLAND(KLON)
LOGICAL           ,INTENT(IN)    :: LDSICE(KLON)
LOGICAL           ,INTENT(IN)    :: LDLICE(KLON)
LOGICAL           ,INTENT(IN)    :: LDSI
LOGICAL           ,INTENT(IN)    :: LDNH(KLON)
LOGICAL           ,INTENT(IN)    :: LDLAKE(KLON)
LOGICAL           ,INTENT(IN)    :: LDOCN_KPP(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLAKE(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSNM1M(KLON,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSNM1M(KLON,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PASNM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRSNM1M(KLON,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWSNM1M(KLON,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSAM1M(KLON,KLEVS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTIAM1M(KLON,KLEVS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWLM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWSAM1M(KLON,KLEVS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRSFC(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRSFL(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSLRFL(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSSFC(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSSFL(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCVL(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCVH(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCUR(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWLMX(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PEVAPSNW(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PUSRF(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVSRF(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSRF(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTSDFL(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PROFD(KLON) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PROFS(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PWFSD(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PMELT(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFWEV(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PENES(KLON,KLEVS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSNE1(KLON,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTSNE1(KLON,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PASNE1(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PRSNE1(KLON,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PWSNE1(KLON,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTSAE1(KLON,KLEVS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTIAE1(KLON,KLEVS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PWLE1(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PWSAE1(KLON,KLEVS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDHTSS(KLON,KLEVSN,KDHVTSS+KDHFTSS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDHTTS(KLON,KLEVS,KDHVTTS+KDHFTTS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDHTIS(KLON,KLEVI,KDHVTIS+KDHFTIS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDHSSS(KLON,KLEVSN,KDHVSSS+KDHFSSS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDHIIS(KLON,KDHVIIS+KDHFIIS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PDHWLS(KLON,KLEVS,KDHVWLS+KDHFWLS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSST(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLICEM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLMNWM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLWMLM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLBOTM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLSFM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PHLICEM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PHLMLM1M(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGEMU(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLDEPTH(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLICEE1(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLMNWE1(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLWMLE1(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLBOTE1(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLSFE1(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PHLICEE1(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PHLMLE1(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PZO(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PHO(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PHO_INV(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PDO(KLON,KLEVO)
REAL(KIND=JPRB)   ,INTENT(IN)    :: POCDEPTH(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PADVT(KLON,KLEVO)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PADVS(KLON,KLEVO)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PUO0(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PVO0(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PUOC(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PVOC(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PUSTRC(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PVSTRC(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTO0(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSO0(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PUOE1(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PVOE1(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTOE1(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSOE1(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTRI0(KLON,KLEVO)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTRI1(KLON,KLEVO)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSWDK_SAVE(KLON,KLEVO)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDIFM(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDIFT(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDIFS(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: POTKE(KLON,KLEVO+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PUSTOKES(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVSTOKES(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTAUOCX(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTAUOCY(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PPHIOC(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWSEMEAN(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWSFMEAN(KLON)
LOGICAL           ,INTENT(IN)    :: LNEMOICETHK
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTHKICE(KLON)
!     ------------------------------------------------------------------

END SUBROUTINE SURFTSTP
!
! 
! this space is left for visual comparison to SURFTSTP* and CALLPAR call
! The variables KLEVSN and KDH* are used in the external routine only
! The number of arguments per line is rearranged for readibility
!
!
!
!
!
!
!
!
!
!
!
!
!
END INTERFACE
