!#:set config_file = os.path.dirname(_THIS_FILE_) + '/surface_fields_config.yaml'
!#:set config = field_config.VariableConfiguration(config_file)
!#:set prognostic = [field_config.VariableGroup(**group) for group in config.schema['prognostic']]
!#:set diagnostic = [field_config.VariableGroup(**group) for group in config.schema['diagnostic']]
!#:set variable_groups = prognostic + diagnostic

MODULE ECLAND_SURFACE_TYPE_MOD

USE PARKIND1,                  ONLY : JPIM, JPRB
!USE FIELD_MODULE,              ONLY : FIELD_2RB, FIELD_3RB, FIELD_4RB, FIELD_2IM
!USE FIELD_FACTORY_MODULE,      ONLY : FIELD_NEW, FIELD_DELETE
!USE FIELD_VARIABLES_MOD,       ONLY : FIELD_VARIABLES
!USE FIELD_REGISTRY_MOD,        ONLY : FIELD_REGISTRY
!USE ECLAND_DIMENSION_TYPE_MOD, ONLY : DIMENSION_TYPE
!USE SURFACE_VARIABLES_MOD,     ONLY : SURFACE_VARIABLES
!USE YOMDYN,                    ONLY : TDYN
!USE YOMCTESSELDIM,             ONLY : IKVTYPES, IKDHVVEGS, IKDHFVEGS
! Using global imports here, since fypp notation breaks cmake's dependency analysis
!USE SURFACE_VIEWS_PROGNOSTIC_MODULE
!USE SURFACE_VIEWS_DIAGNOSTIC_MODULE

IMPLICIT NONE

PRIVATE

TYPE, PUBLIC :: SURFACE_PROGNOSTIC 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PHLICE 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PTLICE 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PTL 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PTLSF 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PTLMNW 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PTLWML 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PSST 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PUO0 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PUOC
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PVO0 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PVOC
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTO0 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PSO0 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZWS1 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PTLBOT 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PASN 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTSN 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PWSA 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTSA 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTIA 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PHLML 
END TYPE SURFACE_PROGNOSTIC 

TYPE, PUBLIC :: SURFACE_DIAGNOSTIC
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCLAKE 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PTVL 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PTVH 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PALB 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PSOTY 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCVL 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCVH 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCUR 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PLSM 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCI 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PZO 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PDO 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PHO 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: POCDEPTH 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PHO_INV 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PEVAPTIU 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PLDEPTH 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PU10M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PV10M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PT2M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PD2M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PQ2M
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PALBF 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PALBICEF 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PLAILC 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PLAIHC 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCO2TYP 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: ZALCOEFF 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PADVT
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PADVS
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTRI0 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTRI1 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZAVGPARC 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PTAUOCX,PTAUOCY 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: POTKE
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PSWDK_SAVE 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PSSDP2 
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PSSDP3 
END TYPE SURFACE_DIAGNOSTIC

TYPE, PUBLIC :: SURF_AND_MORE_TYPE
!UCURR,VCURR,PQ2M,PTSN,PWSN,PASN
  ! --------------------------------------
  ! ----  Surface field group views  -----
  ! -- prognostic
!#:for group in prognostic
!  TYPE(SURFACE_VIEW_GROUP_${group.name}$) :: GSP_${group.short}$
!#:endfor
!  ! -- diagnostic
!#:for group in diagnostic
!  TYPE(SURFACE_VIEW_GROUP_${group.name}$) :: GSD_${group.short}$
!#:endfor
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PSP_SL, PSP_RR, PSP_X2, PSD_WS, PSD_VF, PSD_S2, &
!    &                                                     PSD_VN, PSD_V2, PSD_VD, PSD_X2, PSD_WW
!  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PSP_SG, PSP_OM, PSP_SB, PSP_EP, PSD_V3, PSD_XA, PSD_SM, PSD_S3

  ! ------------------------------
  ! ----  Local array views  -----
   TYPE(SURFACE_PROGNOSTIC) :: GSP
   TYPE(SURFACE_DIAGNOSTIC) :: GSD
!  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PEXTRD 
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCOVPTOT => NULL()  !Precip fraction
!  ! T star tiles
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PUSTRTI  ! E-W (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PVSTRTI  ! N-S (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PAHFSTI  ! (INSTANTANEOUS) SURFACE SENSIBLE HEAT FLUX FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PEVAPTI  ! (INSTANTANEOUS) EVAPORATION FOR EACH TILE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTSKTI   ! SKIN TEMPERATURE FOR EACH TILE
!  ! other 
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS ::  ZEMIS !PEMIS      ! MODEL SURFACE LONGWAVE EMISSIVITY.
!  ! GPP/REC flux adjustment coefficients
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCGPP, PCREC ! to store bias correction coefficients
!  !  Tendencies from surface scheme
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PSNSE1   ! OF MULTI-LAYER SNOW MASS PER UNIT SURFACE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PRSNE1   ! OF MULTI-LAYER SNOW DENSITY
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTSNE1   ! OF MULTI-LAYER SNOW TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PWSNE1   ! OF MULTI-LAYER SNOW LIQUID WATER MASS PER UNIT SURFACE
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PASNE1   ! OF SNOW ALBEDO : only the top layer is used
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PWLE1    ! OF SKIN RESERVOIR WATER CONTENT
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PTLE1    ! OF SKIN TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER, CONTIGUOUS :: PLAIE1 
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER, CONTIGUOUS :: PBSTRE1 
   REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER, CONTIGUOUS :: PBSTR2E1 
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTSAE1   ! OF MULTI-LAYER SOIL TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PWSAE1   ! OF MULTI-LAYER SOIL WETNESS
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTIAE1   ! OF MULTI-LAYER SEA ICE TEMPERATURE
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PUOE1    ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PVOE1    ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PTOE1    ! TEMPERATURE TENDENCY OF OCEAN MIXED LAYER MODEL  K/S
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PSOE1    ! SALINITY TENDENCY OF OCEAN MIXED LAYER MODEL  psu/S
   REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PSDOR !PHSTD    ! STANDARD DEVIATION OF SUBGRID OROGRAPHY
  INTEGER(KIND=JPIM), DIMENSION(:,:), POINTER, CONTIGUOUS :: ITVH, ITVL, ICO2TYP, ISOTY ! to store vegetation indices and soil type index
  INTEGER(KIND=JPIM), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: IVEG
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCVL, PCVH, PCUR       ! to store vegetation covers
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZCVL, ZCVH, ZCUR       ! to store vegetation covers
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCIL                   ! to store land-ice fraction
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PPHIOC
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PRESPBSTR,PRESPBSTR2 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PBLOSSVT,PBGAINVT 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PBIOMASS_LAST 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PBIOMASSTR_LAST 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PBIOMASSTR2_LAST 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PRSOIL_STR,PCO2FLUX,PCH4FLUX
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PUSTOKES,PVSTOKES 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PWSEMEAN,PWSFMEAN !PEMEAN,PFMEAN
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PDIFM,PDIFT,PDIFS
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PUSTRC,PVSTRC,PRECO 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PAN,PAG,PRD
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCO2TYP          ! to store co2 photosynthesis type for low vegetation cover
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PLAIL, PLAIH     ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PLAI
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PBIOM,PBLOSS,PBGAIN 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PBIOMSTR,PBIOMSTR2
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLAILP,ZLAIHP !PLAILP, PLAIHP   ! to store variable LAI previous time
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLAIL, ZLAIH     ! to store variable LAI
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZCHAR,ZCHARHQ 
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZTE,ZQE,ZVOM,ZVOL 
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: ZTENC
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZUCURR,ZVCURR
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZAVGPAR !PAVGPAR          ! Average PAR for BVOC emis module
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PISOP_EP         ! Isoprene emission potential
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFWET            ! to store wetland fraction
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PEVAPMU    ! potential evaporation
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: PTLICEE1       ! tendency of lake ice temperature
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: PTLMNWE1       ! tendency of lake totat layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: PTLWMLE1       ! tendency of lake mixed layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: PTLBOTE1       ! tendency of lake bottom layer temperature
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: PTLSFE1        ! tendency of lake shape factor - 
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: PHLICEE1       ! tendency of lake ice depth m
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: PHLMLE1        ! tendency of lake mixed layer depth m/s
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: PSRSOD
  REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: PSRTHD

!  CLASS(FIELD_2RB), POINTER :: F_PEMIS, F_PCGPP, F_PCREC, F_PWLE1, F_PTLE1, F_PHSTD, F_PCVL, F_PCO2TYP, F_PCVH, F_PCUR, F_PCIL, F_PLAIL, &
!   & F_PLAIH, F_PFWET, F_PEVAPMU, F_PTLICEE1, F_PTLMNWE1, F_PTLWMLE1, F_PTLBOTE1, F_PTLSFE1, F_PHLICEE1, F_PHLMLE1, &
!   & F_PLAILP, F_PLAIHP, F_PAVGPAR, F_PISOP_EP
!  CLASS(FIELD_3RB), POINTER :: F_PCOVPTOT, F_PUSTRTI, F_PVSTRTI, F_PAHFSTI, F_PEVAPTI, F_PTSKTI, F_PSNSE1, F_PRSNE1, &
!   & F_PTSNE1, F_PWSNE1, F_PASNE1, F_PTSAE1, F_PWSAE1, F_PTIAE1, F_PUOE1, F_PVOE1, F_PTOE1, F_PSOE1
!  CLASS(FIELD_2IM), POINTER :: F_ITVH, F_ITVL, F_ISOTY, F_ICO2TYP

!CONTAINS
!  PROCEDURE :: INIT => SURF_AND_MORE_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => SURF_AND_MORE_TYPE_UPDATE_VIEW
!  PROCEDURE :: SET9TO0 => SURF_AND_MORE_TYPE_SET9TO0
!  PROCEDURE :: SET1TO9 => SURF_AND_MORE_TYPE_SET1TO9
!  PROCEDURE :: SET1TO0 => SURF_AND_MORE_TYPE_SET1TO0
!  PROCEDURE :: SET0TO1 => SURF_AND_MORE_TYPE_SET0TO1
!  PROCEDURE :: PHTFILT => SURF_AND_MORE_TYPE_PHTFILT
!  PROCEDURE :: FINAL => SURF_AND_MORE_TYPE_FINAL

END TYPE SURF_AND_MORE_TYPE


TYPE, PUBLIC :: SURF_AND_MORE_LOCAL_TYPE
!   ZEXDIAG,CHAR,CHARHQ,PZIDLWV
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER, CONTIGUOUS  :: PLAILI, PLAIHI !ZLAILI, ZLAIHI   ! Arrays for interactive LAI (CITESSEL option)
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER, CONTIGUOUS  :: ZLAIL, ZLAIH
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER, CONTIGUOUS  :: PWL !ZWLM1M
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER, CONTIGUOUS  :: PZIDLWV 
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: PSNS,PRSN !ZSNM1M, ZRSNM1M ! KLON,KLEVSN
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: PTSN,PWSN
!   REAL(KIND=JPRB), DIMENSION(:),    POINTER, CONTIGUOUS  :: ZHSDFOR
!   REAL(KIND=JPRB), DIMENSION(:),    POINTER, CONTIGUOUS  :: ZPCLAKE           ! lake fraction
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER, CONTIGUOUS  :: ZTHKICE!, ZSNTICE  ! sea ice
!   REAL(KIND=JPRB), DIMENSION(:),    POINTER, CONTIGUOUS  :: PCGPP, PCREC ! to store flux adjustment coefficients
    REAL(KIND=JPRB), DIMENSION(:,:),    POINTER, CONTIGUOUS  :: ZWLMX
    REAL(KIND=JPRB), DIMENSION(:,:),  POINTER, CONTIGUOUS  :: ZCSN
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: ZCVT 
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: ZLAIVT 
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: ZKH 
    REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: ZEXDIAG
!   REAL(KIND=JPRB), DIMENSION(:),    POINTER, CONTIGUOUS  :: ZEMIR ! Surface emissivity outside the IR atmospheric window
!   REAL(KIND=JPRB), DIMENSION(:),    POINTER, CONTIGUOUS  :: ZEMIW ! Surface emissivity inside  the IR atmospheric window
   ! Longwave surface spectral emissivity in two or more bands,
   ! dimensioned (KLON,NLWEMISS); note that ZEMIR and ZEMIW point to
   ! the first two columns of this matrix:
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: ZSPECTRALEMISS
     REAL(KIND=JPRB), DIMENSION(:,:),    POINTER, CONTIGUOUS  :: ZEVAPSNW
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: ZFRTI ,ZALBTI ! KLON,KTILES
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: ZFRSOTI
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: PSLRFLTI !ZAHFTRTI
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: ZALBD ,ZALBP ! KLON,NTSW
   !  CTESSEL: Carbon model
     REAL(KIND=JPRB), DIMENSION(:,:,:),  POINTER, CONTIGUOUS  :: PANDAYVT, PANFMVT !ZANDAYVT, ZANFMVT
  !   REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER, CONTIGUOUS  :: ZDHVEGS

!  ! Storage fields to provide thread-local views
!  CLASS(FIELD_2RB), POINTER :: F_ZLAILI, F_ZLAIHI, F_ZWLM1M, F_ZHSDFOR, F_ZPCLAKE, F_ZTHKICE, F_ZSNTICE, F_PCGPP, F_PCREC, &
!   & F_ZWLMX, F_ZEVAPSNW
!  CLASS(FIELD_3RB), POINTER :: F_ZSNM1M, F_ZRSNM1M, F_ZSPECTRALEMISS, F_ZFRTI, F_ZALBTI, F_ZFRSOTI, F_ZAHFTRTI, F_ZALBD, &
!   & F_ZALBP, F_ZANDAYVT, F_ZANFMVT
!  CLASS(FIELD_4RB), POINTER :: F_ZDHVEGS

!CONTAINS
!  PROCEDURE :: INIT => SURF_AND_MORE_LOCAL_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => SURF_AND_MORE_LOCAL_TYPE_UPDATE_VIEW
!  PROCEDURE :: FINAL => SURF_AND_MORE_LOCAL_TYPE_FINAL
END TYPE SURF_AND_MORE_LOCAL_TYPE



TYPE, PUBLIC :: DDH_SURF_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHTLS      ! Diagnostic array for tiles (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHTSS      ! Diagnostic array for snow T (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHTTS      ! Diagnostic array for soil T (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHTIS      ! Diagnostic array for ice T (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHCO2S    
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHBVOCS    
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHBIOS    
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHVEGS    
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHSSS      ! Diagnostic array for snow mass (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER, CONTIGUOUS :: PDHIIS      ! Diagnostic array for interception layer (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: PDHWLS      ! Diagnostic array for soil water (see module yomcdh)
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: PDHFSS

!  ! Storage fields to provide thread-local views
!  CLASS(FIELD_3RB), POINTER :: F_PDHFSS, F_PDHIIS
!  CLASS(FIELD_4RB), POINTER :: F_PDHTLS, F_PDHTSS, F_PDHTTS, F_PDHTIS, F_PDHSSS, F_PDHWLS
!
!CONTAINS
!  PROCEDURE :: INIT => DDH_SURF_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => DDH_SURF_TYPE_UPDATE_VIEW
!  PROCEDURE :: FINAL => DDH_SURF_TYPE_FINAL
END TYPE DDH_SURF_TYPE


!CONTAINS
!
!  SUBROUTINE SURF_AND_MORE_TYPE_INIT(SELF, REGISTRY, VARIABLES, SURFVARS, NLEVS, NLEVSN, NLEVO, PERSISTENT)
!    ! Constructor of the array view type for a surface variable group
!    CLASS(SURF_AND_MORE_TYPE) :: SELF
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    TYPE(FIELD_VARIABLES), INTENT(INOUT) :: VARIABLES
!    TYPE(SURFACE_VARIABLES), TARGET, INTENT(INOUT) :: SURFVARS
!    INTEGER(KIND=JPIM), INTENT(IN) :: NLEVS, NLEVSN, NLEVO
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!
!#:for group in prognostic
!    CALL SELF%GSP_${group.short}$%INIT(SURFVARS%GSP_${group.short}$)
!#:endfor
!#:for group in diagnostic
!    CALL SELF%GSD_${group.short}$%INIT(SURFVARS%GSD_${group.short}$)
!#:endfor
!
!    ! Get references to state fields or create temporaries for local views
!    SELF%F_PUSTRTI => VARIABLES%ECLAND%USTRTI%FT0
!    SELF%F_PVSTRTI => VARIABLES%ECLAND%VSTRTI%FT0
!    SELF%F_PAHFSTI => VARIABLES%ECLAND%AHFSTI%FT0
!    SELF%F_PEVAPTI => VARIABLES%ECLAND%EVAPTI%FT0
!    SELF%F_PTSKTI  => VARIABLES%ECLAND%TSKTI%FT0
!
!    CALL FIELD_NEW (SELF%F_PEMIS   , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PSNSE1  , UBOUNDS=[NPROMA, NLEVSN, NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PASNE1  , UBOUNDS=[NPROMA, NLEVSN, NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PRSNE1  , UBOUNDS=[NPROMA, NLEVSN, NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTSNE1  , UBOUNDS=[NPROMA, NLEVSN, NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PWSNE1  , UBOUNDS=[NPROMA, NLEVSN, NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PWLE1   , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTLE1   , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PHSTD   , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCVL    , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCO2TYP , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCVH    , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCUR    , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCIL    , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PLAIL   , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PLAIH   , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PLAILP  , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PLAIHP  , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PAVGPAR , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PISOP_EP, UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFWET   , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PEVAPMU , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTLICEE1, UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTLMNWE1, UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTLWMLE1, UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTLBOTE1, UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTLSFE1 , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PHLICEE1, UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PHLMLE1 , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTSAE1  , UBOUNDS=[NPROMA, NLEVS,  NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PWSAE1  , UBOUNDS=[NPROMA, NLEVS,  NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTIAE1  , UBOUNDS=[NPROMA, NLEVS,  NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PUOE1   , UBOUNDS=[NPROMA, NLEVO,  NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PVOE1   , UBOUNDS=[NPROMA, NLEVO,  NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTOE1   , UBOUNDS=[NPROMA, NLEVO,  NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PSOE1   , UBOUNDS=[NPROMA, NLEVO,  NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ITVH    , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ITVL    , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ICO2TYP , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ISOTY   , UBOUNDS=[NPROMA,         NGPBLKS],  PERSISTENT=PERSISTENT)
!
!    END ASSOCIATE
!
!  END SUBROUTINE SURF_AND_MORE_TYPE_INIT
!
!  SUBROUTINE SURF_AND_MORE_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    ! Extract local array views from field objects
!    CLASS(SURF_AND_MORE_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!#:for group in prognostic
!    CALL SELF%GSP_${group.short}$%UPDATE_VIEW(BLOCK_INDEX)
!#:endfor
!#:for group in diagnostic
!    CALL SELF%GSD_${group.short}$%UPDATE_VIEW(BLOCK_INDEX)
!#:endfor
!
!    ! Set up local view pointer from storage fields
!     IF(ASSOCIATED(SELF%F_PUSTRTI))  SELF%PUSTRTI => SELF%F_PUSTRTI%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PVSTRTI))  SELF%PVSTRTI => SELF%F_PVSTRTI%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PAHFSTI))  SELF%PAHFSTI => SELF%F_PAHFSTI%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PEVAPTI))  SELF%PEVAPTI => SELF%F_PEVAPTI%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTSKTI))   SELF%PTSKTI => SELF%F_PTSKTI%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PEMIS))    SELF%PEMIS => SELF%F_PEMIS%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PSNSE1))   SELF%PSNSE1 => SELF%F_PSNSE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PASNE1))   SELF%PASNE1 => SELF%F_PASNE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PRSNE1))   SELF%PRSNE1 => SELF%F_PRSNE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTSNE1))   SELF%PTSNE1 => SELF%F_PTSNE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PWSNE1))   SELF%PWSNE1 => SELF%F_PWSNE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PWLE1))    SELF%PWLE1 => SELF%F_PWLE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTLE1))    SELF%PTLE1 => SELF%F_PTLE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PHSTD))    SELF%PHSTD => SELF%F_PHSTD%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PCVL))     SELF%PCVL => SELF%F_PCVL%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PCO2TYP))  SELF%PCO2TYP => SELF%F_PCO2TYP%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PCVH))     SELF%PCVH => SELF%F_PCVH%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PCUR))     SELF%PCUR => SELF%F_PCUR%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PCIL))     SELF%PCIL => SELF%F_PCIL%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PLAIL))    SELF%PLAIL => SELF%F_PLAIL%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PLAIH))    SELF%PLAIH => SELF%F_PLAIH%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PLAILP))   SELF%PLAILP => SELF%F_PLAILP%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PLAIHP))   SELF%PLAIHP => SELF%F_PLAIHP%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PAVGPAR))  SELF%PAVGPAR => SELF%F_PAVGPAR%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PISOP_EP)) SELF%PISOP_EP => SELF%F_PISOP_EP%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PFWET))    SELF%PFWET => SELF%F_PFWET%GET_VIEW(BLOCK_INDEX) 
!     IF(ASSOCIATED(SELF%F_PEVAPMU))  SELF%PEVAPMU => SELF%F_PEVAPMU%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTLICEE1)) SELF%PTLICEE1 => SELF%F_PTLICEE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTLMNWE1)) SELF%PTLMNWE1 => SELF%F_PTLMNWE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTLWMLE1)) SELF%PTLWMLE1 => SELF%F_PTLWMLE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTLBOTE1)) SELF%PTLBOTE1 => SELF%F_PTLBOTE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTLSFE1))  SELF%PTLSFE1 => SELF%F_PTLSFE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PHLICEE1)) SELF%PHLICEE1 => SELF%F_PHLICEE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PHLMLE1))  SELF%PHLMLE1 => SELF%F_PHLMLE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTSAE1))   SELF%PTSAE1 => SELF%F_PTSAE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PWSAE1))   SELF%PWSAE1 => SELF%F_PWSAE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTIAE1))   SELF%PTIAE1 => SELF%F_PTIAE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PUOE1))    SELF%PUOE1 => SELF%F_PUOE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PVOE1))    SELF%PVOE1 => SELF%F_PVOE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PTOE1))    SELF%PTOE1 => SELF%F_PTOE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_PSOE1))    SELF%PSOE1 => SELF%F_PSOE1%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_ITVH))     SELF%ITVH => SELF%F_ITVH%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_ITVL))     SELF%ITVL => SELF%F_ITVL%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_ICO2TYP))  SELF%ICO2TYP => SELF%F_ICO2TYP%GET_VIEW(BLOCK_INDEX)
!     IF(ASSOCIATED(SELF%F_ISOTY))    SELF%ISOTY=> SELF%F_ISOTY%GET_VIEW(BLOCK_INDEX)
!  END SUBROUTINE SURF_AND_MORE_TYPE_UPDATE_VIEW
!
!  SUBROUTINE SURF_AND_MORE_TYPE_SET9TO0(SELF)
!    ! Field update operation for timestepping schemes
!    CLASS(SURF_AND_MORE_TYPE) :: SELF
!
!#:for group in prognostic
!    CALL SELF%GSP_${group.short}$%SET9TO0()
!#:endfor
!  END SUBROUTINE SURF_AND_MORE_TYPE_SET9TO0
!
!  SUBROUTINE SURF_AND_MORE_TYPE_SET1TO9(SELF)
!    ! Field update operation for timestepping schemes
!    CLASS(SURF_AND_MORE_TYPE) :: SELF
!
!#:for group in prognostic
!    CALL SELF%GSP_${group.short}$%SET1TO9()
!#:endfor
!  END SUBROUTINE SURF_AND_MORE_TYPE_SET1TO9
!
!  SUBROUTINE SURF_AND_MORE_TYPE_SET1TO0(SELF)
!    ! Field update operation for timestepping schemes
!    CLASS(SURF_AND_MORE_TYPE) :: SELF
!
!#:for group in prognostic
!    CALL SELF%GSP_${group.short}$%SET1TO0()
!#:endfor
!  END SUBROUTINE SURF_AND_MORE_TYPE_SET1TO0
!
!  SUBROUTINE SURF_AND_MORE_TYPE_SET0TO1(SELF)
!    ! Field update operation for timestepping schemes
!    CLASS(SURF_AND_MORE_TYPE) :: SELF
!
!#:for group in prognostic
!    CALL SELF%GSP_${group.short}$%SET0TO1()
!#:endfor
!  END SUBROUTINE SURF_AND_MORE_TYPE_SET0TO1
!
!  SUBROUTINE SURF_AND_MORE_TYPE_PHTFILT(SELF, YDDYN)
!    ! Field update operation for timestepping schemes
!    CLASS(SURF_AND_MORE_TYPE) :: SELF
!    TYPE(TDYN), INTENT(IN) :: YDDYN
!
!#:for group in prognostic
!    CALL SELF%GSP_${group.short}$%PHTFILT(YDDYN)
!#:endfor
!  END SUBROUTINE SURF_AND_MORE_TYPE_PHTFILT
!
!  SUBROUTINE SURF_AND_MORE_TYPE_FINAL(SELF)
!    ! Finalize underlying field storage
!    CLASS(SURF_AND_MORE_TYPE) :: SELF
!
!    CALL FIELD_DELETE (SELF%F_PEMIS)
!    CALL FIELD_DELETE (SELF%F_PSNSE1)
!    CALL FIELD_DELETE (SELF%F_PASNE1)
!    CALL FIELD_DELETE (SELF%F_PRSNE1)
!    CALL FIELD_DELETE (SELF%F_PTSNE1)
!    CALL FIELD_DELETE (SELF%F_PWSNE1)
!    CALL FIELD_DELETE (SELF%F_PWLE1)
!    CALL FIELD_DELETE (SELF%F_PTLE1)
!    CALL FIELD_DELETE (SELF%F_PHSTD)
!    CALL FIELD_DELETE (SELF%F_PCVL)
!    CALL FIELD_DELETE (SELF%F_PCO2TYP)
!    CALL FIELD_DELETE (SELF%F_PCVH)
!    CALL FIELD_DELETE (SELF%F_PCUR)
!    CALL FIELD_DELETE (SELF%F_PCIL)
!    CALL FIELD_DELETE (SELF%F_PLAIL)
!    CALL FIELD_DELETE (SELF%F_PLAIH)
!    CALL FIELD_DELETE (SELF%F_PLAILP)
!    CALL FIELD_DELETE (SELF%F_PLAIHP)
!    CALL FIELD_DELETE (SELF%F_PAVGPAR)
!    CALL FIELD_DELETE (SELF%F_PISOP_EP)
!    CALL FIELD_DELETE (SELF%F_PFWET)
!    CALL FIELD_DELETE (SELF%F_PEVAPMU)
!    CALL FIELD_DELETE (SELF%F_PTLICEE1)
!    CALL FIELD_DELETE (SELF%F_PTLMNWE1)
!    CALL FIELD_DELETE (SELF%F_PTLWMLE1)
!    CALL FIELD_DELETE (SELF%F_PTLBOTE1)
!    CALL FIELD_DELETE (SELF%F_PTLSFE1)
!    CALL FIELD_DELETE (SELF%F_PHLICEE1)
!    CALL FIELD_DELETE (SELF%F_PHLMLE1)
!    CALL FIELD_DELETE (SELF%F_PTSAE1)
!    CALL FIELD_DELETE (SELF%F_PWSAE1)
!    CALL FIELD_DELETE (SELF%F_PTIAE1)
!    CALL FIELD_DELETE (SELF%F_PUOE1)
!    CALL FIELD_DELETE (SELF%F_PVOE1)
!    CALL FIELD_DELETE (SELF%F_PTOE1)
!    CALL FIELD_DELETE (SELF%F_PSOE1)
!    CALL FIELD_DELETE (SELF%F_ITVH)
!    CALL FIELD_DELETE (SELF%F_ITVL)
!    CALL FIELD_DELETE (SELF%F_ICO2TYP)
!    CALL FIELD_DELETE (SELF%F_ISOTY)
!  END SUBROUTINE SURF_AND_MORE_TYPE_FINAL
!
!
!  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT(SELF, REGISTRY, NLEVSN, NTILES, NTSW, NLWEMISS, PERSISTENT)
!    ! Constructor of the array view type for a surface variable group
!    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    INTEGER(KIND=JPIM), INTENT(IN) :: NLEVSN, NTILES, NTSW, NLWEMISS
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!
!    CALL FIELD_NEW (SELF%F_ZLAILI        , UBOUNDS=[NPROMA,                                NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZLAIHI        , UBOUNDS=[NPROMA,                                NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZSNM1M        , UBOUNDS=[NPROMA, NLEVSN,                        NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZRSNM1M       , UBOUNDS=[NPROMA, NLEVSN,                        NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZWLM1M        , UBOUNDS=[NPROMA,                                NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZHSDFOR       , UBOUNDS=[NPROMA,                                NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZWLMX         , UBOUNDS=[NPROMA,                                NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZSPECTRALEMISS, UBOUNDS=[NPROMA, NLWEMISS,                      NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZEVAPSNW      , UBOUNDS=[NPROMA,                                NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZTHKICE       , UBOUNDS=[NPROMA,                                NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZSNTICE       , UBOUNDS=[NPROMA,                                NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZFRTI         , UBOUNDS=[NPROMA, NTILES,                        NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZALBTI        , UBOUNDS=[NPROMA, NTILES,                        NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZFRSOTI       , UBOUNDS=[NPROMA, NTILES,                        NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZAHFTRTI      , UBOUNDS=[NPROMA, NTILES,                        NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZALBD         , UBOUNDS=[NPROMA, NTSW,                          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZALBP         , UBOUNDS=[NPROMA, NTSW,                          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZANDAYVT      , UBOUNDS=[NPROMA, IKVTYPES,                      NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZANFMVT       , UBOUNDS=[NPROMA, IKVTYPES,                      NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZDHVEGS       , UBOUNDS=[NPROMA, IKVTYPES, IKDHVVEGS+IKDHFVEGS, NGPBLKS], PERSISTENT=PERSISTENT)
!
!    END ASSOCIATE
!
!  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT
!
!  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    ! Extract local array views from field objects
!    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    SELF%ZLAILI => SELF%F_ZLAILI%GET_VIEW(BLOCK_INDEX)
!    SELF%ZLAIHI => SELF%F_ZLAIHI%GET_VIEW(BLOCK_INDEX)
!    SELF%ZSNM1M => SELF%F_ZSNM1M%GET_VIEW(BLOCK_INDEX)
!    SELF%ZRSNM1M => SELF%F_ZRSNM1M%GET_VIEW(BLOCK_INDEX)
!    SELF%ZWLM1M => SELF%F_ZWLM1M%GET_VIEW(BLOCK_INDEX)
!    SELF%ZHSDFOR => SELF%F_ZHSDFOR%GET_VIEW(BLOCK_INDEX)
!    SELF%ZWLMX => SELF%F_ZWLMX%GET_VIEW(BLOCK_INDEX)
!    SELF%ZSPECTRALEMISS => SELF%F_ZSPECTRALEMISS%GET_VIEW(BLOCK_INDEX)
!    SELF%ZEVAPSNW => SELF%F_ZEVAPSNW%GET_VIEW(BLOCK_INDEX)
!    SELF%ZTHKICE => SELF%F_ZTHKICE%GET_VIEW(BLOCK_INDEX)
!    SELF%ZSNTICE => SELF%F_ZSNTICE%GET_VIEW(BLOCK_INDEX)
!    SELF%ZFRTI => SELF%F_ZFRTI%GET_VIEW(BLOCK_INDEX)
!    SELF%ZALBTI => SELF%F_ZALBTI%GET_VIEW(BLOCK_INDEX)
!    SELF%ZFRSOTI => SELF%F_ZFRSOTI%GET_VIEW(BLOCK_INDEX)
!    SELF%ZAHFTRTI => SELF%F_ZAHFTRTI%GET_VIEW(BLOCK_INDEX)
!    SELF%ZALBD => SELF%F_ZALBD%GET_VIEW(BLOCK_INDEX)
!    SELF%ZALBP => SELF%F_ZALBP%GET_VIEW(BLOCK_INDEX)
!    SELF%ZANDAYVT => SELF%F_ZANDAYVT%GET_VIEW(BLOCK_INDEX)
!    SELF%ZANFMVT => SELF%F_ZANFMVT%GET_VIEW(BLOCK_INDEX)
!    SELF%ZDHVEGS => SELF%F_ZDHVEGS%GET_VIEW(BLOCK_INDEX)
!  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_UPDATE_VIEW
!
!  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL(SELF)
!    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
!
!    CALL FIELD_DELETE (SELF%F_ZLAILI)
!    CALL FIELD_DELETE (SELF%F_ZLAIHI)
!    CALL FIELD_DELETE (SELF%F_ZSNM1M)
!    CALL FIELD_DELETE (SELF%F_ZRSNM1M)
!    CALL FIELD_DELETE (SELF%F_ZWLM1M)
!    CALL FIELD_DELETE (SELF%F_ZHSDFOR)
!    CALL FIELD_DELETE (SELF%F_ZWLMX)
!    CALL FIELD_DELETE (SELF%F_ZSPECTRALEMISS)
!    CALL FIELD_DELETE (SELF%F_ZEVAPSNW)
!    CALL FIELD_DELETE (SELF%F_ZTHKICE)
!    CALL FIELD_DELETE (SELF%F_ZSNTICE)
!    CALL FIELD_DELETE (SELF%F_ZFRTI)
!    CALL FIELD_DELETE (SELF%F_ZALBTI)
!    CALL FIELD_DELETE (SELF%F_ZFRSOTI)
!    CALL FIELD_DELETE (SELF%F_ZAHFTRTI)
!    CALL FIELD_DELETE (SELF%F_ZALBD)
!    CALL FIELD_DELETE (SELF%F_ZALBP)
!    CALL FIELD_DELETE (SELF%F_ZANDAYVT)
!    CALL FIELD_DELETE (SELF%F_ZANFMVT)
!    CALL FIELD_DELETE (SELF%F_ZDHVEGS)
!  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL
!
!
!  SUBROUTINE DDH_SURF_TYPE_INIT(SELF, REGISTRY, DIMS, PERSISTENT)
!    ! Constructor of the array view type for a surface variable group
!    CLASS(DDH_SURF_TYPE) :: SELF
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    TYPE(DIMENSION_TYPE), INTENT(IN) :: DIMS
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!
!    CALL FIELD_NEW (SELF%F_PDHTLS, UBOUNDS=[NPROMA, DIMS%KTILES,               DIMS%KDHVTLS+DIMS%KDHFTLS, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDHTSS, UBOUNDS=[NPROMA, DIMS%KLEVSN,               DIMS%KDHVTSS+DIMS%KDHFTSS, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDHTTS, UBOUNDS=[NPROMA, DIMS%KLEVS,                DIMS%KDHVTTS+DIMS%KDHFTTS, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDHTIS, UBOUNDS=[NPROMA, DIMS%KLEVI,                DIMS%KDHVTIS+DIMS%KDHFTIS, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDHSSS, UBOUNDS=[NPROMA, DIMS%KLEVSN,               DIMS%KDHVSSS+DIMS%KDHFSSS, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDHIIS, UBOUNDS=[NPROMA, DIMS%KDHVIIS+DIMS%KDHFIIS                           , NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDHWLS, UBOUNDS=[NPROMA, DIMS%KLEVS,                DIMS%KDHVWLS+DIMS%KDHFWLS, NGPBLKS], PERSISTENT=PERSISTENT)
!
!    END ASSOCIATE
!
!  END SUBROUTINE DDH_SURF_TYPE_INIT
!
!  SUBROUTINE DDH_SURF_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    ! Extract local array views from field objects
!    CLASS(DDH_SURF_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    SELF%PDHTLS => SELF%F_PDHTLS%GET_VIEW(BLOCK_INDEX)
!    SELF%PDHTSS => SELF%F_PDHTSS%GET_VIEW(BLOCK_INDEX)
!    SELF%PDHTTS => SELF%F_PDHTTS%GET_VIEW(BLOCK_INDEX)
!    SELF%PDHTIS => SELF%F_PDHTIS%GET_VIEW(BLOCK_INDEX)
!    SELF%PDHSSS => SELF%F_PDHSSS%GET_VIEW(BLOCK_INDEX)
!    SELF%PDHIIS => SELF%F_PDHIIS%GET_VIEW(BLOCK_INDEX)
!    SELF%PDHWLS => SELF%F_PDHWLS%GET_VIEW(BLOCK_INDEX)
!  END SUBROUTINE DDH_SURF_TYPE_UPDATE_VIEW
!
!  SUBROUTINE DDH_SURF_TYPE_FINAL(SELF)
!    CLASS(DDH_SURF_TYPE) :: SELF
!
!    CALL FIELD_DELETE (SELF%F_PDHTLS)
!    CALL FIELD_DELETE (SELF%F_PDHTSS)
!    CALL FIELD_DELETE (SELF%F_PDHTTS)
!    CALL FIELD_DELETE (SELF%F_PDHTIS)
!    CALL FIELD_DELETE (SELF%F_PDHSSS)
!    CALL FIELD_DELETE (SELF%F_PDHIIS)
!    CALL FIELD_DELETE (SELF%F_PDHWLS)
!  END SUBROUTINE DDH_SURF_TYPE_FINAL
!
END MODULE ECLAND_SURFACE_TYPE_MOD
