MODULE ECLAND_AUX_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
!USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB, FIELD_2LM
!USE FIELD_FACTORY_MODULE
!USE FIELD_REGISTRY_MOD, ONLY: FIELD_REGISTRY
!USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES

IMPLICIT NONE

TYPE AUX_TYPE
  INTEGER(KIND=JPIM) :: NLEV  ! Number of vertical levels

!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PAPHI,PAPHIF ! half and full level geopotential
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PGEOM1 !,PGEOMH ! half and full level distance from surface (in gpm)
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PAPRS !,PAPRSF ! half and full level pressure
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDELP        ! layer thickness  (in pressure units)
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PRS1,PRSF1   ! provisional t+dt pressure on half and full levels
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDELP1       ! provisional t+dt layer thickness  (in pressure units)
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PVERVEL      ! diagnostic vertical velocity
  !  geometry
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS   :: GELAT, GELAM ! PLAT ! PGELAM, PGELAT  ! LONGITUDE, LATITUDE (RADIANS)
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS   :: PGAW         ! GAUSSIAN WEIGHTS - Reduced Grid - ~ grid box area
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS   :: PCLON, PSLON ! cosine, sine of longitude
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS   ::PMU0M ! PMU0, PMU0M, PMU0T  ! local cosine of instantaneous (mean) solar zenith angle
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS   :: PGEMU        ! sine of latitude 
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS   :: POROG        ! orography
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS   :: PGNORDL,PGNORDM ! Longitudial/latitudial derivatives of orography
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS   :: PGSQM2

!  ! Storage fields to provide thread-local views
!  CLASS (FIELD_2RB), POINTER :: F_PGELAM, F_PGELAT, F_PGAW, F_PCLON, F_PSLON, F_PMU0, F_PMU0M, F_PMU0T, F_PGEMU, F_POROG, &
!   & F_PGNORDL, F_PGNORDM, F_PGSQM2
!  CLASS (FIELD_3RB), POINTER :: F_PAPHI, F_PAPHIF, F_PGEOM1, F_PGEOMH, F_PAPRS, F_PAPRSF, F_PDELP, F_PRS1, F_PRSF1, F_PVERVEL
!
!CONTAINS
!  PROCEDURE :: INIT => AUX_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => AUX_TYPE_UPDATE_VIEW
!  PROCEDURE :: FINAL => AUX_TYPE_FINAL
END TYPE AUX_TYPE
!
!
TYPE KEYS_LOCAL_TYPE
  LOGICAL, DIMENSION(:,:), POINTER, CONTIGUOUS  :: LLLAND, LLSICE,LLLICE, LLNH, LLCUM, LLSC, LLSHCV, LLCUM_LIG
  LOGICAL, DIMENSION(:,:), POINTER, CONTIGUOUS  :: LLLAKE, LLOCN_KPP
  LOGICAL ::  LLSLPHY      !  key keeping the active state of LSPLHY
  LOGICAL ::  LLRAIN1D     !  key reserved for 1D var rain
  LOGICAL ::  LL_DIAGCLOUDAER !  key determining cloud and aerosols diagnostic is on/off
  LOGICAL, POINTER ::  LLCLDCOVER     !  key deciding to compute/not compute the cloud cover
  LOGICAL, POINTER ::  LLMAINCALL     !  key controlling the complexity of cloudsc scheme
!
!  ! Storage fields to provide thread-local views
!  CLASS (FIELD_2LM), POINTER :: F_LLLAND, F_LLSICE, F_LLLICE, F_LLNH, F_LLCUM, F_LLSC, F_LLSHCV, F_LLLAKE, F_LLOCN_KPP, F_LLCUM_LIG
!
!CONTAINS
!  PROCEDURE :: INIT => KEYS_LOCAL_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => KEYS_LOCAL_TYPE_UPDATE_VIEW
!  PROCEDURE :: FINAL => KEYS_LOCAL_TYPE_FINAL
END TYPE KEYS_LOCAL_TYPE
!
!
!CONTAINS
!
!  SUBROUTINE AUX_TYPE_INIT(SELF, REGISTRY, VARIABLES, NLEV, PERSISTENT)
!    CLASS(AUX_TYPE) :: SELF
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    TYPE(FIELD_VARIABLES), INTENT(INOUT) :: VARIABLES
!    INTEGER(KIND=JPIM), INTENT(IN) :: NLEV
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    SELF%F_PGELAM  => VARIABLES%GEOMETRY%GELAM%FT0
!    SELF%F_PGELAT  => VARIABLES%GEOMETRY%GELAT%FT0
!    SELF%F_PGAW    => VARIABLES%GEOMETRY%GAW%FT0
!    SELF%F_PCLON   => VARIABLES%GEOMETRY%GECLO%FT0
!    SELF%F_PSLON   => VARIABLES%GEOMETRY%GESLO%FT0
!    SELF%F_PGEMU   => VARIABLES%GEOMETRY%GEMU%FT0
!    SELF%F_POROG   => VARIABLES%GEOMETRY%OROG%FT0
!    SELF%F_PGNORDL => VARIABLES%GEOMETRY%GNORDL%FT0
!    SELF%F_PGNORDM => VARIABLES%GEOMETRY%GNORDM%FT0
!    SELF%F_PGSQM2  => VARIABLES%GEOMETRY%GSQM2%FT0
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!    CALL FIELD_NEW (SELF%F_PMU0   , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PMU0M  , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PMU0T  , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PAPHI  , UBOUNDS=[NPROMA, NLEV+1, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PAPRS  , UBOUNDS=[NPROMA, NLEV+1, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PGEOMH , UBOUNDS=[NPROMA, NLEV+1, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PRS1   , UBOUNDS=[NPROMA, NLEV+1, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PAPHIF , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PAPRSF , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PGEOM1 , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PRSF1  , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    END ASSOCIATE
!  END SUBROUTINE AUX_TYPE_INIT
!
!  SUBROUTINE AUX_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    CLASS(AUX_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    IF(ASSOCIATED(SELF%F_PGELAM))  SELF%PGELAM => SELF%F_PGELAM%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PGELAT))  SELF%PGELAT => SELF%F_PGELAT%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PGAW))    SELF%PGAW => SELF%F_PGAW%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PCLON))   SELF%PCLON => SELF%F_PCLON%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PSLON))   SELF%PSLON => SELF%F_PSLON%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PGEMU))   SELF%PGEMU => SELF%F_PGEMU%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_POROG))   SELF%POROG => SELF%F_POROG%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PGNORDL)) SELF%PGNORDL => SELF%F_PGNORDL%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PGNORDM)) SELF%PGNORDM => SELF%F_PGNORDM%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PGSQM2))  SELF%PGSQM2 => SELF%F_PGSQM2%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PMU0))    SELF%PMU0 => SELF%F_PMU0%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PMU0M))   SELF%PMU0M => SELF%F_PMU0M%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PMU0T))   SELF%PMU0T => SELF%F_PMU0T%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PAPHI))   SELF%PAPHI(1:,0:) => SELF%F_PAPHI%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PAPRS))   SELF%PAPRS(1:,0:) => SELF%F_PAPRS%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PGEOMH))  SELF%PGEOMH(1:,0:) => SELF%F_PGEOMH%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PRS1))    SELF%PRS1(1:,0:) => SELF%F_PRS1%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PAPHIF))  SELF%PAPHIF => SELF%F_PAPHIF%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PAPRSF))  SELF%PAPRSF => SELF%F_PAPRSF%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PGEOM1))  SELF%PGEOM1 => SELF%F_PGEOM1%GET_VIEW(BLOCK_INDEX)
!    IF(ASSOCIATED(SELF%F_PRSF1))   SELF%PRSF1 => SELF%F_PRSF1%GET_VIEW(BLOCK_INDEX)
!  END SUBROUTINE AUX_TYPE_UPDATE_VIEW
!
!  SUBROUTINE AUX_TYPE_FINAL(SELF)
!    CLASS(AUX_TYPE) :: SELF
!
!    CALL FIELD_DELETE (SELF%F_PMU0)
!    CALL FIELD_DELETE (SELF%F_PMU0M)
!    CALL FIELD_DELETE (SELF%F_PMU0T)
!    CALL FIELD_DELETE (SELF%F_PAPHI)
!    CALL FIELD_DELETE (SELF%F_PAPRS)
!    CALL FIELD_DELETE (SELF%F_PGEOMH)
!    CALL FIELD_DELETE (SELF%F_PRS1)
!    CALL FIELD_DELETE (SELF%F_PAPHIF)
!    CALL FIELD_DELETE (SELF%F_PAPRSF)
!    CALL FIELD_DELETE (SELF%F_PGEOM1)
!    CALL FIELD_DELETE (SELF%F_PRSF1)
!  END SUBROUTINE AUX_TYPE_FINAL
!
!
!  SUBROUTINE KEYS_LOCAL_TYPE_INIT(SELF, REGISTRY, PERSISTENT)
!    CLASS(KEYS_LOCAL_TYPE) :: SELF
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!    CALL FIELD_NEW (SELF%F_LLLAND        , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_LLSICE        , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_LLLICE        , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_LLNH          , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_LLCUM         , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_LLSC          , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_LLSHCV        , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_LLCUM_LIG     , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_LLLAKE        , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_LLOCN_KPP     , UBOUNDS=[NPROMA, NGPBLKS], PERSISTENT=PERSISTENT)
!    END ASSOCIATE
!
!  END SUBROUTINE KEYS_LOCAL_TYPE_INIT
!
!  SUBROUTINE KEYS_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    CLASS(KEYS_LOCAL_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    SELF%LLLAND => SELF%F_LLLAND%GET_VIEW(BLOCK_INDEX)
!    SELF%LLSICE => SELF%F_LLSICE%GET_VIEW(BLOCK_INDEX)
!    SELF%LLLICE => SELF%F_LLLICE%GET_VIEW(BLOCK_INDEX)
!    SELF%LLNH => SELF%F_LLNH%GET_VIEW(BLOCK_INDEX)
!    SELF%LLCUM => SELF%F_LLCUM%GET_VIEW(BLOCK_INDEX)
!    SELF%LLSC => SELF%F_LLSC%GET_VIEW(BLOCK_INDEX)
!    SELF%LLSHCV => SELF%F_LLSHCV%GET_VIEW(BLOCK_INDEX)
!    SELF%LLCUM_LIG => SELF%F_LLCUM_LIG%GET_VIEW(BLOCK_INDEX)
!    SELF%LLLAKE => SELF%F_LLLAKE%GET_VIEW(BLOCK_INDEX)
!    SELF%LLOCN_KPP => SELF%F_LLOCN_KPP%GET_VIEW(BLOCK_INDEX)
!  END SUBROUTINE KEYS_LOCAL_TYPE_UPDATE_VIEW
!
!  SUBROUTINE KEYS_LOCAL_TYPE_FINAL(SELF)
!    CLASS(KEYS_LOCAL_TYPE) :: SELF
!
!    CALL FIELD_DELETE (SELF%F_LLLAND)
!    CALL FIELD_DELETE (SELF%F_LLSICE)
!    CALL FIELD_DELETE (SELF%F_LLLICE)
!    CALL FIELD_DELETE (SELF%F_LLNH)
!    CALL FIELD_DELETE (SELF%F_LLCUM)
!    CALL FIELD_DELETE (SELF%F_LLSC)
!    CALL FIELD_DELETE (SELF%F_LLSHCV)
!    CALL FIELD_DELETE (SELF%F_LLCUM_LIG)
!    CALL FIELD_DELETE (SELF%F_LLLAKE)
!    CALL FIELD_DELETE (SELF%F_LLOCN_KPP)
!  END SUBROUTINE KEYS_LOCAL_TYPE_FINAL
!
END MODULE ECLAND_AUX_TYPE_MOD
