MODULE ECLAND_AUX_DIAG_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
!USE FIELD_MODULE
!USE FIELD_FACTORY_MODULE
!USE FIELD_REGISTRY_MOD, ONLY: FIELD_REGISTRY

IMPLICIT NONE

TYPE AUX_DIAG_TYPE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCAPE      !  CONVECTIVE AVAILABLE POTENTIAL ENERGY (J/KG)
  REAL(KIND=JPRB), DIMENSION(:,:),POINTER,CONTIGUOUS :: ZCAPE      !  CAPE (J/KG) archive new multi-diagnostics
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PPDEPL     !  PRESSURE AT DEPARTURE LEVEL FOR MAX CAPE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCBASE     !  CLOUD BASE HEIGHT
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCBASEA    !  CLOUD BASE HEIGHT AVIATION
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCTOPC     !  CLOUD TOP  HEIGHT CONVECTIVE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: P0DEGL     !  0  DEGREE CELSIUS LEVEL
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PM10DEGL   ! -10 DEGREE CELSIUS LEVEL
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PTROPOTP   !  PRESSURE AT THERMAL TROPOPAUSE
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PVISIH     ! HORIZONTAL VISIBILITY
  REAL(KIND=JPRB), DIMENSION(:,:),POINTER,CONTIGUOUS :: PCIN       ! CIN multi diagnostics
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PVDISCU    ! Vert-integrated convection dissipation rate (W/m2)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PVDIS      ! Vert-integrated turbulent dissipation rate (W/m2)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PVDISG     ! Vert-integrated gravity wave drag dissipation rate(W/m2)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PUSTRG     ! GRAVITY WAVE DRAG SURFACE U-STRESS
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PVSTRG     ! GRAVITY WAVE DRAG SURFACE V-STRESS
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PGUST! PI10FG     ! WIND GUST AT 10 m FOR CURRENT TIME LEVEL (m/s)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PPRECTYPE  ! Precipitation type
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFZRA      ! Freezing rain rate
  !INTEGER(KIND=JPIM),dimension(:), pointer :: KTYPE    ! Convection type (0,1,2)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCONVIND ! CONVECTIVE INDICES
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PZTWETB  ! HEIGHT OF 0 1 DEG C WET BULB TEMPERATURE
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PQSAT    ! SPECIFIC HUMIDITY AT SATURATION.
  !    3D DIAGNOSTICS FOR ERA40
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PMFUDE_RATE   ! UD detrainmnet rate (KG/(M3*S))
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PMFDDE_RATE   ! DD detrainmnet rate (KG/(M3*S))
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PKH_VDF       ! turbulent diffusion coefficient for heat 
  !    additional turbulence diagnostics
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PKM_VDF       ! turbulent diffusion coefficient for momentum
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZRI           ! Richardson number
  REAL(KIND=JPRB), DIMENSION(:),   POINTER, CONTIGUOUS :: ZEIS          ! PBL normalised inversion strength
  REAL(KIND=JPRB), DIMENSION(:),   POINTER, CONTIGUOUS :: ZMFUB_SC      ! Index for identification of StCu regime
  REAL(KIND=JPRB), DIMENSION(:,:),   POINTER, CONTIGUOUS :: ZINV          ! convective turbulent mixing height
  !    array for precipitation fraction
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PCOVPTOT     !  PRECIPITATION FRACTION IN EACH LAYER
  ! Convection and PBL types
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER, CONTIGUOUS :: ITYPE, ICBOT, ICTOP
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER, CONTIGUOUS :: IPBLTYPE
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER, CONTIGUOUS :: ICBOT_LIG, ICTOP_LIG
! Convection to cloud communication
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PMFU,PMFD    !  Conv. mass flux up/down
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLUDE      ! DETRAINED TOTAL CONDENSATE
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER, CONTIGUOUS:: ZLUDELI    ! DETRAINED LIQUID, ICE, VAPOR, T
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLU        ! LIQUID WATER CONTENT IN UPDRAFTS
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLRAIN     ! RAIN+SNOW WATER CONTENT IN UPDRAFTS
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER, CONTIGUOUS:: ZSNDE      ! DETRAINED SNOW/RAIN
  REAL(KIND=JPRB), DIMENSION(:,:,:),POINTER, CONTIGUOUS:: PRSUD      ! VOLUME MEAN CONVECTIVE RAIN AND SNOW CONTENT
  ! Lightning fields
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PLIGH_TOT !  Total lightning density (intra-cloud and cloud-to-ground) (flash/km2/year)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PLIGH_CTG !  Cloud-to-ground lightning density (flash/km2/year)
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PCHARGE_LIG ! Electric charge production rate from lightning.
 ! vertically-integrated, instantaneous fluxes for mass, ozone, energy budgets for passing to postphy_glob
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIEM  ! vert.-int. eastward mass flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINM  ! vert.-int. northward mass flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIEWV ! vert.-int. eastward water vapour flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINWV ! vert.-int. northward water vapour flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIELW ! vert.-int. eastward cloud liquid water flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINLW ! vert.-int. northward cloud liquid water flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIEIW ! vert.-int. eastward cloud ice water flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINIW ! vert.-int. northward cloud ice water flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIER  ! vert.-int. eastward rain flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINR  ! vert.-int. northward rain flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIES  ! vert.-int. eastward snow flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINS  ! vert.-int. northward snow flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIEOZ ! vert.-int. eastward ozone flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINOZ ! vert.-int. northward ozone flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIEEN ! vert.-int. eastward enthalpy flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINEN ! vert.-int. northward enthalpy flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIEG  ! vert.-int. eastward geopotential flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVING  ! vert.-int. northward geopotential flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIEKE ! vert.-int. eastward kinetic energy flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINKE ! vert.-int. northward kinetic energy flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIETE ! vert.-int. eastward total energy flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINTE ! vert.-int. northward total energy flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIEWEN ! vert.-int. eastward water enthalpy flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINWEN ! vert.-int. northward water enthalpy flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVIEWG ! vert.-int. eastward water geopotential flux
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PIVINWG ! vert.-int. northward water geopotential flux


!  ! Storage fields to provide thread-local views
!  CLASS (FIELD_2RB), POINTER :: F_PCAPE, F_PPDEPL, F_PCBASE, F_PCBASEA, F_PCTOPC, F_P0DEGL, F_PM10DEGL, F_PVISIH, F_PVDISCU, F_PVDIS, &
!   & F_PVDISG, F_PUSTRG, F_PVSTRG, F_PI10FG, F_PPRECTYPE, F_PFZRA, F_PLIGH_TOT, F_PLIGH_CTG, F_PCHARGE_LIG, F_ZEIS, F_ZINV, F_PTROPOTP, &
!   & F_PIVIEM, F_PIVINM, F_PIVIEWV, F_PIVINWV, F_PIVIELW, F_PIVINLW, &
!   & F_PIVIEIW, F_PIVINIW, F_PIVIER, F_PIVINR, F_PIVIES, F_PIVINS, &
!   & F_PIVIEOZ, F_PIVINOZ, F_PIVIEEN, F_PIVINEN, F_PIVIEG, F_PIVING, &
!   & F_PIVIEKE, F_PIVINKE, F_PIVIETE, F_PIVINTE, F_PIVIEWEN, F_PIVINWEN, &
!   & F_PIVIEWG, F_PIVINWG, F_ZMFUB_SC
!  CLASS(FIELD_3RB), POINTER :: F_PCONVIND, F_PZTWETB, F_PQSAT, F_PZTENQ, F_PMFUDE_RATE, F_PMFDDE_RATE, F_PKH_VDF, &
!   & F_PCOVPTOT, F_PMFU, F_PMFD, F_ZLUDE, F_ZLU, F_ZLRAIN, F_PKM_VDF, F_ZRI, F_ZCAPE, F_PCIN
!  CLASS (FIELD_4RB), POINTER :: F_ZLUDELI, F_ZSNDE, F_PRSUD
!  CLASS (FIELD_2IM), POINTER :: F_ITYPE, F_ICBOT, F_ICTOP, F_IPBLTYPE, F_ICBOT_LIG, F_ICTOP_LIG
!
!CONTAINS
!  PROCEDURE :: INIT => AUX_DIAG_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => AUX_DIAG_TYPE_UPDATE_VIEW
!  PROCEDURE :: FINAL => AUX_DIAG_TYPE_FINAL
END TYPE AUX_DIAG_TYPE


TYPE AUX_DIAG_LOCAL_TYPE
  INTEGER(KIND=JPIM)                                 :: IEXT3D   ! position in extra field for diagnostics
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZPAPSRF
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZWND     ! horizontal wind in the lowest model level
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZCCNL, ZCCNO
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: ZRAINFRAC_TOPRFZ => NULL() ! rain fraction at top of melting layer
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER, CONTIGUOUS :: ITOPC, IBASC, IBOTSC
  ! radiation scheme for convenience
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS ::  ZEMIT ! Diagnosed surface broadband longwave emissivity
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS ::  ZTRSOD, ZSUDU !  radiation working arrays
  ! Skin temperature from radiation
  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: ZTSKRAD   !  Skin temperature from radiation
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS ::  ZTHT ! half level temperature
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS ::  ZCTRSO,ZCEMTR ! radiation working arrays
  !     LOCAL 3D ARRAYS TO PASS OUTPUT FROM GWD TO IMPLICIT SOLVER OF VDF
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZSOTEU    ! Explicit part of U-tendency from subgrid orography scheme
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZSOTEV    ! Explicit part of V-tendency from subgrid orography scheme
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZSOBETA   ! Implicit part of subgrid orography
  ! aerosols in microphysics
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLCRIT_AER ! critical liquid mmr for rain autoconversion process
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZICRIT_AER ! critical liquid mmr for snow autoconversion process
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZRE_LIQ    ! effective radius liquid
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZRE_ICE    ! effective radius ice
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZCCN       ! CCN (prognostic, diagnostic)
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZNICE      ! ice no concentration
  !    Local arrays for new cloud scheme of the linearized model
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZPATMP     ! CLOUD COVER OF INDIVIDUAL LAYER
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZPLSMP     ! ICE WATER CONTENT
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZPLTMP     ! LIQUID WATER CONTENT
  ! liquid water loading in environment neglected in convection
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZLISUM     ! Local array for sum of liquid water and ice to be available
  ! local arrays variables for lightning
  ! REAL(KIND=JPRB)    :: ZLIGH_TOT(KDIM%KLON), ZLIGH_CTG(KDIM%KLON), ZLIGH_EMI(KDIM%KLON), ZWMFU(KDIM%KLON)
  ! REAL(KIND=JPRB)    :: ZCTOPH(KDIM%KLON), ZPRECMX(KDIM%KLON), ZICETOT(KDIM%KLON), ZCDEPTH(KDIM%KLON)

!  ! Storage fields to provide thread-local views
!  CLASS (FIELD_2RB), POINTER :: F_ZWND, F_ZCCNL, F_ZCCNO, F_ZRAINFRAC_TOPRFZ, F_ZEMIT, F_ZTRSOD, F_ZSUDU, F_ZTSKRAD
!  CLASS (FIELD_3RB), POINTER :: F_ZTHT, F_ZCTRSO, F_ZCEMTR, F_ZSOTEU, F_ZSOTEV, F_ZSOBETA, F_ZLCRIT_AER, F_ZICRIT_AER, &
!   & F_ZRE_LIQ, F_ZRE_ICE, F_ZCCN, F_ZNICE, F_ZPATMP, F_ZPLSMP, F_ZPLTMP, F_ZLISUM
!  CLASS (FIELD_2IM), POINTER :: F_ITOPC, F_IBASC, F_IBOTSC
!
!CONTAINS
!  PROCEDURE :: INIT => AUX_DIAG_LOCAL_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW
!  PROCEDURE :: FINAL => AUX_DIAG_LOCAL_TYPE_FINAL
END TYPE AUX_DIAG_LOCAL_TYPE


!CONTAINS
!
!  SUBROUTINE AUX_DIAG_TYPE_INIT(SELF, REGISTRY, NLEV, PERSISTENT)
!    CLASS(AUX_DIAG_TYPE) :: SELF
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    INTEGER(KIND=JPIM), INTENT(IN) :: NLEV
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!    CALL FIELD_NEW (SELF%F_PCAPE      , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PPDEPL     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCBASE     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCBASEA    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCTOPC     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_P0DEGL     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PM10DEGL   , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTROPOTP   , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PVISIH     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PVDISCU    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PVDIS      , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PVDISG     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PUSTRG     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PVSTRG     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PI10FG     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PPRECTYPE  , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFZRA      , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCONVIND   , UBOUNDS=[NPROMA, 2,       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PZTWETB    , UBOUNDS=[NPROMA, 2,       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZCAPE      , UBOUNDS=[NPROMA, 4,       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCIN       , UBOUNDS=[NPROMA, 3,       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PQSAT      , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PZTENQ     , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PMFUDE_RATE, UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PMFDDE_RATE, UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PKH_VDF    , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PKM_VDF    , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZRI        , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCOVPTOT   , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PMFU       , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PMFD       , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZLUDE      , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZLUDELI    , UBOUNDS=[NPROMA, NLEV, 4, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZSNDE      , UBOUNDS=[NPROMA, NLEV, 2, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PRSUD      , UBOUNDS=[NPROMA, NLEV, 2, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZLU        , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZLRAIN     , UBOUNDS=[NPROMA, NLEV,    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PLIGH_TOT  , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PLIGH_CTG  , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PCHARGE_LIG, UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZMFUB_SC   , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZEIS       , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZINV       , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ITYPE      , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ICBOT      , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ICTOP      , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_IPBLTYPE   , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ICBOT_LIG  , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ICTOP_LIG  , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIEM     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINM     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIEWV    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINWV    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIELW    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINLW    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIEIW    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINIW    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIER     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINR     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIES     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINS     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIEOZ    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINOZ    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIEEN    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINEN    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIEG     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVING     , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIEKE    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINKE    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIETE    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINTE    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIEWEN   , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINWEN   , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVIEWG    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PIVINWG    , UBOUNDS=[NPROMA,          NGPBLKS], PERSISTENT=PERSISTENT)
!    END ASSOCIATE
!
! END SUBROUTINE AUX_DIAG_TYPE_INIT
!
!  SUBROUTINE AUX_DIAG_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    CLASS(AUX_DIAG_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    SELF%PCAPE => SELF%F_PCAPE%GET_VIEW(BLOCK_INDEX)
!    SELF%ZCAPE => SELF%F_ZCAPE%GET_VIEW(BLOCK_INDEX)
!    SELF%PPDEPL => SELF%F_PPDEPL%GET_VIEW(BLOCK_INDEX)
!    SELF%PCBASE => SELF%F_PCBASE%GET_VIEW(BLOCK_INDEX)
!    SELF%PCBASEA => SELF%F_PCBASEA%GET_VIEW(BLOCK_INDEX)
!    SELF%PCTOPC => SELF%F_PCTOPC%GET_VIEW(BLOCK_INDEX)
!    SELF%P0DEGL => SELF%F_P0DEGL%GET_VIEW(BLOCK_INDEX)
!    SELF%PM10DEGL => SELF%F_PM10DEGL%GET_VIEW(BLOCK_INDEX)
!    SELF%PTROPOTP => SELF%F_PTROPOTP%GET_VIEW(BLOCK_INDEX)
!    SELF%PVISIH => SELF%F_PVISIH%GET_VIEW(BLOCK_INDEX)
!    SELF%PCIN => SELF%F_PCIN%GET_VIEW(BLOCK_INDEX)
!    SELF%PVDISCU => SELF%F_PVDISCU%GET_VIEW(BLOCK_INDEX)
!    SELF%PVDIS => SELF%F_PVDIS%GET_VIEW(BLOCK_INDEX)
!    SELF%PVDISG => SELF%F_PVDISG%GET_VIEW(BLOCK_INDEX)
!    SELF%PUSTRG => SELF%F_PUSTRG%GET_VIEW(BLOCK_INDEX)
!    SELF%PVSTRG => SELF%F_PVSTRG%GET_VIEW(BLOCK_INDEX)
!    SELF%PI10FG => SELF%F_PI10FG%GET_VIEW(BLOCK_INDEX)
!    SELF%PPRECTYPE => SELF%F_PPRECTYPE%GET_VIEW(BLOCK_INDEX)
!    SELF%PFZRA => SELF%F_PFZRA%GET_VIEW(BLOCK_INDEX)
!    SELF%PCONVIND => SELF%F_PCONVIND%GET_VIEW(BLOCK_INDEX)
!    SELF%PZTWETB => SELF%F_PZTWETB%GET_VIEW(BLOCK_INDEX)
!    SELF%PQSAT => SELF%F_PQSAT%GET_VIEW(BLOCK_INDEX)
!    SELF%PMFUDE_RATE => SELF%F_PMFUDE_RATE%GET_VIEW(BLOCK_INDEX)
!    SELF%PMFDDE_RATE => SELF%F_PMFDDE_RATE%GET_VIEW(BLOCK_INDEX)
!    SELF%PKH_VDF => SELF%F_PKH_VDF%GET_VIEW(BLOCK_INDEX)
!    SELF%PKM_VDF => SELF%F_PKM_VDF%GET_VIEW(BLOCK_INDEX)
!    SELF%ZRI => SELF%F_ZRI%GET_VIEW(BLOCK_INDEX)
!    SELF%PCOVPTOT => SELF%F_PCOVPTOT%GET_VIEW(BLOCK_INDEX)
!    SELF%PMFU => SELF%F_PMFU%GET_VIEW(BLOCK_INDEX)
!    SELF%PMFD => SELF%F_PMFD%GET_VIEW(BLOCK_INDEX)
!    SELF%ZLUDE => SELF%F_ZLUDE%GET_VIEW(BLOCK_INDEX)
!    SELF%ZLUDELI => SELF%F_ZLUDELI%GET_VIEW(BLOCK_INDEX)
!    SELF%ZSNDE => SELF%F_ZSNDE%GET_VIEW(BLOCK_INDEX)
!    SELF%PRSUD => SELF%F_PRSUD%GET_VIEW(BLOCK_INDEX)
!    SELF%ZLU => SELF%F_ZLU%GET_VIEW(BLOCK_INDEX)
!    SELF%ZLRAIN => SELF%F_ZLRAIN%GET_VIEW(BLOCK_INDEX)
!    SELF%PLIGH_TOT => SELF%F_PLIGH_TOT%GET_VIEW(BLOCK_INDEX)
!    SELF%PLIGH_CTG => SELF%F_PLIGH_CTG%GET_VIEW(BLOCK_INDEX)
!    SELF%PCHARGE_LIG => SELF%F_PCHARGE_LIG%GET_VIEW(BLOCK_INDEX)
!    SELF%ZEIS => SELF%F_ZEIS%GET_VIEW(BLOCK_INDEX)
!    SELF%ZMFUB_SC => SELF%F_ZMFUB_SC%GET_VIEW(BLOCK_INDEX)
!    SELF%ZINV => SELF%F_ZINV%GET_VIEW(BLOCK_INDEX)
!    SELF%ITYPE => SELF%F_ITYPE%GET_VIEW(BLOCK_INDEX)
!    SELF%ICBOT => SELF%F_ICBOT%GET_VIEW(BLOCK_INDEX)
!    SELF%ICTOP => SELF%F_ICTOP%GET_VIEW(BLOCK_INDEX)
!    SELF%IPBLTYPE => SELF%F_IPBLTYPE%GET_VIEW(BLOCK_INDEX)
!    SELF%ICBOT_LIG => SELF%F_ICBOT_LIG%GET_VIEW(BLOCK_INDEX)
!    SELF%ICTOP_LIG => SELF%F_ICTOP_LIG%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIEM => SELF%F_PIVIEM%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINM => SELF%F_PIVINM%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIEWV => SELF%F_PIVIEWV%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINWV => SELF%F_PIVINWV%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIELW => SELF%F_PIVIELW%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINLW => SELF%F_PIVINLW%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIEIW => SELF%F_PIVIEIW%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINIW => SELF%F_PIVINIW%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIER => SELF%F_PIVIER%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINR => SELF%F_PIVINR%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIES => SELF%F_PIVIES%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINS => SELF%F_PIVINS%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIEOZ => SELF%F_PIVIEOZ%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINOZ => SELF%F_PIVINOZ%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIEEN => SELF%F_PIVIEEN%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINEN => SELF%F_PIVINEN%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIEG => SELF%F_PIVIEG%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVING => SELF%F_PIVING%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIEKE => SELF%F_PIVIEKE%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINKE => SELF%F_PIVINKE%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIETE => SELF%F_PIVIETE%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINTE => SELF%F_PIVINTE%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIEWEN => SELF%F_PIVIEWEN%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINWEN => SELF%F_PIVINWEN%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVIEWG => SELF%F_PIVIEWG%GET_VIEW(BLOCK_INDEX)
!    SELF%PIVINWG => SELF%F_PIVINWG%GET_VIEW(BLOCK_INDEX)
!        
!  END SUBROUTINE AUX_DIAG_TYPE_UPDATE_VIEW
!
!  SUBROUTINE AUX_DIAG_TYPE_FINAL(SELF)
!    CLASS(AUX_DIAG_TYPE) :: SELF
!
!    CALL FIELD_DELETE (SELF%F_PCAPE)
!    CALL FIELD_DELETE (SELF%F_ZCAPE)
!    CALL FIELD_DELETE (SELF%F_PPDEPL)
!    CALL FIELD_DELETE (SELF%F_PCBASE)
!    CALL FIELD_DELETE (SELF%F_PCBASEA)
!    CALL FIELD_DELETE (SELF%F_PCTOPC)
!    CALL FIELD_DELETE (SELF%F_P0DEGL)
!    CALL FIELD_DELETE (SELF%F_PM10DEGL)
!    CALL FIELD_DELETE (SELF%F_PTROPOTP)
!    CALL FIELD_DELETE (SELF%F_PVISIH)
!    CALL FIELD_DELETE (SELF%F_PCIN)
!    CALL FIELD_DELETE (SELF%F_PVDISCU)
!    CALL FIELD_DELETE (SELF%F_PVDIS)
!    CALL FIELD_DELETE (SELF%F_PVDISG)
!    CALL FIELD_DELETE (SELF%F_PUSTRG)
!    CALL FIELD_DELETE (SELF%F_PVSTRG)
!    CALL FIELD_DELETE (SELF%F_PI10FG)
!    CALL FIELD_DELETE (SELF%F_PPRECTYPE)
!    CALL FIELD_DELETE (SELF%F_PFZRA)
!    CALL FIELD_DELETE (SELF%F_PCONVIND)
!    CALL FIELD_DELETE (SELF%F_PZTWETB)
!    CALL FIELD_DELETE (SELF%F_PQSAT)
!    CALL FIELD_DELETE (SELF%F_PZTENQ)
!    CALL FIELD_DELETE (SELF%F_PMFUDE_RATE)
!    CALL FIELD_DELETE (SELF%F_PMFDDE_RATE)
!    CALL FIELD_DELETE (SELF%F_PKH_VDF)
!    CALL FIELD_DELETE (SELF%F_PKM_VDF)
!    CALL FIELD_DELETE (SELF%F_ZRI)
!    CALL FIELD_DELETE (SELF%F_PCOVPTOT)
!    CALL FIELD_DELETE (SELF%F_PMFU)
!    CALL FIELD_DELETE (SELF%F_PMFD)
!    CALL FIELD_DELETE (SELF%F_ZLUDE)
!    CALL FIELD_DELETE (SELF%F_ZLUDELI)
!    CALL FIELD_DELETE (SELF%F_ZSNDE)
!    CALL FIELD_DELETE (SELF%F_PRSUD)
!    CALL FIELD_DELETE (SELF%F_ZLU)
!    CALL FIELD_DELETE (SELF%F_ZLRAIN)
!    CALL FIELD_DELETE (SELF%F_PLIGH_TOT)
!    CALL FIELD_DELETE (SELF%F_PLIGH_CTG)
!    CALL FIELD_DELETE (SELF%F_PCHARGE_LIG)
!    CALL FIELD_DELETE (SELF%F_ZEIS)
!    CALL FIELD_DELETE (SELF%F_ZMFUB_SC)
!    CALL FIELD_DELETE (SELF%F_ZINV)
!    CALL FIELD_DELETE (SELF%F_ITYPE)
!    CALL FIELD_DELETE (SELF%F_ICBOT)
!    CALL FIELD_DELETE (SELF%F_ICTOP)
!    CALL FIELD_DELETE (SELF%F_IPBLTYPE)
!    CALL FIELD_DELETE (SELF%F_ICBOT_LIG)
!    CALL FIELD_DELETE (SELF%F_ICTOP_LIG)
!    CALL FIELD_DELETE (SELF%F_PIVIEM)
!    CALL FIELD_DELETE (SELF%F_PIVINM)
!    CALL FIELD_DELETE (SELF%F_PIVIEWV)
!    CALL FIELD_DELETE (SELF%F_PIVINWV)
!    CALL FIELD_DELETE (SELF%F_PIVIELW)
!    CALL FIELD_DELETE (SELF%F_PIVINLW)
!    CALL FIELD_DELETE (SELF%F_PIVIEIW)
!    CALL FIELD_DELETE (SELF%F_PIVINIW)
!    CALL FIELD_DELETE (SELF%F_PIVIER)
!    CALL FIELD_DELETE (SELF%F_PIVINR)
!    CALL FIELD_DELETE (SELF%F_PIVIES)
!    CALL FIELD_DELETE (SELF%F_PIVINS)
!    CALL FIELD_DELETE (SELF%F_PIVIEOZ)
!    CALL FIELD_DELETE (SELF%F_PIVINOZ)
!    CALL FIELD_DELETE (SELF%F_PIVIEEN)
!    CALL FIELD_DELETE (SELF%F_PIVINEN)
!    CALL FIELD_DELETE (SELF%F_PIVIEG)
!    CALL FIELD_DELETE (SELF%F_PIVING)
!    CALL FIELD_DELETE (SELF%F_PIVIEKE)
!    CALL FIELD_DELETE (SELF%F_PIVINKE)
!    CALL FIELD_DELETE (SELF%F_PIVIETE)
!    CALL FIELD_DELETE (SELF%F_PIVINTE)
!    CALL FIELD_DELETE (SELF%F_PIVIEWEN)
!    CALL FIELD_DELETE (SELF%F_PIVINWEN)
!    CALL FIELD_DELETE (SELF%F_PIVIEWG)
!    CALL FIELD_DELETE (SELF%F_PIVINWG)
!  END SUBROUTINE AUX_DIAG_TYPE_FINAL
!
!
!  SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT(SELF, REGISTRY, NLEV, PERSISTENT)
!    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    INTEGER(KIND=JPIM), INTENT(IN) :: NLEV
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!    CALL FIELD_NEW (SELF%F_ZWND            , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZCCNL           , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZCCNO           , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZEMIT           , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZTRSOD          , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZSUDU           , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZTSKRAD         , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZRAINFRAC_TOPRFZ, UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZTHT            , UBOUNDS=[NPROMA, NLEV+1, NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZSOTEU          , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZSOTEV          , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZSOBETA         , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZLCRIT_AER      , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZICRIT_AER      , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZRE_LIQ         , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZRE_ICE         , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZCCN            , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZNICE           , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZPATMP          , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZPLTMP          , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZPLSMP          , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZLISUM          , UBOUNDS=[NPROMA, NLEV,   NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZCTRSO          , UBOUNDS=[NPROMA, 2,      NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ZCEMTR          , UBOUNDS=[NPROMA, 2,      NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_ITOPC           , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_IBASC           , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_IBOTSC          , UBOUNDS=[NPROMA,         NGPBLKS], PERSISTENT=PERSISTENT)
!    END ASSOCIATE
!  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT
!
!  SUBROUTINE AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    SELF%ZWND => SELF%F_ZWND%GET_VIEW(BLOCK_INDEX)
!    SELF%ZCCNL => SELF%F_ZCCNL%GET_VIEW(BLOCK_INDEX)
!    SELF%ZCCNO => SELF%F_ZCCNO%GET_VIEW(BLOCK_INDEX)
!    SELF%ZEMIT => SELF%F_ZEMIT%GET_VIEW(BLOCK_INDEX)
!    SELF%ZTRSOD => SELF%F_ZTRSOD%GET_VIEW(BLOCK_INDEX)
!    SELF%ZSUDU => SELF%F_ZSUDU%GET_VIEW(BLOCK_INDEX)
!    SELF%ZTSKRAD => SELF%F_ZTSKRAD%GET_VIEW(BLOCK_INDEX)
!    SELF%ZRAINFRAC_TOPRFZ => SELF%F_ZRAINFRAC_TOPRFZ%GET_VIEW(BLOCK_INDEX)
!    SELF%ZTHT(1:,0:) => SELF%F_ZTHT%GET_VIEW(BLOCK_INDEX)
!    SELF%ZSOTEU => SELF%F_ZSOTEU%GET_VIEW(BLOCK_INDEX)
!    SELF%ZSOTEV => SELF%F_ZSOTEV%GET_VIEW(BLOCK_INDEX)
!    SELF%ZSOBETA => SELF%F_ZSOBETA%GET_VIEW(BLOCK_INDEX)
!    SELF%ZLCRIT_AER => SELF%F_ZLCRIT_AER%GET_VIEW(BLOCK_INDEX)
!    SELF%ZICRIT_AER => SELF%F_ZICRIT_AER%GET_VIEW(BLOCK_INDEX)
!    SELF%ZRE_LIQ => SELF%F_ZRE_LIQ%GET_VIEW(BLOCK_INDEX)
!    SELF%ZRE_ICE => SELF%F_ZRE_ICE%GET_VIEW(BLOCK_INDEX)
!    SELF%ZCCN => SELF%F_ZCCN%GET_VIEW(BLOCK_INDEX)
!    SELF%ZNICE => SELF%F_ZNICE%GET_VIEW(BLOCK_INDEX)
!    SELF%ZPATMP => SELF%F_ZPATMP%GET_VIEW(BLOCK_INDEX)
!    SELF%ZPLTMP => SELF%F_ZPLTMP%GET_VIEW(BLOCK_INDEX)
!    SELF%ZPLSMP => SELF%F_ZPLSMP%GET_VIEW(BLOCK_INDEX)
!    SELF%ZLISUM => SELF%F_ZLISUM%GET_VIEW(BLOCK_INDEX)
!    SELF%ZCTRSO(1:,0:) => SELF%F_ZCTRSO%GET_VIEW(BLOCK_INDEX)
!    SELF%ZCEMTR(1:,0:) => SELF%F_ZCEMTR%GET_VIEW(BLOCK_INDEX)
!    SELF%ITOPC => SELF%F_ITOPC%GET_VIEW(BLOCK_INDEX)
!    SELF%IBASC => SELF%F_IBASC%GET_VIEW(BLOCK_INDEX)
!    SELF%IBOTSC => SELF%F_IBOTSC%GET_VIEW(BLOCK_INDEX)
!  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW
!
!  SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL(SELF)
!    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
!
!    CALL FIELD_DELETE (SELF%F_ZWND)
!    CALL FIELD_DELETE (SELF%F_ZCCNL)
!    CALL FIELD_DELETE (SELF%F_ZCCNO)
!    CALL FIELD_DELETE (SELF%F_ZEMIT)
!    CALL FIELD_DELETE (SELF%F_ZTRSOD)
!    CALL FIELD_DELETE (SELF%F_ZSUDU)
!    CALL FIELD_DELETE (SELF%F_ZTSKRAD)
!    CALL FIELD_DELETE (SELF%F_ZRAINFRAC_TOPRFZ)
!    CALL FIELD_DELETE (SELF%F_ZTHT)
!    CALL FIELD_DELETE (SELF%F_ZSOTEU)
!    CALL FIELD_DELETE (SELF%F_ZSOTEV)
!    CALL FIELD_DELETE (SELF%F_ZSOBETA)
!    CALL FIELD_DELETE (SELF%F_ZLCRIT_AER)
!    CALL FIELD_DELETE (SELF%F_ZICRIT_AER)
!    CALL FIELD_DELETE (SELF%F_ZRE_LIQ)
!    CALL FIELD_DELETE (SELF%F_ZRE_ICE)
!    CALL FIELD_DELETE (SELF%F_ZCCN)
!    CALL FIELD_DELETE (SELF%F_ZNICE)
!    CALL FIELD_DELETE (SELF%F_ZPATMP)
!    CALL FIELD_DELETE (SELF%F_ZPLTMP)
!    CALL FIELD_DELETE (SELF%F_ZPLSMP)
!    CALL FIELD_DELETE (SELF%F_ZLISUM)
!    CALL FIELD_DELETE (SELF%F_ZCTRSO)
!    CALL FIELD_DELETE (SELF%F_ZCEMTR)
!    CALL FIELD_DELETE (SELF%F_ITOPC)
!    CALL FIELD_DELETE (SELF%F_IBASC)
!    CALL FIELD_DELETE (SELF%F_IBOTSC)
!  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL
!
END MODULE ECLAND_AUX_DIAG_TYPE_MOD
