MODULE ECPHYS_FLUX_TYPE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
!USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB, FIELD_4RB
!USE FIELD_FACTORY_MODULE
!USE FIELD_REGISTRY_MOD, ONLY: FIELD_REGISTRY

IMPLICIT NONE

TYPE FLUX_TYPE
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFRSOC,PFRTHC ! (KLON,0:1) SHORTWAVE and LONGWAVE CLEAR SKY RADIATIVE FLUX
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDIFCQ     ! CONVECTIVE FLUX OF SPECIFIC HUMIDITY (NOT RAIN/SNOW).
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDIFCS     ! CONVECTIVE FLUX OF ENTHALPY (NOT RAIN/SNOW).
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PDIFTQ     ! TURBULENT FLUX (INC. Q NEGATIVE) OF SPECIFIC HUMIDITY.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PDIFTI,PDIFTL ! TURBULENT FLUX (INC. Q NEGATIVE) OF SOLID/LIQUID WATER
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PDIFTS     ! TURBULENT FLUX OF ENTHALPY (OR DRY STATIC ENERGY).
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCQNG     ! PSEUDO-FLUX OF WATER TO CORRECT FOR Q<0.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCQLNG,PFCQNNG  ! PSEUDO-FLUX OF LIQUID WATER/ICE TO CORRECT FOR Q<0.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCQRNG,PFCQSNG  ! PSEUDO-FLUX OF RAIN/SNOW TO CORRECT FOR Q<0.
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLCL     ! CONVECTIVE PRECIPITATION AS RAIN.
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLCN     ! CONVECTIVE PRECIPITATION AS SNOW.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLCLO    ! CONVECTIVE PRECIPITATION AS RAIN ORG, NO STRATIFORM HANDOVER
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLCNO    ! CONVECTIVE PRECIPITATION AS SNOW ORG, NO STRATIFORM HANDOVER
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLSL     ! STRATIFORM PRECIPITATION AS RAIN.
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFPLSN     ! STRATIFORM PRECIPITATION AS SNOW.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFHPCL     ! ENTHALPY FLUX OF CONVECTIVE PRECIPITATION AS RAIN
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFHPCN     ! ENTHALPY FLUX OF CONVECTIVE PRECIPITATION AS SNOW.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFHPSL     ! ENTHALPY FLUX OF STRATIFORM PRECIPITATION AS RAIN.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFHPSN     ! ENTHALPY FLUX OF STRATIFORM PRECIPITATION AS SNOW.
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PFRSO      ! SHORTWAVE RADIATIVE FLUX.
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PFRTH      ! LONGWAVE RADIATIVE FLUX.
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: ZFRTH      ! LONGWAVE RADIATIVE FLUX.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PSTRCU,PSTRCV ! CONVECTIVE FLUX OF MOMENTUM (U and V)
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PSTRDU,PSTRDV ! GRAVITY WAVE DRAG FLUX OF MOMENTUM (U and V)
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PSTRTU,PSTRTV ! TURBULENT FLUX OF MOMENTUM (U and V)
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCCQL,PFCCQN ! CONVECTIVE CONDENSATION FLUX FOR LIQUID WATER/ICE.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFCSQL,PFCSQN ! STRATIFORM CONDENSATION FLUX FOR LIQUID WATER/ICE.
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFSQRF,PFSQSF ! RAIN/SNOW FLUX FROM LS CLOUD SCHEME
!  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFSQLTUR,PFSQITUR ! LIQUID/ICE FLUX DUE TO VDF
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFRSOD,PFRSODC  ! DOWNWARD (CLEAR-SKY) SHORTWAVE FLUX AT SURFACE
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PFRTHD,PFRTHDC  ! DOWNWARD (CLEAR-SKY) LONGWAVE FLUX AT SURFACE
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PUVDF,PPARF     ! DOWNWARD UV,PAR FLUX AT SURFACE
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PPARCF          ! CLEAR-SKY DOWNWARD PAR FLUX AT SURFACE
!  REAL(KIND=JPRB), DIMENSION(:), POINTER, CONTIGUOUS :: PTOFDU,PTOFDV   ! TOFD COMP. OF TURBULENT FLUX OF U/V-MOMEMTUM
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFTG12!PTSDFL          ! HEAT FLUX FROM LAYER 1 TO 2  ! NOT USED
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFWG12 !PWFSD          ! WATER FLUX FROM LAYER 1 TO 2  ! NOT USED
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFWEV           ! SURFACE WATER VAPOUR FLUX (EVAPORATION)
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFWSB           ! SURFACE WATER VAPOUR FLUX (SUBLIMATION)
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFWMLT !PFMLT         ! WATER FLUX CORRESPONDING TO SURFACE SNOW MELT.
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFWROD          ! RUN-OFF FLUX AT DEEPER LAYERS (2-4)
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFWRO1          ! RUN-OFF FLUX AT LAYER 1
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFTLHEV         ! SURFACE LATENT HEAT FLUX (SNOW FREE FRACTION)
   REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS :: PFTLHSB         ! SURFACE LATENT HEAT FLUX (SNOW COVERED FRACTION)
   REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: ZENES !PENES         !  ???
!  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: PAERODDF    ! Diagnostic array with aerosol fluxes (sources and sinks)

!  ! Storage fields to provide thread-local views
!  CLASS (FIELD_2RB), POINTER :: F_PFRSOD, F_PFRSODC, F_PFRTHD, F_PFRTHDC, F_PUVDF, F_PPARF, F_PPARCF, F_PTOFDU, F_PTOFDV, &
!   & F_PFTG12, F_PFWG12, F_PFWEV, F_PFWSB, F_PFWMLT, F_PFWROD, F_PFWRO1, F_PFTLHEV, F_PFTLHSB
!  CLASS (FIELD_3RB), POINTER :: F_PFRSOC, F_PFRTHC, F_PDIFCQ, F_PDIFCS, F_PDIFTQ, F_PDIFTI, F_PDIFTL, F_PDIFTS, F_PFCQNG, &
!   & F_PFCQLNG, F_PFCQNNG, F_PFCQRNG, F_PFCQSNG, F_PFPLCL, F_PFPLCN, F_PFPLSL, F_PFPLSN, F_PFHPCL, F_PFHPCN, F_PFHPSL, &
!   & F_PFHPSN, F_PFRSO, F_PFRTH, F_PSTRCU, F_PSTRCV, F_PSTRDU, F_PSTRDV, F_PSTRTU, F_PSTRTV, F_PFCCQL, F_PFCCQN, F_PFCSQL, &
!   & F_PFCSQN, F_PFSQRF, F_PFSQSF, F_PFSQLTUR, F_PFSQITUR, F_PENES,  F_PFPLCLO, F_PFPLCNO
!  CLASS (FIELD_4RB), POINTER :: F_PAERODDF
!
!CONTAINS
!  PROCEDURE :: INIT => FLUX_TYPE_INIT
!  PROCEDURE :: UPDATE_VIEW => FLUX_TYPE_UPDATE_VIEW
!  PROCEDURE :: FINAL => FLUX_TYPE_FINAL
END TYPE FLUX_TYPE

!CONTAINS
!
!  SUBROUTINE FLUX_TYPE_INIT(SELF, REGISTRY, NLEV, NLEVS, NACTAERO, NPAERODIAG, PERSISTENT)
!    CLASS(FLUX_TYPE) :: SELF
!    TYPE(FIELD_REGISTRY), INTENT(INOUT) :: REGISTRY
!    INTEGER(KIND=JPIM), INTENT(IN) :: NLEV, NLEVS, NACTAERO, NPAERODIAG
!    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
!
!    ASSOCIATE (NPROMA => REGISTRY%GEOM%YRDIM%NPROMA, NFLEVG => REGISTRY%GEOM%YRDIMV%NFLEVG, NGPBLKS => REGISTRY%GEOM%YRDIM%NGPBLKS)
!    CALL FIELD_NEW (SELF%F_PFRSOD  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFRSODC ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PUVDF   ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PPARF   ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PPARCF  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFRTHD  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFRTHDC ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTOFDU  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PTOFDV  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFTG12  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFWEV   ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFWSB   ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFWG12  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFWMLT  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFWROD  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFWRO1  ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFTLHEV ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFTLHSB ,  UBOUNDS=[NPROMA,                       NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFRSOC  ,  UBOUNDS=[NPROMA, 2,                    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFRTHC  ,  UBOUNDS=[NPROMA, 2,                    NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDIFCQ  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDIFCS  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDIFTQ  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDIFTS  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFCQNG  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFPLCL  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFPLCNO ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFPLCLO ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFPLCN  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFPLSL  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFPLSN  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFHPCL  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFHPCN  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFHPSL  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFHPSN  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFRSO   ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFRTH   ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PSTRCU  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PSTRCV  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PSTRDU  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PSTRDV  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PSTRTU  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PSTRTV  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDIFTL  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PDIFTI  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFCCQL  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFCCQN  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFCSQL  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFCSQN  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFCQLNG ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFCQNNG ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFSQRF  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFSQSF  ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFCQRNG ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFCQSNG ,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFSQLTUR,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PFSQITUR,  UBOUNDS=[NPROMA, NLEV+1,               NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PENES   ,  UBOUNDS=[NPROMA, NLEVS,                NGPBLKS], PERSISTENT=PERSISTENT)
!    CALL FIELD_NEW (SELF%F_PAERODDF,  UBOUNDS=[NPROMA, NACTAERO, NPAERODIAG, NGPBLKS], PERSISTENT=PERSISTENT)
!    END ASSOCIATE
!
!  END SUBROUTINE FLUX_TYPE_INIT
!
!  SUBROUTINE FLUX_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
!    CLASS(FLUX_TYPE) :: SELF
!    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
!
!    SELF%PFRSOD => SELF%F_PFRSOD%GET_VIEW(BLOCK_INDEX)
!    SELF%PFRSODC => SELF%F_PFRSODC%GET_VIEW(BLOCK_INDEX)
!    SELF%PUVDF => SELF%F_PUVDF%GET_VIEW(BLOCK_INDEX)
!    SELF%PPARF => SELF%F_PPARF%GET_VIEW(BLOCK_INDEX)
!    SELF%PPARCF => SELF%F_PPARCF%GET_VIEW(BLOCK_INDEX)
!    SELF%PFRTHD => SELF%F_PFRTHD%GET_VIEW(BLOCK_INDEX)
!    SELF%PFRTHDC => SELF%F_PFRTHDC%GET_VIEW(BLOCK_INDEX)
!    SELF%PTOFDU => SELF%F_PTOFDU%GET_VIEW(BLOCK_INDEX)
!    SELF%PTOFDV => SELF%F_PTOFDV%GET_VIEW(BLOCK_INDEX)
!    SELF%PFTG12 => SELF%F_PFTG12%GET_VIEW(BLOCK_INDEX)
!    SELF%PFWEV => SELF%F_PFWEV%GET_VIEW(BLOCK_INDEX)
!    SELF%PFWSB => SELF%F_PFWSB%GET_VIEW(BLOCK_INDEX)
!    SELF%PFWG12 => SELF%F_PFWG12%GET_VIEW(BLOCK_INDEX)
!    SELF%PFWMLT => SELF%F_PFWMLT%GET_VIEW(BLOCK_INDEX)
!    SELF%PFWROD => SELF%F_PFWROD%GET_VIEW(BLOCK_INDEX)
!    SELF%PFWRO1 => SELF%F_PFWRO1%GET_VIEW(BLOCK_INDEX)
!    SELF%PFTLHEV => SELF%F_PFTLHEV%GET_VIEW(BLOCK_INDEX)
!    SELF%PFTLHSB => SELF%F_PFTLHSB%GET_VIEW(BLOCK_INDEX)
!    SELF%PFRSOC(1:,0:) => SELF%F_PFRSOC%GET_VIEW(BLOCK_INDEX)
!    SELF%PFRTHC(1:,0:) => SELF%F_PFRTHC%GET_VIEW(BLOCK_INDEX)
!    SELF%PDIFCQ(1:,0:) => SELF%F_PDIFCQ%GET_VIEW(BLOCK_INDEX)
!    SELF%PDIFCS(1:,0:) => SELF%F_PDIFCS%GET_VIEW(BLOCK_INDEX)
!    SELF%PDIFTQ(1:,0:) => SELF%F_PDIFTQ%GET_VIEW(BLOCK_INDEX)
!    SELF%PDIFTS(1:,0:) => SELF%F_PDIFTS%GET_VIEW(BLOCK_INDEX)
!    SELF%PFCQNG(1:,0:) => SELF%F_PFCQNG%GET_VIEW(BLOCK_INDEX)
!    SELF%PFPLCL(1:,0:) => SELF%F_PFPLCL%GET_VIEW(BLOCK_INDEX)
!    SELF%PFPLCN(1:,0:) => SELF%F_PFPLCN%GET_VIEW(BLOCK_INDEX)
!    SELF%PFPLCLO(1:,0:)=> SELF%F_PFPLCLO%GET_VIEW(BLOCK_INDEX)
!    SELF%PFPLCNO(1:,0:)=> SELF%F_PFPLCNO%GET_VIEW(BLOCK_INDEX)
!    SELF%PFPLSL(1:,0:) => SELF%F_PFPLSL%GET_VIEW(BLOCK_INDEX)
!    SELF%PFPLSN(1:,0:) => SELF%F_PFPLSN%GET_VIEW(BLOCK_INDEX)
!    SELF%PFHPCL(1:,0:) => SELF%F_PFHPCL%GET_VIEW(BLOCK_INDEX)
!    SELF%PFHPCN(1:,0:) => SELF%F_PFHPCN%GET_VIEW(BLOCK_INDEX)
!    SELF%PFHPSL(1:,0:) => SELF%F_PFHPSL%GET_VIEW(BLOCK_INDEX)
!    SELF%PFHPSN(1:,0:) => SELF%F_PFHPSN%GET_VIEW(BLOCK_INDEX)
!    SELF%PFRSO(1:,0:) => SELF%F_PFRSO%GET_VIEW(BLOCK_INDEX)
!    SELF%PFRTH(1:,0:) => SELF%F_PFRTH%GET_VIEW(BLOCK_INDEX)
!    SELF%PSTRCU(1:,0:) => SELF%F_PSTRCU%GET_VIEW(BLOCK_INDEX)
!    SELF%PSTRCV(1:,0:) => SELF%F_PSTRCV%GET_VIEW(BLOCK_INDEX)
!    SELF%PSTRDU(1:,0:) => SELF%F_PSTRDU%GET_VIEW(BLOCK_INDEX)
!    SELF%PSTRDV(1:,0:) => SELF%F_PSTRDV%GET_VIEW(BLOCK_INDEX)
!    SELF%PSTRTU(1:,0:) => SELF%F_PSTRTU%GET_VIEW(BLOCK_INDEX)
!    SELF%PSTRTV(1:,0:) => SELF%F_PSTRTV%GET_VIEW(BLOCK_INDEX)
!    SELF%PDIFTL(1:,0:) => SELF%F_PDIFTL%GET_VIEW(BLOCK_INDEX)
!    SELF%PDIFTI(1:,0:) => SELF%F_PDIFTI%GET_VIEW(BLOCK_INDEX)
!    SELF%PFCCQL(1:,0:) => SELF%F_PFCCQL%GET_VIEW(BLOCK_INDEX)
!    SELF%PFCCQN(1:,0:) => SELF%F_PFCCQN%GET_VIEW(BLOCK_INDEX)
!    SELF%PFCSQL(1:,0:) => SELF%F_PFCSQL%GET_VIEW(BLOCK_INDEX)
!    SELF%PFCSQN(1:,0:) => SELF%F_PFCSQN%GET_VIEW(BLOCK_INDEX)
!    SELF%PFCQLNG(1:,0:) => SELF%F_PFCQLNG%GET_VIEW(BLOCK_INDEX)
!    SELF%PFCQNNG(1:,0:) => SELF%F_PFCQNNG%GET_VIEW(BLOCK_INDEX)
!    SELF%PFSQRF(1:,0:) => SELF%F_PFSQRF%GET_VIEW(BLOCK_INDEX)
!    SELF%PFSQSF(1:,0:) => SELF%F_PFSQSF%GET_VIEW(BLOCK_INDEX)
!    SELF%PFCQRNG(1:,0:) => SELF%F_PFCQRNG%GET_VIEW(BLOCK_INDEX)
!    SELF%PFCQSNG(1:,0:) => SELF%F_PFCQSNG%GET_VIEW(BLOCK_INDEX)
!    SELF%PFSQLTUR(1:,0:) => SELF%F_PFSQLTUR%GET_VIEW(BLOCK_INDEX)
!    SELF%PFSQITUR(1:,0:) => SELF%F_PFSQITUR%GET_VIEW(BLOCK_INDEX)
!    SELF%PAERODDF => SELF%F_PAERODDF%GET_VIEW(BLOCK_INDEX)
!    SELF%PENES => SELF%F_PENES%GET_VIEW(BLOCK_INDEX)
!  END SUBROUTINE FLUX_TYPE_UPDATE_VIEW
!
!  SUBROUTINE FLUX_TYPE_FINAL(SELF)
!    CLASS(FLUX_TYPE) :: SELF
!
!    CALL FIELD_DELETE (SELF%F_PFRSOD)
!    CALL FIELD_DELETE (SELF%F_PFRSODC)
!    CALL FIELD_DELETE (SELF%F_PUVDF)
!    CALL FIELD_DELETE (SELF%F_PPARF)
!    CALL FIELD_DELETE (SELF%F_PPARCF)
!    CALL FIELD_DELETE (SELF%F_PFRTHD)
!    CALL FIELD_DELETE (SELF%F_PFRTHDC)
!    CALL FIELD_DELETE (SELF%F_PTOFDU)
!    CALL FIELD_DELETE (SELF%F_PTOFDV)
!    CALL FIELD_DELETE (SELF%F_PFTG12)
!    CALL FIELD_DELETE (SELF%F_PFWEV)
!    CALL FIELD_DELETE (SELF%F_PFWSB)
!    CALL FIELD_DELETE (SELF%F_PFWG12)
!    CALL FIELD_DELETE (SELF%F_PFWMLT)
!    CALL FIELD_DELETE (SELF%F_PFWROD)
!    CALL FIELD_DELETE (SELF%F_PFWRO1)
!    CALL FIELD_DELETE (SELF%F_PFTLHEV)
!    CALL FIELD_DELETE (SELF%F_PFTLHSB)
!    CALL FIELD_DELETE (SELF%F_PFRSOC)
!    CALL FIELD_DELETE (SELF%F_PFRTHC)
!    CALL FIELD_DELETE (SELF%F_PDIFCQ)
!    CALL FIELD_DELETE (SELF%F_PDIFCS)
!    CALL FIELD_DELETE (SELF%F_PDIFTQ)
!    CALL FIELD_DELETE (SELF%F_PDIFTS)
!    CALL FIELD_DELETE (SELF%F_PFCQNG)
!    CALL FIELD_DELETE (SELF%F_PFPLCL)
!    CALL FIELD_DELETE (SELF%F_PFPLCN)
!    CALL FIELD_DELETE (SELF%F_PFPLCLO)
!    CALL FIELD_DELETE (SELF%F_PFPLCNO)
!    CALL FIELD_DELETE (SELF%F_PFPLSL)
!    CALL FIELD_DELETE (SELF%F_PFPLSN)
!    CALL FIELD_DELETE (SELF%F_PFHPCL)
!    CALL FIELD_DELETE (SELF%F_PFHPCN)
!    CALL FIELD_DELETE (SELF%F_PFHPSL)
!    CALL FIELD_DELETE (SELF%F_PFHPSN)
!    CALL FIELD_DELETE (SELF%F_PFRSO)
!    CALL FIELD_DELETE (SELF%F_PFRTH)
!    CALL FIELD_DELETE (SELF%F_PSTRCU)
!    CALL FIELD_DELETE (SELF%F_PSTRCV)
!    CALL FIELD_DELETE (SELF%F_PSTRDU)
!    CALL FIELD_DELETE (SELF%F_PSTRDV)
!    CALL FIELD_DELETE (SELF%F_PSTRTU)
!    CALL FIELD_DELETE (SELF%F_PSTRTV)
!    CALL FIELD_DELETE (SELF%F_PDIFTL)
!    CALL FIELD_DELETE (SELF%F_PDIFTI)
!    CALL FIELD_DELETE (SELF%F_PFCCQL)
!    CALL FIELD_DELETE (SELF%F_PFCCQN)
!    CALL FIELD_DELETE (SELF%F_PFCSQL)
!    CALL FIELD_DELETE (SELF%F_PFCSQN)
!    CALL FIELD_DELETE (SELF%F_PFCQLNG)
!    CALL FIELD_DELETE (SELF%F_PFCQNNG)
!    CALL FIELD_DELETE (SELF%F_PFSQRF)
!    CALL FIELD_DELETE (SELF%F_PFSQSF)
!    CALL FIELD_DELETE (SELF%F_PFCQRNG)
!    CALL FIELD_DELETE (SELF%F_PFCQSNG)
!    CALL FIELD_DELETE (SELF%F_PFSQLTUR)
!    CALL FIELD_DELETE (SELF%F_PFSQITUR)
!    CALL FIELD_DELETE (SELF%F_PENES)
!    CALL FIELD_DELETE (SELF%F_PAERODDF)
!  END SUBROUTINE FLUX_TYPE_FINAL
!
END MODULE ECPHYS_FLUX_TYPE_MOD
