MODULE SRFSN_TRISOLVER_MOD
USE PARKIND1, ONLY : JPIM, JPRB
IMPLICIT NONE
CONTAINS

SUBROUTINE TRISOLVER(KSNLAC,KLEVSN,ZA,ZB,ZC,ZF,ZTSTAR)
!! SINGLE POINT TRIDIAGONAL SOLVER !

!* DECLARATION OF ARGUMENTS
INTEGER(KIND=JPIM)  ,INTENT(IN)  :: KSNLAC ! NUMBER OF ACTIVE SNOW LAYERS
INTEGER(KIND=JPIM)  ,INTENT(IN)  :: KLEVSN
REAL(KIND=JPRB),INTENT(IN),DIMENSION(:)  :: ZA,ZB,ZC,ZF
REAL(KIND=JPRB),INTENT(INOUT),DIMENSION(:) :: ZTSTAR
!* LOCAL VARIABLES
INTEGER(KIND=JPIM)  :: JK
REAL(KIND=JPRB)     :: BET
REAL(KIND=JPRB),DIMENSION(KLEVSN) :: GAM

!$loki routine seq

BET=ZB(1)

ZTSTAR(1)=ZF(1)/BET
DO JK=2,KSNLAC
  GAM(JK)=ZC(JK-1)/BET
  BET=ZB(JK)-ZA(JK)*GAM(JK)
  ZTSTAR(JK)=(ZF(JK)-ZA(JK)*ZTSTAR(JK-1))/BET
ENDDO
DO JK=KSNLAC-1,1,-1
  ZTSTAR(JK)=ZTSTAR(JK)-GAM(JK+1)*ZTSTAR(JK+1)
ENDDO

END SUBROUTINE TRISOLVER

END MODULE SRFSN_TRISOLVER_MOD
