MODULE SRFSN_TRISOLVER_MOD
USE PARKIND1, ONLY : JPIM, JPRB
IMPLICIT NONE
CONTAINS

SUBROUTINE TRISOLVER(KLON,KSNLAC,KLEVSN,ZA,ZB,ZC,ZF,ZTSTAR,GAM,JLL)
!! SINGLE POINT TRIDIAGONAL SOLVER !

!* DECLARATION OF ARGUMENTS
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KSNLAC ! NUMBER OF ACTIVE SNOW LAYERS
INTEGER(KIND=JPIM), INTENT(IN) :: KLEVSN
INTEGER(KIND=JPIM), INTENT(IN) :: JLL
REAL(KIND=JPRB),INTENT(IN),DIMENSION(KLON,KLEVSN)  :: ZA,ZB,ZC,ZF
REAL(KIND=JPRB),INTENT(INOUT),DIMENSION(KLON,KLEVSN) :: ZTSTAR
REAL(KIND=JPRB),INTENT(INOUT),DIMENSION(KLON,KLEVSN) :: GAM
!* LOCAL VARIABLES
INTEGER(KIND=JPIM)  :: JK
REAL(KIND=JPRB)     :: BET

!$loki routine seq

BET=ZB(JLL,1)

ZTSTAR(JLL,1)=ZF(JLL,1)/BET
DO JK=2,KSNLAC
  GAM(JLL,JK)=ZC(JLL,JK-1)/BET
  BET=ZB(JLL,JK)-ZA(JLL,JK)*GAM(JLL,JK)
  ZTSTAR(JLL,JK)=(ZF(JLL,JK)-ZA(JLL,JK)*ZTSTAR(JLL,JK-1))/BET
ENDDO
DO JK=KSNLAC-1,1,-1
  ZTSTAR(JLL,JK)=ZTSTAR(JLL,JK)-GAM(JLL,JK+1)*ZTSTAR(JLL,JK+1)
ENDDO

END SUBROUTINE TRISOLVER

END MODULE SRFSN_TRISOLVER_MOD
