SUBROUTINE CALLPAR1S (CDCONF &
     & , IST,IEND,IBL,IPROMA,NPROMA &
     & , KIDIA,KFDIA,KLON,KLEVS,KTILES,KVTYPES &
     & , KLEV   ,KSTART ,KSTEP  ,KTRAC   &
     & , KLEVI  ,KLEVO  ,KLEVSN          &                      !KPP
     & , KDHVTLS,KDHFTLS,KDHVTSS,KDHFTSS &
     & , KDHVTTS,KDHFTTS,KDHVTIS,KDHFTIS &
     & , KDHVSSS,KDHFSSS,KDHVIIS,KDHFIIS &
     & , KDHVWLS,KDHFWLS,KDHVRESS,KDHFRESS &
     & , KDHVCO2S,KDHFCO2S &
     & , KDHVBIOS,KDHFBIOS,KDHVBVOCS,KDHVVEGS,KDHFVEGS &
     & , PTSPHY &
!-----------------------------------------------------------------------
! - INPUT .
     & , LLKEYS &
! - OUTPUT .
     & , PSURF, PSURFL, PAUX, PAUXL, PCLIM, PFLUX, PDIAG, PINTER, STATE, GEMSL, PDDHS ) 
! (C) Copyright 1995- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!**** *CALLPAR1S * - CALL PHYSICS

!     PURPOSE.
!     --------
!     - CALL THE SUBROUTINES OF THE PHYSICS PACKAGE.

!**   Interface.
!     ----------
!        *CALL* *CALLPAR1S*

!-----------------------------------------------------------------------

! -   INPUT ARGUMENTS.
!     -------------------

! - DIMENSIONS ETC.

! KIDIA   : START OF HORIZONTAL LOOP
! KFDIA   : END OF HORIZONTAL LOOP
! KLON    : HORIZONTAL DIMENSION
! KTRAC   : NUMBER OF TRACERS
! KLEVS   : NUMBER OF LEVELS IN SOIL
! KTILES  : NUMBER OF vegetation (surface cover) tiles
! KVTYPES : NUMBER OF VEGETATION TYPES
! KLEV    : END OF VERTICAL LOOP AND VERTICAL DIMENSION
! KSTART  : FIRST STEP OF MODEL
! KSTEP   : CURRENT TIME STEP
!    *KLEVSN*       Number of snow layers (diagnostics) 
!    *KLEVI*        Number of sea ice layers (diagnostics)
!    *KDHVTLS*      Number of variables for individual tiles
!    *KDHFTLS*      Number of fluxes for individual tiles
!    *KDHVTSS*      Number of variables for snow energy budget
!    *KDHFTSS*      Number of fluxes for snow energy budget
!    *KDHVTTS*      Number of variables for soil energy budget
!    *KDHFTTS*      Number of fluxes for soil energy budget
!    *KDHVTIS*      Number of variables for sea ice energy budget
!    *KDHFTIS*      Number of fluxes for sea ice energy budget
!    *KDHVIIS*      Number of variables for interception water budget
!    *KDHFIIS*      Number of fluxes for interception water budget
!    *KDHVWLS*      Number of variables for soil water budget
!    *KDHFWLS*      Number of fluxes for soil water budget
!    *KDHVRESS*     Number of variables for resistances 
!    *KDHFRESS*     Number of fluxes for resistances

!    *KDHVCO2S*     Number of variables for CO2
!    *KDHFCO2S*     Number of fluxes for CO2
!    *KDHVBIOS*     Number of variables for biomass
!    *KDHFBIOS*     Number of fluxes for biomass
!    *KDHVBVOCS*    Number of variables for BVOC
!    *KDHVVEGS*     Number of variables for variables per vegetation type
!    *KDHFVEGS*     Number of fluxes for variables per vegetation type

! PTSPHY  : PHYSICS TIME STEP

! - 2D (0:KLEV) .

! PAPRS      : PRESSURE ON HALF-LEVELS.

! - 2D (1:KLEV) .

! PGEOM1     : GEOPOTENTIAL ON FULL LEVELS.
! PU         : X-COMPONENT OF WIND.
! PV         : Y-COMPONENT OF WIND.
! PT         : TEMPERATURE.
! PQ         : SPECIFIC HUMIDITY (WATER VAPOUR).

! - 1D (PROGNOSTIC QUANTITIES) .

! PSNS       : SNOW DEPTH (kg m-2)
! PASN       : Snow albedo (0-1)
! PRSN       : Snow density (kg m-3)
! PTSN       : Snow temperature (K)
! PTSA       : MULTI-LAYER SOIL TEMPERATURE
! PWSA       : MULTI-LAYER SOIL WETNESS
! PWL        : SKIN RESERVOIR WATER CONTENT (kg m-2)
! PTL        : SKIN TEMPERATURE
! PTIA       : MULTI-LAYER ICE TEMPERATURE

! - 1D (GEOGRAPHICAL DISTRIBUTION) .

! PALBF      : BACKGROUND SURFACE SHORTWAVE ALBEDO (SNOW-FREE).
! PALUVP     : MODIS ALBEDO UV-VIS PARALLEL (DIRECT) RADIATION
! PALUVD     : MODIS ALBEDO UV-VIS DIFFUSE RADIATION
! PALNIP     : MODIS ALBEDO NEAR IR PARALLEL (DIRECT) RADIATION
! PALNID     : MODIS ALBEDO NEAR IR DIFFUSE RADIATION
! PAL[UV|NI][I|V|G] : 6-component MODIS albedo coefficients
! PSDOR      : OROGRAPHIC STANDARD DEVIATION (M)
! PGEMU      : SIN of latitude
! PLSM       : LAND/SEA MASK.
! PZ0MCL     : ROUGHNESS LENGTH   (NB: Units   m)
! PMU0M      : LOCAL COSINE OF INSTANTANEOUS MEAN SOLAR ZENITH ANGLE.
! PZ0HCL     : ROUGHNESS LENGTH FOR HEAT   (NB: Units   m)
! PTVL       : LOW VEGETATION TYPE
! PCO2TYP   : TYPE OF PHOTOSYNTHESIS PATHWAY FOR LOW VEGETATION (C3/C4)
! PISOP_EP   : Isoprene emission potential
! PTVH       : HIGH VEGETATION TYPE

! PLAIH      : LEAF AREA INDEX HIGH
! PLAIL      : LEAF AREA INDEX LOW
! PRSMH      : STOMATAL RESISTANCE HIGH VEGETATION
! PRSML      : STOMATAL RESISTANCE LOW VEGETATION
! PANDAYVT   : DAILY NET CO2 ASSIM.OVER CANOPY PER VEGTYPE     KG_CO2/M2
! PANFMVT    : MAXIMUM LEAF ASSIMILATION PER VEGTYPE         KG_CO2/KG_AIR M/S  
! PRESPBSTR  : RESPIRATION OF ABOVE GROUND STRUCTURAL BIOMASS    KG_CO2/M2
! PRESPBSTR2 : RESPIRATION OF BELOW GROUND STRUCTURAL BIOMASS    KG_CO2/M2
! PBIOMASS_LAST: (ACTIVE) LEAF BIOMASS OF PREVIOUS DAY               KG/M2
!     NB: value only after nitro_decline, not after laigain!!!!
! PBIOMASSTR_LAST: ABOVE GROUND STRUCTURAL BIOMASS OF PREVIOUS DAY   KG/M2
! PBIOMASSTR2_LAST: BELOW GROUND STRUCTURAL BIOMASS OF PREVIOUS DAY  KG/M2
! PBLOSSVT   : ACTIVE BIOMASS LOSS                                   KG/M2
! PBGAINVT   : ACTIVE BIOMASS GAIN                                   KG/M2


! PSOTY      : SOIL TYPE
! PCVL       : LOW VEGETATION COVER
! PCVH       : HIGH VEGETATION COVER
! PCUR       : URBAN COVER (PASSIVE)
! PCFLX      : TRACER SURFACE FLUX
! PUSTRTI    : (INSTANTANEOUS) TILED SURFACE STRESS U-COMPONENT
! PVSTRTI    : (INSTANTANEOUS) TILED SURFACE STRESS V-COMPONENT
! PAHFSTI    : (INSTANTANEOUS) TILED SURFACE SENSIBLE HEAT FLUX
! PEVAPTI    : (INSTANTANEOUS) TILED EVAPORATION
! PTSKTI     : TILED SKIN TEMPERATURE
! PSLRFLTI    : Tile net longwave (not I/O of callpar1s)

! - 2D (1:KLEV) AT T+1 .

! PT1        : TEMPERATURE AT T+1
! PQ1        : HUMIDITY AT T+1
! PU1        : U-COMP. AT T+1
! PV1        : V-COMP. AT T+1

! - 1D (SURFACE 1D FORCING) .

! PSRSOD     : SURFACE SHORTWAVE RADIATIVE FLUX DOWNWARDS.
! PSRTHD     : SURFACE LONGWAVE RADIATIVE FLUX DOWNWARDS.
! PFPLCL     : CONVECTIVE PRECIPITATION AS RAIN.
! PFPLCN     : CONVECTIVE PRECIPITATION AS SNOW.
! PFPLSL     : STRATIFORM PRECIPITATION AS RAIN.
! PFPLSN     : STRATIFORM PRECIPITATION AS SNOW.
!-----------------------------------------------------------------------

! -   OUTPUT ARGUMENTS.
!     --------------------

! - 2D (0:KLEV) FLUXES .

! PDIFTQ     : TURBULENT FLUX (INC. Q NEGATIVE) OF SPECIFIC HUMIDITY.
! PDIFTS     : TURBULENT FLUX OF HEAT.
! PFRSO      : SHORTWAVE RADIATIVE FLUX.
! PFRTH      : LONGWAVE RADIATIVE FLUX.
! PSTRTU     : TURBULENT FLUX OF MOMENTUM "U".
! PSTRTV     : TURBULENT FLUX OF MOMENTUM "V".

! PAN        : NET CO2 ASSIMILATION OVER CANOPY.          
! PAG        : GROSS CO2 ASSIMILATION OVER CANOPY.       
! PRD        : DARK RESPIRATION.                         
! PRSOIL_STR : RESPIRATION FROM SOIL AND STRUCTURAL BIOMASS.
! PRECO      : ECOSYSTEM RESPIRATION.                   
! PCO2FLUX   : CO2 FLUX.
! PCH4FLUX   : CH4 FLUX.
! PBVOCFLUX  : Biogenic VOC FLUX.

! - 1D (TENDENCIES FROM SURFACE SCHEME)

! PSNSE1     : OF SNOW MASS PER UNIT SURFACE
! PASNE1     : of snow albedo
! PRSNE1     : of snow density
! PTSNE1     : of snow temperature
! PWLE1      : OF SKIN RESERVOIR WATER CONTENT
! PTLE1      : OF SKIN TEMPERATURE
! PTSAE1     : OF MULTI-LAYER SOIL TEMPERATURE
! PWSAE1     : OF MULTI-LAYER SOIL WETNESS
! PTIAE1     : OF MULTI-LAYER ICE TEMPERATURE

! PLAIE1     : OF LAI PER VEGETATION TYPE
! PBSTRE1    : OF ABOVE GROUND STRUCTURAL BIOMASS PER VEGETATION TYPE 
! PBSTR2E1   : OF BELOW GROUND STRUCTURAL BIOMASS PER VEGETATION TYPE 


! - 1D (DIAGNOSTIC) .

! PLAI       : LAI (M2/M2)
! PBIOM      : BIOMASS (KG/M2)
! PBLOSS     : BIOMASS LOSS (KG/M2)
! PBGAIN     : BIOMASS GAIN (KG/M2)
! PBIOMSTR   : ABOVE GROUND STRUCTURAL BIOMASS (KG/M2)
! PBIOMSTR2  : BELOW GROUND STRUCTURAL BIOMASS (KG/M2)


! PALB       : MODEL SURFACE SHORTWAVE ALBEDO.
! PFTLHEV    : SURFACE LATENT HEAT FLUX (SNOW FREE FRACTION)
! PFTLHSB    : SURFACE LATENT HEAT FLUX (SNOW COVERED FRACTION)
! PFTG12     : HEAT FLUX FROM LAYER 1 TO 2
! PFWEV      : SURFACE WATER VAPOUR FLUX (EVAPORATION)
! PFWSB      : SURFACE WATER VAPOUR FLUX (SUBLIMATION)
! PFWG12     : WATER FLUX FROM LAYER 1 TO 2
! PFWMLT     : WATER FLUX CORRESPONDING TO SURFACE SNOW MELT.
! PZ0M       : ROUGHNESS LENGTH (CURRENT)    (NB: Units   m)
! PZ0H       : ROUGHNESS LENGTH FOR HEAT (CURRENT)   (NB: Units   m)
! PFWROD     : RUN-OFF FLUX AT DEEPER LAYERS (2-4)
! PFWRO1     : RUN-OFF FLUX AT LAYER 1
! PVDIS      : TURBULENT DISSIPATION
!    *PU10M*        U-COMPONENT WIND AT 10 M                      M/S
!    *PV10M*        V-COMPONENT WIND AT 10 M                      M/S
!    *PT2M*         TEMPERATURE AT 2M                                K
!    *PD2M*         DEW POINT TEMPERATURE AT 2M                      K
!    *PQ2M*         SPECIFIC HUMIDITY AT 2M                       KG/KG
!    *PMEAN*        AREA AVERAGED WIND SP. AT 10 M INT. FROM KLEV   M/S
!    *PGUST*        GUST AT 10 M                                    M/S
!    *PZIDLWV*      Zi/L used for gustiness in wave model           m/m
!                   (NOTE: Positive values of Zi/L are set to ZERO)
!    *PBLH*         BOUNDARY LAYER HEIGHT                            M
!    *PDHTLS*       Diagnostic array for tiles (see module yomcdh)
!    *PDHTTS*       Diagnostic array for soil T (see module yomcdh)
!                      (Wm-2 for fluxes)
!    *PDHTIS*       Diagnostic array for ice T (see module yomcdh)
!                      (Wm-2 for fluxes)
!    *PDHTSS*     Diagnostic array for snow T (see module yomcdh)
!                      (Wm-2 for fluxes)
!    *PDHSSS*     Diagnostic array for snow mass (see module yomcdh)
!                      (m/s for fluxes)
!    *PDHIIS*     Diagnostic array for interception layer (see module yomcdh)
!    *PDHWLS*     Diagnostic array for soil water (see module yomcdh)
!    *PDHRESS*      Diagnostic array for resistances (see module yomcdh) 

!    *PDHCO2S*    Diagnostic array for CO2 (see module yomcdh)
!    *PDHBIOS*    Diagnostic array for biomass (see module yomcdh)
!    *PDHBVOCS*   Diagnostic array for BVOC emissions (see module yomcdh)
!    *PDHVEGS*    Diagnostic array for variables per vegetation type
!                (see module yomcdh)


!-----------------------------------------------------------------------

!     Externals.  RADSRF -
!     ---------   VDFMAIN1S-
!                 SRFMAIN-

!     Method. See documentaion.
!     -------
!     Modifications.
!     --------------
!     ORIGINAL 95-03-08 Pedro VITERBO
!            2008-01-22 Victor STEPANENKO
!     Components of wind stress (PUSTRTI AND PVSTRTI)
!     and sea surface temperature (PSST) are added to the arguments of subroutine SURFTSTP  
!     S. Boussetta/G.Balsamo May 2010 Add CTESSEL based on: 
!     Marita Voogt (KNMI) CTESSEL
!     Sebastien simplified CTESSEL
!     E. Dutra      29/05/2014      net longwave tiled
!     R. Hogan      15/01/2019      6-component MODIS albedo coefficients

!-----------------------------------------------------------------------
!     ******************************************************************
!     ****** IDIOSYNCRASIES *** IDIOSYNCRASIES *** IDIOSYNCRASIES ******
!     ******************************************************************
!     ***  MOREOVER, WATER IN DEEPER LAYERS HAS TO BE NORMALIZED TO  ***
!     ***  THE FIRST LAYER DEPTH. THIS IS EQUIVALENT TO A CHANGE OF  ***
!     ***  UNITS FROM PURE VOLUMETRIC UNITS (M3/M3, USED ELSEWHERE   ***
!     ***  IN THE CODE) TO MODIFIED VOLUMETRIC UNITS, NORMALIZED BY  ***
!     ***  THE DEPTH OF THE FIRST LAYER (M/0.07M, USED IN THE        ***
!     ***  PHYSICS)                                                  ***
!     ******************************************************************
!     ******************************************************************

USE YOMLUN1S , ONLY : NULOUT
USE YOMGF1S  , ONLY : RALT     ,RZUV

USE YOMCST   , ONLY : RSIGMA   ,RDAY
USE YOERAD   , ONLY : NSW      ,NTSW, NLWEMISS
USE YOERDI1S , ONLY : REMISS
USE YOMRIP   , ONLY : RSTATI   ,NSSSSS
USE YOEPHY   , ONLY : LERADS, LESICE, LESURF, LEVDIF, LECTESSEL, LEINTWIND, LEWARMSTART, LESNML,LESNICE, NALBEDOSCHEME, NCWS, LBVOC_EMIS
USE YOETHF   , ONLY : RHOH2O
USE YOMLOG1S , ONLY : LSEMISS
USE YOMGDI1S , ONLY : D1SRFLD  ,D1SRFLU  ,D1TRFLD  ,D1TRFLU &
     &             , D1SALB, D1SWDS  ,D1SSDS   ,D1SWLDS

USE YOMDPHY  ,ONLY : YSURF, NCSS
USE YOMSURF_SSDP_MOD, ONLY: NSSDP3D
USE PARKIND1 ,ONLY : JPIM     ,JPRB, JPRD, JPIB
USE YOMHOOK  ,ONLY : LHOOK    ,DR_HOOK, JPHOOK

USE MPL_MODULE

USE ECLAND_ATMO_TYPE_MOD,       ONLY: ATMO_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD,   ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECLAND_AUX_TYPE_MOD,        ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_FLUX_TYPE_MOD,       ONLY: FLUX_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY: CLIMATE_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY: INTERNAL_TYPE
USE ECLAND_GEMS_TYPE_MOD,       ONLY: GEMS_LOCAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY: SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY: SURF_AND_MORE_LOCAL_TYPE, DDH_SURF_TYPE 

IMPLICIT NONE


TYPE(AUX_DIAG_TYPE)           , INTENT(INOUT) :: PDIAG
TYPE(AUX_DIAG_LOCAL_TYPE)     , INTENT(INOUT) :: PAUXL
TYPE(AUX_TYPE)                , INTENT(INOUT) :: PAUX
TYPE(INTERNAL_TYPE)           , INTENT(INOUT) :: PINTER
TYPE(CLIMATE_TYPE)            , INTENT(INOUT) :: PCLIM
TYPE(FLUX_TYPE)               , INTENT(INOUT) :: PFLUX
TYPE(ATMO_TYPE)               , INTENT(INOUT) :: STATE
TYPE(GEMS_LOCAL_TYPE)         , INTENT(INOUT) :: GEMSL 
TYPE(KEYS_LOCAL_TYPE)         , INTENT(INOUT) :: LLKEYS  
TYPE(SURF_AND_MORE_TYPE)      , INTENT(INOUT) :: PSURF
TYPE(DDH_SURF_TYPE)           , INTENT(INOUT) :: PDDHS
TYPE(SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: PSURFL

!*
!     ------------------------------------------------------------------
CHARACTER*1,INTENT(IN) :: CDCONF

INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA,KFDIA,KLON,KLEVS,KTILES &
     &                         , KLEV   , KSTART , KSTEP ,KTRAC &
     &                         , KLEVSN ,KLEVI  ,KDHVTLS,KDHFTLS,KDHVTSS,KDHFTSS &
     &                         , KDHVTTS,KDHFTTS,KDHVTIS,KDHFTIS &
     &                         , KDHVSSS,KDHFSSS, KDHVIIS,KDHFIIS &
     &                         , KDHVWLS ,KDHFWLS ,KDHVRESS,KDHFRESS &
     &                         , KLEVO  !KPP 

INTEGER(KIND=JPIM),INTENT(IN)    :: KVTYPES
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVCO2S 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFCO2S 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVBIOS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFBIOS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVBVOCS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVVEGS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFVEGS
 REAL(KIND=JPRB) :: PTSPHY

!
!!            0.2  LOCAL VARIABLES
!!                 ---------------
!
!REAL(KIND=JPRB) :: ZEMIR(KLON),ZEMIW(KLON)
REAL(KIND=JPRB) :: ZFAC(KLON)
REAL(KIND=JPRD) :: ZJUL ! needed jprd for dattim
INTEGER(KIND=JPIM) :: IMON(12)
INTEGER(KIND=JPIM) :: IYY,IMM,IDD,IINC,ISEC0,IYMD,IHM
INTEGER(KIND=JPIM) :: JK,JL,JTILE,JVT
LOGICAL LDEBUGPRINT
!
!REAL(KIND=JPRB)  :: PALBICEF(KLON)
LOGICAL          :: LNEMOLIMALB
LOGICAL          :: LNEMOICETHK
!
INTEGER(KIND=JPIM) :: JPDIAG=12
!REAL(KIND=JPRB)  :: ZEXDIAG(KLON,12)
!
INTEGER(KIND=JPIM), INTENT(IN) :: IST,IEND,IBL,IPROMA,NPROMA
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


#include "surfbc.h"
#include "surfws.h"
#include "surfrad.h"
#include "surftstp.h"

#include "updcal.intfb.h"
#include "vdfmain1s.intfb.h"

#include "fcttim.h"

IF (LHOOK) CALL DR_HOOK('CALLPAR1S',0,ZHOOK_HANDLE)

!    ------------------------------------------------------------------

!*         1.     INITIAL COMPUTATIONS.
!                 ---------------------

!* Interpolate wind to correct height 
!IF(RALT.NE.RZUV) THEN
IF(RALT .NE. RZUV .AND. KSTEP .NE. KSTART ) THEN
    ZFAC(1:IPROMA)=LOG(RALT/GEMSL%PZ0M(1:IPROMA))/LOG(RZUV/GEMSL%PZ0M(1:IPROMA))
    STATE%PU(1:IPROMA)  = ZFAC* STATE%PU(1:IPROMA)
    STATE%PV(1:IPROMA)  = ZFAC* STATE%PV(1:IPROMA)
    STATE%PU1(1:IPROMA) = ZFAC*STATE%PU1(1:IPROMA)
    STATE%PV1(1:IPROMA) = ZFAC*STATE%PV1(1:IPROMA)
ENDIF


!*      1.2  TENDENCIES OF FORCINGS

 PSURF%ZTE(1:IPROMA)=(STATE%PT1(1:IPROMA)-STATE%PT(1:IPROMA))/PTSPHY
 PSURF%ZQE(1:IPROMA)=(STATE%PQ1(1:IPROMA)-STATE%PQ(1:IPROMA))/PTSPHY
PSURF%ZVOM(1:IPROMA)=(STATE%PU1(1:IPROMA)-STATE%PU(1:IPROMA))/PTSPHY
PSURF%ZVOL(1:IPROMA)=(STATE%PV1(1:IPROMA)-STATE%PV(1:IPROMA))/PTSPHY
IF(KTRAC .GT. 0 ) THEN
  PSURF%ZTENC(1:IPROMA,1:KTRAC)= &
    &   (GEMSL%PC1(1:IPROMA,1:KTRAC)-GEMSL%PC(1:IPROMA,1:KTRAC))/PTSPHY
ENDIF


PSURFL%ZCSN(1:IPROMA)=0.0_JPRB
!*      1.3a   AUXILLIARY VARIABLES FOR VDF, SRF AND RADSRF
!

  CALL SURFBC (YSURF=YSURF,KIDIA=1,KFDIA=IPROMA,KLON=KLON,KTILES=KTILES,KLEVSN=KLEVSN,&
   & PSSDP2=PINTER%PSSDP2(:,:), PTVL=PCLIM%PTVL(:),PCO2TYP=PCLIM%PCO2TYP(:),&
   & PTVH=PCLIM%PTVH(:), PSOTY=PCLIM%PSOTY(:),PSDOR=PSURF%PSDOR(:),PCVLC=PCLIM%PCVL(:), &
   & PCVHC=PCLIM%PCVH(:),PCURC=PCLIM%PCUR(:),&
   &  PLAILC=PSURF%GSD%PLAILC(:), PLAIHC=PSURF%GSD%PLAIHC(:),&
   &  PLAILI=   PSURFL%PLAILI(:), PLAIHI=   PSURFL%PLAIHI(:),&
   & PLAILCP=PSURF%GSD%PLAILC(:),PLAIHCP=PSURF%GSD%PLAIHC(:),&
   & PAVGPARC=PSURF%GSD%ZAVGPARC(:),&
   & PLSM=PCLIM%PLSM(:),PCI=PCLIM%PCI(:),PCIL=PSURF%PCIL(:),&
   & PCLAKE=PCLIM%PCLAKE(:),PHLICE=PSURF%GSP%PHLICE(:),&
   & PGEMU=PAUX%PGEMU(:),PSNM1M=PSURFL%PSNS(:,:),PWLM1M=PSURFL%PWL(:),PRSNM1M=PSURFL%PRSN(:,:), &
   & LESNICE=LESNICE,&
   & LDLAND=LLKEYS%LLLAND(:),LDSICE=LLKEYS%LLSICE(:),LDLICE=LLKEYS%LLLICE(:),LDLAKE=LLKEYS%LLLAKE(:),&
   & LDNH=LLKEYS%LLNH(:),LDOCN_KPP=LLKEYS%LLOCN_KPP(:),&
   & KTVL=PSURF%ITVL(:),KCO2TYP=PSURF%ICO2TYP(:),KTVH=PSURF%ITVH(:),KSOTY=PSURF%ISOTY(:),&
   & PCVL=PSURF%ZCVL(:),PCVH=PSURF%ZCVH(:),PCUR=PSURF%ZCUR(:),PLAIL=PSURFL%ZLAIL(:),PLAIH=PSURFL%ZLAIH(:),&
   & PLAILP=PSURF%ZLAILP(:),PLAIHP=PSURF%ZLAIHP(:),&
   & PAVGPAR=PSURF%ZAVGPAR(:), &
   & PWLMX=PSURFL%ZWLMX(:),PFRTI=PSURFL%ZFRTI(:,:), PCSN=PSURFL%ZCSN(:))

!*      1.3   GLOBAL AUXILLIARY VARIABLES
  PSURF%ZCHAR(1:IPROMA)=0.018_JPRB
PSURF%ZCHARHQ(1:IPROMA)=0.006_JPRB


!*      1.3a   GLOBAL OCEAN TEMPORALY SET TO ZERO (to check with PJ)
PSURF%PUSTOKES(1:IPROMA)=0.0_JPRB
PSURF%PVSTOKES(1:IPROMA)=0.0_JPRB
PSURF%GSD%PTAUOCX(1:IPROMA)=0.0_JPRB
PSURF%GSD%PTAUOCY(1:IPROMA)=0.0_JPRB
PSURF%PPHIOC(1:IPROMA)=0.0_JPRB
PSURF%PWSEMEAN(1:IPROMA)=0.0_JPRB
PSURF%PWSFMEAN(1:IPROMA)=0.0_JPRB

!*       1.4  SET SURFACE TENDENCIES TO ZERO
PSURF%PTSAE1(1:IPROMA,1:KLEVS)=0.0_JPRB
PSURF%PWSAE1(1:IPROMA,1:KLEVS)=0.0_JPRB
PSURF%PTIAE1(1:IPROMA,1:KLEVS)=0.0_JPRB
PSURF%PTLE1(1:IPROMA)=0.0_JPRB
PSURF%PWLE1(1:IPROMA)=0.0_JPRB
PSURF%PSNSE1(1:IPROMA,1:KLEVSN)=0.0_JPRB
PSURF%PTSNE1(1:IPROMA,1:KLEVSN)=0.0_JPRB
PSURF%PRSNE1(1:IPROMA,1:KLEVSN)=0.0_JPRB
PSURF%PWSNE1(1:IPROMA,1:KLEVSN)=0.0_JPRB
PSURF%PASNE1(1:IPROMA)=0.0_JPRB
PSURF%ZUCURR(1:IPROMA)=0.0_JPRB
PSURF%ZVCURR(1:IPROMA)=0.0_JPRB

!* FLAKE
PSURF%PTLICEE1(1:IPROMA)=0.0_JPRB
PSURF%PTLMNWE1(1:IPROMA)=0.0_JPRB
PSURF%PTLWMLE1(1:IPROMA)=0.0_JPRB
PSURF%PTLBOTE1(1:IPROMA)=0.0_JPRB
PSURF%PTLSFE1(1:IPROMA)=0.0_JPRB
PSURF%PHLICEE1(1:IPROMA)=0.0_JPRB
PSURF%PHLMLE1(1:IPROMA)=0.0_JPRB
!* FLAKE 

PSURF%PUOE1(1:IPROMA,1:KLEVO+1)=0.0_JPRB !KPP
PSURF%PVOE1(1:IPROMA,1:KLEVO+1)=0.0_JPRB !KPP
PSURF%PTOE1(1:IPROMA,1:KLEVO+1)=0.0_JPRB !KPP
PSURF%PSOE1(1:IPROMA,1:KLEVO+1)=0.0_JPRB !KPP
PSURF%GSP%PUOC(1:IPROMA,1:KLEVO+1)=0.0_JPRB  !KPP
PSURF%GSP%PVOC(1:IPROMA,1:KLEVO+1)=0.0_JPRB  !KPP
PSURF%PUSTRC(1:IPROMA)=0.0_JPRB          !KPP
PSURF%PVSTRC(1:IPROMA)=0.0_JPRB          !KPP

!* CTESSEL
PSURF%PLAIE1(1:IPROMA,1:KVTYPES)=0.0_JPRB
PSURF%PBSTRE1(1:IPROMA,1:KVTYPES)=0.0_JPRB
PSURF%PBSTR2E1(1:IPROMA,1:KVTYPES)=0.0_JPRB
!* CTESSEL

!     ------------------------------------------------------------------

!*         2.     RADIATION TRANSFER
!                 ------------------

!*         2.2 SURFACE BOUNDARY CONDITIONS
IF (LERADS) THEN
!* get time variables
    CALL DATTIM(ZJUL,IYMD,IHM)  
    IDD=NDD(IYMD)
    IMM=NMM(IYMD) 
    IYY=NCCAA(IYMD)
    IINC=0
    ISEC0=MOD(NSSSSS+NINT(RSTATI,KIND=JPIB),NINT(RDAY))   
    CALL UPDCAL  (IDD,IMM,IYY,IINC,IDD,IMM,IYY,IMON,-1_JPIM)  
    PAUXL%ZWND(1:IPROMA)=SQRT(STATE%PU(1:IPROMA)**2  &
   &                                +STATE%PV(1:IPROMA)**2)
    PSURF%GSP%ZWS1(1:IPROMA)=PSURF%GSP%PWSA(1:IPROMA,1)
    LDEBUGPRINT=.FALSE.
!   IF (LDEBUGPRINT) THEN
!     PRINT *,"DEBUG SURFRAD -->"
!     PRINT *,"NSW",NSW
!     PRINT *,"LLNH",LLNH
!     PRINT *,"PALBF",PALBF
!     PRINT *,"PASN",PASN
!     PRINT *,"PMU0M",PMU0M
!     PRINT *,"PTL",PTL
!     PRINT *,"ZWND",ZWND
!     PRINT *,"ZWS1",ZWS1
!     PRINT *,"ZFRTI",ZFRTI
!     PRINT *,"ZALBD(:,1:NSW)",ZALBD(:,1:NSW)
!     PRINT *,"ZALBP(:,1:NSW)",ZALBP(:,1:NSW)
!     PRINT *,"PALB",PALB
!     PRINT *,"ZEMIR",ZEMIR
!     PRINT *,"ZEMIW",ZEMIW
!     PRINT *,"ZEMIS",ZEMIS
!     PRINT *,"ZALBTI",ZALBTI
!     PRINT *,"ZCCNL",ZCCNL
!     PRINT *,"ZCCNO",ZCCNO
!   ENDIF
    LNEMOLIMALB=.FALSE.
    PSURF%GSD%PALBICEF(:) = -999._JPRB
    
    CALL SURFRAD &
     &     ( YSURF,KDD=IDD, KMM=IMM, KMON=IMON  , KSECO=ISEC0 &
     &     , KIDIA=1, KFDIA=IPROMA, KLON=KLON   , KTILES=KTILES , KCSS=NCSS, KSSDP3D=NSSDP3D, KSW=NSW, KLW=NLWEMISS &
     &     , LDNH=LLKEYS%LLNH(:),LDLAND=LLKEYS%LLLAND(:) &
     &     , PSSDP3=PINTER%PSSDP3(:,:,:) &
     &     , PALBF=PSURF%GSD%PALBF(:) ,PALBICEF=PSURF%GSD%PALBICEF(:),PTVH=PCLIM%PTVH(:) &
     &     , PALCOEFF=PSURF%GSD%ZALCOEFF(:,:) ,PCUR=PCLIM%PCUR(:), PCVH=PCLIM%PCVH(:) &
     &     , PASN=PSURF%GSP%PASN(:)   , PMU0=PAUX%PMU0M(:)  , PTS=PSURF%GSP%PTL(:)    , PWND=PAUXL%ZWND(:) &
     &     , PWS1=PSURF%GSP%ZWS1(:), KSOTY=PSURF%ISOTY(:) &
     &     , PFRTI=PSURFL%ZFRTI(:,:),PHLICE=PSURF%GSP%PHLICE(:),PTLICE=PSURF%GSP%PTLICE(:) &
     &     , PALBD=PSURFL%ZALBD(:,1:NSW)  , PALBP=PSURFL%ZALBP(:,1:NSW)  , PALB=PCLIM%PALB(:) &
     &     , PSPECTRALEMISS=PSURFL%ZSPECTRALEMISS(:,1:NLWEMISS) , PEMIT=PSURF%ZEMIS(:) &
     &     , PALBTI=PSURFL%ZALBTI(:,:), PCCNL=PAUXL%ZCCNL(:), PCCNO=PAUXL%ZCCNO(:) &
     &     , LNEMOLIMALB=LNEMOLIMALB&
     &     , LESNICE=LESNICE)
!   ZEMIR(IST:IEND) = PSURFL%ZSPECTRALEMISS(1:IPROMA,1)
!   ZEMIW(IST:IEND) = PSURFL%ZSPECTRALEMISS(1:IPROMA,2)

!      PRINT *,"PMU0M",PMU0M
!   IF (LDEBUGPRINT) THEN
!     PRINT *,"DEBUG SURFRAD <--"
!     PRINT *,"NSW",NSW
!     PRINT *,"LLNH",LLNH
!     PRINT *,"PALBF",PALBF
!     PRINT *,"PASN",PASN
!     PRINT *,"PMU0M",PMU0M
!     PRINT *,"PTL",PTL
!     PRINT *,"ZWND",ZWND
!     PRINT *,"ZWS1",ZWS1
!     PRINT *,"ZFRTI",ZFRTI
!     PRINT *,"ZALBD(:,1:NSW)",ZALBD(:,1:NSW)
!     PRINT *,"ZALBP(:,1:NSW)",ZALBP(:,1:NSW)
!     PRINT *,"PALB",PALB
!     PRINT *,"ZEMIR",ZEMIR
!     PRINT *,"ZEMIW",ZEMIW
!     PRINT *,"ZEMIS",ZEMIS
!     PRINT *,"ZALBTI",ZALBTI
!     PRINT *,"ZCCNL",ZCCNL
!     PRINT *,"ZCCNO",ZCCNO
!   ENDIF
ELSE
  DO JK=1,KTILES
    PSURFL%ZALBTI(1:IPROMA,JK)=PSURF%GSD%PALBF(1:IPROMA)
  ENDDO
  PCLIM%PALB(1:IPROMA)=PSURF%GSD%PALBF(1:IPROMA)
  PSURF%ZEMIS(1:IPROMA)=REMISS
! ZEMIR(IST:IEND)=REMISS
! ZEMIW(IST:IEND)=REMISS
ENDIF
IF (LSEMISS) PSURF%ZEMIS(1:IPROMA)=REMISS
PFLUX%PFRSO(1:IPROMA,KLEV)=PSURF%PSRSOD(1:IPROMA)*(1._JPRB-PCLIM%PALB(1:IPROMA))
PFLUX%PFRTH(1:IPROMA,KLEV)=PSURF%ZEMIS(1:IPROMA)* &
     &       (PSURF%PSRTHD(1:IPROMA)-RSIGMA*PSURF%GSP%PTL(1:IPROMA)**4)

!*      1.3b 

IF ( (KSTEP==KSTART) .AND. (LEWARMSTART) )  THEN

  CALL SURFWS(YSURF=YSURF, KIDIA=1, KFDIA=IPROMA, KLON=KLON, KLEVS=KLEVS, KLEVSN=KLEVSN, KTILES=KTILES  &
             ,PSDOR=PSURF%PSDOR(:),LDSICE=LLKEYS%LLSICE(:)                                      &
             ,PLSM=PCLIM%PLSM(:), PCIL=PSURF%PCIL(:), PFRTI=PSURFL%ZFRTI(:,:), PMU0=PAUX%PMU0M(:)         &
             ,PTSAM1M=PSURF%GSP%PTSA(:,:), PTSKIN=PSURF%GSP%PTL(:),PALBSN=PSURF%GSP%PASN(:)                                    &
             ,PTSNM1M=PSURF%GSP%PTSN(:,:), PSNM1M=PSURFL%PSNS(:,:), PRSNM1M=PSURFL%PRSN(:,:), PWSNM1M=PSURFL%PWSN(:,:)                           )

ENDIF
         

!     ------------------------------------------------------------------

!*         3.     VERTICAL EXCHANGE OF U,V,T,Q BY TURBULENCE
!                 ------------------------------------------

IF ( LEVDIF ) THEN

!IF (LDEBUGPRINT) THEN
!   PRINT *, "DEBUG IN VDFMAIN1S:"
!   PRINT *, "------------------>"
!   PRINT *,'CDCONF',CDCONF
!   PRINT *,'KIDIA',KIDIA
!   PRINT *,'KFDIA',KFDIA
!   PRINT *,'KLON',KLON
!   PRINT *,'KLEV',KLEV
!   PRINT *,'KLEVS',KLEVS
!   PRINT *,'KSTEP',KSTEP
!   PRINT *,'KTILES',KTILES
!   PRINT *,'KTRAC',KTRAC
!   PRINT *,'KLEVSN',KLEVSN 
!   PRINT *,'KLEVI',KLEVI  
!   PRINT *,'KDHVTLS',KDHVTLS
!   PRINT *,'KDHFTLS',KDHFTLS
!   PRINT *,'KDHVTSS',KDHVTSS
!   PRINT *,'KDHFTSS',KDHFTSS
!   PRINT *,'KDHVTTS',KDHVTTS
!   PRINT *,'KDHFTTS',KDHFTTS
!   PRINT *,'KDHVTIS',KDHVTIS
!   PRINT *,'KDHFTIS',KDHFTIS
!   PRINT *,'PTSPHY',PTSPHY
!   PRINT *,'ITVL',ITVL
!   PRINT *,'ICO2TYP',ICO2TYP
!   PRINT *,'ITVH',ITVH
!   PRINT *,'ISOTY',ISOTY
!   PRINT *,'ZCVL',ZCVL
!   PRINT *,'ZCVH',ZCVH
!   PRINT *,'ZCUR',ZCUR
!   PRINT *,'ZCIL',PCIL
!   PRINT *,'ZLAIL',ZLAIL
!   PRINT *,'ZLAIH',ZLAIH
!   PRINT *,'ZLAILP',ZLAILP
!   PRINT *,'ZLAIHP',ZLAIHP
!   PRINT *,'ZAVGPAR',ZAVGPAR
!   PRINT *,'PU',PU  
!   PRINT *,'PV',PV  
!   PRINT *,'PT',PT  
!   PRINT *,'PQ',PQ  
!   PRINT *,'PC',PC  
!   PRINT *,'PAPRS',PAPRS
!   PRINT *,'PGEOM1',PGEOM1
!   PRINT *,'PTL',PTL
!   PRINT *,'PTSA',PTSA
!   PRINT *,'PWSA',PWSA
!   PRINT *,'PFRSO(1,KLEV)',PFRSO(1,KLEV)
!   PRINT *,'PFRTH(1,KLEV)',PFRTH(1,KLEV)
!   PRINT *,'ZEMIS',ZEMIS
!   PRINT *,'PTSN',PTSN
!   PRINT *,'PTIA',PTIA
!   PRINT *,'PSST',PSST  
!   PRINT *,'ZFRTI',ZFRTI 
!   PRINT *,'ZALBTI',ZALBTI
!   PRINT *,'ZWLMX',ZWLMX
!   PRINT *,'ZCHAR',ZCHAR 
!   PRINT *,'ZCHARHQ',ZCHARHQ 
!   PRINT *,'PTL',PTL
!! skin temp at latest rad timestep
!   PRINT *,'PCFLX',PCFLX
!   PRINT *,'PZ0M',PZ0M
!   PRINT *,'PZ0H',PZ0H
!   PRINT *,'PVDIS',PVDIS 
!   PRINT *,'PFTLHEV',PFTLHEV
!   PRINT *,'PFTLHSB',PFTLHSB
!   PRINT *,'PFWSB',PFWSB
!   PRINT *,'PU10M',PU10M 
!   PRINT *,'PV10M',PV10M 
!   PRINT *,'PT2M',PT2M  
!   PRINT *,'PD2M',PD2M 
!   PRINT *,'PQ2M',PQ2M 
!   PRINT *,'PBLH',PBLH 
!   PRINT *,'ZFRSOTI',ZFRSOTI
!   PRINT *,'ZEVAPSNW',ZEVAPSNW
!   PRINT *,'PGUST',PGUST
!   PRINT *,'PZIDLWV',PZIDLWV
!!-UPDATED TENDENCIES
!   PRINT *,'ZTE',ZTE   
!   PRINT *,'ZQE',ZQE   
!   PRINT *,'ZVOM',ZVOM  
!   PRINT *,'ZVOL',ZVOL  
!   PRINT *,'ZTENC',ZTENC 
!   PRINT *,'PTLE1',PTLE1
!!-UPDATED FIELDS FOR TILES
!   PRINT *,'PUSTRTI',PUSTRTI
!   PRINT *,'PVSTRTI',PVSTRTI
!   PRINT *,'PAHFSTI',PAHFSTI
!   PRINT *,'PEVAPTI',PEVAPTI
!   PRINT *,'PTSKTI',PTSKTI
!!-OUTPUT FLUXES
!   PRINT *,'PDIFTS',PDIFTS
!   PRINT *,'PDIFTQ',PDIFTQ
!   PRINT *,'PSTRTU',PSTRTU
!   PRINT *,'PSTRTV',PSTRTV
!!    PRINT *,'ZKH',ZKH
! ! DDH OUTPUTS
!   PRINT *,'PDHTLS',PDHTLS
!   PRINT *,'PDHTSS',PDHTSS
!   PRINT *,'PDHTTS',PDHTTS
!   PRINT *,'PDHTIS',PDHTIS
!ENDIF

!   Create space for diagnostic array (for possible pp of canopy resitances)
!   Put LAT/LON in field 1 an 2, just in case that it is needed in SURF for debugging.  
PSURFL%ZEXDIAG(1:IPROMA,11)=PAUX%GELAT(1:IPROMA) ! Latitude
PSURFL%ZEXDIAG(1:IPROMA,12)=PAUX%GELAM(1:IPROMA) ! Longitude

  CALL VDFMAIN1S ( CDCONF=CDCONF,&
 & KIDIA=1, KFDIA=IPROMA, KLON=KLON, KLEV=KLEV, KLEVS=KLEVS, KSTEP=KSTEP, KTILES=KTILES, KVTYPES=KVTYPES, KDIAG=JPDIAG,&
 & KTRAC=KTRAC, KLEVSN=KLEVSN, KLEVI=KLEVI, LDLAND=LLKEYS%LLLAND(:), &
 & KDHVTLS=KDHVTLS, KDHFTLS=KDHFTLS, KDHVTSS=KDHVTSS, KDHFTSS=KDHFTSS, &
 & KDHVTTS=KDHVTTS,KDHFTTS=KDHFTTS,KDHVTIS=KDHVTIS,KDHFTIS=KDHFTIS, &
 & KDHVCO2S=KDHVCO2S,KDHFCO2S=KDHFCO2S,KDHVBVOCS=KDHVBVOCS,KDHVVEGS= KDHVVEGS,KDHFVEGS=KDHFVEGS,  &
 & LESNICE=LESNICE,&
 & PMU0=PAUX%PMU0M(:)   , &
 & PTSPHY=PTSPHY,KTVL=PSURF%ITVL(:),KCO2TYP=PSURF%ICO2TYP(:),KTVH=PSURF%ITVH(:),PCVL=PSURF%ZCVL(:),PCVH=PSURF%ZCVH(:), &
!Note that PLAT argument is renamed as GELAT here to avoid duplication
 & PCUR=PCLIM%PCUR(:),PFWET=PSURF%PFWET(:),PLAT=PAUX%GELAT(:),PLAIL=PSURFL%ZLAIL(:),PLAIH=PSURFL%ZLAIH(:),&
 & PLAILP=PSURF%ZLAILP(:), PLAIHP=PSURF%ZLAIHP(:), PAVGPAR=PSURF%ZAVGPAR(:), PISOP_EP=PSURF%PISOP_EP(:), &
 & PCIL=PSURF%PCIL(:), &
 & PSNM1M=PSURFL%PSNS(:,:),PRSNM1M=PSURFL%PRSN(:,:), &
 & PUM1=STATE%PU(:) ,PVM1=STATE%PV(:)  ,PTM1=STATE%PT(:)  ,&
 & PQM1=STATE%PQ(:)  ,PCM1=GEMSL%PC(:,:)  ,&
 & PAPHM1=STATE%PAPRS(:,:),PGEOM1=STATE%PGEOM1(:,:),&
 & PTSKM1M=PSURF%GSP%PTL(:),PTSAM1M=PSURF%GSP%PTSA(:,:),PWSAM1M=PSURF%GSP%PWSA(:,:),&
 & PSSRFL=PFLUX%PFRSO(:,KLEV),PSLRFL=PFLUX%PFRTH(:,KLEV),PEMIS=PSURF%ZEMIS(:),&
 & PTSN=PSURF%GSP%PTSN(:,:), PTICE=PSURF%GSP%PTIA(:,:),&
 & PHLICE=PSURF%GSP%PHLICE(:), PTLICE=PSURF%GSP%PTLICE(:), PTLWML=PSURF%GSP%PTLWML(:), &                             !FLAKE
 & PSST=PSURF%GSP%PSST(:)  ,KSOTY=PSURF%ISOTY(:), PFRTI=PSURFL%ZFRTI(:,:) , PALBTI=PSURFL%ZALBTI(:,:), PWLMX=PSURFL%ZWLMX(:),&
 & PCHAR=PSURF%ZCHAR(:) , PCHARHQ=PSURF%ZCHARHQ(:), PUCURR=PSURF%ZUCURR(:) , PVCURR=PSURF%ZVCURR(:),&
 & PTSKRAD=PSURF%GSP%PTL(:),&                         ! skin temp at latest rad timestep
 & PCFLX=GEMSL%PCFLX(:,:),&
 & PSSDP2=PINTER%PSSDP2(:,:), PSSDP3=PINTER%PSSDP3(:,:,:),&
 !-OUTPUT
 & PZ0M=GEMSL%PZ0M(:) ,PZ0H=GEMSL%PZ0H(:) ,&
 & PVDIS=PDIAG%PVDIS(:) , PAHFLEV=PFLUX%PFTLHEV(:),&
 & PAHFLSB=PFLUX%PFTLHSB(:),&
 & PFWSB=PFLUX%PFWSB(:),&
 & PU10M=PSURF%GSD%PU10M(:) , PV10M=PSURF%GSD%PV10M(:) , &
 & PT2M=PSURF%GSD%PT2M(:)  , PD2M=PSURF%GSD%PD2M(:) ,&
 &  PQ2M=PSURF%GSD%PQ2M(:) ,PZINV=PDIAG%ZINV(:) ,PSSRFLTI=PSURFL%ZFRSOTI(:,:),PEVAPSNW=PSURFL%ZEVAPSNW(:),&
 & PEXDIAG=PSURFL%ZEXDIAG(:,:),PGUST=PDIAG%PGUST(:), PZIDLWV=PSURFL%PZIDLWV(:),&
 !-UPDATED TENDENCIES
 &  PTE=PSURF%ZTE(:)   ,PQE=PSURF%ZQE(:)  ,PVOM=PSURF%ZVOM(:)  ,&
 & PVOL=PSURF%ZVOL(:)  ,PTENC=PSURF%ZTENC(:,:) ,PTSKE1=PSURF%PTLE1(:),&
 !-UPDATED FIELDS FOR TILES
 & PUSTRTI=PSURF%PUSTRTI(:,:),PVSTRTI=PSURF%PVSTRTI(:,:), PAHFSTI=PSURF%PAHFSTI(:,:), &
 & PEVAPTI=PSURF%PEVAPTI(:,:), PTSKTI=PSURF%PTSKTI(:,:) ,PSLRFLTI=PSURFL%PSLRFLTI(:,:), &
 !-UPDATED FIELDS FOR VEGETATION TYPES
 & PANDAYVT=PSURFL%PANDAYVT(:,:),PANFMVT=PSURFL%PANFMVT(:,:),& 
 !-OUTPUT FLUXES
 & PEVAPTIU=PSURF%GSD%PEVAPTIU(:,:),PDIFTS=PFLUX%PDIFTS(:,:),PDIFTQ=PFLUX%PDIFTQ(:,:), &
 & PSTRTU=PFLUX%PSTRTU(:,:),PSTRTV=PFLUX%PSTRTV(:,:),PKH=PSURFL%ZKH(:,:),&
 & PAN=PSURF%PAN(:),PAG=PSURF%PAG(:),PRD=PSURF%PRD(:),PRSOIL_STR=PSURF%PRSOIL_STR(:),&
 & PRECO=PSURF%PRECO(:),PCO2FLUX=PSURF%PCO2FLUX(:),PCH4FLUX=PSURF%PCH4FLUX(:),& 
 & PBVOCFLUX=GEMSL%PBVOCFLUX(:,:), &
 ! DDH OUTPUTS
 & PDHTLS=PDDHS%PDHTLS(:,:,:),PDHTSS=PDDHS%PDHTSS(:,:,:),PDHTTS=PDDHS%PDHTTS(:,:,:), &
 & PDHTIS=PDDHS%PDHTIS(:,:,:),PDHCO2S=PDDHS%PDHCO2S(:,:,:),PDHBVOCS=PDDHS%PDHBVOCS(:,:,:),PDHVEGS=PDDHS%PDHVEGS(:,:,:))

  
!IF (LDEBUGPRINT) THEN
!   PRINT *, "DEBUG IN VDFMAIN1S:"
!   PRINT *, "<------------------"
!   PRINT *,'CDCONF',CDCONF
!   PRINT *,'KIDIA',KIDIA
!   PRINT *,'KFDIA',KFDIA
!   PRINT *,'KLON',KLON
!   PRINT *,'KLEV',KLEV
!   PRINT *,'KLEVS',KLEVS
!   PRINT *,'KSTEP',KSTEP
!   PRINT *,'KTILES',KTILES
!   PRINT *,'KTRAC',KTRAC
!   PRINT *,'KLEVSN',KLEVSN 
!   PRINT *,'KLEVI',KLEVI  
!   PRINT *,'KDHVTLS',KDHVTLS
!   PRINT *,'KDHFTLS',KDHFTLS
!   PRINT *,'KDHVTSS',KDHVTSS
!   PRINT *,'KDHFTSS',KDHFTSS
!   PRINT *,'KDHVTTS',KDHVTTS
!   PRINT *,'KDHFTTS',KDHFTTS
!   PRINT *,'KDHVTIS',KDHVTIS
!   PRINT *,'KDHFTIS',KDHFTIS
!   PRINT *,'PTSPHY',PTSPHY
!   PRINT *,'ITVL',ITVL
!   PRINT *,'ICO2TYP',ICO2TYP
!   PRINT *,'ITVH',ITVH
!   PRINT *,'ZCVL',ZCVL
!   PRINT *,'ZCVH',ZCVH
!   PRINT *,'ZCUR',ZCUR
!   PRINT *,'ZLAIL',ZLAIL
!   PRINT *,'ZLAIH',ZLAIH
!   PRINT *,'PU',PU  
!   PRINT *,'PV',PV  
!   PRINT *,'PT',PT  
!   PRINT *,'PQ',PQ  
!   PRINT *,'PC',PC  
!   PRINT *,'PAPRS',PAPRS
!   PRINT *,'PGEOM1',PGEOM1
!   PRINT *,'PTL',PTL
!   PRINT *,'PTSA',PTSA
!   PRINT *,'PWSA',PWSA
!   PRINT *,'PFRSO(1,KLEV)',PFRSO(1,KLEV)
!   PRINT *,'PFRTH(1,KLEV)',PFRTH(1,KLEV)
!   PRINT *,'ZEMIS',ZEMIS
!   PRINT *,'PTSN',PTSN
!   PRINT *,'PTIA',PTIA
!   PRINT *,'PSST',PSST  
!   PRINT *,'ZFRTI',ZFRTI 
!   PRINT *,'ZALBTI',ZALBTI
!   PRINT *,'ZWLMX',ZWLMX
!   PRINT *,'ZCHAR',ZCHAR 
!   PRINT *,'ZCHARHQ',ZCHARHQ 
!   PRINT *,'PTL',PTL
!! skin temp at latest rad timestep
!   PRINT *,'PCFLX',PCFLX
!   PRINT *,'PZ0M',PZ0M
!   PRINT *,'PZ0H',PZ0H
!   PRINT *,'PVDIS',PVDIS 
!   PRINT *,'PFTLHEV',PFTLHEV
!   PRINT *,'PFTLHSB',PFTLHSB
!   PRINT *,'PFWSB',PFWSB
!   PRINT *,'PU10M',PU10M 
!   PRINT *,'PV10M',PV10M 
!   PRINT *,'PT2M',PT2M  
!   PRINT *,'PD2M',PD2M 
!   PRINT *,'PQ2M',PQ2M 
!   PRINT *,'PBLH',PBLH 
!   PRINT *,'ZFRSOTI',ZFRSOTI
!   PRINT *,'ZEVAPSNW',ZEVAPSNW
!   PRINT *,'PGUST',PGUST
!   PRINT *,'PZIDLWV',PZIDLWV
!!-UPDATED TENDENCIES
!   PRINT *,'ZTE',ZTE   
!   PRINT *,'ZQE',ZQE   
!   PRINT *,'ZVOM',ZVOM  
!   PRINT *,'ZVOL',ZVOL  
!   PRINT *,'ZTENC',ZTENC 
!   PRINT *,'PTLE1',PTLE1
!!-UPDATED FIELDS FOR TILES
!   PRINT *,'PUSTRTI',PUSTRTI
!   PRINT *,'PVSTRTI',PVSTRTI
!   PRINT *,'PAHFSTI',PAHFSTI
!   PRINT *,'PEVAPTI',PEVAPTI
!   PRINT *,'PTSKTI',PTSKTI
!!-OUTPUT FLUXES
!   PRINT *,'PDIFTS',PDIFTS
!   PRINT *,'PDIFTQ',PDIFTQ
!   PRINT *,'PSTRTU',PSTRTU
!   PRINT *,'PSTRTV',PSTRTV
!   PRINT *,'ZKH',ZKH
! ! DDH OUTPUTS
!   PRINT *,'PDHTLS',PDHTLS
!   PRINT *,'PDHTSS',PDHTSS
!   PRINT *,'PDHTTS',PDHTTS
!   PRINT *,'PDHTIS',PDHTIS
!  STOP
!ENDIF

ELSE

!*         3.1     NECESSARY COMPUTATIONS IF SUBROUTINE IS BY-PASSED.      

  PDIAG%PVDIS(1:IPROMA)=0._JPRB
  PFLUX%PFTLHEV(1:IPROMA)=0._JPRB
  PFLUX%PFTLHSB(1:IPROMA)=0._JPRB
  PFLUX%PFWSB(1:IPROMA)=0._JPRB
  PSURFL%ZEVAPSNW(1:IPROMA)=0._JPRB
  PFLUX%PDIFTQ(1:IPROMA,1:KLEVS)=0._JPRB
  PFLUX%PDIFTS(1:IPROMA,1:KLEVS)=0._JPRB
  PFLUX%PSTRTU(1:IPROMA,1:KLEVS)=0._JPRB
  PFLUX%PSTRTV(1:IPROMA,1:KLEVS)=0._JPRB
  DO JTILE=1,KTILES
    PSURFL%ZFRSOTI(1:IPROMA,JTILE)=PFLUX%PFRSO(1:IPROMA,KLEV)
    PSURF%PUSTRTI(1:IPROMA,JTILE)=0._JPRB
    PSURF%PVSTRTI(1:IPROMA,JTILE)=0._JPRB
    PSURF%PAHFSTI(1:IPROMA,JTILE)=0._JPRB
    PSURF%PEVAPTI(1:IPROMA,JTILE)=0._JPRB
    PSURF%PTSKTI(1:IPROMA,JTILE)=PSURF%GSP%PTL(1:IPROMA)
  ENDDO
ENDIF
!     ------------------------------------------------------------------

!*         4.      COMPUTATION OF NEW SURFACE VALUES
!                  ---------------------------------

PAUXL%ZPAPSRF(1:IPROMA)=STATE%PAPRS(1:IPROMA,KLEV)
IF ( LESURF ) THEN
!*         4.1   CALL SURFTSTP
  PFLUX%ZFRTH(1:IPROMA)=PFLUX%PFRTH(1:IPROMA,KLEV)  
  PSURFL%ZTHKICE(1:IPROMA)=1.5_JPRB
  LNEMOICETHK=.FALSE.
!-END OF CALL SURFTSTP

  CALL SURFTSTP  (YSURF=YSURF, KIDIA=1, KFDIA=IPROMA,&
   &  KLON=KLON, KLEVS=KLEVS, KCWS=NCWS, KTILES=KTILES,&
   &  KLEVSN=KLEVSN,   KLEVO=KLEVO ,KLEVI=KLEVI, KSTART=KSTART, KSTEP=KSTEP,&!KP
   &  KDHVTSS=KDHVTSS, KDHFTSS=KDHFTSS,&
   &  KDHVTTS=KDHVTTS, KDHFTTS=KDHFTTS,&
   &  KDHVTIS=KDHVTIS, KDHFTIS=KDHFTIS,&
   &  KDHVSSS=KDHVSSS, KDHFSSS=KDHFSSS,&
   &  KDHVIIS=KDHVIIS, KDHFIIS=KDHFIIS,&
   &  KDHVWLS=KDHVWLS, KDHFWLS=KDHFWLS,&
   &  KDHVBIOS=KDHVBIOS, KDHFBIOS=KDHFBIOS,&!CTESSEL
   &  KDHVVEGS=KDHVVEGS, KDHFVEGS=KDHFVEGS,&!CTESSEL
   &  KTVL=PSURF%ITVL(:) ,KTVH=PSURF%ITVH(:), KVEG=PSURF%IVEG(:,:),KSOTY=PSURF%ISOTY(:),& !Why KVEG not in DT!!!
   &  PSSDP2=PINTER%PSSDP2(:,:), PSSDP3=PINTER%PSSDP3(:,:,:), &
   &  PTSPHY=PTSPHY,PSDOR=PSURF%PSDOR(:), PFRTI=PSURFL%ZFRTI(:,:),&
   &  PSST=PSURF%GSP%PSST(:), PUSTRTI=PSURF%PUSTRTI(:,:), PVSTRTI=PSURF%PVSTRTI(:,:),&
   &  PAHFSTI=PSURF%PAHFSTI(:,:), PEVAPTI=PSURF%PEVAPTI(:,:), &
   &  PSSRFLTI=PSURFL%ZFRSOTI(:,:),PSLRFLTI=PSURFL%PSLRFLTI(:,:),&
!Note that PLAT is again GELAT here,, CALLPAR argument was duplicated under two different names. Check if correct!
   &  PLAT=PAUX%GELAT(:),PANFMVT=PSURFL%PANFMVT(:,:), PANDAYVT=PSURFL%PANDAYVT(:,:), PMU0=PAUX%PMU0M(:),&!CTESSEL    
   &  PCVT=PSURFL%ZCVT(:,:), PLAIVT=PSURFL%ZLAIVT(:,:),  &
   & PLAIL=PSURFL%ZLAIL(:), PLAIH=PSURFL%ZLAIH(:),&!CTESSEL
   &  PCIL=PSURF%PCIL(:), &
   &  PLAILC=PSURF%GSD%PLAILC(:), PLAIHC=PSURF%GSD%PLAIHC(:),&
   &  LDLAND=LLKEYS%LLLAND(:), LDSICE=LLKEYS%LLSICE(:), LDLICE=LLKEYS%LLLICE(:), LDSI=LESICE, LDNH=LLKEYS%LLNH(:), &
   &  LDOCN_KPP=LLKEYS%LLOCN_KPP(:),&
   &  PSNM1M=PSURFL%PSNS(:,:) ,PTSNM1M=PSURF%GSP%PTSN(:,:), PASNM1M=PSURF%GSP%PASN(:), &
   &  PRSNM1M=PSURFL%PRSN(:,:), PWSNM1M=PSURFL%PWSN(:,:), &
   &  PAPRS=PAUXL%ZPAPSRF(:), PTSKM1M=PSURF%GSP%PTL(:),&
   &  PTSAM1M=PSURF%GSP%PTSA(:,:), PTIAM1M=PSURF%GSP%PTIA(:,:),&
   &  PWLM1M=PSURFL%PWL(:), PWSAM1M=PSURF%GSP%PWSA(:,:),&
   &  PTLICEM1M=PSURF%GSP%PTLICE(:),PTLMNWM1M=PSURF%GSP%PTLMNW(:),&!LAKE
   &  PTLWMLM1M=PSURF%GSP%PTLWML(:),PTLBOTM1M=PSURF%GSP%PTLBOT(:),&!LAKE
   &  PTLSFM1M=PSURF%GSP%PTLSF(:),&!LAKE
   &  PHLICEM1M=PSURF%GSP%PHLICE(:),PHLMLM1M=PSURF%GSP%PHLML(:),&!LAKE
   &  PGEMU=PAUX%PGEMU(:),&
   &  PLDEPTH=PCLIM%PLDEPTH(:),LDLAKE=LLKEYS%LLLAKE(:), PCLAKE=PCLIM%PCLAKE(:),&!LAKE
   &  PRSFC=PFLUX%PFPLCL(:),PRSFL=PFLUX%PFPLSL(:),&
   &  PSLRFL=PFLUX%ZFRTH(:), PSSFC=PFLUX%PFPLCN(:), PSSFL=PFLUX%PFPLSN(:),&
   &  PCVL=PSURF%ZCVL(:), PCVH=PSURF%ZCVH(:), PCUR=PCLIM%PCUR(:), &
   &  PWLMX=PSURFL%ZWLMX(:) , PEVAPSNW=PSURFL%ZEVAPSNW(:),&
   &  PUSRF=STATE%PU(:),PVSRF=STATE%PV(:),PTSRF=STATE%PT(:),&

!-KPP
   &  PZO=PCLIM%PZO(:,:),PHO=PSURF%GSD%PHO(:,:),&
   &  PHO_INV=PSURF%GSD%PHO_INV(:,:),PDO=PSURF%GSD%PDO(:,:),&
   &  POCDEPTH=PSURF%GSD%POCDEPTH(:),&
   &  PUO0=PSURF%GSP%PUO0(:,:),PVO0=PSURF%GSP%PVO0(:,:),&
   &  PUOC=PSURF%GSP%PUOC(:,:),PVOC=PSURF%GSP%PVOC(:,:),&
   &  PTO0=PSURF%GSP%PTO0(:,:),&
   &  PSO0=PSURF%GSP%PSO0(:,:),PADVT=PSURF%GSD%PADVT(:,:),&
   &  PADVS=PSURF%GSD%PADVS(:,:),PTRI0=PSURF%GSD%PTRI0(:,:),&
   &  PTRI1=PSURF%GSD%PTRI1(:,:),&
   &  PSWDK_SAVE=PSURF%GSD%PSWDK_SAVE(:,:),PUSTRC=PSURF%PUSTRC(:),&
   &  PVSTRC=PSURF%PVSTRC(:),&

   &  PUSTOKES=PSURF%PUSTOKES(:),PVSTOKES=PSURF%PVSTOKES(:),&
   &  PTAUOCX=PSURF%GSD%PTAUOCX(:),PTAUOCY=PSURF%GSD%PTAUOCY(:),&
   &  PPHIOC=PSURF%PPHIOC(:),&
   &  PWSEMEAN=PSURF%PWSEMEAN(:),PWSFMEAN=PSURF%PWSFMEAN(:),&
   &  LNEMOICETHK=LNEMOICETHK, PTHKICE=PSURFL%ZTHKICE(:), &

!-DIAGNOSTICS OUTPUT
   & PTSDFL=PFLUX%PFTG12(:), PROFD=PFLUX%PFWROD(:), PROFS=PFLUX%PFWRO1(:),&
   & PWFSD=PFLUX%PFWG12(:), PMELT=PFLUX%PFWMLT(:), PFWEV=PFLUX%PFWEV(:) , PENES=PFLUX%ZENES(:,:),&
   & PDIFM=PSURF%PDIFM(:,:), PDIFT=PSURF%PDIFT(:,:),&
   & PDIFS=PSURF%PDIFS(:,:), POTKE=PSURF%GSD%POTKE(:,:),&
   & PRESPBSTR=PSURF%PRESPBSTR(:,:),PRESPBSTR2=PSURF%PRESPBSTR2(:,:),PBIOMASS_LAST=PSURF%PBIOMASS_LAST(:,:),& !CTESSEL
   & PBIOMASSTR_LAST=PSURF%PBIOMASSTR_LAST(:,:),PBIOMASSTR2_LAST=PSURF%PBIOMASSTR2_LAST(:,:), &    !CTESSEL
   & PBLOSSVT=PSURF%PBLOSSVT(:,:), PBGAINVT=PSURF%PBGAINVT(:,:),&                                  !CTESSEL
   & PLAI=PSURF%PLAI(:), PBIOM=PSURF%PBIOM(:), PBLOSS=PSURF%PBLOSS(:),PBGAIN=PSURF%PBGAIN(:),&                   !CTESSEL
   & PBIOMSTR=PSURF%PBIOMSTR(:),PBIOMSTR2=PSURF%PBIOMSTR2(:),&    
                             !CTESSEL  
!-TENDENCIES OUTPUT
   &  PSNE1=PSURF%PSNSE1(:,:), PTSNE1=PSURF%PTSNE1(:,:), PASNE1=PSURF%PASNE1(:),&
   &  PRSNE1=PSURF%PRSNE1(:,:), PWSNE1=PSURF%PWSNE1(:,:), PTSAE1=PSURF%PTSAE1(:,:), PTIAE1=PSURF%PTIAE1(:,:),&
   &  PWLE1=PSURF%PWLE1(:),PWSAE1=PSURF%PWSAE1(:,:),&
   & PTLICEE1=PSURF%PTLICEE1(:),PTLMNWE1=PSURF%PTLMNWE1(:),PTLWMLE1=PSURF%PTLWMLE1(:),& !LAKE
   & PTLBOTE1=PSURF%PTLBOTE1(:),PTLSFE1=PSURF%PTLSFE1(:),&                           !LAKE
   & PHLICEE1=PSURF%PHLICEE1(:),PHLMLE1=PSURF%PHLMLE1(:),&                           !LAKE
   & PUOE1=PSURF%PUOE1(:,:),PVOE1=PSURF%PVOE1(:,:),PTOE1=PSURF%PTOE1(:,:),PSOE1=PSURF%PSOE1(:,:),&     
   & PLAIE1=PSURF%PLAIE1(:,:),PBSTRE1=PSURF%PBSTRE1(:,:),PBSTR2E1=PSURF%PBSTR2E1(:,:), &                      !CTESSEL  

!-DDH OUTPUTS
   & PDHTSS=PDDHS%PDHTSS(:,:,:), PDHTTS=PDDHS%PDHTTS(:,:,:), PDHTIS=PDDHS%PDHTIS(:,:,:),&
   & PDHSSS=PDDHS%PDHSSS(:,:,:), PDHIIS=PDDHS%PDHIIS(:,:), PDHWLS=PDDHS%PDHWLS(:,:,:),&
   & PDHBIOS=PDDHS%PDHBIOS(:,:,:),PDHVEGS=PDDHS%PDHVEGS(:,:,:))     
!write(6,*) 'callpar1s pdhwls(1,4,8)',pdhwls(1,4,8)
ELSE

!*         4.2     NECESSARY COMPUTATIONS IF SUBROUTINE IS BY-PASSED.
  PFLUX%PFTG12(1:IPROMA)=0._JPRB
  PFLUX%PFWROD(1:IPROMA)=0._JPRB
  PFLUX%PFWRO1(1:IPROMA)=0._JPRB
  PFLUX%PFWMLT(1:IPROMA)=0._JPRB
  PFLUX%PFWG12(1:IPROMA)=0._JPRB
  PFLUX%PFWEV(1:IPROMA)=0._JPRB
ENDIF

!*              5.     END OF E.C.M.W.F. PHYSICS
!                      -------------------------
IF (LHOOK) CALL DR_HOOK('CALLPAR1S',1,ZHOOK_HANDLE)

END SUBROUTINE CALLPAR1S
