MODULE CALLPAR1S_LAYER_MOD
USE YOMLUN1S , ONLY : NULOUT
USE YOMGF1S  , ONLY : RALT     ,RZUV

USE YOMCST   , ONLY : RSIGMA   ,RDAY
USE YOERAD   , ONLY : NSW      ,NTSW, NLWEMISS
USE YOERDI1S , ONLY : REMISS
USE YOMRIP   , ONLY : RSTATI   ,NSSSSS
USE YOEPHY   , ONLY : LERADS, LESICE, LESURF, LEVDIF, LECTESSEL, LEINTWIND, LEWARMSTART, LESNML,LESNICE, NALBEDOSCHEME, NCWS, LBVOC_EMIS
USE YOETHF   , ONLY : RHOH2O
USE YOMLOG1S , ONLY : LSEMISS
USE YOMGDI1S , ONLY : D1SRFLD  ,D1SRFLU  ,D1TRFLD  ,D1TRFLU &
     &             , D1SALB, D1SWDS  ,D1SSDS   ,D1SWLDS

USE YOMDPHY  ,ONLY : YSURF
USE PARKIND1 ,ONLY : JPIM     ,JPRB, JPRD, JPIB
USE YOMHOOK  ,ONLY : LHOOK    ,DR_HOOK, JPHOOK

USE MPL_MODULE

USE ECPHYS_SURFACE_TYPE_MOD, ONLY: SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE
USE ECPHYS_SURFACE_TYPE_MOD, ONLY: DDH_SURF_TYPE 
USE ECPHYS_AUX_DIAG_TYPE_MOD, ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECPHYS_AUX_TYPE_MOD, ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECPHYS_FLUX_TYPE_MOD, ONLY: FLUX_TYPE
USE ECLAND_STATE_TYPE_MOD, ONLY: STATE_TYPE
USE YOMPHYDER, ONLY: GEMS_LOCAL_TYPE

IMPLICIT NONE

CONTAINS

SUBROUTINE CALLPAR1S_LAYER_OPENMP (CDCONF &
     & , KIDIA,KFDIA,KLON,KLEVS,KTILES,KVTYPES &
     & , KLEV   ,KSTART ,KSTEP  ,KTRAC   &
     & , KLEVI  ,KLEVO  ,KLEVSN          &                      !KPP
     & , KDHVTLS,KDHFTLS,KDHVTSS,KDHFTSS &
     & , KDHVTTS,KDHFTTS,KDHVTIS,KDHFTIS &
     & , KDHVSSS,KDHFSSS,KDHVIIS,KDHFIIS &
     & , KDHVWLS,KDHFWLS,KDHVRESS,KDHFRESS &
     & , KDHVCO2S,KDHFCO2S &
     & , KDHVBIOS,KDHFBIOS,KDHVBVOCS,KDHVVEGS,KDHFVEGS &
     & , PTSPHY &
!-----------------------------------------------------------------------
! - INPUT .
     & , LLKEYS &
! - OUTPUT .
     & , PSURF, PSURFL, PAUX, PAUXL, PFLUX, PDIAG, STATE, GEMSL, PDDHS ) 
! (C) Copyright 1995- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!**** *CALLPAR1S * - CALL PHYSICS

!     PURPOSE.
!     --------
!     - CALL THE SUBROUTINES OF THE PHYSICS PACKAGE.

!**   Interface.
!     ----------
!        *CALL* *CALLPAR1S*

!-----------------------------------------------------------------------

! -   INPUT ARGUMENTS.
!     -------------------

! - DIMENSIONS ETC.

! KIDIA   : START OF HORIZONTAL LOOP
! KFDIA   : END OF HORIZONTAL LOOP
! KLON    : HORIZONTAL DIMENSION
! KTRAC   : NUMBER OF TRACERS
! KLEVS   : NUMBER OF LEVELS IN SOIL
! KTILES  : NUMBER OF vegetation (surface cover) tiles
! KVTYPES : NUMBER OF VEGETATION TYPES
! KLEV    : END OF VERTICAL LOOP AND VERTICAL DIMENSION
! KSTART  : FIRST STEP OF MODEL
! KSTEP   : CURRENT TIME STEP
!    *KLEVSN*       Number of snow layers (diagnostics) 
!    *KLEVI*        Number of sea ice layers (diagnostics)
!    *KDHVTLS*      Number of variables for individual tiles
!    *KDHFTLS*      Number of fluxes for individual tiles
!    *KDHVTSS*      Number of variables for snow energy budget
!    *KDHFTSS*      Number of fluxes for snow energy budget
!    *KDHVTTS*      Number of variables for soil energy budget
!    *KDHFTTS*      Number of fluxes for soil energy budget
!    *KDHVTIS*      Number of variables for sea ice energy budget
!    *KDHFTIS*      Number of fluxes for sea ice energy budget
!    *KDHVIIS*      Number of variables for interception water budget
!    *KDHFIIS*      Number of fluxes for interception water budget
!    *KDHVWLS*      Number of variables for soil water budget
!    *KDHFWLS*      Number of fluxes for soil water budget
!    *KDHVRESS*     Number of variables for resistances 
!    *KDHFRESS*     Number of fluxes for resistances

!    *KDHVCO2S*     Number of variables for CO2
!    *KDHFCO2S*     Number of fluxes for CO2
!    *KDHVBIOS*     Number of variables for biomass
!    *KDHFBIOS*     Number of fluxes for biomass
!    *KDHVBVOCS*    Number of variables for BVOC
!    *KDHVVEGS*     Number of variables for variables per vegetation type
!    *KDHFVEGS*     Number of fluxes for variables per vegetation type

! PTSPHY  : PHYSICS TIME STEP

! - 2D (0:KLEV) .

! PAPRS      : PRESSURE ON HALF-LEVELS.

! - 2D (1:KLEV) .

! PGEOM1     : GEOPOTENTIAL ON FULL LEVELS.
! PU         : X-COMPONENT OF WIND.
! PV         : Y-COMPONENT OF WIND.
! PT         : TEMPERATURE.
! PQ         : SPECIFIC HUMIDITY (WATER VAPOUR).

! - 1D (PROGNOSTIC QUANTITIES) .

! PSNS       : SNOW DEPTH (kg m-2)
! PASN       : Snow albedo (0-1)
! PRSN       : Snow density (kg m-3)
! PTSN       : Snow temperature (K)
! PTSA       : MULTI-LAYER SOIL TEMPERATURE
! PWSA       : MULTI-LAYER SOIL WETNESS
! PWL        : SKIN RESERVOIR WATER CONTENT (kg m-2)
! PTL        : SKIN TEMPERATURE
! PTIA       : MULTI-LAYER ICE TEMPERATURE

! - 1D (GEOGRAPHICAL DISTRIBUTION) .

! PALBF      : BACKGROUND SURFACE SHORTWAVE ALBEDO (SNOW-FREE).
! PALUVP     : MODIS ALBEDO UV-VIS PARALLEL (DIRECT) RADIATION
! PALUVD     : MODIS ALBEDO UV-VIS DIFFUSE RADIATION
! PALNIP     : MODIS ALBEDO NEAR IR PARALLEL (DIRECT) RADIATION
! PALNID     : MODIS ALBEDO NEAR IR DIFFUSE RADIATION
! PAL[UV|NI][I|V|G] : 6-component MODIS albedo coefficients
! PSDOR      : OROGRAPHIC STANDARD DEVIATION (M)
! PGEMU      : SIN of latitude
! PLSM       : LAND/SEA MASK.
! PZ0MCL     : ROUGHNESS LENGTH   (NB: Units   m)
! PMU0M      : LOCAL COSINE OF INSTANTANEOUS MEAN SOLAR ZENITH ANGLE.
! PZ0HCL     : ROUGHNESS LENGTH FOR HEAT   (NB: Units   m)
! PTVL       : LOW VEGETATION TYPE
! PCO2TYP   : TYPE OF PHOTOSYNTHESIS PATHWAY FOR LOW VEGETATION (C3/C4)
! PISOP_EP   : Isoprene emission potential
! PTVH       : HIGH VEGETATION TYPE

! PLAIH      : LEAF AREA INDEX HIGH
! PLAIL      : LEAF AREA INDEX LOW
! PRSMH      : STOMATAL RESISTANCE HIGH VEGETATION
! PRSML      : STOMATAL RESISTANCE LOW VEGETATION
! PANDAYVT   : DAILY NET CO2 ASSIM.OVER CANOPY PER VEGTYPE     KG_CO2/M2
! PANFMVT    : MAXIMUM LEAF ASSIMILATION PER VEGTYPE         KG_CO2/KG_AIR M/S  
! PRESPBSTR  : RESPIRATION OF ABOVE GROUND STRUCTURAL BIOMASS    KG_CO2/M2
! PRESPBSTR2 : RESPIRATION OF BELOW GROUND STRUCTURAL BIOMASS    KG_CO2/M2
! PBIOMASS_LAST: (ACTIVE) LEAF BIOMASS OF PREVIOUS DAY               KG/M2
!     NB: value only after nitro_decline, not after laigain!!!!
! PBIOMASSTR_LAST: ABOVE GROUND STRUCTURAL BIOMASS OF PREVIOUS DAY   KG/M2
! PBIOMASSTR2_LAST: BELOW GROUND STRUCTURAL BIOMASS OF PREVIOUS DAY  KG/M2
! PBLOSSVT   : ACTIVE BIOMASS LOSS                                   KG/M2
! PBGAINVT   : ACTIVE BIOMASS GAIN                                   KG/M2


! PSOTY      : SOIL TYPE
! PCVL       : LOW VEGETATION COVER
! PCVH       : HIGH VEGETATION COVER
! PCUR       : URBAN COVER (PASSIVE)
! PCFLX      : TRACER SURFACE FLUX
! PUSTRTI    : (INSTANTANEOUS) TILED SURFACE STRESS U-COMPONENT
! PVSTRTI    : (INSTANTANEOUS) TILED SURFACE STRESS V-COMPONENT
! PAHFSTI    : (INSTANTANEOUS) TILED SURFACE SENSIBLE HEAT FLUX
! PEVAPTI    : (INSTANTANEOUS) TILED EVAPORATION
! PTSKTI     : TILED SKIN TEMPERATURE
! PSLRFLTI    : Tile net longwave (not I/O of callpar1s)

! - 2D (1:KLEV) AT T+1 .

! PT1        : TEMPERATURE AT T+1
! PQ1        : HUMIDITY AT T+1
! PU1        : U-COMP. AT T+1
! PV1        : V-COMP. AT T+1

! - 1D (SURFACE 1D FORCING) .

! PSRSOD     : SURFACE SHORTWAVE RADIATIVE FLUX DOWNWARDS.
! PSRTHD     : SURFACE LONGWAVE RADIATIVE FLUX DOWNWARDS.
! PFPLCL     : CONVECTIVE PRECIPITATION AS RAIN.
! PFPLCN     : CONVECTIVE PRECIPITATION AS SNOW.
! PFPLSL     : STRATIFORM PRECIPITATION AS RAIN.
! PFPLSN     : STRATIFORM PRECIPITATION AS SNOW.
!-----------------------------------------------------------------------

! -   OUTPUT ARGUMENTS.
!     --------------------

! - 2D (0:KLEV) FLUXES .

! PDIFTQ     : TURBULENT FLUX (INC. Q NEGATIVE) OF SPECIFIC HUMIDITY.
! PDIFTS     : TURBULENT FLUX OF HEAT.
! PFRSO      : SHORTWAVE RADIATIVE FLUX.
! PFRTH      : LONGWAVE RADIATIVE FLUX.
! PSTRTU     : TURBULENT FLUX OF MOMENTUM "U".
! PSTRTV     : TURBULENT FLUX OF MOMENTUM "V".

! PAN        : NET CO2 ASSIMILATION OVER CANOPY.          
! PAG        : GROSS CO2 ASSIMILATION OVER CANOPY.       
! PRD        : DARK RESPIRATION.                         
! PRSOIL_STR : RESPIRATION FROM SOIL AND STRUCTURAL BIOMASS.
! PRECO      : ECOSYSTEM RESPIRATION.                   
! PCO2FLUX   : CO2 FLUX.
! PCH4FLUX   : CH4 FLUX.
! PBVOCFLUX  : Biogenic VOC FLUX.

! - 1D (TENDENCIES FROM SURFACE SCHEME)

! PSNSE1     : OF SNOW MASS PER UNIT SURFACE
! PASNE1     : of snow albedo
! PRSNE1     : of snow density
! PTSNE1     : of snow temperature
! PWLE1      : OF SKIN RESERVOIR WATER CONTENT
! PTLE1      : OF SKIN TEMPERATURE
! PTSAE1     : OF MULTI-LAYER SOIL TEMPERATURE
! PWSAE1     : OF MULTI-LAYER SOIL WETNESS
! PTIAE1     : OF MULTI-LAYER ICE TEMPERATURE

! PLAIE1     : OF LAI PER VEGETATION TYPE
! PBSTRE1    : OF ABOVE GROUND STRUCTURAL BIOMASS PER VEGETATION TYPE 
! PBSTR2E1   : OF BELOW GROUND STRUCTURAL BIOMASS PER VEGETATION TYPE 


! - 1D (DIAGNOSTIC) .

! PLAI       : LAI (M2/M2)
! PBIOM      : BIOMASS (KG/M2)
! PBLOSS     : BIOMASS LOSS (KG/M2)
! PBGAIN     : BIOMASS GAIN (KG/M2)
! PBIOMSTR   : ABOVE GROUND STRUCTURAL BIOMASS (KG/M2)
! PBIOMSTR2  : BELOW GROUND STRUCTURAL BIOMASS (KG/M2)


! PALB       : MODEL SURFACE SHORTWAVE ALBEDO.
! PFTLHEV    : SURFACE LATENT HEAT FLUX (SNOW FREE FRACTION)
! PFTLHSB    : SURFACE LATENT HEAT FLUX (SNOW COVERED FRACTION)
! PFTG12     : HEAT FLUX FROM LAYER 1 TO 2
! PFWEV      : SURFACE WATER VAPOUR FLUX (EVAPORATION)
! PFWSB      : SURFACE WATER VAPOUR FLUX (SUBLIMATION)
! PFWG12     : WATER FLUX FROM LAYER 1 TO 2
! PFWMLT     : WATER FLUX CORRESPONDING TO SURFACE SNOW MELT.
! PZ0M       : ROUGHNESS LENGTH (CURRENT)    (NB: Units   m)
! PZ0H       : ROUGHNESS LENGTH FOR HEAT (CURRENT)   (NB: Units   m)
! PFWROD     : RUN-OFF FLUX AT DEEPER LAYERS (2-4)
! PFWRO1     : RUN-OFF FLUX AT LAYER 1
! PVDIS      : TURBULENT DISSIPATION
!    *PU10M*        U-COMPONENT WIND AT 10 M                      M/S
!    *PV10M*        V-COMPONENT WIND AT 10 M                      M/S
!    *PT2M*         TEMPERATURE AT 2M                                K
!    *PD2M*         DEW POINT TEMPERATURE AT 2M                      K
!    *PQ2M*         SPECIFIC HUMIDITY AT 2M                       KG/KG
!    *PMEAN*        AREA AVERAGED WIND SP. AT 10 M INT. FROM KLEV   M/S
!    *PGUST*        GUST AT 10 M                                    M/S
!    *PZIDLWV*      Zi/L used for gustiness in wave model           m/m
!                   (NOTE: Positive values of Zi/L are set to ZERO)
!    *PBLH*         BOUNDARY LAYER HEIGHT                            M
!    *PDHTLS*       Diagnostic array for tiles (see module yomcdh)
!    *PDHTTS*       Diagnostic array for soil T (see module yomcdh)
!                      (Wm-2 for fluxes)
!    *PDHTIS*       Diagnostic array for ice T (see module yomcdh)
!                      (Wm-2 for fluxes)
!    *PDHTSS*     Diagnostic array for snow T (see module yomcdh)
!                      (Wm-2 for fluxes)
!    *PDHSSS*     Diagnostic array for snow mass (see module yomcdh)
!                      (m/s for fluxes)
!    *PDHIIS*     Diagnostic array for interception layer (see module yomcdh)
!    *PDHWLS*     Diagnostic array for soil water (see module yomcdh)
!    *PDHRESS*      Diagnostic array for resistances (see module yomcdh) 

!    *PDHCO2S*    Diagnostic array for CO2 (see module yomcdh)
!    *PDHBIOS*    Diagnostic array for biomass (see module yomcdh)
!    *PDHBVOCS*   Diagnostic array for BVOC emissions (see module yomcdh)
!    *PDHVEGS*    Diagnostic array for variables per vegetation type
!                (see module yomcdh)


!-----------------------------------------------------------------------

!     Externals.  RADSRF -
!     ---------   VDFMAIN1S-
!                 SRFMAIN-

!     Method. See documentaion.
!     -------
!     Modifications.
!     --------------
!     ORIGINAL 95-03-08 Pedro VITERBO
!            2008-01-22 Victor STEPANENKO
!     Components of wind stress (PUSTRTI AND PVSTRTI)
!     and sea surface temperature (PSST) are added to the arguments of subroutine SURFTSTP  
!     S. Boussetta/G.Balsamo May 2010 Add CTESSEL based on: 
!     Marita Voogt (KNMI) CTESSEL
!     Sebastien simplified CTESSEL
!     E. Dutra      29/05/2014      net longwave tiled
!     R. Hogan      15/01/2019      6-component MODIS albedo coefficients

!-----------------------------------------------------------------------
!     ******************************************************************
!     ****** IDIOSYNCRASIES *** IDIOSYNCRASIES *** IDIOSYNCRASIES ******
!     ******************************************************************
!     ***  MOREOVER, WATER IN DEEPER LAYERS HAS TO BE NORMALIZED TO  ***
!     ***  THE FIRST LAYER DEPTH. THIS IS EQUIVALENT TO A CHANGE OF  ***
!     ***  UNITS FROM PURE VOLUMETRIC UNITS (M3/M3, USED ELSEWHERE   ***
!     ***  IN THE CODE) TO MODIFIED VOLUMETRIC UNITS, NORMALIZED BY  ***
!     ***  THE DEPTH OF THE FIRST LAYER (M/0.07M, USED IN THE        ***
!     ***  PHYSICS)                                                  ***
!     ******************************************************************
!     ******************************************************************



TYPE(SURF_AND_MORE_TYPE) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE) :: PSURFL
TYPE(AUX_DIAG_TYPE) :: PDIAG
TYPE(AUX_DIAG_LOCAL_TYPE) :: PAUXL
TYPE(AUX_TYPE) :: PAUX
TYPE(FLUX_TYPE) :: PFLUX
TYPE(STATE_TYPE) :: STATE,TENDENCY_LOC 
TYPE(GEMS_LOCAL_TYPE) :: GEMSL 
TYPE(KEYS_LOCAL_TYPE) :: LLKEYS  
TYPE(DDH_SURF_TYPE) :: PDDHS

!*
!     ------------------------------------------------------------------
CHARACTER*1,INTENT(IN) :: CDCONF

INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA,KFDIA,KLON,KLEVS,KTILES &
     & , KLEV   , KSTART , KSTEP ,KTRAC &
     & , KLEVSN ,KLEVI  ,KDHVTLS,KDHFTLS,KDHVTSS,KDHFTSS &
     & , KDHVTTS,KDHFTTS,KDHVTIS,KDHFTIS &
     & , KDHVSSS,KDHFSSS, KDHVIIS,KDHFIIS &
     & , KDHVWLS ,KDHFWLS ,KDHVRESS,KDHFRESS &
     & , KLEVO  !KPP 

INTEGER(KIND=JPIM),INTENT(IN)    :: KVTYPES
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVCO2S 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFCO2S 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVBIOS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFBIOS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVBVOCS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHVVEGS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDHFVEGS
 REAL(KIND=JPRB) :: PTSPHY

!
!!            0.2  LOCAL VARIABLES
!!                 ---------------
!
!REAL(KIND=JPRB) :: ZEMIR(KLON),ZEMIW(KLON)
REAL(KIND=JPRB) :: ZFAC(KLON)
REAL(KIND=JPRD) :: ZJUL ! needed jprd for dattim
INTEGER(KIND=JPIM) :: IMON(12)
INTEGER(KIND=JPIM) :: IYY,IMM,IDD,IINC,ISEC0,IYMD,IHM
INTEGER(KIND=JPIM) :: JK,JL,JTILE,JVT
LOGICAL LDEBUGPRINT
!
!REAL(KIND=JPRB)  :: PALBICEF(KLON)
LOGICAL          :: LNEMOLIMALB
LOGICAL          :: LNEMOICETHK
!
INTEGER(KIND=JPIM) :: JPDIAG=12
!REAL(KIND=JPRB)  :: ZEXDIAG(KLON,12)
!
INTEGER(KIND=JPIM) :: JLL,IST,IEND,IBL,IPROMA,NPROMA
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


#include "surfbc.h"
#include "surfws.h"
#include "surfrad.h"
#include "surftstp.h"

#include "updcal.intfb.h"
#include "vdfmain1s.intfb.h"

#include "fcttim.h"

IF (LHOOK) CALL DR_HOOK('CALLPAR1S',0,ZHOOK_HANDLE)

NPROMA=MIN(KLON,KFDIA-KIDIA+1)
!$OMP PARALLEL DO PRIVATE(IST,IEND,IBL,IPROMA,ZFAC)
DO IST = KIDIA, KFDIA, NPROMA
  IEND = MIN(IST+NPROMA-1,KFDIA-KIDIA+1)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1
!    ------------------------------------------------------------------

!*         1.     INITIAL COMPUTATIONS.
!                 ---------------------

!* Interpolate wind to correct height 
!IF(RALT.NE.RZUV) THEN
IF(RALT .NE. RZUV .AND. KSTEP .NE. KSTART ) THEN
    ZFAC(1:IPROMA)=LOG(RALT/GEMSL%PZ0M(1:IPROMA,IBL))/LOG(RZUV/GEMSL%PZ0M(1:IPROMA,IBL))
     STATE%PU(1:IPROMA,IBL) = ZFAC* STATE%PU(1:IPROMA,IBL)
     STATE%PV(1:IPROMA,IBL) = ZFAC* STATE%PV(1:IPROMA,IBL)
     STATE%PU1(1:IPROMA,IBL) = ZFAC*STATE%PU1(1:IPROMA,IBL)
     STATE%PV1(1:IPROMA,IBL) = ZFAC*STATE%PV1(1:IPROMA,IBL)
ENDIF


!*      1.2  TENDENCIES OF FORCINGS

 PSURF%ZTE(1:IPROMA,IBL)=(STATE%PT1(1:IPROMA,IBL)-STATE%PT(1:IPROMA,IBL))/PTSPHY
 PSURF%ZQE(1:IPROMA,IBL)=(STATE%PQ1(1:IPROMA,IBL)-STATE%PQ(1:IPROMA,IBL))/PTSPHY
PSURF%ZVOM(1:IPROMA,IBL)=(STATE%PU1(1:IPROMA,IBL)-STATE%PU(1:IPROMA,IBL))/PTSPHY
PSURF%ZVOL(1:IPROMA,IBL)=(STATE%PV1(1:IPROMA,IBL)-STATE%PV(1:IPROMA,IBL))/PTSPHY
IF(KTRAC .GT. 0 ) THEN
  PSURF%ZTENC(1:IPROMA,1:KTRAC,IBL)= &
    &   (GEMSL%PC1(1:IPROMA,1:KTRAC,IBL)-GEMSL%PC(1:IPROMA,1:KTRAC,IBL))/PTSPHY
ENDIF


PSURFL%ZCSN(1:IPROMA,IBL)=0.0_JPRB
    ENDDO
!$OMP END PARALLEL DO
!*      1.3a   AUXILLIARY VARIABLES FOR VDF, SRF AND RADSRF
!

!$OMP PARALLEL DO PRIVATE(IST,IEND,IBL,IPROMA)
DO IST = KIDIA, KFDIA, NPROMA
  IEND = MIN(IST+NPROMA-1,KFDIA-KIDIA+1)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1
  CALL SURFBC (YSURF=YSURF,KIDIA=1,KFDIA=IPROMA,KLON=KLON,KTILES=KTILES,KLEVSN=KLEVSN,&
   & PSSDP2=PSURF%GSD%PSSDP2(:,:,IBL), PTVL=PSURF%GSD%PTVL(:,IBL),PCO2TYP=PSURF%GSD%PCO2TYP(:,IBL),&
   & PTVH=PSURF%GSD%PTVH(:,IBL), PSOTY=PSURF%GSD%PSOTY(:,IBL),PSDOR=PSURF%PSDOR(:,IBL),PCVLC=PSURF%GSD%PCVL(:,IBL), &
   & PCVHC=PSURF%GSD%PCVH(:,IBL),PCURC=PSURF%GSD%PCUR(:,IBL),&
   &  PLAILC=PSURF%GSD%PLAILC(:,IBL), PLAIHC=PSURF%GSD%PLAIHC(:,IBL),&
   &  PLAILI=   PSURFL%PLAILI(:,IBL), PLAIHI=   PSURFL%PLAIHI(:,IBL),&
   & PLAILCP=PSURF%GSD%PLAILC(:,IBL),PLAIHCP=PSURF%GSD%PLAIHC(:,IBL),&
   & PAVGPARC=PSURF%GSD%ZAVGPARC(:,IBL),&
   & PLSM=PSURF%GSD%PLSM(:,IBL),PCI=PSURF%GSD%PCI(:,IBL),PCIL=PSURF%PCIL(:,IBL),&
   & PCLAKE=PSURF%GSD%PCLAKE(:,IBL),PHLICE=PSURF%GSP%PHLICE(:,IBL),&
   & PGEMU=PAUX%PGEMU(:,IBL),PSNM1M=PSURFL%PSNS(:,:,IBL),PWLM1M=PSURFL%PWL(:,IBL),PRSNM1M=PSURFL%PRSN(:,:,IBL), &
   & LESNICE=LESNICE,&
   & LDLAND=LLKEYS%LLLAND(:,IBL),LDSICE=LLKEYS%LLSICE(:,IBL),LDLICE=LLKEYS%LLLICE(:,IBL),LDLAKE=LLKEYS%LLLAKE(:,IBL),&
   & LDNH=LLKEYS%LLNH(:,IBL),LDOCN_KPP=LLKEYS%LLOCN_KPP(:,IBL),&
   & KTVL=PSURF%ITVL(:,IBL),KCO2TYP=PSURF%ICO2TYP(:,IBL),KTVH=PSURF%ITVH(:,IBL),KSOTY=PSURF%ISOTY(:,IBL),&
   & PCVL=PSURF%ZCVL(:,IBL),PCVH=PSURF%ZCVH(:,IBL),PCUR=PSURF%ZCUR(:,IBL),PLAIL=PSURFL%ZLAIL(:,IBL),PLAIH=PSURFL%ZLAIH(:,IBL),&
   & PLAILP=PSURF%ZLAILP(:,IBL),PLAIHP=PSURF%ZLAIHP(:,IBL),&
   & PAVGPAR=PSURF%ZAVGPAR(:,IBL), &
   & PWLMX=PSURFL%ZWLMX(:,IBL),PFRTI=PSURFL%ZFRTI(:,:,IBL), PCSN=PSURFL%ZCSN(:,IBL))

!*      1.3   GLOBAL AUXILLIARY VARIABLES
  PSURF%ZCHAR(1:IPROMA,IBL)=0.018_JPRB
PSURF%ZCHARHQ(1:IPROMA,IBL)=0.006_JPRB


!*      1.3a   GLOBAL OCEAN TEMPORALY SET TO ZERO (to check with PJ)
PSURF%PUSTOKES(1:IPROMA,IBL)=0.0_JPRB
PSURF%PVSTOKES(1:IPROMA,IBL)=0.0_JPRB
PSURF%GSD%PTAUOCX(1:IPROMA,IBL)=0.0_JPRB
PSURF%GSD%PTAUOCY(1:IPROMA,IBL)=0.0_JPRB
PSURF%PPHIOC(1:IPROMA,IBL)=0.0_JPRB
PSURF%PWSEMEAN(1:IPROMA,IBL)=0.0_JPRB
PSURF%PWSFMEAN(1:IPROMA,IBL)=0.0_JPRB

!*       1.4  SET SURFACE TENDENCIES TO ZERO
PSURF%PTSAE1(1:IPROMA,1:KLEVS,IBL)=0.0_JPRB
PSURF%PWSAE1(1:IPROMA,1:KLEVS,IBL)=0.0_JPRB
PSURF%PTIAE1(1:IPROMA,1:KLEVS,IBL)=0.0_JPRB
PSURF%PTLE1(1:IPROMA,IBL)=0.0_JPRB
PSURF%PWLE1(1:IPROMA,IBL)=0.0_JPRB
PSURF%PSNSE1(1:IPROMA,1:KLEVSN,IBL)=0.0_JPRB
PSURF%PTSNE1(1:IPROMA,1:KLEVSN,IBL)=0.0_JPRB
PSURF%PRSNE1(1:IPROMA,1:KLEVSN,IBL)=0.0_JPRB
PSURF%PWSNE1(1:IPROMA,1:KLEVSN,IBL)=0.0_JPRB
PSURF%PASNE1(1:IPROMA,IBL)=0.0_JPRB
PSURF%ZUCURR(1:IPROMA,IBL)=0.0_JPRB
PSURF%ZVCURR(1:IPROMA,IBL)=0.0_JPRB

!* FLAKE
PSURF%PTLICEE1(1:IPROMA,IBL)=0.0_JPRB
PSURF%PTLMNWE1(1:IPROMA,IBL)=0.0_JPRB
PSURF%PTLWMLE1(1:IPROMA,IBL)=0.0_JPRB
PSURF%PTLBOTE1(1:IPROMA,IBL)=0.0_JPRB
PSURF%PTLSFE1(1:IPROMA,IBL)=0.0_JPRB
PSURF%PHLICEE1(1:IPROMA,IBL)=0.0_JPRB
PSURF%PHLMLE1(1:IPROMA,IBL)=0.0_JPRB
!* FLAKE 

PSURF%PUOE1(1:IPROMA,1:KLEVO+1,IBL)=0.0_JPRB !KPP
PSURF%PVOE1(1:IPROMA,1:KLEVO+1,IBL)=0.0_JPRB !KPP
PSURF%PTOE1(1:IPROMA,1:KLEVO+1,IBL)=0.0_JPRB !KPP
PSURF%PSOE1(1:IPROMA,1:KLEVO+1,IBL)=0.0_JPRB !KPP
PSURF%GSP%PUOC(1:IPROMA,1:KLEVO+1,IBL)=0.0_JPRB  !KPP
PSURF%GSP%PVOC(1:IPROMA,1:KLEVO+1,IBL)=0.0_JPRB  !KPP
PSURF%PUSTRC(1:IPROMA,IBL)=0.0_JPRB          !KPP
PSURF%PVSTRC(1:IPROMA,IBL)=0.0_JPRB          !KPP

!* CTESSEL
PSURF%PLAIE1(1:IPROMA,1:KVTYPES,IBL)=0.0_JPRB
PSURF%PBSTRE1(1:IPROMA,1:KVTYPES,IBL)=0.0_JPRB
PSURF%PBSTR2E1(1:IPROMA,1:KVTYPES,IBL)=0.0_JPRB
!* CTESSEL
    ENDDO
!$OMP END PARALLEL DO

!     ------------------------------------------------------------------

!*         2.     RADIATION TRANSFER
!                 ------------------
!$OMP PARALLEL DO PRIVATE(IST,IEND,IBL,IPROMA)
DO IST = KIDIA, KFDIA, NPROMA
  IEND = MIN(IST+NPROMA-1,KFDIA-KIDIA+1)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1

!*         2.2 SURFACE BOUNDARY CONDITIONS
IF (LERADS) THEN
!* get time variables
    CALL DATTIM(ZJUL,IYMD,IHM)  
    IDD=NDD(IYMD)
    IMM=NMM(IYMD) 
    IYY=NCCAA(IYMD)
    IINC=0
    ISEC0=MOD(NSSSSS+NINT(RSTATI,KIND=JPIB),NINT(RDAY))   
    CALL UPDCAL  (IDD,IMM,IYY,IINC,IDD,IMM,IYY,IMON,-1_JPIM)  
    PAUXL%ZWND(1:IPROMA,IBL)=SQRT(STATE%PU(1:IPROMA,IBL)**2  &
   &                                +STATE%PV(1:IPROMA,IBL)**2)
    PSURF%GSP%ZWS1(1:IPROMA,IBL)=PSURF%GSP%PWSA(1:IPROMA,1,IBL)
    LDEBUGPRINT=.FALSE.
!   IF (LDEBUGPRINT) THEN
!     PRINT *,"DEBUG SURFRAD -->"
!     PRINT *,"NSW",NSW
!     PRINT *,"LLNH",LLNH
!     PRINT *,"PALBF",PALBF
!     PRINT *,"PASN",PASN
!     PRINT *,"PMU0M",PMU0M
!     PRINT *,"PTL",PTL
!     PRINT *,"ZWND",ZWND
!     PRINT *,"ZWS1",ZWS1
!     PRINT *,"ZFRTI",ZFRTI
!     PRINT *,"ZALBD(:,1:NSW)",ZALBD(:,1:NSW)
!     PRINT *,"ZALBP(:,1:NSW)",ZALBP(:,1:NSW)
!     PRINT *,"PALB",PALB
!     PRINT *,"ZEMIR",ZEMIR
!     PRINT *,"ZEMIW",ZEMIW
!     PRINT *,"ZEMIS",ZEMIS
!     PRINT *,"ZALBTI",ZALBTI
!     PRINT *,"ZCCNL",ZCCNL
!     PRINT *,"ZCCNO",ZCCNO
!   ENDIF
    LNEMOLIMALB=.FALSE.
    PSURF%GSD%PALBICEF(:,IBL) = -999._JPRB
    
    CALL SURFRAD &
     &     ( YSURF,KDD=IDD, KMM=IMM, KMON=IMON  , KSECO=ISEC0 &
     &     , KIDIA=1, KFDIA=IPROMA, KLON=KLON   , KTILES=KTILES , KSW=NSW, KLW=NLWEMISS &
     &     , LDNH=LLKEYS%LLNH(:,IBL),LDLAND=LLKEYS%LLLAND(:,IBL) &
     &     , PSSDP3=PSURF%GSD%PSSDP3(:,:,:,IBL) &
     &     , PALBF=PSURF%GSD%PALBF(:,IBL) ,PALBICEF=PSURF%GSD%PALBICEF(:,IBL),PTVH=PSURF%GSD%PTVH(:,IBL) &
     &     , PALCOEFF=PSURF%GSD%ZALCOEFF(:,:,IBL) ,PCUR=PSURF%GSD%PCUR(:,IBL), PCVH=PSURF%GSD%PCVH(:,IBL) &
     &     , PASN=PSURF%GSP%PASN(:,IBL)   , PMU0=PAUX%PMU0M(:,IBL)  , PTS=PSURF%GSP%PTL(:,IBL)    , PWND=PAUXL%ZWND(:,IBL) &
     &     , PWS1=PSURF%GSP%ZWS1(:,IBL), KSOTY=PSURF%ISOTY(:,IBL) &
     &     , PFRTI=PSURFL%ZFRTI(:,:,IBL),PHLICE=PSURF%GSP%PHLICE(:,IBL),PTLICE=PSURF%GSP%PTLICE(:,IBL) &
     &     , PALBD=PSURFL%ZALBD(:,1:NSW,IBL)  , PALBP=PSURFL%ZALBP(:,1:NSW,IBL)  , PALB=PSURF%GSD%PALB(:,IBL) &
     &     , PSPECTRALEMISS=PSURFL%ZSPECTRALEMISS(:,1:NLWEMISS,IBL) , PEMIT=PSURF%ZEMIS(:,IBL) &
     &     , PALBTI=PSURFL%ZALBTI(:,:,IBL), PCCNL=PAUXL%ZCCNL(:,IBL), PCCNO=PAUXL%ZCCNO(:,IBL) &
     &     , LNEMOLIMALB=LNEMOLIMALB&
     &     , LESNICE=LESNICE)
!   ZEMIR(IST:IEND) = PSURFL%ZSPECTRALEMISS(1:IPROMA,1,IBL)
!   ZEMIW(IST:IEND) = PSURFL%ZSPECTRALEMISS(1:IPROMA,2,IBL)

!      PRINT *,"PMU0M",PMU0M
!   IF (LDEBUGPRINT) THEN
!     PRINT *,"DEBUG SURFRAD <--"
!     PRINT *,"NSW",NSW
!     PRINT *,"LLNH",LLNH
!     PRINT *,"PALBF",PALBF
!     PRINT *,"PASN",PASN
!     PRINT *,"PMU0M",PMU0M
!     PRINT *,"PTL",PTL
!     PRINT *,"ZWND",ZWND
!     PRINT *,"ZWS1",ZWS1
!     PRINT *,"ZFRTI",ZFRTI
!     PRINT *,"ZALBD(:,1:NSW)",ZALBD(:,1:NSW)
!     PRINT *,"ZALBP(:,1:NSW)",ZALBP(:,1:NSW)
!     PRINT *,"PALB",PALB
!     PRINT *,"ZEMIR",ZEMIR
!     PRINT *,"ZEMIW",ZEMIW
!     PRINT *,"ZEMIS",ZEMIS
!     PRINT *,"ZALBTI",ZALBTI
!     PRINT *,"ZCCNL",ZCCNL
!     PRINT *,"ZCCNO",ZCCNO
!   ENDIF
ELSE
  DO JK=1,KTILES
    PSURFL%ZALBTI(1:IPROMA,JK,IBL)=PSURF%GSD%PALBF(1:IPROMA,IBL)
  ENDDO
  PSURF%GSD%PALB(1:IPROMA,IBL)=PSURF%GSD%PALBF(1:IPROMA,IBL)
  PSURF%ZEMIS(1:IPROMA,IBL)=REMISS
! ZEMIR(IST:IEND)=REMISS
! ZEMIW(IST:IEND)=REMISS
ENDIF
IF (LSEMISS) PSURF%ZEMIS(1:IPROMA,IBL)=REMISS
PFLUX%PFRSO(1:IPROMA,KLEV,IBL)=PSURF%PSRSOD(1:IPROMA,IBL)*(1._JPRB-PSURF%GSD%PALB(1:IPROMA,IBL))
PFLUX%PFRTH(1:IPROMA,KLEV,IBL)=PSURF%ZEMIS(1:IPROMA,IBL)* &
     &       (PSURF%PSRTHD(1:IPROMA,IBL)-RSIGMA*PSURF%GSP%PTL(1:IPROMA,IBL)**4)

!*      1.3b 

IF ( (KSTEP==KSTART) .AND. (LEWARMSTART) )  THEN

  CALL SURFWS(YSURF=YSURF, KIDIA=1, KFDIA=IPROMA, KLON=KLON, KLEVS=KLEVS, KLEVSN=KLEVSN, KTILES=KTILES  &
             ,PSDOR=PSURF%PSDOR(:,IBL),LDSICE=LLKEYS%LLSICE(:,IBL)                                      &
             ,PLSM=PSURF%GSD%PLSM(:,IBL), PCIL=PSURF%PCIL(:,IBL), PFRTI=PSURFL%ZFRTI(:,:,IBL), PMU0=PAUX%PMU0M(:,IBL)         &
             ,PTSAM1M=PSURF%GSP%PTSA(:,:,IBL), PTSKIN=PSURF%GSP%PTL(:,IBL),PALBSN=PSURF%GSP%PASN(:,IBL)                                    &
             ,PTSNM1M=PSURF%GSP%PTSN(:,:,IBL), PSNM1M=PSURFL%PSNS(:,:,IBL), PRSNM1M=PSURFL%PRSN(:,:,IBL), PWSNM1M=PSURFL%PWSN(:,:,IBL)                           )

ENDIF
         

    ENDDO
!$OMP END PARALLEL DO
!     ------------------------------------------------------------------

!*         3.     VERTICAL EXCHANGE OF U,V,T,Q BY TURBULENCE
!                 ------------------------------------------
!$OMP PARALLEL DO PRIVATE(IST,IEND,IBL,IPROMA)
DO IST = KIDIA, KFDIA, NPROMA
  IEND = MIN(IST+NPROMA-1,KFDIA-KIDIA+1)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1

IF ( LEVDIF ) THEN

!IF (LDEBUGPRINT) THEN
!   PRINT *, "DEBUG IN VDFMAIN1S:"
!   PRINT *, "------------------>"
!   PRINT *,'CDCONF',CDCONF
!   PRINT *,'KIDIA',KIDIA
!   PRINT *,'KFDIA',KFDIA
!   PRINT *,'KLON',KLON
!   PRINT *,'KLEV',KLEV
!   PRINT *,'KLEVS',KLEVS
!   PRINT *,'KSTEP',KSTEP
!   PRINT *,'KTILES',KTILES
!   PRINT *,'KTRAC',KTRAC
!   PRINT *,'KLEVSN',KLEVSN 
!   PRINT *,'KLEVI',KLEVI  
!   PRINT *,'KDHVTLS',KDHVTLS
!   PRINT *,'KDHFTLS',KDHFTLS
!   PRINT *,'KDHVTSS',KDHVTSS
!   PRINT *,'KDHFTSS',KDHFTSS
!   PRINT *,'KDHVTTS',KDHVTTS
!   PRINT *,'KDHFTTS',KDHFTTS
!   PRINT *,'KDHVTIS',KDHVTIS
!   PRINT *,'KDHFTIS',KDHFTIS
!   PRINT *,'PTSPHY',PTSPHY
!   PRINT *,'ITVL',ITVL
!   PRINT *,'ICO2TYP',ICO2TYP
!   PRINT *,'ITVH',ITVH
!   PRINT *,'ISOTY',ISOTY
!   PRINT *,'ZCVL',ZCVL
!   PRINT *,'ZCVH',ZCVH
!   PRINT *,'ZCUR',ZCUR
!   PRINT *,'ZCIL',PCIL
!   PRINT *,'ZLAIL',ZLAIL
!   PRINT *,'ZLAIH',ZLAIH
!   PRINT *,'ZLAILP',ZLAILP
!   PRINT *,'ZLAIHP',ZLAIHP
!   PRINT *,'ZAVGPAR',ZAVGPAR
!   PRINT *,'PU',PU  
!   PRINT *,'PV',PV  
!   PRINT *,'PT',PT  
!   PRINT *,'PQ',PQ  
!   PRINT *,'PC',PC  
!   PRINT *,'PAPRS',PAPRS
!   PRINT *,'PGEOM1',PGEOM1
!   PRINT *,'PTL',PTL
!   PRINT *,'PTSA',PTSA
!   PRINT *,'PWSA',PWSA
!   PRINT *,'PFRSO(1,KLEV)',PFRSO(1,KLEV)
!   PRINT *,'PFRTH(1,KLEV)',PFRTH(1,KLEV)
!   PRINT *,'ZEMIS',ZEMIS
!   PRINT *,'PTSN',PTSN
!   PRINT *,'PTIA',PTIA
!   PRINT *,'PSST',PSST  
!   PRINT *,'ZFRTI',ZFRTI 
!   PRINT *,'ZALBTI',ZALBTI
!   PRINT *,'ZWLMX',ZWLMX
!   PRINT *,'ZCHAR',ZCHAR 
!   PRINT *,'ZCHARHQ',ZCHARHQ 
!   PRINT *,'PTL',PTL
!! skin temp at latest rad timestep
!   PRINT *,'PCFLX',PCFLX
!   PRINT *,'PZ0M',PZ0M
!   PRINT *,'PZ0H',PZ0H
!   PRINT *,'PVDIS',PVDIS 
!   PRINT *,'PFTLHEV',PFTLHEV
!   PRINT *,'PFTLHSB',PFTLHSB
!   PRINT *,'PFWSB',PFWSB
!   PRINT *,'PU10M',PU10M 
!   PRINT *,'PV10M',PV10M 
!   PRINT *,'PT2M',PT2M  
!   PRINT *,'PD2M',PD2M 
!   PRINT *,'PQ2M',PQ2M 
!   PRINT *,'PBLH',PBLH 
!   PRINT *,'ZFRSOTI',ZFRSOTI
!   PRINT *,'ZEVAPSNW',ZEVAPSNW
!   PRINT *,'PGUST',PGUST
!   PRINT *,'PZIDLWV',PZIDLWV
!!-UPDATED TENDENCIES
!   PRINT *,'ZTE',ZTE   
!   PRINT *,'ZQE',ZQE   
!   PRINT *,'ZVOM',ZVOM  
!   PRINT *,'ZVOL',ZVOL  
!   PRINT *,'ZTENC',ZTENC 
!   PRINT *,'PTLE1',PTLE1
!!-UPDATED FIELDS FOR TILES
!   PRINT *,'PUSTRTI',PUSTRTI
!   PRINT *,'PVSTRTI',PVSTRTI
!   PRINT *,'PAHFSTI',PAHFSTI
!   PRINT *,'PEVAPTI',PEVAPTI
!   PRINT *,'PTSKTI',PTSKTI
!!-OUTPUT FLUXES
!   PRINT *,'PDIFTS',PDIFTS
!   PRINT *,'PDIFTQ',PDIFTQ
!   PRINT *,'PSTRTU',PSTRTU
!   PRINT *,'PSTRTV',PSTRTV
!!    PRINT *,'ZKH',ZKH
! ! DDH OUTPUTS
!   PRINT *,'PDHTLS',PDHTLS
!   PRINT *,'PDHTSS',PDHTSS
!   PRINT *,'PDHTTS',PDHTTS
!   PRINT *,'PDHTIS',PDHTIS
!ENDIF

!   Create space for diagnostic array (for possible pp of canopy resitances)
!   Put LAT/LON in field 1 an 2, just in case that it is needed in SURF for debugging.  
PSURFL%ZEXDIAG(1:IPROMA,11,IBL)=PAUX%GELAT(1:IPROMA,IBL) ! Latitude
PSURFL%ZEXDIAG(1:IPROMA,12,IBL)=PAUX%GELAM(1:IPROMA,IBL) ! Longitude

  CALL VDFMAIN1S ( CDCONF=CDCONF,&
 & KIDIA=1, KFDIA=IPROMA, KLON=KLON, KLEV=KLEV, KLEVS=KLEVS, KSTEP=KSTEP, KTILES=KTILES, KVTYPES=KVTYPES, KDIAG=JPDIAG,&
 & KTRAC=KTRAC, KLEVSN=KLEVSN, KLEVI=KLEVI, LDLAND=LLKEYS%LLLAND, &
 & KDHVTLS=KDHVTLS, KDHFTLS=KDHFTLS, KDHVTSS=KDHVTSS, KDHFTSS=KDHFTSS, &
 & KDHVTTS=KDHVTTS,KDHFTTS=KDHFTTS,KDHVTIS=KDHVTIS,KDHFTIS=KDHFTIS, &
 & KDHVCO2S=KDHVCO2S,KDHFCO2S=KDHFCO2S,KDHVBVOCS=KDHVBVOCS,KDHVVEGS= KDHVVEGS,KDHFVEGS=KDHFVEGS,  &
 & LESNICE=LESNICE,&
 & PMU0=PAUX%PMU0M(:,IBL)   , &
 & PTSPHY=PTSPHY,KTVL=PSURF%ITVL(:,IBL),KCO2TYP=PSURF%ICO2TYP(:,IBL),KTVH=PSURF%ITVH(:,IBL),PCVL=PSURF%ZCVL(:,IBL),PCVH=PSURF%ZCVH(:,IBL), &
!Note that PLAT argument is renamed as GELAT here to avoid duplication
 & PCUR=PSURF%GSD%PCUR(:,IBL),PFWET=PSURF%PFWET(:,IBL),PLAT=PAUX%GELAT(:,IBL),PLAIL=PSURFL%ZLAIL(:,IBL),PLAIH=PSURFL%ZLAIH(:,IBL),&
 & PLAILP=PSURF%ZLAILP(:,IBL), PLAIHP=PSURF%ZLAIHP(:,IBL), PAVGPAR=PSURF%ZAVGPAR(:,IBL), PISOP_EP=PSURF%PISOP_EP(:,IBL), &
 & PCIL=PSURF%PCIL(:,IBL), &
 & PSNM1M=PSURFL%PSNS(:,:,IBL),PRSNM1M=PSURFL%PRSN(:,:,IBL), &
 & PUM1=STATE%PU(:,IBL) ,PVM1=STATE%PV(:,IBL)  ,PTM1=STATE%PT(:,IBL)  ,&
 & PQM1=STATE%PQ(:,IBL)  ,PCM1=GEMSL%PC(:,:,IBL)  ,&
 & PAPHM1=PAUX%PAPRS(:,:,IBL),PGEOM1=PAUX%PGEOM1(:,:,IBL),&
 & PTSKM1M=PSURF%GSP%PTL(:,IBL),PTSAM1M=PSURF%GSP%PTSA(:,:,IBL),PWSAM1M=PSURF%GSP%PWSA(:,:,IBL),&
 & PSSRFL=PFLUX%PFRSO(:,KLEV,IBL),PSLRFL=PFLUX%PFRTH(:,KLEV,IBL),PEMIS=PSURF%ZEMIS(:,IBL),&
 & PTSN=PSURF%GSP%PTSN(:,:,IBL), PTICE=PSURF%GSP%PTIA(:,:,IBL),&
 & PHLICE=PSURF%GSP%PHLICE(:,IBL), PTLICE=PSURF%GSP%PTLICE(:,IBL), PTLWML=PSURF%GSP%PTLWML(:,IBL), &                             !FLAKE
 & PSST=PSURF%GSP%PSST(:,IBL)  ,KSOTY=PSURF%ISOTY(:,IBL), PFRTI=PSURFL%ZFRTI(:,:,IBL) , PALBTI=PSURFL%ZALBTI(:,:,IBL), PWLMX=PSURFL%ZWLMX(:,IBL),&
 & PCHAR=PSURF%ZCHAR(:,IBL) , PCHARHQ=PSURF%ZCHARHQ(:,IBL), PUCURR=PSURF%ZUCURR(:,IBL) , PVCURR=PSURF%ZVCURR(:,IBL),&
 & PTSKRAD=PSURF%GSP%PTL(:,IBL),&                         ! skin temp at latest rad timestep
 & PCFLX=GEMSL%PCFLX(:,:,IBL),&
 & PSSDP2=PSURF%GSD%PSSDP2(:,:,IBL), PSSDP3=PSURF%GSD%PSSDP3(:,:,:,IBL),&
 !-OUTPUT
 & PZ0M=GEMSL%PZ0M(:,IBL) ,PZ0H=GEMSL%PZ0H(:,IBL) ,&
 & PVDIS=PDIAG%PVDIS(:,IBL) , PAHFLEV=PFLUX%PFTLHEV(:,IBL),&
 & PAHFLSB=PFLUX%PFTLHSB(:,IBL),&
 & PFWSB=PFLUX%PFWSB(:,IBL),&
 & PU10M=PSURF%GSD%PU10M(:,IBL) , PV10M=PSURF%GSD%PV10M(:,IBL) , &
 & PT2M=PSURF%GSD%PT2M(:,IBL)  , PD2M=PSURF%GSD%PD2M(:,IBL) ,&
 &  PQ2M=PSURF%GSD%PQ2M(:,IBL) ,PZINV=PDIAG%ZINV(:,IBL) ,PSSRFLTI=PSURFL%ZFRSOTI(:,:,IBL),PEVAPSNW=PSURFL%ZEVAPSNW(:,IBL),&
 & PEXDIAG=PSURFL%ZEXDIAG(:,:,IBL),PGUST=PDIAG%PGUST(:,IBL), PZIDLWV=PSURFL%PZIDLWV(:,IBL),&
 !-UPDATED TENDENCIES
 &  PTE=PSURF%ZTE(:,IBL)   ,PQE=PSURF%ZQE(:,IBL)  ,PVOM=PSURF%ZVOM(:,IBL)  ,&
 & PVOL=PSURF%ZVOL(:,IBL)  ,PTENC=PSURF%ZTENC(:,:,IBL) ,PTSKE1=PSURF%PTLE1(:,IBL),&
 !-UPDATED FIELDS FOR TILES
 & PUSTRTI=PSURF%PUSTRTI(:,:,IBL),PVSTRTI=PSURF%PVSTRTI(:,:,IBL), PAHFSTI=PSURF%PAHFSTI(:,:,IBL), &
 & PEVAPTI=PSURF%PEVAPTI(:,:,IBL), PTSKTI=PSURF%PTSKTI(:,:,IBL) ,PSLRFLTI=PSURFL%PSLRFLTI(:,:,IBL), &
 !-UPDATED FIELDS FOR VEGETATION TYPES
 & PANDAYVT=PSURFL%PANDAYVT(:,:,IBL),PANFMVT=PSURFL%PANFMVT(:,:,IBL),& 
 !-OUTPUT FLUXES
 & PEVAPTIU=PSURF%GSD%PEVAPTIU(:,:,IBL),PDIFTS=PFLUX%PDIFTS(:,:,IBL),PDIFTQ=PFLUX%PDIFTQ(:,:,IBL), &
 & PSTRTU=PFLUX%PSTRTU(:,:,IBL),PSTRTV=PFLUX%PSTRTV(:,:,IBL),PKH=PSURFL%ZKH(:,:,IBL),&
 & PAN=PSURF%PAN(:,IBL),PAG=PSURF%PAG(:,IBL),PRD=PSURF%PRD(:,IBL),PRSOIL_STR=PSURF%PRSOIL_STR(:,IBL),&
 & PRECO=PSURF%PRECO(:,IBL),PCO2FLUX=PSURF%PCO2FLUX(:,IBL),PCH4FLUX=PSURF%PCH4FLUX(:,IBL),& 
 & PBVOCFLUX=GEMSL%PBVOCFLUX(:,:,IBL), &
 ! DDH OUTPUTS
 & PDHTLS=PDDHS%PDHTLS(:,:,:,IBL),PDHTSS=PDDHS%PDHTSS(:,:,:,IBL),PDHTTS=PDDHS%PDHTTS(:,:,:,IBL), &
 & PDHTIS=PDDHS%PDHTIS(:,:,:,IBL),PDHCO2S=PDDHS%PDHCO2S(:,:,:,IBL),PDHBVOCS=PDDHS%PDHBVOCS(:,:,:,IBL),PDHVEGS=PDDHS%PDHVEGS(:,:,:,IBL))

  
!IF (LDEBUGPRINT) THEN
!   PRINT *, "DEBUG IN VDFMAIN1S:"
!   PRINT *, "<------------------"
!   PRINT *,'CDCONF',CDCONF
!   PRINT *,'KIDIA',KIDIA
!   PRINT *,'KFDIA',KFDIA
!   PRINT *,'KLON',KLON
!   PRINT *,'KLEV',KLEV
!   PRINT *,'KLEVS',KLEVS
!   PRINT *,'KSTEP',KSTEP
!   PRINT *,'KTILES',KTILES
!   PRINT *,'KTRAC',KTRAC
!   PRINT *,'KLEVSN',KLEVSN 
!   PRINT *,'KLEVI',KLEVI  
!   PRINT *,'KDHVTLS',KDHVTLS
!   PRINT *,'KDHFTLS',KDHFTLS
!   PRINT *,'KDHVTSS',KDHVTSS
!   PRINT *,'KDHFTSS',KDHFTSS
!   PRINT *,'KDHVTTS',KDHVTTS
!   PRINT *,'KDHFTTS',KDHFTTS
!   PRINT *,'KDHVTIS',KDHVTIS
!   PRINT *,'KDHFTIS',KDHFTIS
!   PRINT *,'PTSPHY',PTSPHY
!   PRINT *,'ITVL',ITVL
!   PRINT *,'ICO2TYP',ICO2TYP
!   PRINT *,'ITVH',ITVH
!   PRINT *,'ZCVL',ZCVL
!   PRINT *,'ZCVH',ZCVH
!   PRINT *,'ZCUR',ZCUR
!   PRINT *,'ZLAIL',ZLAIL
!   PRINT *,'ZLAIH',ZLAIH
!   PRINT *,'PU',PU  
!   PRINT *,'PV',PV  
!   PRINT *,'PT',PT  
!   PRINT *,'PQ',PQ  
!   PRINT *,'PC',PC  
!   PRINT *,'PAPRS',PAPRS
!   PRINT *,'PGEOM1',PGEOM1
!   PRINT *,'PTL',PTL
!   PRINT *,'PTSA',PTSA
!   PRINT *,'PWSA',PWSA
!   PRINT *,'PFRSO(1,KLEV)',PFRSO(1,KLEV)
!   PRINT *,'PFRTH(1,KLEV)',PFRTH(1,KLEV)
!   PRINT *,'ZEMIS',ZEMIS
!   PRINT *,'PTSN',PTSN
!   PRINT *,'PTIA',PTIA
!   PRINT *,'PSST',PSST  
!   PRINT *,'ZFRTI',ZFRTI 
!   PRINT *,'ZALBTI',ZALBTI
!   PRINT *,'ZWLMX',ZWLMX
!   PRINT *,'ZCHAR',ZCHAR 
!   PRINT *,'ZCHARHQ',ZCHARHQ 
!   PRINT *,'PTL',PTL
!! skin temp at latest rad timestep
!   PRINT *,'PCFLX',PCFLX
!   PRINT *,'PZ0M',PZ0M
!   PRINT *,'PZ0H',PZ0H
!   PRINT *,'PVDIS',PVDIS 
!   PRINT *,'PFTLHEV',PFTLHEV
!   PRINT *,'PFTLHSB',PFTLHSB
!   PRINT *,'PFWSB',PFWSB
!   PRINT *,'PU10M',PU10M 
!   PRINT *,'PV10M',PV10M 
!   PRINT *,'PT2M',PT2M  
!   PRINT *,'PD2M',PD2M 
!   PRINT *,'PQ2M',PQ2M 
!   PRINT *,'PBLH',PBLH 
!   PRINT *,'ZFRSOTI',ZFRSOTI
!   PRINT *,'ZEVAPSNW',ZEVAPSNW
!   PRINT *,'PGUST',PGUST
!   PRINT *,'PZIDLWV',PZIDLWV
!!-UPDATED TENDENCIES
!   PRINT *,'ZTE',ZTE   
!   PRINT *,'ZQE',ZQE   
!   PRINT *,'ZVOM',ZVOM  
!   PRINT *,'ZVOL',ZVOL  
!   PRINT *,'ZTENC',ZTENC 
!   PRINT *,'PTLE1',PTLE1
!!-UPDATED FIELDS FOR TILES
!   PRINT *,'PUSTRTI',PUSTRTI
!   PRINT *,'PVSTRTI',PVSTRTI
!   PRINT *,'PAHFSTI',PAHFSTI
!   PRINT *,'PEVAPTI',PEVAPTI
!   PRINT *,'PTSKTI',PTSKTI
!!-OUTPUT FLUXES
!   PRINT *,'PDIFTS',PDIFTS
!   PRINT *,'PDIFTQ',PDIFTQ
!   PRINT *,'PSTRTU',PSTRTU
!   PRINT *,'PSTRTV',PSTRTV
!   PRINT *,'ZKH',ZKH
! ! DDH OUTPUTS
!   PRINT *,'PDHTLS',PDHTLS
!   PRINT *,'PDHTSS',PDHTSS
!   PRINT *,'PDHTTS',PDHTTS
!   PRINT *,'PDHTIS',PDHTIS
!  STOP
!ENDIF

ELSE

!*         3.1     NECESSARY COMPUTATIONS IF SUBROUTINE IS BY-PASSED.      

  PDIAG%PVDIS(1:IPROMA,IBL)=0._JPRB
  PFLUX%PFTLHEV(1:IPROMA,IBL)=0._JPRB
  PFLUX%PFTLHSB(1:IPROMA,IBL)=0._JPRB
  PFLUX%PFWSB(1:IPROMA,IBL)=0._JPRB
  PSURFL%ZEVAPSNW(1:IPROMA,IBL)=0._JPRB
  PFLUX%PDIFTQ(1:IPROMA,1:KLEVS,IBL)=0._JPRB
  PFLUX%PDIFTS(1:IPROMA,1:KLEVS,IBL)=0._JPRB
  PFLUX%PSTRTU(1:IPROMA,1:KLEVS,IBL)=0._JPRB
  PFLUX%PSTRTV(1:IPROMA,1:KLEVS,IBL)=0._JPRB
  DO JTILE=1,KTILES
    PSURFL%ZFRSOTI(1:IPROMA,JTILE,IBL)=PFLUX%PFRSO(1:IPROMA,KLEV,IBL)
    PSURF%PUSTRTI(1:IPROMA,JTILE,IBL)=0._JPRB
    PSURF%PVSTRTI(1:IPROMA,JTILE,IBL)=0._JPRB
    PSURF%PAHFSTI(1:IPROMA,JTILE,IBL)=0._JPRB
    PSURF%PEVAPTI(1:IPROMA,JTILE,IBL)=0._JPRB
    PSURF%PTSKTI(1:IPROMA,JTILE,IBL)=PSURF%GSP%PTL(1:IPROMA,IBL)
  ENDDO
ENDIF
    ENDDO
!$OMP END PARALLEL DO
!$OMP PARALLEL DO PRIVATE(IST,IEND,IBL,IPROMA)
DO IST = KIDIA, KFDIA, NPROMA
  IEND = MIN(IST+NPROMA-1,KFDIA-KIDIA+1)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1
!     ------------------------------------------------------------------

!*         4.      COMPUTATION OF NEW SURFACE VALUES
!                  ---------------------------------

PAUXL%ZPAPSRF(1:IPROMA,IBL)=PAUX%PAPRS(1:IPROMA,KLEV,IBL)
IF ( LESURF ) THEN
!*         4.1   CALL SURFTSTP
  PFLUX%ZFRTH(1:IPROMA,IBL)=PFLUX%PFRTH(1:IPROMA,KLEV,IBL)  
  PSURFL%ZTHKICE(1:IPROMA,IBL)=1.5_JPRB
  LNEMOICETHK=.FALSE.
!-END OF CALL SURFTSTP

  CALL SURFTSTP  (YSURF=YSURF, KIDIA=1, KFDIA=IPROMA,&
   &  KLON=KLON, KLEVS=KLEVS, KCWS=NCWS, KTILES=KTILES,&
   &  KLEVSN=KLEVSN,   KLEVO=KLEVO ,KLEVI=KLEVI, KSTART=KSTART, KSTEP=KSTEP,&!KP
   &  KDHVTSS=KDHVTSS, KDHFTSS=KDHFTSS,&
   &  KDHVTTS=KDHVTTS, KDHFTTS=KDHFTTS,&
   &  KDHVTIS=KDHVTIS, KDHFTIS=KDHFTIS,&
   &  KDHVSSS=KDHVSSS, KDHFSSS=KDHFSSS,&
   &  KDHVIIS=KDHVIIS, KDHFIIS=KDHFIIS,&
   &  KDHVWLS=KDHVWLS, KDHFWLS=KDHFWLS,&
   &  KDHVBIOS=KDHVBIOS, KDHFBIOS=KDHFBIOS,&!CTESSEL
   &  KDHVVEGS=KDHVVEGS, KDHFVEGS=KDHFVEGS,&!CTESSEL
   &  KTVL=PSURF%ITVL(:,IBL) ,KTVH=PSURF%ITVH(:,IBL), KVEG=PSURF%IVEG(:,:,IBL),KSOTY=PSURF%ISOTY(:,IBL),& !Why KVEG not in DT!!!
   &  PSSDP2=PSURF%GSD%PSSDP2(:,:,IBL), PSSDP3=PSURF%GSD%PSSDP3(:,:,:,IBL), &
   &  PTSPHY=PTSPHY,PSDOR=PSURF%PSDOR(:,IBL), PFRTI=PSURFL%ZFRTI(:,:,IBL),&
   &  PSST=PSURF%GSP%PSST(:,IBL), PUSTRTI=PSURF%PUSTRTI(:,:,IBL), PVSTRTI=PSURF%PVSTRTI(:,:,IBL),&
   &  PAHFSTI=PSURF%PAHFSTI(:,:,IBL), PEVAPTI=PSURF%PEVAPTI(:,:,IBL), &
   &  PSSRFLTI=PSURFL%ZFRSOTI(:,:,IBL),PSLRFLTI=PSURFL%PSLRFLTI(:,:,IBL),&
!Note that PLAT is again GELAT here,, CALLPAR argument was duplicated under two different names. Check if correct!
   &  PLAT=PAUX%GELAT(:,IBL),PANFMVT=PSURFL%PANFMVT(:,:,IBL), PANDAYVT=PSURFL%PANDAYVT(:,:,IBL), PMU0=PAUX%PMU0M(:,IBL),&!CTESSEL    
   &  PCVT=PSURFL%ZCVT(:,:,IBL), PLAIVT=PSURFL%ZLAIVT(:,:,IBL),  &
   & PLAIL=PSURFL%ZLAIL(:,IBL), PLAIH=PSURFL%ZLAIH(:,IBL),&!CTESSEL
   &  PCIL=PSURF%PCIL(:,IBL), &
   &  PLAILC=PSURF%GSD%PLAILC(:,IBL), PLAIHC=PSURF%GSD%PLAIHC(:,IBL),&
   &  LDLAND=LLKEYS%LLLAND(:,IBL), LDSICE=LLKEYS%LLSICE(:,IBL), LDLICE=LLKEYS%LLLICE(:,IBL), LDSI=LESICE, LDNH=LLKEYS%LLNH(:,IBL), &
   &  LDOCN_KPP=LLKEYS%LLOCN_KPP(:,IBL),&
   &  PSNM1M=PSURFL%PSNS(:,:,IBL) ,PTSNM1M=PSURF%GSP%PTSN(:,:,IBL), PASNM1M=PSURF%GSP%PASN(:,IBL), &
   &  PRSNM1M=PSURFL%PRSN(:,:,IBL), PWSNM1M=PSURFL%PWSN(:,:,IBL), &
   &  PAPRS=PAUXL%ZPAPSRF(:,IBL), PTSKM1M=PSURF%GSP%PTL(:,IBL),&
   &  PTSAM1M=PSURF%GSP%PTSA(:,:,IBL), PTIAM1M=PSURF%GSP%PTIA(:,:,IBL),&
   &  PWLM1M=PSURFL%PWL(:,IBL), PWSAM1M=PSURF%GSP%PWSA(:,:,IBL),&
   &  PTLICEM1M=PSURF%GSP%PTLICE(:,IBL),PTLMNWM1M=PSURF%GSP%PTLMNW(:,IBL),&!LAKE
   &  PTLWMLM1M=PSURF%GSP%PTLWML(:,IBL),PTLBOTM1M=PSURF%GSP%PTLBOT(:,IBL),&!LAKE
   &  PTLSFM1M=PSURF%GSP%PTLSF(:,IBL),&!LAKE
   &  PHLICEM1M=PSURF%GSP%PHLICE(:,IBL),PHLMLM1M=PSURF%GSP%PHLML(:,IBL),&!LAKE
   &  PGEMU=PAUX%PGEMU(:,IBL),&
   &  PLDEPTH=PSURF%GSD%PLDEPTH(:,IBL),LDLAKE=LLKEYS%LLLAKE(:,IBL), PCLAKE=PSURF%GSD%PCLAKE(:,IBL),&!LAKE
   &  PRSFC=PFLUX%PFPLCL(:,IBL),PRSFL=PFLUX%PFPLSL(:,IBL),&
   &  PSLRFL=PFLUX%ZFRTH(:,IBL), PSSFC=PFLUX%PFPLCN(:,IBL), PSSFL=PFLUX%PFPLSN(:,IBL),&
   &  PCVL=PSURF%ZCVL(:,IBL), PCVH=PSURF%ZCVH(:,IBL), PCUR=PSURF%GSD%PCUR(:,IBL), &
   &  PWLMX=PSURFL%ZWLMX(:,IBL) , PEVAPSNW=PSURFL%ZEVAPSNW(:,IBL),&
   &  PUSRF=STATE%PU(:,IBL),PVSRF=STATE%PV(:,IBL),PTSRF=STATE%PT(:,IBL),&

!-KPP
   &  PZO=PSURF%GSD%PZO(:,:,IBL),PHO=PSURF%GSD%PHO(:,:,IBL),&
   &  PHO_INV=PSURF%GSD%PHO_INV(:,:,IBL),PDO=PSURF%GSD%PDO(:,:,IBL),&
   &  POCDEPTH=PSURF%GSD%POCDEPTH(:,IBL),&
   &  PUO0=PSURF%GSP%PUO0(:,:,IBL),PVO0=PSURF%GSP%PVO0(:,:,IBL),&
   &  PUOC=PSURF%GSP%PUOC(:,:,IBL),PVOC=PSURF%GSP%PVOC(:,:,IBL),&
   &  PTO0=PSURF%GSP%PTO0(:,:,IBL),&
   &  PSO0=PSURF%GSP%PSO0(:,:,IBL),PADVT=PSURF%GSD%PADVT(:,:,IBL),&
   &  PADVS=PSURF%GSD%PADVS(:,:,IBL),PTRI0=PSURF%GSD%PTRI0(:,:,IBL),&
   &  PTRI1=PSURF%GSD%PTRI1(:,:,IBL),&
   &  PSWDK_SAVE=PSURF%GSD%PSWDK_SAVE(:,:,IBL),PUSTRC=PSURF%PUSTRC(:,IBL),&
   &  PVSTRC=PSURF%PVSTRC(:,IBL),&

   &  PUSTOKES=PSURF%PUSTOKES(:,IBL),PVSTOKES=PSURF%PVSTOKES(:,IBL),&
   &  PTAUOCX=PSURF%GSD%PTAUOCX(:,IBL),PTAUOCY=PSURF%GSD%PTAUOCY(:,IBL),&
   &  PPHIOC=PSURF%PPHIOC(:,IBL),&
   &  PWSEMEAN=PSURF%PWSEMEAN(:,IBL),PWSFMEAN=PSURF%PWSFMEAN(:,IBL),&
   &  LNEMOICETHK=LNEMOICETHK, PTHKICE=PSURFL%ZTHKICE(:,IBL), &

!-DIAGNOSTICS OUTPUT
   & PTSDFL=PFLUX%PFTG12(:,IBL), PROFD=PFLUX%PFWROD(:,IBL), PROFS=PFLUX%PFWRO1(:,IBL),&
   & PWFSD=PFLUX%PFWG12(:,IBL), PMELT=PFLUX%PFWMLT(:,IBL), PFWEV=PFLUX%PFWEV(:,IBL) , PENES=PFLUX%ZENES(:,:,IBL),&
   & PDIFM=PSURF%PDIFM(:,:,IBL), PDIFT=PSURF%PDIFT(:,:,IBL),&
   & PDIFS=PSURF%PDIFS(:,:,IBL), POTKE=PSURF%GSD%POTKE(:,:,IBL),&
   & PRESPBSTR=PSURF%PRESPBSTR(:,:,IBL),PRESPBSTR2=PSURF%PRESPBSTR2(:,:,IBL),PBIOMASS_LAST=PSURF%PBIOMASS_LAST(:,:,IBL),& !CTESSEL
   & PBIOMASSTR_LAST=PSURF%PBIOMASSTR_LAST(:,:,IBL),PBIOMASSTR2_LAST=PSURF%PBIOMASSTR2_LAST(:,:,IBL), &    !CTESSEL
   & PBLOSSVT=PSURF%PBLOSSVT(:,:,IBL), PBGAINVT=PSURF%PBGAINVT(:,:,IBL),&                                  !CTESSEL
   & PLAI=PSURF%PLAI(:,IBL), PBIOM=PSURF%PBIOM(:,IBL), PBLOSS=PSURF%PBLOSS(:,IBL),PBGAIN=PSURF%PBGAIN(:,IBL),&                   !CTESSEL
   & PBIOMSTR=PSURF%PBIOMSTR(:,IBL),PBIOMSTR2=PSURF%PBIOMSTR2(:,IBL),&    
                             !CTESSEL  
!-TENDENCIES OUTPUT
   &  PSNE1=PSURF%PSNSE1(:,:,IBL), PTSNE1=PSURF%PTSNE1(:,:,IBL), PASNE1=PSURF%PASNE1(:,IBL),&
   &  PRSNE1=PSURF%PRSNE1(:,:,IBL), PWSNE1=PSURF%PWSNE1(:,:,IBL), PTSAE1=PSURF%PTSAE1(:,:,IBL), PTIAE1=PSURF%PTIAE1(:,:,IBL),&
   &  PWLE1=PSURF%PWLE1(:,IBL),PWSAE1=PSURF%PWSAE1(:,:,IBL),&
   & PTLICEE1=PSURF%PTLICEE1(:,IBL),PTLMNWE1=PSURF%PTLMNWE1(:,IBL),PTLWMLE1=PSURF%PTLWMLE1(:,IBL),& !LAKE
   & PTLBOTE1=PSURF%PTLBOTE1(:,IBL),PTLSFE1=PSURF%PTLSFE1(:,IBL),&                           !LAKE
   & PHLICEE1=PSURF%PHLICEE1(:,IBL),PHLMLE1=PSURF%PHLMLE1(:,IBL),&                           !LAKE
   & PUOE1=PSURF%PUOE1(:,:,IBL),PVOE1=PSURF%PVOE1(:,:,IBL),PTOE1=PSURF%PTOE1(:,:,IBL),PSOE1=PSURF%PSOE1(:,:,IBL),&     
   & PLAIE1=PSURF%PLAIE1(:,:,IBL),PBSTRE1=PSURF%PBSTRE1(:,:,IBL),PBSTR2E1=PSURF%PBSTR2E1(:,:,IBL), &                      !CTESSEL  

!-DDH OUTPUTS
   & PDHTSS=PDDHS%PDHTSS(:,:,:,IBL), PDHTTS=PDDHS%PDHTTS(:,:,:,IBL), PDHTIS=PDDHS%PDHTIS(:,:,:,IBL),&
   & PDHSSS=PDDHS%PDHSSS(:,:,:,IBL), PDHIIS=PDDHS%PDHIIS(:,:,IBL), PDHWLS=PDDHS%PDHWLS(:,:,:,IBL),&
   & PDHBIOS=PDDHS%PDHBIOS(:,:,:,IBL),PDHVEGS=PDDHS%PDHVEGS(:,:,:,IBL))     
!write(6,*) 'callpar1s pdhwls(1,4,8)',pdhwls(1,4,8)
ELSE

!*         4.2     NECESSARY COMPUTATIONS IF SUBROUTINE IS BY-PASSED.
  PFLUX%PFTG12(1:IPROMA,IBL)=0._JPRB
  PFLUX%PFWROD(1:IPROMA,IBL)=0._JPRB
  PFLUX%PFWRO1(1:IPROMA,IBL)=0._JPRB
  PFLUX%PFWMLT(1:IPROMA,IBL)=0._JPRB
  PFLUX%PFWG12(1:IPROMA,IBL)=0._JPRB
  PFLUX%PFWEV(1:IPROMA,IBL)=0._JPRB
ENDIF

!*              5.     END OF E.C.M.W.F. PHYSICS
!                      -------------------------
    ENDDO
!$OMP END PARALLEL DO
IF (LHOOK) CALL DR_HOOK('CALLPAR1S',1,ZHOOK_HANDLE)

END SUBROUTINE CALLPAR1S_LAYER_OPENMP

END MODULE CALLPAR1S_LAYER_MOD
