
SUBROUTINE CPG1S_LAYER

USE YOMDPHY  ,  ONLY : NCSS     ,NLEV     ,NGPP     ,NPOI     ,NTILES   ,&
     &                 NTRAC   ,NVHILO    ,NCOM     ,YSURF    ,NCSNEC   ,&
     &                 NBLOCKS
USE YOERAD   , ONLY : NSW, NTSW, NLWEMISS  
USE YOMCDH1S  , ONLY : NLEVI  , &
     &  NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
     &  NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS, &
     &  NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS, &
     &  NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS, &
     &  NDHVCO2S,NDHFCO2S, &
     &  NDHVBIOS,NDHFBIOS,NDHVBVOCS,NDHVVEGS,NDHFVEGS
 
USE YOMDYN1S , ONLY : NSTEP    ,TDT,TSTEP
USE YOMGPD1S , ONLY : VFZ0F    ,VFALBF   ,&
     &            VFALUVP  ,VFALUVD  ,VFALNIP  ,VFALNID  , &
     &            VFALUVI  ,VFALUVV  ,VFALUVG  , &
     &            VFALNII  ,VFALNIV  ,VFALNIG  , &
     &            VFITM    , &
     &            VFZ0H    ,VFCVL    ,VFCVH    ,VFCUR    ,VFTVL    ,VFTVH    , &
     &            VFLAIL   ,VFLAIH   ,VFFWET   ,VFAVGPAR ,VFRSML   ,VFRSMH   , &
     &            VFSOTY   ,VFCI     ,VFCIL, VFSST    ,VFSDOR   , &
     &            VFCO2TYP, VFISOP_EP, &
     &            VDALB    ,VDZ0F    ,VDZ0H    , &
     &            VDIEWSSTL,VDINSSSTL,VDISSHFTL,VDIETL   ,VDTSKTL,&
     &            VFLDEPTH,VFCLAKEF   ,& ! FLAKE
     &            VFZO     ,VFHO     ,VFHO_INV ,VFDO     ,VFOCDEPTH, & !KPP 
     &            VFADVT ,VFADVS  ,VFTRI0   ,VFTRI1   ,VFSWDK_SAVE,&  !KPP
     &            VDANDAYVT,VDANFMVT , &
     &            VDRESPBSTR,VDRESPBSTR2,VDBIOMASS_LAST,&
     &            VDBLOSSVT,VDBGAINVT, GPD_SDP2, GPD_SDP3

USE YOMGF1S  , ONLY : UNLEV0   ,VNLEV0   ,TNLEV0   ,QNLEV0   , CNLEV0  ,&
     &            PNLP0    ,UNLEV1   ,VNLEV1   ,TNLEV1   ,QNLEV1   , PNLP1, &
     &            CNLEV1   ,FSSRD    ,FSTRD    ,FLSRF    ,FCRF     , &
     &            FLSSF    , &
     &            FCSF     ,RALT
USE YOMGP1S0 , ONLY : GP0      ,TSLNU0   ,QLINU0   ,FSNNU0   , &
     &            TSNNU0   ,ASNNU0   ,RSNNU0   , WSNNU0,&
     &            TRENU0   ,WRENU0   ,TILNU0,&
     &            TLICENU0,TLMNWNU0,TLWMLNU0,TLBOTNU0,TLSFNU0,& ! FLAKE
     &            HLICENU0,HLMLNU0 ,&                           ! FLAKE
     &            UONU0    ,VONU0    ,TONU0    ,SONU0,&         ! KPP
!     &            UONUC    ,VONUC    ,USTRCNU  ,VSTRNUC,&       ! KPP
     &            LAINU0, BSTRNU0, BSTR2NU0
USE YOMGP1S1 , ONLY : GP1
USE PTRGP1S  , ONLY : MTSLNU   ,MQLINU   ,MFSNNU   , &
     &            MTSNNU   ,MASNNU   ,MRSNNU   , &
     &            MTRENU   ,MWRENU   ,MTILNU, & 
     &            MTLICENU,MTLMNWNU,MTLWMLNU,MTLBOTNU,MTLSFNU,& ! FLAKE
     &            MHLICENU,MHLMLNU,&                            ! FLAKE 
     &            MUONU    ,MVONU    ,MTONU    ,MSONU,&           !KPP
     &            MLAINU , MBSTRNU, MBSTR2NU,MWSNNU
USE YOMLOG1S,   ONLY: IDBGS1

USE YOMGC1S  , ONLY : GEMU     ,GELAM    ,GELAT
USE YOMCT01S , ONLY : NSTART
USE YOMCST   , ONLY : RG
USE YOERIP   , ONLY : RCODECM  ,RSIDECM  ,RCOVSRM  ,RSIVSRM
USE YOMDIM1S , ONLY : NPROMA

USE YOMRIP   , ONLY :  RCODEC  ,RSIDEC  ,RCOVSR  ,RSIVSR
USE YOEPHY   , ONLY :  NALBEDOSCHEME, RLAIINT, LBVOC_EMIS

USE YOMGDI1S , ONLY : GDI1S    ,N2DDI ,&
                      &GDIAUX1S ,N2DDIAUX

USE YOMLUN1S, ONLY : NULOUT
USE YOMSURF_SSDP_MOD, ONLY : NSSDP2D, NSSDP3D

USE ECPHYS_SURFACE_TYPE_MOD, ONLY: SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE
USE ECPHYS_SURFACE_TYPE_MOD, ONLY: DDH_SURF_TYPE
USE ECPHYS_AUX_DIAG_TYPE_MOD, ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECPHYS_AUX_TYPE_MOD, ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECPHYS_FLUX_TYPE_MOD, ONLY: FLUX_TYPE
USE ECLAND_STATE_TYPE_MOD, ONLY: STATE_TYPE
USE YOMPHYDER, ONLY: GEMS_LOCAL_TYPE

USE CALLPAR1S_LAYER_MOD, ONLY: CALLPAR1S_LAYER_OPENMP
USE OMP_LIB
!USE MPL_MODULE


#ifdef DOC
! (C) Copyright 1995- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!**** *CPG1S* - Grid point calculations.

!     Purpose.
!     --------
!           Grid point calculations .

!**   Interface.
!     ----------
!        *CALL* *CPG1S*

!        Explicit arguments :
!        --------------------

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        Called by STEPO1S.

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the one column model

!     Author.
!     -------
!        Pedro Viterbo   *ECMWF*

!     Modifications.
!     --------------
!        Original : 95-03-21
!        Bart vd Hurk (KNMI): multi-column setup
!     S. Boussetta/G.Balsamo May 2010 Add CTESSEL based on:
!        Marita Voogt (KNMI) "C-Tessel" 09/2005
!        Sebastien Lafont (ECMWF) "C-TESSEL"

!     ------------------------------------------------------------------
#endif
USE PARKIND1  ,ONLY : JPIM     ,JPRB,    JPRD
USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK
IMPLICIT NONE


CHARACTER*1 :: CDCONF 
REAL(KIND=JPRB),TARGET ::  ZKH(NPROMA,NLEV,NBLOCKS)
REAL(KIND=JPRB),TARGET ::  ZAPRS(NPROMA,0:NLEV,NBLOCKS),ZAPHIF(NPROMA,NLEV,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZDIFTQ(NPROMA,0:NLEV,NBLOCKS),ZDIFTS(NPROMA,0:NLEV,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZFRSO(NPROMA,0:NLEV,NBLOCKS),PFRTH(NPROMA,0:NLEV,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZSTRTU(NPROMA,0:NLEV,NBLOCKS),ZSTRTV(NPROMA,0:NLEV,NBLOCKS)

REAL(KIND=JPRB), DIMENSION(NPROMA,NBLOCKS), TARGET ::  ZAN,ZAG,ZRD &
     &   , ZRSOIL_STR,ZRECO,ZCO2FLUX,ZCH4FLUX
REAL(KIND=JPRB), DIMENSION(NPROMA,NDHVBVOCS,NBLOCKS), TARGET :: ZBVOCFLUX 
REAL(KIND=JPRB), DIMENSION(NPROMA,NBLOCKS), TARGET ::  ZLAI,ZBIOM,ZBLOSS,ZBGAIN &
     &   , ZBIOMSTR,ZBIOMSTR2

REAL(KIND=JPRB), TARGET ::  ZMU0M(NPROMA,NBLOCKS),   ZFTG12(NPROMA,NBLOCKS)  &
     &   , ZFWEV(NPROMA,NBLOCKS)   ,ZFWSB(NPROMA,NBLOCKS)   ,ZFWG12(NPROMA,NBLOCKS) &
     &   , ZFWMLT(NPROMA,NBLOCKS)  ,ZFWROD(NPROMA,NBLOCKS)  ,ZFWRO1(NPROMA,NBLOCKS) &
     &   , ZFTLHEV(NPROMA,NBLOCKS) ,ZFTLHSB(NPROMA,NBLOCKS) ,ZVDIS(NPROMA,NBLOCKS)  &
     &   , ZCFLX(NPROMA,NTRAC,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZDHTLS(NPROMA,NTILES,NDHVTLS+NDHFTLS,NBLOCKS) 
REAL(KIND=JPRB), TARGET :: ZDHTSS(NPROMA,NCSNEC,NDHVTSS+NDHFTSS,NBLOCKS) 
REAL(KIND=JPRB), TARGET :: ZDHSSS(NPROMA,NCSNEC,NDHVSSS+NDHFSSS,NBLOCKS) 
REAL(KIND=JPRB), TARGET :: ZDHTTS(NPROMA,NCSS  ,NDHVTTS+NDHFTTS,NBLOCKS) 
REAL(KIND=JPRB), TARGET :: ZDHWLS(NPROMA,NCSS  ,NDHVWLS+NDHFWLS,NBLOCKS) 
REAL(KIND=JPRB), TARGET :: ZDHTIS(NPROMA,NLEVI ,NDHVTIS+NDHFTIS,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZDHIIS(NPROMA,       NDHVIIS+NDHFIIS,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZDHRESS(NPROMA,2    ,NDHVRESS+NDHFRESS,NBLOCKS) 
REAL(KIND=JPRB), TARGET :: ZENES(NPROMA,NCSS,NBLOCKS) 

REAL(KIND=JPRB), TARGET :: ZDIFM(NPROMA,0:NCOM,NBLOCKS)     !KPP
REAL(KIND=JPRB), TARGET :: ZDIFT(NPROMA,0:NCOM,NBLOCKS)     !KPP
REAL(KIND=JPRB), TARGET :: ZDIFS(NPROMA,0:NCOM,NBLOCKS)     !KPP
REAL(KIND=JPRB), TARGET :: ZOTKE(NPROMA,0:NCOM,NBLOCKS)     !TKE
REAL(KIND=JPRB) :: UONUC(NPOI,0:NCOM)     !KPP 
REAL(KIND=JPRB) :: VONUC(NPOI,0:NCOM)     !KPP
REAL(KIND=JPRB) :: USTRCNU(NPOI)          !KPP
REAL(KIND=JPRB) :: VSTRNUC(NPOI)          !KPP
REAL(KIND=JPRB), TARGET :: ZPUSTRC(NPROMA,NBLOCKS)                  !KPP
REAL(KIND=JPRB), TARGET :: ZPVSTRC(NPROMA,NBLOCKS)                  !KPP
REAL(KIND=JPRB), TARGET :: ZPUOC(NPROMA,1:NCOM+1,NBLOCKS)                  !KPP
REAL(KIND=JPRB), TARGET :: ZPVOC(NPROMA,1:NCOM+1,NBLOCKS)                  !KPP
REAL(KIND=JPRB), TARGET  :: BLK_GPD_SDP2(NPROMA,NSSDP2D,NBLOCKS)          !KPP
REAL(KIND=JPRB), TARGET  :: BLK_GPD_SDP3(NPROMA,NCSS,NSSDP3D,NBLOCKS)          !KPP

REAL(KIND=JPRB),TARGET :: ZDHCO2S(NPROMA,NVHILO,NDHVCO2S+NDHFCO2S,NBLOCKS)
REAL(KIND=JPRB),TARGET :: ZDHBIOS(NPROMA,NVHILO,NDHVBIOS+NDHFBIOS,NBLOCKS)
REAL(KIND=JPRB),TARGET :: ZDHBVOCS(NPROMA,NVHILO,NDHVBVOCS,NBLOCKS)
REAL(KIND=JPRB),TARGET :: ZDHVEGS(NPROMA,NVHILO,NDHVVEGS+NDHFVEGS,NBLOCKS)

REAL(KIND=JPRB), TARGET ::  ZLAIHI(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZLAILI(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZAVGPARC(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZALCOEFF(NPROMA,6,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZTE(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZQE(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVOM(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVOL(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZTENC(NPROMA,NTRAC,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZCSN(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZCVT(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZLAIVT(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZCVL(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZCVH(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZCUR(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZUCURR(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVCURR(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZLAIL(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZLAIH(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZWLMX(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZFRTH(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZTHKICE(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZCCNL(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZCCNO(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZWS1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZWND(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZCHAR(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZCHARHQ(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZFRTI(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZFRSOTI(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZSLRFLTI(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZALBTI(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZSPECTRALEMISS(NPROMA,NLWEMISS,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZEVAPSNW(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZEMIS(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZINV(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZPAPSRF(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZLAILP(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZLAIHP(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZALBD(NPROMA,NTSW,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZALBP(NPROMA,NTSW,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  PUSTOKES(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  PVSTOKES(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  PTAUOCX(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  PTAUOCY(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  PPHIOC(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  PVDIS(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  PWSEMEAN(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  PWSFMEAN(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  PALBICEF(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVFISOP_EP(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVFFWET(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDIEWSSTL(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDINSSSTL(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDISSHFTL(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDIETL(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDTSKTL(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDRESPBSTR(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDRESPBSTR2(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDBIOMASS_LAST(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZBSTRNU0(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZBSTR2NU0(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDBLOSSVT(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDBGAINVT(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDANDAYVT(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDANFMVT(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVFCIL(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVFSDOR(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVFAVGPAR(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDZ0F(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZVDZ0H(NPROMA,NBLOCKS)

LOGICAL, TARGET :: LLLAND(NPROMA,NBLOCKS)
LOGICAL, TARGET :: LLSICE(NPROMA,NBLOCKS)
LOGICAL, TARGET :: LLNH(NPROMA,NBLOCKS)
LOGICAL, TARGET :: LLLICE(NPROMA,NBLOCKS)
LOGICAL, TARGET :: LLLAKE(NPROMA,NBLOCKS)
LOGICAL, TARGET :: LLOCN_KPP(NPROMA,NBLOCKS)
INTEGER(KIND=JPIM), TARGET :: ITVL(NPROMA,NBLOCKS)
INTEGER(KIND=JPIM), TARGET :: ITVH(NPROMA,NBLOCKS)
INTEGER(KIND=JPIM), TARGET :: ISOTY(NPROMA,NBLOCKS)
INTEGER(KIND=JPIM), TARGET :: ICO2TYP(NPROMA,NBLOCKS)
INTEGER(KIND=JPIM), TARGET :: IVEG(NPROMA,NVHILO,NBLOCKS)

REAL(KIND=JPRB), TARGET ::  ZEVAPTIU(NPROMA,NTILES,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZEXDIAG(NPROMA,12,NBLOCKS)

 
!    *ZU10M*        U-COMPONENT WIND AT 10 M                      M/S
!    *ZV10M*        V-COMPONENT WIND AT 10 M                      M/S
!    *ZT2M*         TEMPERATURE AT 2M                                K
!    *ZD2M*         DEW POINT TEMPERATURE AT 2M                      K
!    *ZQ2M*         SPECIFIC HUMIDITY AT 2M                       KG/KG
!    *ZMEAN*        AREA AVERAGED WIND SP. AT 10 M INT. FROM KLEV   M/S
!    *ZGUST*        GUST AT 10 M                                    M/S
!    *ZZIDLWV*      Zi/L used for gustiness in wave model           m/m
!                   (NOTE: Positive values of Zi/L are set to ZERO)
!    *ZBLH*         BOUNDARY LAYER HEIGHT                            M
REAL(KIND=JPRB), DIMENSION(NPROMA,NBLOCKS), TARGET :: ZU10M,ZV10M,ZT2M,ZD2M,&
     &    ZQ2M,ZMEAN,ZGUST,ZZIDLWV,ZBLH
     
REAL(KIND=JPRB),ALLOCATABLE,TARGET:: ZGPE(:,:,:) 
REAL(KIND=JPRB), TARGET :: ZTSAE1(NPROMA,NCSS,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZWSAE1(NPROMA,NCSS,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZSNSE1(NPROMA,NCSNEC,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTSNE1(NPROMA,NCSNEC,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZWSNE1(NPROMA,NCSNEC,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZRSNE1(NPROMA,NCSNEC,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZASNE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZTLE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZWLE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTILE1(NPROMA,NCSS,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTLICENE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTLMNWNE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTLWMLNE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTLBOTNE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTLSFNE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZHLICENE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZHLMLNE1(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZUOE1(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVOE1(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTOE1(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZSOE1(NPROMA,NCOM+1,NBLOCKS)

REAL(KIND=JPRB), TARGET :: ZLAIE1(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZBSTRE1(NPROMA,NVHILO,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZBSTR2E1(NPROMA,NVHILO,NBLOCKS)

REAL(KIND=JPRB), TARGET :: ZVFSST(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFLDEPTH(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFCLAKEF(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFALBF(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFCVL(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFCVH(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFCUR(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFTVL(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFITM(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFCI(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFSOTY(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFLAIH(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFLAIL(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFCO2TYP(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFTVH(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFOCDEPTH(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVDALB(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZASNNU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTRENU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZWRENU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTLICENU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTLMNWNU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTLWMLNU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTLBOTNU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZTLSFNU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZHLICENU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET ::  ZHLMLNU0(NPROMA,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTSLNU0(NPROMA,NCSS,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZQLINU0(NPROMA,NCSS,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTILNU0(NPROMA,NCSS,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTSNNU0(NPROMA,NCSNEC,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZFSNNU0(NPROMA,NCSNEC,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZRSNNU0(NPROMA,NCSNEC,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZWSNNU0(NPROMA,NCSNEC,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZUONU0(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVONU0(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZTONU0(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZSONU0(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFZO(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFHO(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFHO_INV(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFDO(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFADVT(NPROMA,NCOM,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFADVS(NPROMA,NCOM,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFTRI0(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFTRI1(NPROMA,NCOM+1,NBLOCKS)
REAL(KIND=JPRB), TARGET :: ZVFSWDK_SAVE(NPROMA,NCOM+1,NBLOCKS)


INTEGER(KIND=JPIM) :: IST,IEND,IPROMA,IFLEV, IBL, NTHREADS
INTEGER(KIND=JPIM) :: JL,J
! INTEGER(KIND=JPIM) :: OMP_GET_MAX_THREADS

TYPE(SURF_AND_MORE_TYPE) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE) :: PSURFL
TYPE(AUX_DIAG_TYPE) :: PDIAG
TYPE(AUX_DIAG_LOCAL_TYPE) :: PAUXL
TYPE(AUX_TYPE) :: PAUX
TYPE(FLUX_TYPE) :: PFLUX
TYPE(STATE_TYPE) :: STATE,TENDENCY_LOC
TYPE(GEMS_LOCAL_TYPE) :: GEMSL
TYPE(KEYS_LOCAL_TYPE) :: LLKEYS
TYPE(DDH_SURF_TYPE) :: PDDHS

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

#include "upddiag.intfb.h"

IF (LHOOK) CALL DR_HOOK('CPG1S',0,ZHOOK_HANDLE)


!     ------------------------------------------------------------------

ASSOCIATE(LEOCML=>YSURF%YOCEAN_ML%LEOCML,RTT=>YSURF%YCST%RTT)

! Some initialisations
ZDHRESS(:,:,:,:)=0._JPRB
ZDHTTS(:,:,:,:)=0._JPRB
ZDHVEGS(:,:,:,:)=0._JPRB

! Allocate variables
ALLOCATE (ZGPE(NPROMA,NGPP,NBLOCKS))
ZTSAE1 = ZGPE(:,MTSLNU:MTSLNU+NCSS-1,:)
ZWSAE1 = ZGPE(:,MQLINU:MQLINU+NCSS-1,:)
ZSNSE1 = ZGPE(:,MFSNNU:MFSNNU+NCSNEC-1,:)
ZTSNE1 = ZGPE(:,MTSNNU:MTSNNU+NCSNEC-1,:)
ZWSNE1 = ZGPE(:,MWSNNU:MWSNNU+NCSNEC-1,:)
ZRSNE1 = ZGPE(:,MRSNNU:MRSNNU+NCSNEC-1,:)
ZASNE1 = ZGPE(:,MASNNU,:)
ZTLE1  = ZGPE(:,MTRENU,:)
ZWLE1  = ZGPE(:,MWRENU,:)
ZTILE1 = ZGPE(:,MTILNU:MTILNU+NCSS-1,:)

!* < FLAKE
ZTLICENE1 = ZGPE(:,MTLICENU,:)
ZTLMNWNE1 = ZGPE(:,MTLMNWNU,:)
ZTLWMLNE1 = ZGPE(:,MTLWMLNU,:)
ZTLBOTNE1 = ZGPE(:,MTLBOTNU,:)
ZTLSFNE1  = ZGPE(:,MTLSFNU,:)
ZHLICENE1 = ZGPE(:,MHLICENU,:)
ZHLMLNE1  = ZGPE(:,MHLMLNU,:)
!* FLAKE > 

ZUOE1 = ZGPE(:,MUONU:MUONU+(NCOM+1)-1,:)  !KPP
ZVOE1 = ZGPE(:,MVONU:MVONU+(NCOM+1)-1,:)  !KPP
ZTOE1 = ZGPE(:,MTONU:MTONU+(NCOM+1)-1,:)  !KPP
ZSOE1 = ZGPE(:,MSONU:MSONU+(NCOM+1)-1,:)  !KPP

UONUC(:,:)=0.0_JPRB     !KPP 
VONUC(:,:)=0.0_JPRB     !KPP
USTRCNU(:)=0.0_JPRB     !KPP
VSTRNUC(:)=0.0_JPRB     !KPP

!* < CTESSEL
ZLAIE1 = ZGPE(:,MLAINU:MLAINU+NVHILO-1,:)
ZBSTRE1 = ZGPE(:,MBSTRNU:MBSTRNU+NVHILO-1,:)
ZBSTR2E1 = ZGPE(:,MBSTR2NU:MBSTR2NU+NVHILO-1,:)
!* CTESSEL >



!*       1.    INITIAL COMPUTATIONS.
!              ---------------------


!     TIME STEP




!*       1.1  INITIALIZING SURFACE VARIABLES AT T-DT (FIRST TIMESTEP).
!             --------------------------------------------------------    

! --- original setting without openMP
!IST=1
!IEND=NPOI
!IPROMA=NPOI
! ---
IFLEV=NLEV
!$OMP PARALLEL
NTHREADS=OMP_GET_MAX_THREADS()
!$OMP END PARALLEL 

IF ( IDBGS1 > 1 ) THEN
  WRITE(NULOUT,*) 'CPG1S:',NPROMA,NPOI,NTHREADS
ENDIF

!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(IST,IEND,IBL,IPROMA)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1

  GP1(1:IPROMA,1:NGPP,IBL)=GP0(1:IPROMA,1:NGPP,IBL)

!     STAFF FOR CALLPAR1S

  ZAPHIF(1:IPROMA,:,IBL)=RG*RALT
  ZAPRS(1:IPROMA,IFLEV,IBL)=PNLP0(1:IPROMA,IBL)
  ZAPRS(1:IPROMA,IFLEV-1,IBL)=PNLP0(1:IPROMA,IBL)-RALT*0.0065_JPRB
! Added "MIN(1._JPRB , ... ) to computation of ZMU0M. This ensures ZMU0M is between physical boundaries.
  ZMU0M(1:IPROMA,IBL)=MIN(1._JPRB, MAX( RSIDECM*GEMU(1:IPROMA,IBL) &
     & -RCODECM*RCOVSRM*SQRT(1._JPRB-GEMU(1:IPROMA,IBL)**2)*COS(GELAM(1:IPROMA,IBL)) &
     & +RCODECM*RSIVSRM*SQRT(1._JPRB-GEMU(1:IPROMA,IBL)**2)*SIN(GELAM(1:IPROMA,IBL)) &
     & ,0._JPRB) )

  IF(LEOCML) THEN
! replace SST with the top layer temp. of the ocean mixed layer (~ 1m depth)
    VFSST(1:IPROMA,IBL) = TONU0(1:IPROMA,1,IBL) + RTT ! The unit of PSST(VFSST) is K.  
  ENDIF

!! init 
  ZCFLX(1:IPROMA,:,IBL) = 0._JPRB 

  LLKEYS%LLLAND=>LLLAND
  LLKEYS%LLSICE=>LLSICE
  LLKEYS%LLNH=>LLNH
  LLKEYS%LLLICE=>LLLICE
  LLKEYS%LLLAKE=>LLLAKE
  LLKEYS%LLOCN_KPP=>LLOCN_KPP

  ZPUSTRC(:,:)=0.0_JPRB
  ZPVSTRC(:,:)=0.0_JPRB
  ZPUOC(:,:,:)=0.0_JPRB
  ZPVOC(:,:,:)=0.0_JPRB
  PSURF%PUSTRC=>ZPUSTRC 
  PSURF%PVSTRC=>ZPVSTRC
  PSURF%PSRSOD=>FSSRD
  PSURF%PSRTHD=>FSTRD
  PSURF%ZCVL=>ZCVL
  PSURF%ZCVH=>ZCVH
  PSURF%ZCUR=>ZCUR
  ZVFISOP_EP=VFISOP_EP
  PSURF%PISOP_EP=>ZVFISOP_EP
  ZVFFWET=VFFWET
  PSURF%PFWET=>ZVFFWET
  ZVFAVGPAR=VFAVGPAR
  PSURF%ZAVGPAR=>ZVFAVGPAR
  ZVFSDOR=VFSDOR
  PSURF%PSDOR=>ZVFSDOR
  ZVFCIL=VFCIL
  PSURF%PCIL=>ZVFCIL
  ZVDIEWSSTL=VDIEWSSTL
  PSURF%PUSTRTI=>ZVDIEWSSTL
  ZVDINSSSTL=VDINSSSTL
  PSURF%PVSTRTI=>ZVDINSSSTL
  ZVDISSHFTL=VDISSHFTL
  PSURF%PAHFSTI=>ZVDISSHFTL
  ZVDIETL=VDIETL
  PSURF%PEVAPTI=>ZVDIETL
  ZVDTSKTL=VDTSKTL
  PSURF%PTSKTI=>ZVDTSKTL
  ZVDRESPBSTR=VDRESPBSTR
  PSURF%PRESPBSTR=>ZVDRESPBSTR 
  ZVDRESPBSTR2=VDRESPBSTR
  PSURF%PRESPBSTR2=>ZVDRESPBSTR2 
  ZVDBIOMASS_LAST=VDBIOMASS_LAST
  PSURF%PBIOMASS_LAST=>ZVDBIOMASS_LAST
  ZBSTRNU0=BSTRNU0
  PSURF%PBIOMASSTR_LAST=>ZBSTRNU0
  ZBSTR2NU0=BSTR2NU0
  PSURF%PBIOMASSTR2_LAST=>ZBSTR2NU0
  ZVDBLOSSVT=VDBLOSSVT
  PSURF%PBLOSSVT=>ZVDBLOSSVT
  ZVDBGAINVT=VDBGAINVT
  PSURF%PBGAINVT=>ZVDBGAINVT
  PSURF%PAN=>ZAN
  PSURF%PAG=>ZAG
  PSURF%PRD=>ZRD
  PSURF%PRSOIL_STR=>ZRSOIL_STR
  PSURF%PRECO=>ZRECO
  PSURF%PCO2FLUX=>ZCO2FLUX
  PSURF%PCH4FLUX=>ZCH4FLUX
  PSURF%PLAI=>ZLAI
  PSURF%ZEMIS=>ZEMIS
  PSURF%ZLAILP=>ZLAILP
  PSURF%ZLAIHP=>ZLAIHP
  PSURF%ZCHAR=>ZCHAR
  PSURF%ZCHARHQ=>ZCHARHQ
  PSURF%ZUCURR=>ZUCURR
  PSURF%ZVCURR=>ZVCURR
  PSURF%PUSTOKES=>PUSTOKES
  PSURF%PVSTOKES=>PVSTOKES
  PSURF%GSD%PTAUOCX=>PTAUOCX
  PSURF%GSD%PTAUOCY=>PTAUOCY
  PSURF%PPHIOC=>PPHIOC
  PSURF%PWSEMEAN=>PWSEMEAN
  PSURF%PWSFMEAN=>PWSFMEAN
  PSURF%PBIOM=>ZBIOM
  PSURF%PBLOSS=>ZBLOSS
  PSURF%PBGAIN=>ZBGAIN
  PSURF%PBIOMSTR=>ZBIOMSTR
  PSURF%PBIOMSTR2=>ZBIOMSTR2
  PSURF%PDIFM=>ZDIFM
  PSURF%PDIFT=>ZDIFT
  PSURF%PDIFS=>ZDIFS
  PSURF%PSNSE1=>ZSNSE1
  PSURF%PASNE1=>ZASNE1
  PSURF%PRSNE1=>ZRSNE1
  PSURF%PTSNE1=>ZTSNE1
  PSURF%PWSNE1=>ZWSNE1
  PSURF%PTSAE1=>ZTSAE1
  PSURF%PWLE1=>ZWLE1
  PSURF%PTLE1=>ZTLE1
  PSURF%PWSAE1=>ZWSAE1
  PSURF%PTIAE1=>ZTILE1
  PSURF%PTLICEE1=>ZTLICENE1
  PSURF%PTLMNWE1=>ZTLMNWNE1
  PSURF%PTLWMLE1=>ZTLWMLNE1
  PSURF%PTLBOTE1=>ZTLBOTNE1
  PSURF%PTLSFE1=>ZTLSFNE1
  PSURF%PHLICEE1=>ZHLICENE1
  PSURF%PHLMLE1=>ZHLMLNE1
  PSURF%PUOE1=>ZUOE1
  PSURF%PVOE1=>ZVOE1
  PSURF%PTOE1=>ZTOE1
  PSURF%PSOE1=>ZSOE1
  PSURF%PLAIE1=>ZLAIE1
  PSURF%PBSTRE1=>ZBSTRE1
  PSURF%PBSTR2E1=>ZBSTR2E1
  PSURF%ZTE => ZTE
  PSURF%ZQE => ZQE
  PSURF%ZVOM => ZVOM
  PSURF%ZVOL => ZVOL
  PSURF%ZTENC => ZTENC
  PSURF%ITVL => ITVL
  PSURF%ITVH => ITVH
  PSURF%ISOTY => ISOTY
  PSURF%ICO2TYP => ICO2TYP
  PSURF%IVEG => IVEG
  ZASNNU0=ASNNU0
  PSURF%GSP%PASN=>ZASNNU0
  ZTSNNU0=TSNNU0
  PSURF%GSP%PTSN=>ZTSNNU0
  ZTSLNU0=TSLNU0
  PSURF%GSP%PTSA=>ZTSLNU0
  ZTRENU0=TRENU0
  PSURF%GSP%PTL=>ZTRENU0
  ZQLINU0=QLINU0
  PSURF%GSP%PWSA=>ZQLINU0
  ZTILNU0=TILNU0
  PSURF%GSP%PTIA=>ZTILNU0
  ZTLICENU0=TLICENU0
  PSURF%GSP%PTLICE=>ZTLICENU0
  ZTLMNWNU0=TLMNWNU0
  PSURF%GSP%PTLMNW=>ZTLMNWNU0
  ZTLWMLNU0=TLWMLNU0
  PSURF%GSP%PTLWML=>ZTLWMLNU0
  ZTLBOTNU0=TLBOTNU0
  PSURF%GSP%PTLBOT=>ZTLBOTNU0
  ZTLSFNU0=TLSFNU0
  PSURF%GSP%PTLSF=>ZTLSFNU0
  ZHLICENU0=HLICENU0
  PSURF%GSP%PHLICE=>ZHLICENU0
  ZHLMLNU0=HLMLNU0
  PSURF%GSP%PHLML=>ZHLMLNU0
  PSURF%GSP%PUOC=>ZPUOC
  PSURF%GSP%PVOC=>ZPVOC
  ZUONU0=UONU0
  PSURF%GSP%PUO0=>ZUONU0
  ZVONU0=VONU0
  PSURF%GSP%PVO0=>ZVONU0
  ZTONU0=TONU0
  PSURF%GSP%PTO0=>ZTONU0
  ZSONU0=SONU0
  PSURF%GSP%PSO0=>ZSONU0
  ZVFSST=VFSST
  PSURF%GSP%PSST=>ZVFSST
  PSURF%GSP%ZWS1=>ZWS1
  BLK_GPD_SDP2(1:IPROMA,:,IBL)=GPD_SDP2(IST:IEND,:)
  BLK_GPD_SDP3(1:IPROMA,:,:,IBL)=GPD_SDP3(IST:IEND,:,:)
  PSURF%GSD%PSSDP2=>BLK_GPD_SDP2
  PSURF%GSD%PSSDP3=>BLK_GPD_SDP3
  ZVFLDEPTH=VFLDEPTH
  PSURF%GSD%PLDEPTH=>ZVFLDEPTH
  ZVFCLAKEF=VFCLAKEF
  PSURF%GSD%PCLAKE=>ZVFCLAKEF
  ZVFALBF=VFALBF
  PSURF%GSD%PALBF=>ZVFALBF  
  ZVFCVL=VFCVL
  PSURF%GSD%PCVL=>ZVFCVL
  ZVFCVH=VFCVH
  PSURF%GSD%PCVH=>ZVFCVH
  ZVFCUR=VFCUR
  PSURF%GSD%PCUR=>ZVFCUR
  ZVFTVL=VFTVL
  PSURF%GSD%PTVL=>ZVFTVL
  ZVFCO2TYP=VFCO2TYP
  PSURF%GSD%PCO2TYP=>ZVFCO2TYP
  ZVFTVH=VFTVH
  PSURF%GSD%PTVH=>ZVFTVH
  ZVFLAIL=VFLAIL
  PSURF%GSD%PLAILC=>ZVFLAIL
  ZVFLAIH=VFLAIH
  PSURF%GSD%PLAIHC=>ZVFLAIH
  ZVFSOTY=VFSOTY
  PSURF%GSD%PSOTY=>ZVFSOTY
  ZVFCI=VFCI
  PSURF%GSD%PCI=>ZVFCI
  ZVFITM=VFITM
  PSURF%GSD%PLSM=>ZVFITM
  ZVFZO=VFZO
  PSURF%GSD%PZO=>ZVFZO
  ZVFHO=VFHO
  PSURF%GSD%PHO=>ZVFHO
  ZVFHO_INV=VFHO_INV
  PSURF%GSD%PHO_INV=>ZVFHO_INV
  ZVFDO=VFDO
  PSURF%GSD%PDO=>ZVFDO
  ZVFOCDEPTH=VFOCDEPTH
  PSURF%GSD%POCDEPTH=>ZVFOCDEPTH
  ZVFADVT=VFADVT
  PSURF%GSD%PADVT=>ZVFADVT
  ZVFADVS=VFADVS
  PSURF%GSD%PADVS=>ZVFADVS 
  ZVFTRI0=VFTRI0
  PSURF%GSD%PTRI0=>ZVFTRI0
  ZVFTRI1=VFTRI1
  PSURF%GSD%PTRI1=>ZVFTRI1
  ZVFSWDK_SAVE=VFSWDK_SAVE
  PSURF%GSD%PSWDK_SAVE=>ZVFSWDK_SAVE
  PSURF%GSD%PEVAPTIU=>ZEVAPTIU
  PSURF%GSD%PU10M=>ZU10M
  PSURF%GSD%PV10M=>ZV10M
  PSURF%GSD%PT2M=>ZT2M
  PSURF%GSD%PD2M=>ZD2M
  PSURF%GSD%PQ2M=>ZQ2M
  PSURF%GSD%POTKE=>ZOTKE
  PSURF%GSD%ZALCOEFF => ZALCOEFF 
  PSURF%GSD%PALBICEF => PALBICEF 
  ZVDALB=VDALB
  PSURF%GSD%PALB=>ZVDALB
  PSURFL%ZSPECTRALEMISS=>ZSPECTRALEMISS
  PSURFL%ZEVAPSNW=>ZEVAPSNW
  PSURFL%ZKH=>ZKH
  PSURFL%ZTHKICE=>ZTHKICE
  ZFSNNU0=FSNNU0
  PSURFL%PSNS=>ZFSNNU0
  PSURFL%ZALBD=>ZALBD
  PSURFL%ZALBP=>ZALBP
  ZRSNNU0=RSNNU0
  PSURFL%PRSN=>ZRSNNU0
  ZWSNNU0=WSNNU0
  PSURFL%PWSN=>ZWSNNU0
  ZWRENU0=WRENU0
  PSURFL%PWL=>ZWRENU0
  ZVDANDAYVT=VDANDAYVT
  PSURFL%PANDAYVT=>ZVDANDAYVT
  ZVDANFMVT=VDANFMVT
  PSURFL%PANFMVT=>ZVDANFMVT
  PSURFL%PZIDLWV=>ZZIDLWV
  PSURFL%ZEXDIAG=>ZEXDIAG
  ZLAILI=LAINU0(:,1,:)
  ZLAIHI=LAINU0(:,2,:)
  PSURFL%PLAILI=>ZLAILI
  PSURFL%PLAIHI=>ZLAIHI
  PSURFL%ZLAIL=>ZLAIL
  PSURFL%ZLAIH=>ZLAIH
  PSURFL%ZWLMX=>ZWLMX
  PSURFL%ZFRTI=>ZFRTI
  PSURFL%ZFRSOTI=>ZFRSOTI
  PSURFL%PSLRFLTI=>ZSLRFLTI
  PSURFL%ZALBTI=>ZALBTI
  PSURFL%ZCSN => ZCSN
  PSURFL%ZCVT => ZCVT
  PSURFL%ZLAIVT => ZLAIVT
  PFLUX%PFPLCL=>FCRF
  PFLUX%PFPLCN=>FCSF
  PFLUX%PFPLSL=>FLSRF
  PFLUX%PFPLSN=>FLSSF
  PFLUX%ZENES=>ZENES
  PFLUX%PDIFTQ=>ZDIFTQ
  PFLUX%PDIFTS=>ZDIFTS
  PFLUX%PFRSO=>ZFRSO
  PFLUX%PFRTH=>PFRTH
  PFLUX%ZFRTH=>ZFRTH
  PFLUX%PSTRTU=>ZSTRTU
  PFLUX%PSTRTV=>ZSTRTV
  PFLUX%PFTG12=>ZFTG12
  PFLUX%PFWEV=>ZFWEV
  PFLUX%PFWSB=>ZFWSB
  PFLUX%PFWG12=>ZFWG12
  PFLUX%PFWMLT=>ZFWMLT
  PFLUX%PFWROD=>ZFWROD
  PFLUX%PFWRO1=>ZFWRO1
  PFLUX%PFTLHEV=>ZFTLHEV
  PFLUX%PFTLHSB=>ZFTLHSB
  ZVDZ0F=VDZ0F
  GEMSL%PZ0M=>ZVDZ0F
  ZVDZ0H=VDZ0H
  GEMSL%PZ0H=>ZVDZ0H
  GEMSL%PC=>CNLEV0
  GEMSL%PC1=>CNLEV1
  GEMSL%PCFLX=>ZCFLX
  GEMSL%PBVOCFLUX=>ZBVOCFLUX
  PDIAG%PGUST=>ZGUST
  PDIAG%PVDIS=>PVDIS
  PDIAG%ZINV=>ZINV
  STATE%PU=>UNLEV0
  STATE%PV=>VNLEV0
  STATE%PT=>TNLEV0
  STATE%PQ=>QNLEV0
  STATE%PU1=>UNLEV1
  STATE%PV1=>VNLEV1
  STATE%PT1=>TNLEV1
  STATE%PQ1=>QNLEV1
  PAUX%PMU0M=>ZMU0M
  PAUX%PGEMU=>GEMU 
  PAUX%GELAT=>GELAT
  PAUX%GELAM=>GELAM
  PAUX%PGEOM1=>ZAPHIF
  PAUX%PAPRS=>ZAPRS
  PAUXL%ZPAPSRF=>ZPAPSRF
  PAUXL%ZWND=>ZWND
  PAUXL%ZCCNL=>ZCCNL
  PAUXL%ZCCNO=>ZCCNO
  PDDHS%PDHTLS=>ZDHTLS
  PDDHS%PDHTSS=>ZDHTSS
  PDDHS%PDHTTS=>ZDHTTS
  PDDHS%PDHTIS=>ZDHTIS
  PDDHS%PDHIIS=>ZDHIIS
  PDDHS%PDHSSS=>ZDHSSS
  PDDHS%PDHWLS=>ZDHWLS
  PDDHS%PDHCO2S=>ZDHCO2S
  PDDHS%PDHBVOCS=>ZDHBVOCS
  PDDHS%PDHBIOS=>ZDHBIOS
  PDDHS%PDHVEGS=>ZDHVEGS

    IF (NALBEDOSCHEME == 2) THEN
      ! 6 components
      PSURF%GSD%ZALCOEFF(1:IPROMA,1,IBL) = VFALUVI(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,2,IBL) = VFALUVV(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,3,IBL) = VFALUVG(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,4,IBL) = VFALNII(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,5,IBL) = VFALNIV(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,6,IBL) = VFALNIG(1:IPROMA,IBL)
    ELSE
      ! 4 components
      PSURF%GSD%ZALCOEFF(1:IPROMA,1,IBL) = VFALUVP(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,2,IBL) = VFALUVD(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,3,IBL) = VFALNIP(1:IPROMA,IBL)
      PSURF%GSD%ZALCOEFF(1:IPROMA,4,IBL) = VFALNID(1:IPROMA,IBL)
    ENDIF
!*       1.1   FIRST TIME-STEP
IF (NSTEP.EQ.NSTART) THEN
  GEMSL%PZ0M(1:IPROMA,IBL)=MAX(0.001_JPRB ,VFZ0F(1:IPROMA,IBL))! PZ0MCL(IST:IEND))
  GEMSL%PZ0H(1:IPROMA,IBL)=MAX(0.0001_JPRB,VFZ0H(1:IPROMA,IBL))!PZ0HCL(IST:IEND))
ENDIF

!* Initialize dummy AVGPAR array, fill with zero if no BVOC emissions
      PSURF%GSD%ZAVGPARC=>ZAVGPARC
IF ( LBVOC_EMIS ) THEN
      PSURF%GSD%ZAVGPARC(1:IPROMA,IBL) = VFAVGPAR(1:IPROMA,IBL) ! W/m2
ELSE
      PSURF%GSD%ZAVGPARC(1:IPROMA,IBL) = 0._JPRB
ENDIF
ENDDO !IST LOOP
!$OMP END PARALLEL DO 

!*      2.   CALL PHYSICS.
!            -------------
  CDCONF='F'
  CALL CALLPAR1S_LAYER_OPENMP (CDCONF=CDCONF &
     & , KIDIA=1, KFDIA=NPOI   , KLON=NPROMA , KLEVS=NCSS  , KTILES=NTILES, KVTYPES=NVHILO & 
     & , KLEV=IFLEV  ,KSTART=NSTART ,KSTEP=NSTEP  ,KTRAC=NTRAC   &
     & , KLEVI=NLEVI  ,KLEVO=NCOM   ,KLEVSN=NCSNEC          &                 !KPP
     & , KDHVTLS=NDHVTLS,KDHFTLS=NDHFTLS,KDHVTSS=NDHVTSS,KDHFTSS=NDHFTSS &
     & , KDHVTTS=NDHVTTS,KDHFTTS=NDHFTTS,KDHVTIS=NDHVTIS,KDHFTIS=NDHFTIS &
     & , KDHVSSS=NDHVSSS,KDHFSSS=NDHFSSS,KDHVIIS=NDHVIIS,KDHFIIS=NDHFIIS &
     & , KDHVWLS=NDHVWLS,KDHFWLS=NDHFWLS,KDHVRESS=NDHVRESS,KDHFRESS=NDHFRESS &
     & , KDHVCO2S=NDHVCO2S,KDHFCO2S=NDHFCO2S &
     & , KDHVBIOS=NDHVBIOS,KDHFBIOS=NDHFBIOS,KDHVBVOCS=NDHVBVOCS,KDHVVEGS=NDHVVEGS,KDHFVEGS=NDHFVEGS  &
     & , PTSPHY=TDT &
!-----------------------------------------------------------------------
! - INPUT .
     & , LLKEYS=LLKEYS &
! - OUTPUT .
     & , PSURF=PSURF, PSURFL=PSURFL, PAUX=PAUX, PAUXL=PAUXL, PFLUX=PFLUX, PDIAG=PDIAG, STATE=STATE, GEMSL=GEMSL, PDDHS=PDDHS)

!*           UPDATE DIAGNOSTICS
!     ------------------------------------------------------------------

!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(IST,IEND,IBL,IPROMA)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1
  CALL UPDDIAG( &
   & 1,IPROMA,NPROMA,IFLEV,NCSS,NCSNEC,NTILES,NVHILO,&   
   & NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
   & NDHVTTS,NDHFTTS,NDHVSSS,NDHFSSS, &
   & NDHVIIS,NDHFIIS,NDHVWLS,NDHFWLS, &
   & NDHVRESS,NDHFRESS, &
   & NDHVCO2S,NDHFCO2S,NDHVBIOS,NDHFBIOS, &
   & NDHVVEGS,NDHFVEGS,NDHVBVOCS, &
   & TDT,IBL, &
   & ZEVAPTIU(:,:,IBL),&
   & ZAN(:,IBL),ZAG(:,IBL),ZRD(:,IBL),ZRSOIL_STR(:,IBL),ZRECO(:,IBL),ZCO2FLUX(:,IBL),ZCH4FLUX(:,IBL), ZBVOCFLUX(:,:,IBL), &
   & ZLAI(:,IBL),ZBIOM(:,IBL),ZBLOSS(:,IBL),ZBGAIN(:,IBL),ZBIOMSTR(:,IBL),ZBIOMSTR2(:,IBL), &
   & TNLEV1(:,IBL),QNLEV1(:,IBL),UNLEV1(:,IBL),VNLEV1(:,IBL),PNLP1(:,IBL),&
   & ZFRSO(:,:,IBL),FSSRD(:,IBL),PFRTH(:,:,IBL),FSTRD(:,IBL),VDALB(:,IBL),ZFTLHEV(:,IBL),ZFTLHSB(:,IBL), &
   & ZDIFTQ(:,:,IBL),ZDIFTS(:,:,IBL),ZSTRTU(:,:,IBL),ZSTRTV(:,:,IBL),ZWSAE1(:,:,IBL),ZSNSE1(:,:,IBL), &
       & ZWLE1(:,IBL), &
   & FCRF(:,IBL)    ,FCSF(:,IBL)   ,FLSRF(:,IBL),FLSSF(:,IBL), ZFWRO1(:,IBL),ZFWROD(:,IBL),ZFWMLT(:,IBL),&
   & ZDHTLS(:,:,:,IBL),ZDHTSS(:,:,:,IBL),ZDHTTS(:,:,:,IBL),ZDHSSS(:,:,:,IBL),ZDHIIS(:,:,IBL),ZDHWLS(:,:,:,IBL), &
       & ZDHRESS(:,:,:,IBL),&
   & ZT2M(:,IBL),ZD2M(:,IBL),ZDHCO2S(:,:,:,IBL),ZDHBIOS(:,:,:,IBL),ZDHVEGS(:,:,:,IBL), &
   & ZDHBVOCS(:,:,:,IBL))

!*       3.  COMPUTATION OF T+DT VALUES FOR SURFACE VARIABLES.
!            -------------------------------------------------
! WARM START FIX
  IF (NSTEP == 0) THEN 
    GP1(1:IPROMA, MRSNNU:MRSNNU+NCSNEC-1,IBL) = RSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
    GP1(1:IPROMA, MTSNNU:MTSNNU+NCSNEC-1,IBL) = TSNNU0(1:IPROMA, 1:NCSNEC, IBL)
    GP1(1:IPROMA, MFSNNU:MFSNNU+NCSNEC-1,IBL) = FSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
    GP1(1:IPROMA, MWSNNU:MWSNNU+NCSNEC-1,IBL) = WSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
  END IF


  GP1(1:IPROMA,1:NGPP,IBL)=GP1(1:IPROMA,1:NGPP,IBL) + TDT*ZGPE(1:IPROMA,1:NGPP,IBL)
!*       4.  SWAPPING OF SURFACE VARIABLES.
!            ------------------------------

  GP0(1:IPROMA,1:NGPP,IBL)=GP1(1:IPROMA,1:NGPP,IBL)

!*       5.   ACCUMULATE 1D DIAGNOSTIC TENDENCIES.
!             ------------------------------------

  DO J=1,N2DDI
    GDI1S(1:IPROMA,J,2,IBL)=GDI1S(1:IPROMA,J,2,IBL)+TSTEP*GDI1S(1:IPROMA,J,1,IBL)
  ENDDO

!*       6.   AVERAGE AUXILIARY DIAGNOSTICS
!             ------------------------------------

  DO J=1,N2DDIAUX
    GDIAUX1S(1:IPROMA,J,2,IBL)=GDIAUX1S(1:IPROMA,J,2,IBL)+TSTEP*GDIAUX1S(1:IPROMA,J,1,IBL)
  ENDDO

ENDDO !IST LOOP
!$OMP END PARALLEL DO 


!     ------------------------------------------------------------------

DEALLOCATE (ZGPE)
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CPG1S',1,ZHOOK_HANDLE)
RETURN
END SUBROUTINE CPG1S_LAYER
