SUBROUTINE CPG1S
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE YOMDPHY  ,  ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NTRAC, &
      &                NVHILO, NGPP, NPOI, NLEV, NBLOCKS  
USE YOMCDH1S ,  ONLY : NLEVI, NDHFCO2S , &
      &                NDHVSSS, NDHFSSS, NDHVIIS, NDHFIIS, &
      &                NDHVWLS, NDHFWLS, NDHVRESS, NDHFRESS, &
      &                NDHVTTS, NDHFTTS, NDHVTIS, NDHFTIS, &
      &                NDHVTLS, NDHFTLS, NDHVTSS, NDHFTSS, &
      &                NDHVCO2S, NDHFCO2S, &
      &                NDHVBIOS, NDHFBIOS, NDHVBVOCS, NDHVVEGS, NDHFVEGS
USE YOMDYN1S ,  ONLY : NSTEP    ,TDT,TSTEP
USE YOMGPD1S ,  ONLY : VFSST, VFALUVI,  VFALUVV, VFALUVG,&
      &                VFALNII, VFALNIV, VFALNIG, VFALUVP, VFALUVD, &
      &                VFALNIP, VFALNID, VFZ0F, VFZ0H, VFAVGPAR
USE YOMGF1S  ,  ONLY : PNLP0, PNLP1, RALT
USE YOMGP1S0 ,  ONLY : GP0, TONU0, RSNNU0, TSNNU0, FSNNU0, WSNNU0, LAINU0 
USE YOMGP1S1 ,  ONLY : GP1, LAINU1
USE PTRGP1S  ,  ONLY : MFSNNU, MRSNNU, MTSNNU, MWSNNU  
USE YOMLOG1S,   ONLY : IDBGS1
USE YOMCT01S ,  ONLY : NSTART
USE YOMCST   ,  ONLY : RG
USE YOERIP   ,  ONLY : RCODECM  ,RSIDECM  ,RCOVSRM  ,RSIVSRM
USE YOERAD   ,  ONLY : NTSW, NLWEMISS
USE YOMDIM1S ,  ONLY : NPROMA
USE YOEPHY   ,  ONLY : NALBEDOSCHEME, LBVOC_EMIS
USE YOMGDI1S ,  ONLY : GDI1S    ,N2DDI ,&
      &                GDIAUX1S ,N2DDIAUX

USE YOMLUN1S, ONLY : NULOUT
USE YOMSURF_SSDP_MOD, ONLY : NSSDP2D, NSSDP3D

USE ECLAND_SURFACE_TYPE_MOD,  ONLY: SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY: SURF_AND_MORE_LOCAL_TYPE, DDH_SURF_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,  ONLY: CLIMATE_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD, ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECLAND_AUX_TYPE_MOD,      ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_FLUX_TYPE_MOD,     ONLY: FLUX_TYPE
USE ECLAND_ATMO_TYPE_MOD,     ONLY: ATMO_TYPE
USE ECLAND_INTERNAL_TYPE_MOD, ONLY: INTERNAL_TYPE
USE ECLAND_GEMS_TYPE_MOD,     ONLY: GEMS_LOCAL_TYPE

USE OMP_LIB


#ifdef DOC
#endif

USE PARKIND1  ,ONLY : JPIM     ,JPRB,    JPRD
USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK, JPHOOK
IMPLICIT NONE


CHARACTER*1 :: CDCONF 
INTEGER(KIND=JPIM) :: IST,IEND,IPROMA,IFLEV, IBL, NTHREADS
INTEGER(KIND=JPIM) :: JL,J

TYPE(SURF_AND_MORE_TYPE)        :: PSURF, ZSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  :: PSURFL
TYPE(CLIMATE_TYPE)              :: PCLIM
TYPE(AUX_DIAG_TYPE)             :: PDIAG
TYPE(AUX_DIAG_LOCAL_TYPE)       :: PAUXL
TYPE(AUX_TYPE)                  :: PAUX
TYPE(FLUX_TYPE)                 :: PFLUX
TYPE(ATMO_TYPE)                 :: STATE
TYPE(INTERNAL_TYPE)             :: PINTER 
TYPE(GEMS_LOCAL_TYPE)           :: GEMSL
TYPE(KEYS_LOCAL_TYPE)           :: LLKEYS
TYPE(DDH_SURF_TYPE)             :: PDDHS

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#include "callpar1s.intfb.h"
#include "upddiag.intfb.h"
IF (LHOOK) CALL DR_HOOK('CPG1S',0,ZHOOK_HANDLE)

!     ------------------------------------------------------------------

CALL PSURF%INIT(NPROMA, NGPP,NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES, NBLOCKS)
CALL PSURFL%INIT(NPROMA, NBLOCKS, NLEV, NTILES, NTSW, NLWEMISS,NVHILO)
CALL PCLIM%INIT()
CALL PDIAG%INIT(NPROMA, NBLOCKS)
CALL PAUXL%INIT(NPROMA, NBLOCKS)
CALL PAUX%INIT(NPROMA,NLEV,NBLOCKS)
CALL PFLUX%INIT(NPROMA, NLEV, NCSS, NBLOCKS)
CALL STATE%INIT(NPROMA,NLEV,NBLOCKS)
CALL PINTER%INIT()
CALL GEMSL%INIT(NPROMA,NBLOCKS,NTRAC,NDHVBVOCS)
CALL LLKEYS%INIT(NPROMA,NBLOCKS)
CALL PDDHS%INIT(NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO )


!*       1.    INITIAL COMPUTATIONS.
!              ---------------------

!     TIME STEP

!*       1.1  INITIALIZING SURFACE VARIABLES AT T-DT (FIRST TIMESTEP).
!             --------------------------------------------------------    

! --- original setting without openMP
!IST=1
!IEND=NPOI
!IPROMA=NPOI
! ---
IFLEV=NLEV
!$OMP PARALLEL
NTHREADS=OMP_GET_MAX_THREADS()
!$OMP END PARALLEL 

IF ( IDBGS1 > 1 ) THEN
  WRITE(NULOUT,*) 'CPG1S:',NPROMA,NPOI,NTHREADS
ENDIF

!$OMP PARALLEL &
!$OMP   PRIVATE(IST,IEND,IBL,IPROMA,CDCONF,ZSURF) &
!$OMP   FIRSTPRIVATE(PSURFL,PCLIM,PDIAG,PAUXL,PAUX,PFLUX,STATE,PINTER,GEMSL,LLKEYS,PDDHS) &
!$OMP   SHARED(GP0,GP1,GDI1S,GDIAUX1S)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1) 
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  IPROMA = IEND-IST+1
  
  ! Update block views
  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL,NCSNEC=NCSNEC,NCSS=NCSS,NCOM=NCOM,NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDIAG%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL STATE%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL GEMSL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDDHS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)

  ASSOCIATE(LEOCML=>YSURF%YOCEAN_ML%LEOCML,RTT=>YSURF%YCST%RTT)


!     STAFF FOR CALLPAR1S

  STATE%PGEOM1(1:IPROMA,1:NLEV)=RG*RALT
  PAUX%PMU0M(1:IPROMA)=MIN(1._JPRB, MAX( RSIDECM*PAUX%PGEMU(1:IPROMA) &
     & -RCODECM*RCOVSRM*SQRT(1._JPRB-PAUX%PGEMU(1:IPROMA)**2)*COS(PAUX%GELAM(1:IPROMA)) &
     & +RCODECM*RSIVSRM*SQRT(1._JPRB-PAUX%PGEMU(1:IPROMA)**2)*SIN(PAUX%GELAM(1:IPROMA)) &
     & ,0._JPRB) )
  STATE%PAPRS(1:IPROMA,IFLEV)=PNLP0(1:IPROMA,IBL)
  STATE%PAPRS(1:IPROMA,IFLEV-1)=PNLP0(1:IPROMA,IBL)-RALT*0.0065_JPRB

  GP1(1:IPROMA,1:NGPP,IBL)=GP0(1:IPROMA,1:NGPP,IBL)
  IF(LEOCML) THEN
    VFSST(1:IPROMA,IBL) = TONU0(1:IPROMA,1,IBL) + RTT
  ENDIF

!! init 
  GEMSL%PCFLX(1:IPROMA,:) = 0._JPRB 

  ZSURF%PUSTRC(:)=0.0_JPRB
  ZSURF%PVSTRC(:)=0.0_JPRB
  ZSURF%GSP%PUOC(:,:)=0.0_JPRB
  ZSURF%GSP%PVOC(:,:)=0.0_JPRB
  ZSURF%GSP%PSST(1:IPROMA)=VFSST(1:IPROMA,IBL)
  PSURFL%PLAILI(:)=LAINU0(:,1,IBL)
  PSURFL%PLAIHI(:)=LAINU0(:,2,IBL)

    IF (NALBEDOSCHEME == 2) THEN
      ZSURF%GSD%ZALCOEFF(1:IPROMA,1) = VFALUVI(1:IPROMA,IBL)
      ZSURF%GSD%ZALCOEFF(1:IPROMA,2) = VFALUVV(1:IPROMA,IBL)
      ZSURF%GSD%ZALCOEFF(1:IPROMA,3) = VFALUVG(1:IPROMA,IBL)
      ZSURF%GSD%ZALCOEFF(1:IPROMA,4) = VFALNII(1:IPROMA,IBL)
      ZSURF%GSD%ZALCOEFF(1:IPROMA,5) = VFALNIV(1:IPROMA,IBL)
      ZSURF%GSD%ZALCOEFF(1:IPROMA,6) = VFALNIG(1:IPROMA,IBL)
    ELSE
      ZSURF%GSD%ZALCOEFF(1:IPROMA,1) = VFALUVP(1:IPROMA,IBL)
      ZSURF%GSD%ZALCOEFF(1:IPROMA,2) = VFALUVD(1:IPROMA,IBL)
      ZSURF%GSD%ZALCOEFF(1:IPROMA,3) = VFALNIP(1:IPROMA,IBL)
      ZSURF%GSD%ZALCOEFF(1:IPROMA,4) = VFALNID(1:IPROMA,IBL)
    ENDIF
!*       1.1   FIRST TIME-STEP
IF (NSTEP.EQ.NSTART) THEN
  GEMSL%PZ0M(1:IPROMA)=MAX(0.001_JPRB ,VFZ0F(1:IPROMA,IBL))
  GEMSL%PZ0H(1:IPROMA)=MAX(0.0001_JPRB,VFZ0H(1:IPROMA,IBL))
ENDIF

!* Initialize dummy AVGPAR array, fill with zero if no BVOC emissions
IF ( LBVOC_EMIS ) THEN
      ZSURF%GSD%ZAVGPARC(1:IPROMA) = VFAVGPAR(1:IPROMA,IBL)
ELSE
      ZSURF%GSD%ZAVGPARC(1:IPROMA) = 0._JPRB
ENDIF

!*      2.   CALL PHYSICS.
  CDCONF='F'
  CALL CALLPAR1S(CDCONF=CDCONF &
     & , IBL=IBL &
     & , KIDIA=1, KFDIA=IPROMA   , KLON=NPROMA , KLEVS=NCSS  , KTILES=NTILES, KVTYPES=NVHILO & 
     & , KLEV=IFLEV  ,KSTART=NSTART ,KSTEP=NSTEP  ,KTRAC=NTRAC   &
     & , KLEVI=NLEVI  ,KLEVO=NCOM   ,KLEVSN=NCSNEC          &
     & , KDHVTLS=NDHVTLS,KDHFTLS=NDHFTLS,KDHVTSS=NDHVTSS,KDHFTSS=NDHFTSS &
     & , KDHVTTS=NDHVTTS,KDHFTTS=NDHFTTS,KDHVTIS=NDHVTIS,KDHFTIS=NDHFTIS &
     & , KDHVSSS=NDHVSSS,KDHFSSS=NDHFSSS,KDHVIIS=NDHVIIS,KDHFIIS=NDHFIIS &
     & , KDHVWLS=NDHVWLS,KDHFWLS=NDHFWLS,KDHVRESS=NDHVRESS,KDHFRESS=NDHFRESS &
     & , KDHVCO2S=NDHVCO2S,KDHFCO2S=NDHFCO2S &
     & , KDHVBIOS=NDHVBIOS,KDHFBIOS=NDHFBIOS,KDHVBVOCS=NDHVBVOCS,KDHVVEGS=NDHVVEGS,KDHFVEGS=NDHFVEGS  &
     & , PTSPHY=TDT &
     & , LLKEYS=LLKEYS &
     & , PSURF=ZSURF, PSURFL=PSURFL, PCLIM=PCLIM, PAUX=PAUX, PAUXL=PAUXL, PFLUX=PFLUX &
     & , PDIAG=PDIAG, PINTER=PINTER,  STATE=STATE, GEMSL=GEMSL, PDDHS=PDDHS)

  CALL UPDDIAG( &
   & IBL=IBL, &
   & KIDIA=1, KFDIA=IPROMA, KLON=NPROMA, KLEV=IFLEV, KLEVS=NCSS, KLEVSN=NCSNEC, KTILES=NTILES,  & 
   & PTSPHY=TDT, &
   & PPSURF=PNLP1, &
   & PSURF=ZSURF, PSURFL=PSURFL, PCLIM=PCLIM, PAUX=PAUX, PAUXL=PAUXL, PFLUX=PFLUX, &
   & PDIAG=PDIAG, STATE=STATE, GEMSL=GEMSL, PDDHS=PDDHS)

! WARM START FIX
  IF (NSTEP == 0) THEN 
    GP1(1:IPROMA, MRSNNU:MRSNNU+NCSNEC-1,IBL) = RSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
    GP1(1:IPROMA, MTSNNU:MTSNNU+NCSNEC-1,IBL) = TSNNU0(1:IPROMA, 1:NCSNEC, IBL)
    GP1(1:IPROMA, MFSNNU:MFSNNU+NCSNEC-1,IBL) = FSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
    GP1(1:IPROMA, MWSNNU:MWSNNU+NCSNEC-1,IBL) = WSNNU0(1:IPROMA, 1:NCSNEC, IBL) 
  END IF

  GP1(1:IPROMA,1:NGPP,IBL)=GP1(1:IPROMA,1:NGPP,IBL) + TDT*ZSURF%ZGPE(1:IPROMA,1:NGPP)

  GP0(1:IPROMA,1:NGPP,IBL)=GP1(1:IPROMA,1:NGPP,IBL)

  DO J=1,N2DDI
    GDI1S(1:IPROMA,J,2,IBL)=GDI1S(1:IPROMA,J,2,IBL)+TSTEP*GDI1S(1:IPROMA,J,1,IBL)
  ENDDO

  DO J=1,N2DDIAUX
    GDIAUX1S(1:IPROMA,J,2,IBL)=GDIAUX1S(1:IPROMA,J,2,IBL)+TSTEP*GDIAUX1S(1:IPROMA,J,1,IBL)
  ENDDO

  END ASSOCIATE
ENDDO !IST LOOP
!$OMP END DO 
!$OMP END PARALLEL

!     ------------------------------------------------------------------
CALL PSURF%FINAL
CALL PSURFL%FINAL
CALL PCLIM%FINAL
CALL PDIAG%FINAL
CALL PAUXL%FINAL
CALL PAUX%FINAL
CALL PFLUX%FINAL
CALL STATE%FINAL
CALL GEMSL%FINAL
CALL LLKEYS%FINAL
CALL PDDHS%FINAL
CALL PINTER%FINAL

IF (LHOOK) CALL DR_HOOK('CPG1S',1,ZHOOK_HANDLE)
END SUBROUTINE CPG1S
