MODULE ECLAND_INTERNAL_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGPD1S, ONLY : GPD_SDP2, GPD_SDP3
USE FIELD_MODULE, ONLY: FIELD_3RB, FIELD_4RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE INTERNAL_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,     POINTER :: PSSDP2  => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PSSDP2  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PSSDP3  => NULL()
  CLASS(FIELD_4RB), POINTER :: F_PSSDP3  => NULL()
CONTAINS
  PROCEDURE :: INIT   => INTERNAL_TYPE_INIT
  PROCEDURE :: FINAL  => INTERNAL_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => INTERNAL_TYPE_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => INTERNAL_TYPE_SYNC_HOST
END TYPE INTERNAL_TYPE

CONTAINS

 SUBROUTINE INTERNAL_TYPE_INIT(SELF)
    CLASS(INTERNAL_TYPE) :: SELF
    CALL FIELD_NEW(SELF%F_PSSDP2,  DATA=GPD_SDP2(:,:,:))
    CALL FIELD_NEW(SELF%F_PSSDP3,  DATA=GPD_SDP3(:,:,:,:))
 END SUBROUTINE INTERNAL_TYPE_INIT

 SUBROUTINE INTERNAL_TYPE_FINAL(SELF)
    CLASS(INTERNAL_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PSSDP2)
    NULLIFY(SELF%PSSDP2)
    CALL FIELD_DELETE(SELF%F_PSSDP3)
    NULLIFY(SELF%PSSDP3)
 END SUBROUTINE INTERNAL_TYPE_FINAL

 SUBROUTINE INTERNAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(INTERNAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    IF(ASSOCIATED(SELF%F_PSSDP2))  SELF%PSSDP2  => SELF%F_PSSDP2%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSSDP3))  SELF%PSSDP3  => SELF%F_PSSDP3%GET_VIEW(BLOCK_INDEX)
 END SUBROUTINE INTERNAL_TYPE_UPDATE_VIEW

 SUBROUTINE INTERNAL_TYPE_SYNC_HOST(SELF)
    CLASS(INTERNAL_TYPE) :: SELF

    CALL SELF%F_PSSDP2%SYNC_HOST_RDWR()
    CALL SELF%F_PSSDP3%SYNC_HOST_RDWR()
 END SUBROUTINE INTERNAL_TYPE_SYNC_HOST

END MODULE ECLAND_INTERNAL_TYPE_MOD
