MODULE ECLAND_AUX_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGC1S  , ONLY : GEMU     ,GELAM    ,GELAT
USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_2LM
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE AUX_TYPE
   REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: GELAT  => NULL() ! PLAT ! PGELAT
   CLASS(FIELD_2RB), POINTER :: F_GELAT  => NULL()
   REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: GELAM  => NULL() ! PGELAM
   CLASS(FIELD_2RB), POINTER :: F_GELAM  => NULL()
   REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PGEMU  => NULL() ! sine of latitude
   CLASS(FIELD_2RB), POINTER :: F_PGEMU  => NULL()
   REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PMU0M  => NULL() ! PMU0 ! local cosine of instantaneous (mean) solar zenith angle
   CLASS(FIELD_2RB), POINTER :: F_PMU0M  => NULL()

CONTAINS
  PROCEDURE :: INIT  => AUX_TYPE_INIT
  PROCEDURE :: FINAL => AUX_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => AUX_TYPE_UPDATE_VIEW
END TYPE AUX_TYPE

TYPE KEYS_LOCAL_TYPE
  LOGICAL, DIMENSION(:), CONTIGUOUS,   POINTER  :: LLLAND
  CLASS(FIELD_2LM), POINTER :: F_LLLAND => NULL()
  LOGICAL, DIMENSION(:), CONTIGUOUS,   POINTER  :: LLSICE
  CLASS(FIELD_2LM), POINTER :: F_LLSICE => NULL()
  LOGICAL, DIMENSION(:), CONTIGUOUS,   POINTER  :: LLLICE
  CLASS(FIELD_2LM), POINTER :: F_LLLICE => NULL()
  LOGICAL, DIMENSION(:), CONTIGUOUS,   POINTER  :: LLNH
  CLASS(FIELD_2LM), POINTER :: F_LLNH   => NULL()
  LOGICAL, DIMENSION(:), CONTIGUOUS,   POINTER  :: LLLAKE
  CLASS(FIELD_2LM), POINTER :: F_LLLAKE   => NULL()
  LOGICAL, DIMENSION(:), CONTIGUOUS,   POINTER  :: LLOCN_KPP
  CLASS(FIELD_2LM), POINTER :: F_LLOCN_KPP => NULL()
CONTAINS
  PROCEDURE :: INIT => KEYS_LOCAL_TYPE_INIT
  PROCEDURE :: FINAL => KEYS_LOCAL_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => KEYS_LOCAL_TYPE_UPDATE_VIEW
END TYPE KEYS_LOCAL_TYPE

CONTAINS

  SUBROUTINE AUX_TYPE_INIT(SELF, NPROMA, NLEV, NBLOCKS, PERSISTENT)
    CLASS(AUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NLEV,NBLOCKS
    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
    LOGICAL :: LLPERSIST

    LLPERSIST = .FALSE.
    IF (PRESENT(PERSISTENT)) LLPERSIST = PERSISTENT

    CALL FIELD_NEW(SELF%F_GELAT, DATA=GELAT)
    CALL FIELD_NEW(SELF%F_GELAM, DATA=GELAM)
    CALL FIELD_NEW(SELF%F_PGEMU, DATA=GEMU)
    CALL FIELD_NEW(SELF%F_PMU0M, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
  END SUBROUTINE AUX_TYPE_INIT

  SUBROUTINE AUX_TYPE_FINAL(SELF)
    CLASS(AUX_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PGEMU)
    NULLIFY(SELF%PGEMU)
    CALL FIELD_DELETE(SELF%F_GELAT)
    NULLIFY(SELF%GELAT)
    CALL FIELD_DELETE(SELF%F_GELAM)
    NULLIFY(SELF%GELAM)
    CALL FIELD_DELETE(SELF%F_PMU0M)
    NULLIFY(SELF%PMU0M)
  END SUBROUTINE AUX_TYPE_FINAL

  SUBROUTINE AUX_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(AUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    IF(ASSOCIATED(SELF%F_PGEMU))  SELF%PGEMU  => SELF%F_PGEMU%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_GELAT))  SELF%GELAT  => SELF%F_GELAT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_GELAM))  SELF%GELAM  => SELF%F_GELAM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PMU0M))  SELF%PMU0M  => SELF%F_PMU0M%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE AUX_TYPE_UPDATE_VIEW

  SUBROUTINE KEYS_LOCAL_TYPE_INIT(SELF, NPROMA, NBLOCKS, PERSISTENT)
    CLASS(KEYS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS
    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
    LOGICAL :: LLPERSIST

    LLPERSIST = .FALSE.
    IF (PRESENT(PERSISTENT)) LLPERSIST = PERSISTENT

    CALL FIELD_NEW(SELF%F_LLLAND,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_LLSICE,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_LLLICE,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_LLNH,      UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_LLLAKE,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_LLOCN_KPP, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
  END SUBROUTINE KEYS_LOCAL_TYPE_INIT

  SUBROUTINE KEYS_LOCAL_TYPE_FINAL(SELF)
    CLASS(KEYS_LOCAL_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_LLLAND)
    NULLIFY(SELF%LLLAND)
    CALL FIELD_DELETE(SELF%F_LLSICE)
    NULLIFY(SELF%LLSICE)
    CALL FIELD_DELETE(SELF%F_LLLICE)
    NULLIFY(SELF%LLLICE)
    CALL FIELD_DELETE(SELF%F_LLNH)
    NULLIFY(SELF%LLNH)
    CALL FIELD_DELETE(SELF%F_LLLAKE)
    NULLIFY(SELF%LLLAKE)
    CALL FIELD_DELETE(SELF%F_LLOCN_KPP)
    NULLIFY(SELF%LLOCN_KPP)
  END SUBROUTINE KEYS_LOCAL_TYPE_FINAL

  SUBROUTINE KEYS_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(KEYS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    IF(ASSOCIATED(SELF%F_LLLAND))    SELF%LLLAND    => SELF%F_LLLAND%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_LLSICE))    SELF%LLSICE    => SELF%F_LLSICE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_LLLICE))    SELF%LLLICE    => SELF%F_LLLICE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_LLNH))      SELF%LLNH      => SELF%F_LLNH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_LLLAKE))    SELF%LLLAKE    => SELF%F_LLLAKE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_LLOCN_KPP)) SELF%LLOCN_KPP => SELF%F_LLOCN_KPP%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE KEYS_LOCAL_TYPE_UPDATE_VIEW

END MODULE ECLAND_AUX_TYPE_MOD
