MODULE ECLAND_AUX_DIAG_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_MODULE, ONLY: FIELD_2RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE AUX_DIAG_TYPE
  REAL(KIND=JPRB), DIMENSION(:),   POINTER, CONTIGUOUS :: PVDIS => NULL()      ! Vert-integrated turbulent dissipation rate (W/m2)
  CLASS(FIELD_2RB), POINTER :: F_PVDIS => NULL()
  REAL(KIND=JPRB), DIMENSION(:),   POINTER, CONTIGUOUS :: PGUST => NULL()! PI10FG     ! WIND GUST AT 10 m FOR CURRENT TIME LEVEL (m/s)
  CLASS(FIELD_2RB), POINTER :: F_PGUST => NULL()
  !    additional turbulence diagnostics
  REAL(KIND=JPRB), DIMENSION(:),   POINTER, CONTIGUOUS :: ZINV => NULL()         ! convective turbulent mixing height
  CLASS(FIELD_2RB), POINTER :: F_ZINV => NULL()

CONTAINS
  PROCEDURE :: INIT  => AUX_DIAG_TYPE_INIT
  PROCEDURE :: FINAL => AUX_DIAG_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => AUX_DIAG_TYPE_UPDATE_VIEW
END TYPE AUX_DIAG_TYPE

TYPE AUX_DIAG_LOCAL_TYPE
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: ZPAPSRF => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZPAPSRF => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: ZWND    => NULL()    ! horizontal wind in the lowest model level
  CLASS(FIELD_2RB), POINTER :: F_ZWND    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: ZCCNL => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCCNL => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: ZCCNO => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCCNO => NULL()

CONTAINS
  PROCEDURE :: INIT  => AUX_DIAG_LOCAL_TYPE_INIT
  PROCEDURE :: FINAL => AUX_DIAG_LOCAL_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW
END TYPE AUX_DIAG_LOCAL_TYPE

CONTAINS

 SUBROUTINE AUX_DIAG_TYPE_INIT(SELF, NPROMA, NBLOCKS, PERSISTENT)
    CLASS(AUX_DIAG_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NBLOCKS
    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
    LOGICAL :: LLPERSIST

    LLPERSIST = .FALSE.
    IF (PRESENT(PERSISTENT)) LLPERSIST = PERSISTENT

    CALL FIELD_NEW(SELF%F_PVDIS, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PGUST, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZINV,  UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
 END SUBROUTINE AUX_DIAG_TYPE_INIT

 SUBROUTINE AUX_DIAG_TYPE_FINAL(SELF)
    CLASS(AUX_DIAG_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PVDIS)
    NULLIFY(SELF%PVDIS)
    CALL FIELD_DELETE(SELF%F_PGUST)
    NULLIFY(SELF%PGUST)
    CALL FIELD_DELETE(SELF%F_ZINV)
    NULLIFY(SELF%ZINV)
 END SUBROUTINE AUX_DIAG_TYPE_FINAL

  SUBROUTINE AUX_DIAG_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(AUX_DIAG_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    IF(ASSOCIATED(SELF%F_PVDIS)) SELF%PVDIS => SELF%F_PVDIS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PGUST)) SELF%PGUST => SELF%F_PGUST%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZINV))  SELF%ZINV  => SELF%F_ZINV%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE AUX_DIAG_TYPE_UPDATE_VIEW

  SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT(SELF,NPROMA,NBLOCKS)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS

    CALL FIELD_NEW(SELF%F_ZPAPSRF, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZWND,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCCNL,   UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCCNO,   UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)

  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_INIT

  SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL(SELF)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_ZPAPSRF)
    NULLIFY(SELF%ZPAPSRF)
    CALL FIELD_DELETE(SELF%F_ZWND)
    NULLIFY(SELF%ZWND)
    CALL FIELD_DELETE(SELF%F_ZCCNL)
    NULLIFY(SELF%ZCCNL)
    CALL FIELD_DELETE(SELF%F_ZCCNO)
    NULLIFY(SELF%ZCCNO)
  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_FINAL

  SUBROUTINE AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(AUX_DIAG_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    IF(ASSOCIATED(SELF%F_ZPAPSRF)) SELF%ZPAPSRF => SELF%F_ZPAPSRF%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZWND))    SELF%ZWND    => SELF%F_ZWND%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCCNL))   SELF%ZCCNL   => SELF%F_ZCCNL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCCNO))   SELF%ZCCNO   => SELF%F_ZCCNO%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE AUX_DIAG_LOCAL_TYPE_UPDATE_VIEW

END MODULE ECLAND_AUX_DIAG_TYPE_MOD
