MODULE ECLAND_FLUX_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGF1S, ONLY : FCRF,FCSF,FLSRF,FLSSF
USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE FLUX_TYPE
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PDIFTQ  => NULL() ! TURBULENT FLUX (INC. Q NEGATIVE) OF SPECIFIC HUMIDITY.
    CLASS(FIELD_3RB), POINTER :: F_PDIFTQ  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PDIFTS  => NULL() ! TURBULENT FLUX OF ENTHALPY (OR DRY STATIC ENERGY).
    CLASS(FIELD_3RB), POINTER :: F_PDIFTS  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFPLCL  => NULL() ! CONVECTIVE PRECIPITATION AS RAIN.
    CLASS(FIELD_2RB), POINTER :: F_PFPLCL  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFPLCN  => NULL() ! CONVECTIVE PRECIPITATION AS SNOW.
    CLASS(FIELD_2RB), POINTER :: F_PFPLCN  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFPLSL  => NULL() ! STRATIFORM PRECIPITATION AS RAIN.
    CLASS(FIELD_2RB), POINTER :: F_PFPLSL  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFPLSN  => NULL() ! STRATIFORM PRECIPITATION AS SNOW.
    CLASS(FIELD_2RB), POINTER :: F_PFPLSN  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PFRSO   => NULL()  ! SHORTWAVE RADIATIVE FLUX.
    CLASS(FIELD_3RB), POINTER :: F_PFRSO   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PFRTH   => NULL()  ! LONGWAVE RADIATIVE FLUX.
    CLASS(FIELD_3RB), POINTER :: F_PFRTH   => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: ZFRTH   => NULL()  ! LONGWAVE RADIATIVE FLUX.
    CLASS(FIELD_2RB), POINTER :: F_ZFRTH   => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PSTRTU  => NULL()  ! TURBULENT FLUX OF MOMENTUM (U and V)
    CLASS(FIELD_3RB), POINTER :: F_PSTRTU  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PSTRTV  => NULL()  ! TURBULENT FLUX OF MOMENTUM (U and V)
    CLASS(FIELD_3RB), POINTER :: F_PSTRTV  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFTG12  => NULL()  !PTSDFL ! HEAT FLUX FROM LAYER 1 TO 2  ! NOT USED
    CLASS(FIELD_2RB), POINTER :: F_PFTG12  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFWG12  => NULL()  !PWFSD ! WATER FLUX FROM LAYER 1 TO 2  ! NOT USED
    CLASS(FIELD_2RB), POINTER :: F_PFWG12  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFWEV   => NULL()  ! SURFACE WATER VAPOUR FLUX (EVAPORATION)
    CLASS(FIELD_2RB), POINTER :: F_PFWEV   => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFWSB   => NULL()  ! SURFACE WATER VAPOUR FLUX (SUBLIMATION)
    CLASS(FIELD_2RB), POINTER :: F_PFWSB   => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFWMLT  => NULL()  !PFMLT ! WATER FLUX CORRESPONDING TO SURFACE SNOW MELT.
    CLASS(FIELD_2RB), POINTER :: F_PFWMLT  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFWROD  => NULL() ! RUN-OFF FLUX AT DEEPER LAYERS (2-4)
    CLASS(FIELD_2RB), POINTER :: F_PFWROD  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFWRO1  => NULL() ! RUN-OFF FLUX AT LAYER 1
    CLASS(FIELD_2RB), POINTER :: F_PFWRO1  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFTLHEV => NULL()! SURFACE LATENT HEAT FLUX (SNOW FREE FRACTION)
    CLASS(FIELD_2RB), POINTER :: F_PFTLHEV => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PFTLHSB => NULL()! SURFACE LATENT HEAT FLUX (SNOW COVERED FRACTION)
    CLASS(FIELD_2RB), POINTER :: F_PFTLHSB => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: ZENES   => NULL()  !PENES         !  ???
    CLASS(FIELD_3RB), POINTER :: F_ZENES   => NULL()

CONTAINS
  PROCEDURE :: INIT => FLUX_TYPE_INIT
  PROCEDURE :: FINAL => FLUX_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => FLUX_TYPE_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => FLUX_TYPE_SYNC_HOST
END TYPE FLUX_TYPE

CONTAINS

  SUBROUTINE FLUX_TYPE_INIT(SELF, NPROMA, NLEV,  NCSS, NBLOCKS)
    CLASS(FLUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NLEV,  NCSS, NBLOCKS

    CALL FIELD_NEW(SELF%F_PFPLCL, DATA=FCRF)
    CALL FIELD_NEW(SELF%F_PFPLCN, DATA=FCSF)
    CALL FIELD_NEW(SELF%F_PFPLSL, DATA=FLSRF)
    CALL FIELD_NEW(SELF%F_PFPLSN, DATA=FLSSF)

    CALL FIELD_NEW(SELF%F_ZENES, UBOUNDS=[NPROMA,NCSS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDIFTQ, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDIFTS, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFRSO, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFRTH, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZFRTH, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PSTRTU, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PSTRTV, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFTG12, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWEV, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWSB, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWG12, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWMLT, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWROD, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFWRO1, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFTLHEV, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PFTLHSB, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)

  END SUBROUTINE FLUX_TYPE_INIT

  SUBROUTINE FLUX_TYPE_FINAL(SELF)
    CLASS(FLUX_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PFPLCL)
    NULLIFY(SELF%PFPLCL)
    CALL FIELD_DELETE(SELF%F_PFPLCN)
    NULLIFY(SELF%PFPLCN)
    CALL FIELD_DELETE(SELF%F_PFPLSL)
    NULLIFY(SELF%PFPLSL)
    CALL FIELD_DELETE(SELF%F_PFPLSN)
    NULLIFY(SELF%PFPLSN)


    CALL FIELD_DELETE(SELF%F_ZENES)
    NULLIFY(SELF%ZENES)
    CALL FIELD_DELETE(SELF%F_PDIFTQ)
    NULLIFY(SELF%PDIFTQ)
    CALL FIELD_DELETE(SELF%F_PDIFTS)
    NULLIFY(SELF%PDIFTS)
    CALL FIELD_DELETE(SELF%F_PFRSO)
    NULLIFY(SELF%PFRSO)
    CALL FIELD_DELETE(SELF%F_PFRTH)
    NULLIFY(SELF%PFRTH)
    CALL FIELD_DELETE(SELF%F_ZFRTH)
    NULLIFY(SELF%ZFRTH)
    CALL FIELD_DELETE(SELF%F_PSTRTU)
    NULLIFY(SELF%PSTRTU)
    CALL FIELD_DELETE(SELF%F_PSTRTV)
    NULLIFY(SELF%PSTRTV)
    CALL FIELD_DELETE(SELF%F_PFTG12)
    NULLIFY(SELF%PFTG12)
    CALL FIELD_DELETE(SELF%F_PFWEV)
    NULLIFY(SELF%PFWEV)
    CALL FIELD_DELETE(SELF%F_PFWSB)
    NULLIFY(SELF%PFWSB)
    CALL FIELD_DELETE(SELF%F_PFWG12)
    NULLIFY(SELF%PFWG12)
    CALL FIELD_DELETE(SELF%F_PFWMLT)
    NULLIFY(SELF%PFWMLT)
    CALL FIELD_DELETE(SELF%F_PFWROD)
    NULLIFY(SELF%PFWROD)
    CALL FIELD_DELETE(SELF%F_PFWRO1)
    NULLIFY(SELF%PFWRO1)
    CALL FIELD_DELETE(SELF%F_PFTLHEV)
    NULLIFY(SELF%PFTLHEV)
    CALL FIELD_DELETE(SELF%F_PFTLHSB)
    NULLIFY(SELF%PFTLHSB)
  END SUBROUTINE FLUX_TYPE_FINAL

  SUBROUTINE FLUX_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(FLUX_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PFPLCL))  SELF%PFPLCL  => SELF%F_PFPLCL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFPLCN))  SELF%PFPLCN  => SELF%F_PFPLCN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFPLSL))  SELF%PFPLSL  => SELF%F_PFPLSL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFPLSN))  SELF%PFPLSN  => SELF%F_PFPLSN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDIFTQ))  SELF%PDIFTQ  => SELF%F_PDIFTQ%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDIFTS))  SELF%PDIFTS  => SELF%F_PDIFTS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFRSO))   SELF%PFRSO   => SELF%F_PFRSO%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFRTH))   SELF%PFRTH   => SELF%F_PFRTH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZFRTH))   SELF%ZFRTH   => SELF%F_ZFRTH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSTRTU))  SELF%PSTRTU  => SELF%F_PSTRTU%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSTRTV))  SELF%PSTRTV  => SELF%F_PSTRTV%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFTG12))  SELF%PFTG12  => SELF%F_PFTG12%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFWG12))  SELF%PFWG12  => SELF%F_PFWG12%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFWEV))   SELF%PFWEV   => SELF%F_PFWEV%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFWSB))   SELF%PFWSB   => SELF%F_PFWSB%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFWMLT))  SELF%PFWMLT  => SELF%F_PFWMLT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFWROD))  SELF%PFWROD  => SELF%F_PFWROD%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFWRO1))  SELF%PFWRO1  => SELF%F_PFWRO1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFTLHEV)) SELF%PFTLHEV => SELF%F_PFTLHEV%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFTLHSB)) SELF%PFTLHSB => SELF%F_PFTLHSB%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZENES))   SELF%ZENES   => SELF%F_ZENES%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE FLUX_TYPE_UPDATE_VIEW

  SUBROUTINE FLUX_TYPE_SYNC_HOST(SELF)
    CLASS(FLUX_TYPE) :: SELF
    CALL SELF%F_PFPLCL%SYNC_HOST_RDWR()
    CALL SELF%F_PFPLCN%SYNC_HOST_RDWR()
    CALL SELF%F_PFPLSL%SYNC_HOST_RDWR()
    CALL SELF%F_PFPLSN%SYNC_HOST_RDWR()
    CALL SELF%F_PDIFTQ%SYNC_HOST_RDWR()
    CALL SELF%F_PDIFTS%SYNC_HOST_RDWR()
    CALL SELF%F_PFRSO%SYNC_HOST_RDWR()
    CALL SELF%F_PFRTH%SYNC_HOST_RDWR()
    CALL SELF%F_ZFRTH%SYNC_HOST_RDWR()
    CALL SELF%F_PSTRTU%SYNC_HOST_RDWR()
    CALL SELF%F_PSTRTV%SYNC_HOST_RDWR()
    CALL SELF%F_PFTG12%SYNC_HOST_RDWR()
    CALL SELF%F_PFWG12%SYNC_HOST_RDWR()
    CALL SELF%F_PFWEV%SYNC_HOST_RDWR()
    CALL SELF%F_PFWSB%SYNC_HOST_RDWR()
    CALL SELF%F_PFWMLT%SYNC_HOST_RDWR()
    CALL SELF%F_PFWROD%SYNC_HOST_RDWR()
    CALL SELF%F_PFWRO1%SYNC_HOST_RDWR()
    CALL SELF%F_PFTLHEV%SYNC_HOST_RDWR()
    CALL SELF%F_PFTLHSB%SYNC_HOST_RDWR()
    CALL SELF%F_ZENES%SYNC_HOST_RDWR()
  END SUBROUTINE FLUX_TYPE_SYNC_HOST

END MODULE ECLAND_FLUX_TYPE_MOD
