MODULE ECLAND_GEMS_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1  ,ONLY : JPIM, JPRB
USE YOMGF1S  , ONLY : CNLEV0, CNLEV1
USE YOMGPD1S , ONLY : VDZ0F, VDZ0H
USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE GEMS_LOCAL_TYPE

!-- basic GEMS fields
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PC => NULL()! PC=ZCEN,ZTENC,ZTENC_SKF
   CLASS(FIELD_3RB), POINTER :: F_PC  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PC1 => NULL()!
   CLASS(FIELD_3RB), POINTER :: F_PC1 => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PCFLX => NULL() !ZCFLX,ZDDVLC,ZCHEMDV,ZCFLXO
   CLASS(FIELD_3RB), POINTER :: F_PCFLX => NULL()
! - aerosols transport arrays
   REAL(KIND=JPRB), DIMENSION(:)    , CONTIGUOUS, POINTER :: PZ0M => NULL()
   CLASS(FIELD_2RB), POINTER :: F_PZ0M => NULL()
   REAL(KIND=JPRB), DIMENSION(:)    , CONTIGUOUS, POINTER :: PZ0H => NULL()
   CLASS(FIELD_2RB), POINTER :: F_PZ0H => NULL()
! Online biogenic VOC emissions
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER::  PBVOCFLUX => NULL()   !(KDIM%KLON,NEMIS_BVOC)
   CLASS(FIELD_3RB), POINTER :: F_PBVOCFLUX => NULL()

CONTAINS
   PROCEDURE :: INIT => GEMS_LOCAL_TYPE_INIT
   PROCEDURE :: FINAL => GEMS_LOCAL_TYPE_FINAL
   PROCEDURE :: UPDATE_VIEW => GEMS_LOCAL_TYPE_UPDATE_VIEW

END TYPE GEMS_LOCAL_TYPE

CONTAINS 

SUBROUTINE GEMS_LOCAL_TYPE_INIT(SELF,NPROMA,NBLOCKS,NTRAC,NDHVBVOCS)
    CLASS(GEMS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NBLOCKS,NTRAC,NDHVBVOCS

    CALL FIELD_NEW(SELF%F_PC,   DATA=CNLEV0)
    CALL FIELD_NEW(SELF%F_PC1,  DATA=CNLEV1)
    CALL FIELD_NEW(SELF%F_PCFLX, UBOUNDS=[NPROMA,NTRAC,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PZ0M, DATA=VDZ0F)
    CALL FIELD_NEW(SELF%F_PZ0H, DATA=VDZ0H)
    CALL FIELD_NEW(SELF%F_PBVOCFLUX, UBOUNDS=[NPROMA,NDHVBVOCS,NBLOCKS], PERSISTENT=.TRUE.)
END SUBROUTINE GEMS_LOCAL_TYPE_INIT

SUBROUTINE GEMS_LOCAL_TYPE_FINAL(SELF)
    CLASS(GEMS_LOCAL_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PC)
    NULLIFY(SELF%PC)
    CALL FIELD_DELETE(SELF%F_PC1)
    NULLIFY(SELF%PC1)
    CALL FIELD_DELETE(SELF%F_PCFLX)
    NULLIFY(SELF%PCFLX) 
    CALL FIELD_DELETE(SELF%F_PZ0M)
    NULLIFY(SELF%PZ0M)
    CALL FIELD_DELETE(SELF%F_PZ0H)
    NULLIFY(SELF%PZ0H)
    CALL FIELD_DELETE(SELF%F_PBVOCFLUX)
    NULLIFY(SELF%PBVOCFLUX) 
END SUBROUTINE GEMS_LOCAL_TYPE_FINAL

SUBROUTINE GEMS_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(GEMS_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    IF(ASSOCIATED(SELF%F_PC))         SELF%PC         => SELF%F_PC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PC1))        SELF%PC1        => SELF%F_PC1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCFLX))      SELF%PCFLX      => SELF%F_PCFLX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PZ0M))       SELF%PZ0M       => SELF%F_PZ0M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PZ0H))       SELF%PZ0H       => SELF%F_PZ0H%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBVOCFLUX))  SELF%PBVOCFLUX  => SELF%F_PBVOCFLUX%GET_VIEW(BLOCK_INDEX)
END SUBROUTINE GEMS_LOCAL_TYPE_UPDATE_VIEW

END MODULE ECLAND_GEMS_TYPE_MOD

