MODULE ECLAND_SURFACE_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1,                  ONLY : JPIM, JPRB
USE YOMGF1S  ,                 ONLY : FSSRD, FSTRD

USE YOMGPD1S , ONLY : VFISOP_EP, &
     & VFFWET , VFAVGPAR, VFSDOR, VFCIL, VDIEWSSTL, VDINSSSTL, VDISSHFTL, VDIETL, &
     & VDTSKTL, VFALBF, VFLAIL, VFLAIH, VFHO, VFHO_INV, VFDO, VFOCDEPTH, &
     & VFADVT ,VFADVS  ,VFTRI0   ,VFTRI1   ,VFSWDK_SAVE, &
     & VDRESPBSTR, VDRESPBSTR2, VDBIOMASS_LAST, VDBLOSSVT, VDBGAINVT

USE YOMGP1S0 , ONLY : BSTRNU0, BSTR2NU0, ASNNU0, TSNNU0, TSLNU0, TRENU0, QLINU0   ,&
     & TILNU0, TLICENU0, TLMNWNU0, TLWMLNU0, TLBOTNU0, TLSFNU0, HLICENU0, HLMLNU0 ,&
     & UONU0, VONU0, TONU0, SONU0

USE PTRGP1S  , ONLY : MTSLNU  ,MQLINU  ,MFSNNU,         &
     &                MTSNNU  ,MASNNU  ,MWSNNU, MRSNNU, &
     &                MTRENU  ,MWRENU  ,MTILNU,         &
     &                MTLICENU,MTLMNWNU,MTLWMLNU,MTLBOTNU,MTLSFNU,& ! FLAKE
     &                MHLICENU,MHLMLNU ,                &           ! FLAKE
     &                MUONU   ,MVONU   ,MTONU   ,MSONU, &           !KPP
     &                MLAINU  ,MBSTRNU ,MBSTR2NU

USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB, FIELD_2IM, FIELD_3IM
USE FIELD_FACTORY_MODULE, ONLY: FIELD_NEW, FIELD_DELETE, GET_STACK_MEMBER

IMPLICIT NONE

PRIVATE

TYPE, PUBLIC :: SURFACE_PROGNOSTIC

  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PHLICE => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PHLICE => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PTLICE => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTLICE => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PTL    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTL    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PTLSF  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTLSF  => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PTLMNW => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTLMNW => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PTLWML => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTLWML => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PSST   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PSST   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PUO0   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PUO0   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PUOC   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PUOC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PVO0   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PVO0   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PVOC   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PVOC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTO0   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PTO0   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PSO0   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PSO0   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: ZWS1   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZWS1   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PTLBOT => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTLBOT => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PASN   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PASN   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTSN   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PTSN   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PWSA   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PWSA   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTSA   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PTSA   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTIA   => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PTIA   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PHLML  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PHLML  => NULL()

CONTAINS
  PROCEDURE :: UPDATE_VIEW => SURFACE_PROGNOSTIC_UPDATE_VIEW

END TYPE SURFACE_PROGNOSTIC

TYPE, PUBLIC :: SURFACE_DIAGNOSTIC

  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PDO      => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PDO      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PHO      => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PHO      => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: POCDEPTH => NULL()
  CLASS(FIELD_2RB), POINTER :: F_POCDEPTH => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PHO_INV  => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PHO_INV  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PEVAPTIU => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PEVAPTIU => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PU10M    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PU10M    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PV10M    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PV10M    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PT2M     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PT2M     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PD2M     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PD2M     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PQ2M     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PQ2M     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PALBF    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PALBF    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PALBICEF => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PALBICEF => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PLAILC   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PLAILC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PLAIHC   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PLAIHC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: ZALCOEFF => NULL()
  CLASS(FIELD_3RB), POINTER :: F_ZALCOEFF => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PADVT    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PADVT    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PADVS    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PADVS    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTRI0    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PTRI0    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTRI1    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PTRI1    => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,   POINTER :: ZAVGPARC => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZAVGPARC => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,   POINTER :: PTAUOCX  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTAUOCX  => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,   POINTER :: PTAUOCY  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTAUOCY  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: POTKE    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_POTKE    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PSWDK_SAVE => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PSWDK_SAVE => NULL()

CONTAINS
  PROCEDURE :: UPDATE_VIEW => SURFACE_DIAGNOSTIC_UPDATE_VIEW

END TYPE SURFACE_DIAGNOSTIC

TYPE, PUBLIC :: SURF_AND_MORE_TYPE

   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: ZGPE_STACK => NULL()
   CLASS(FIELD_3RB), POINTER :: F_ZGPE_STACK => NULL()

   TYPE(SURFACE_PROGNOSTIC) :: GSP
   TYPE(SURFACE_DIAGNOSTIC) :: GSD
  ! T star tiles
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PUSTRTI  => NULL()  ! E-W (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   CLASS(FIELD_3RB), POINTER :: F_PUSTRTI  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PVSTRTI  => NULL()  ! N-S (INSTANTANEOUS) SURFACE STRESS FOR EACH TILE
   CLASS(FIELD_3RB), POINTER :: F_PVSTRTI  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PAHFSTI  => NULL()  ! (INSTANTANEOUS) SURFACE SENSIBLE HEAT FLUX FOR EACH TILE
   CLASS(FIELD_3RB), POINTER :: F_PAHFSTI  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PEVAPTI  => NULL()  ! (INSTANTANEOUS) EVAPORATION FOR EACH TILE
   CLASS(FIELD_3RB), POINTER :: F_PEVAPTI  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTSKTI   => NULL()  ! SKIN TEMPERATURE FOR EACH TILE
   CLASS(FIELD_3RB), POINTER :: F_PTSKTI   => NULL()
  ! other
   REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: ZEMIS    => NULL()  ! MODEL SURFACE LONGWAVE EMISSIVITY.
   CLASS(FIELD_2RB), POINTER :: F_ZEMIS    => NULL()

!ZGPE pointers
  !  Tendencies from surface scheme
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PSNSE1   => NULL()  ! OF MULTI-LAYER SNOW MASS PER UNIT SURFACE
   CLASS(FIELD_3RB), POINTER :: F_PSNSE1   => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTSNE1   => NULL()  ! OF MULTI-LAYER SNOW TEMPERATURE
   CLASS(FIELD_3RB), POINTER :: F_PTSNE1   => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PWSNE1   => NULL()  ! OF MULTI-LAYER SNOW LIQUID WATER MASS PER UNIT SURFACE
   CLASS(FIELD_3RB), POINTER :: F_PWSNE1   => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PRSNE1   => NULL()  ! OF MULTI-LAYER SNOW DENSITY
   CLASS(FIELD_3RB), POINTER :: F_PRSNE1   => NULL()
   REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,   POINTER :: PASNE1   => NULL()  ! OF SNOW ALBEDO : only the top layer is used
   CLASS(FIELD_2RB), POINTER :: F_PASNE1   => NULL()
   REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,   POINTER :: PTLE1    => NULL()  ! OF SKIN TEMPERATURE
   CLASS(FIELD_2RB), POINTER :: F_PTLE1    => NULL()
   REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,   POINTER :: PWLE1    => NULL()  ! OF SKIN RESERVOIR WATER CONTENT
   CLASS(FIELD_2RB), POINTER :: F_PWLE1    => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTIAE1   => NULL()  ! OF MULTI-LAYER SEA ICE TEMPERATURE
   CLASS(FIELD_3RB), POINTER :: F_PTIAE1   => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PWSAE1   => NULL()  ! OF MULTI-LAYER SOIL WETNESS
   CLASS(FIELD_3RB), POINTER :: F_PWSAE1   => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTSAE1   => NULL()  ! OF MULTI-LAYER SOIL TEMPERATURE
   CLASS(FIELD_3RB), POINTER :: F_PTSAE1   => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,    POINTER :: PTLICEE1 => NULL()  ! tendency of lake ice temperature
  CLASS(FIELD_2RB), POINTER :: F_PTLICEE1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,    POINTER :: PTLMNWE1 => NULL()  ! tendency of lake total layer temperature
  CLASS(FIELD_2RB), POINTER :: F_PTLMNWE1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,    POINTER :: PTLWMLE1 => NULL()  ! tendency of lake mixed layer temperature
  CLASS(FIELD_2RB), POINTER :: F_PTLWMLE1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,    POINTER :: PTLBOTE1 => NULL()  ! tendency of lake bottom layer temperature
  CLASS(FIELD_2RB), POINTER :: F_PTLBOTE1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,    POINTER :: PTLSFE1  => NULL()  ! tendency of lake shape factor
  CLASS(FIELD_2RB), POINTER :: F_PTLSFE1  => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,    POINTER :: PHLICEE1 => NULL()  ! tendency of lake ice depth m
  CLASS(FIELD_2RB), POINTER :: F_PHLICEE1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:)  , CONTIGUOUS,    POINTER :: PHLMLE1  => NULL()  ! tendency of lake mixed layer depth m/s
  CLASS(FIELD_2RB), POINTER :: F_PHLMLE1  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PUOE1    => NULL()  ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   CLASS(FIELD_3RB), POINTER :: F_PUOE1    => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PVOE1    => NULL()  ! VELOCITY TENDENCY OF OCEAN MIXED LAYER MODEL M/S**2
   CLASS(FIELD_3RB), POINTER :: F_PVOE1    => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PTOE1    => NULL()  ! TEMPERATURE TENDENCY OF OCEAN MIXED LAYER MODEL  K/S
   CLASS(FIELD_3RB), POINTER :: F_PTOE1    => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PSOE1    => NULL()  ! SALINITY TENDENCY OF OCEAN MIXED LAYER MODEL  psu/S
   CLASS(FIELD_3RB), POINTER :: F_PSOE1    => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PLAIE1   => NULL()
   CLASS(FIELD_3RB), POINTER :: F_PLAIE1   => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PBSTRE1  => NULL()
   CLASS(FIELD_3RB), POINTER :: F_PBSTRE1  => NULL()
   REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PBSTR2E1 => NULL()
   CLASS(FIELD_3RB), POINTER :: F_PBSTR2E1 => NULL()

   REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PSDOR    => NULL()  ! STANDARD DEVIATION OF SUBGRID OROGRAPHY
   CLASS(FIELD_2RB), POINTER :: F_PSDOR    => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:), CONTIGUOUS,   POINTER :: ITVH     => NULL()
  CLASS(FIELD_2IM), POINTER :: F_ITVH     => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:), CONTIGUOUS,   POINTER :: ITVL     => NULL()
  CLASS(FIELD_2IM), POINTER :: F_ITVL     => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:), CONTIGUOUS,   POINTER :: ICO2TYP  => NULL()
  CLASS(FIELD_2IM), POINTER :: F_ICO2TYP  => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:), CONTIGUOUS,   POINTER :: ISOTY    => NULL()  ! to store vegetation indices and soil type index
  CLASS(FIELD_2IM), POINTER :: F_ISOTY    => NULL()
  INTEGER(KIND=JPIM), DIMENSION(:,:), CONTIGUOUS, POINTER :: IVEG     => NULL()
  CLASS(FIELD_3IM), POINTER :: F_IVEG     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZCVL     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCVL     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZCVH     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCVH     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZCUR     => NULL()  ! to store vegetation covers
  CLASS(FIELD_2RB), POINTER :: F_ZCUR     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PCIL     => NULL()  ! to store land-ice fraction
  CLASS(FIELD_2RB), POINTER :: F_PCIL     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PPHIOC   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PPHIOC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PRESPBSTR        => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PRESPBSTR        => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PRESPBSTR2       => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PRESPBSTR2       => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PBLOSSVT         => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PBLOSSVT         => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PBGAINVT         => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PBGAINVT         => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PBIOMASS_LAST    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PBIOMASS_LAST    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PBIOMASSTR_LAST  => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PBIOMASSTR_LAST  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PBIOMASSTR2_LAST => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PBIOMASSTR2_LAST => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PRSOIL_STR       => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PRSOIL_STR       => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PCO2FLUX => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCO2FLUX => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PCH4FLUX => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCH4FLUX => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PUSTOKES => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PUSTOKES => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PVSTOKES => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PVSTOKES => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PWSEMEAN => NULL()  ! PEMEAN
  CLASS(FIELD_2RB), POINTER :: F_PWSEMEAN => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PWSFMEAN => NULL()  ! PFMEAN
  CLASS(FIELD_2RB), POINTER :: F_PWSFMEAN => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PDIFM    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PDIFM    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PDIFT    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PDIFT    => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: PDIFS    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PDIFS    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PUSTRC   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PUSTRC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PVSTRC   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PVSTRC   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PRECO    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PRECO    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PAN      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PAN      => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PAG      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PAG      => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PRD      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PRD      => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PLAIL    => NULL()  ! to store variable LAI
  CLASS(FIELD_2RB), POINTER :: F_PLAIL    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PLAIH    => NULL()  ! to store variable LAI
  CLASS(FIELD_2RB), POINTER :: F_PLAIH    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PLAI     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PLAI     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PBIOM    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBIOM    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PBLOSS   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBLOSS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PBGAIN   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBGAIN   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PBIOMSTR => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBIOMSTR => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PBIOMSTR2=> NULL()
  CLASS(FIELD_2RB), POINTER :: F_PBIOMSTR2 => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZLAILP   => NULL()  ! to store variable LAI previous time
  CLASS(FIELD_2RB), POINTER :: F_ZLAILP   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZLAIHP   => NULL()  ! to store variable LAI previous time
  CLASS(FIELD_2RB), POINTER :: F_ZLAIHP   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZLAIL    => NULL()  ! to store variable LAI
  CLASS(FIELD_2RB), POINTER :: F_ZLAIL    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZLAIH    => NULL()  ! to store variable LAI
  CLASS(FIELD_2RB), POINTER :: F_ZLAIH    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZCHAR    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCHAR    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZCHARHQ  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZCHARHQ  => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZTE      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZTE      => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZQE      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZQE      => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZVOM     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZVOM     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZVOL     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZVOL     => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER :: ZTENC    => NULL()
  CLASS(FIELD_3RB), POINTER :: F_ZTENC    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZUCURR   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZUCURR   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZVCURR   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_ZVCURR   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: ZAVGPAR  => NULL()  ! Average PAR for BVOC emis module
  CLASS(FIELD_2RB), POINTER :: F_ZAVGPAR  => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PISOP_EP => NULL()  ! Isoprene emission potential
  CLASS(FIELD_2RB), POINTER :: F_PISOP_EP => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PFWET    => NULL()  ! to store wetland fraction
  CLASS(FIELD_2RB), POINTER :: F_PFWET    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PSRSOD   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PSRSOD   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER :: PSRTHD   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PSRTHD   => NULL()

CONTAINS
  PROCEDURE :: INIT        => SURF_AND_MORE_TYPE_INIT
  PROCEDURE :: FINAL       => SURF_AND_MORE_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => SURF_AND_MORE_TYPE_UPDATE_VIEW

END TYPE SURF_AND_MORE_TYPE


CONTAINS

  SUBROUTINE SURF_AND_MORE_TYPE_INIT(SELF, NPROMA, NGPP, NCOM, NCSNEC, NCSS, &
    &                                NSSDP2D, NSSDP3D, NTRAC, NVHILO, NTILES, NBLOCKS, PERSISTENT)
    CLASS(SURF_AND_MORE_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NGPP, NCOM, NCSNEC, NCSS, NSSDP2D, NSSDP3D
    INTEGER(KIND=JPIM), INTENT(IN) :: NTRAC, NVHILO, NTILES, NBLOCKS
    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
    INTEGER(KIND=JPIM), PARAMETER :: NSTACK_MEMBERS = 24
    INTEGER(KIND=JPIM) :: MEMBER_LBOUNDS(NSTACK_MEMBERS)
    INTEGER(KIND=JPIM) :: MEMBER_MAP(2*NSTACK_MEMBERS)
    INTEGER(KIND=JPIM) :: INDXMEM
    INTEGER(KIND=JPIM) :: INDX_PASNE1
    INTEGER(KIND=JPIM) :: INDX_PTLE1
    INTEGER(KIND=JPIM) :: INDX_PWLE1
    INTEGER(KIND=JPIM) :: INDX_PTLICEE1
    INTEGER(KIND=JPIM) :: INDX_PTLMNWE1
    INTEGER(KIND=JPIM) :: INDX_PTLWMLE1
    INTEGER(KIND=JPIM) :: INDX_PTLBOTE1
    INTEGER(KIND=JPIM) :: INDX_PTLSFE1
    INTEGER(KIND=JPIM) :: INDX_PHLICEE1
    INTEGER(KIND=JPIM) :: INDX_PHLMLE1
    INTEGER(KIND=JPIM) :: INDX_PUOE1
    INTEGER(KIND=JPIM) :: INDX_PVOE1
    INTEGER(KIND=JPIM) :: INDX_PTOE1
    INTEGER(KIND=JPIM) :: INDX_PSOE1
    INTEGER(KIND=JPIM) :: INDX_PLAIE1
    INTEGER(KIND=JPIM) :: INDX_PBSTRE1
    INTEGER(KIND=JPIM) :: INDX_PBSTR2E1
    INTEGER(KIND=JPIM) :: INDX_PTIAE1
    INTEGER(KIND=JPIM) :: INDX_PWSAE1
    INTEGER(KIND=JPIM) :: INDX_PTSAE1
    INTEGER(KIND=JPIM) :: INDX_PSNSE1
    INTEGER(KIND=JPIM) :: INDX_PTSNE1
    INTEGER(KIND=JPIM) :: INDX_PWSNE1
    INTEGER(KIND=JPIM) :: INDX_PRSNE1

    LOGICAL :: LLPERSIST

    LLPERSIST = .FALSE.
    IF (PRESENT(PERSISTENT)) LLPERSIST = PERSISTENT

    CALL FIELD_NEW(SELF%F_PISOP_EP, DATA=VFISOP_EP)
    CALL FIELD_NEW(SELF%F_PFWET,    DATA=VFFWET)
    CALL FIELD_NEW(SELF%F_ZAVGPAR,  DATA=VFAVGPAR)
    CALL FIELD_NEW(SELF%F_PSDOR,    DATA=VFSDOR)
    CALL FIELD_NEW(SELF%F_PCIL,     DATA=VFCIL)
    CALL FIELD_NEW(SELF%F_PUSTRTI,  DATA=VDIEWSSTL)
    CALL FIELD_NEW(SELF%F_PVSTRTI,  DATA=VDINSSSTL)
    CALL FIELD_NEW(SELF%F_PAHFSTI,  DATA=VDISSHFTL)
    CALL FIELD_NEW(SELF%F_PEVAPTI,  DATA=VDIETL)
    CALL FIELD_NEW(SELF%F_PTSKTI,   DATA=VDTSKTL)
    CALL FIELD_NEW(SELF%F_PRESPBSTR,  DATA=VDRESPBSTR)
    CALL FIELD_NEW(SELF%F_PRESPBSTR2, DATA=VDRESPBSTR2)
    CALL FIELD_NEW(SELF%F_PBIOMASS_LAST,   DATA=VDBIOMASS_LAST)
    CALL FIELD_NEW(SELF%F_PBIOMASSTR_LAST, DATA=BSTRNU0)
    CALL FIELD_NEW(SELF%F_PBIOMASSTR2_LAST,DATA=BSTR2NU0)
    CALL FIELD_NEW(SELF%F_PBLOSSVT, DATA=VDBLOSSVT)
    CALL FIELD_NEW(SELF%F_PBGAINVT, DATA=VDBGAINVT)
    CALL FIELD_NEW(SELF%GSP%F_PASN, DATA=ASNNU0)
    CALL FIELD_NEW(SELF%GSP%F_PTSN, DATA=TSNNU0)
    CALL FIELD_NEW(SELF%GSP%F_PTSA, DATA=TSLNU0)
    CALL FIELD_NEW(SELF%GSP%F_PTL,  DATA=TRENU0)
    CALL FIELD_NEW(SELF%GSP%F_PWSA, DATA=QLINU0)
    CALL FIELD_NEW(SELF%GSP%F_PTIA, DATA=TILNU0)
    CALL FIELD_NEW(SELF%GSP%F_PTLICE, DATA=TLICENU0)
    CALL FIELD_NEW(SELF%GSP%F_PTLMNW, DATA=TLMNWNU0)
    CALL FIELD_NEW(SELF%GSP%F_PTLWML, DATA=TLWMLNU0)
    CALL FIELD_NEW(SELF%GSP%F_PTLBOT, DATA=TLBOTNU0)
    CALL FIELD_NEW(SELF%GSP%F_PTLSF,  DATA=TLSFNU0)
    CALL FIELD_NEW(SELF%GSP%F_PHLICE, DATA=HLICENU0)
    CALL FIELD_NEW(SELF%GSP%F_PHLML,  DATA=HLMLNU0)
    CALL FIELD_NEW(SELF%GSP%F_PUO0,   DATA=UONU0)
    CALL FIELD_NEW(SELF%GSP%F_PVO0,   DATA=VONU0)
    CALL FIELD_NEW(SELF%GSP%F_PTO0,   DATA=TONU0)
    CALL FIELD_NEW(SELF%GSP%F_PSO0,   DATA=SONU0)
    CALL FIELD_NEW(SELF%GSD%F_PHO,    DATA=VFHO)
    CALL FIELD_NEW(SELF%GSD%F_PDO,    DATA=VFDO)
    CALL FIELD_NEW(SELF%GSD%F_PALBF,  DATA=VFALBF)
    CALL FIELD_NEW(SELF%GSD%F_PLAILC, DATA=VFLAIL)
    CALL FIELD_NEW(SELF%GSD%F_PLAIHC, DATA=VFLAIH)
    CALL FIELD_NEW(SELF%GSD%F_PHO_INV,  DATA=VFHO_INV)
    CALL FIELD_NEW(SELF%GSD%F_POCDEPTH, DATA=VFOCDEPTH)
    CALL FIELD_NEW(SELF%GSD%F_PADVT,    DATA=VFADVT)
    CALL FIELD_NEW(SELF%GSD%F_PADVS,    DATA=VFADVS)
    CALL FIELD_NEW(SELF%GSD%F_PTRI0,    DATA=VFTRI0)
    CALL FIELD_NEW(SELF%GSD%F_PTRI1,    DATA=VFTRI1)
    CALL FIELD_NEW(SELF%GSD%F_PSWDK_SAVE, DATA=VFSWDK_SAVE)
    CALL FIELD_NEW(SELF%F_PSRSOD,         DATA=FSSRD)
    CALL FIELD_NEW(SELF%F_PSRTHD,         DATA=FSTRD)

    CALL FIELD_NEW(SELF%F_PUSTRC, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PVSTRC, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZCVL,   UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZCVH,   UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZCUR,   UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PAN,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PAG,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PRD,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PRSOIL_STR,  UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PRECO,       UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PCO2FLUX,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PCH4FLUX,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PLAI,        UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZEMIS,       UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZLAILP,      UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZLAIHP,      UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZCHAR,       UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZCHARHQ,     UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZUCURR,      UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZVCURR,      UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PUSTOKES,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PVSTOKES,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_PTAUOCX, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_PTAUOCY, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PPHIOC,      UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PWSEMEAN,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PWSFMEAN,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PBIOM,       UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PBLOSS,      UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PBGAIN,      UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PBIOMSTR,    UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PBIOMSTR2,   UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PDIFM, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NCOM,NBLOCKS], PERSISTENT = LLPERSIST)     !KPP
    CALL FIELD_NEW(SELF%F_PDIFT, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NCOM,NBLOCKS], PERSISTENT = LLPERSIST)     !KPP
    CALL FIELD_NEW(SELF%F_PDIFS, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NCOM,NBLOCKS], PERSISTENT = LLPERSIST)

    CALL FIELD_NEW(SELF%F_ZTE,   UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZQE,   UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZVOM,  UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZVOL,  UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ZTENC, UBOUNDS=[NPROMA,NTRAC,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ITVL,  UBOUNDS=[NPROMA,NBLOCKS],       PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ITVH,  UBOUNDS=[NPROMA,NBLOCKS],       PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ISOTY, UBOUNDS=[NPROMA,NBLOCKS],       PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_ICO2TYP,  UBOUNDS=[NPROMA,NBLOCKS],    PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_IVEG,     UBOUNDS=[NPROMA,NVHILO,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSP%F_PUOC, UBOUNDS=[NPROMA,NCOM+1,NBLOCKS], PERSISTENT = LLPERSIST)                 !KPP
    CALL FIELD_NEW(SELF%GSP%F_PVOC, UBOUNDS=[NPROMA,NCOM+1,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSP%F_PSST, UBOUNDS=[NPROMA,NBLOCKS],        PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSP%F_ZWS1, UBOUNDS=[NPROMA,NBLOCKS],        PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_PEVAPTIU, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_PU10M,    UBOUNDS=[NPROMA,NBLOCKS],        PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_PV10M,    UBOUNDS=[NPROMA,NBLOCKS],        PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_PT2M,     UBOUNDS=[NPROMA,NBLOCKS],        PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_PD2M,     UBOUNDS=[NPROMA,NBLOCKS],        PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_PQ2M,     UBOUNDS=[NPROMA,NBLOCKS],        PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_POTKE, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NCOM,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_ZALCOEFF, UBOUNDS=[NPROMA,6,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_PALBICEF, UBOUNDS=[NPROMA,NBLOCKS],   PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%GSD%F_ZAVGPARC, UBOUNDS=[NPROMA,NBLOCKS],   PERSISTENT = LLPERSIST)

    INDXMEM=1
    INDX_PASNE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MASNNU)
    MEMBER_MAP(INDXMEM) = MASNNU
    MEMBER_MAP(INDXMEM+1) = MASNNU

    INDXMEM=INDXMEM+2
    INDX_PTLE1  = (INDXMEM+1)/2   !SELF%ZGPE(:,MTRENU)
    MEMBER_MAP(INDXMEM) = MTRENU
    MEMBER_MAP(INDXMEM+1) = MTRENU

    INDXMEM=INDXMEM+2
    INDX_PWLE1  = (INDXMEM+1)/2   !SELF%ZGPE(:,MWRENU)
    MEMBER_MAP(INDXMEM) = MWRENU
    MEMBER_MAP(INDXMEM+1) = MWRENU

    INDXMEM=INDXMEM+2
    INDX_PTLICEE1 = (INDXMEM+1)/2 !SELF%ZGPE(:,MTLICENU)
    MEMBER_MAP(INDXMEM) = MTLICENU
    MEMBER_MAP(INDXMEM+1) = MTLICENU

    INDXMEM=INDXMEM+2
    INDX_PTLMNWE1 = (INDXMEM+1)/2 !SELF%ZGPE(:,MTLMNWNU)
    MEMBER_MAP(INDXMEM)  = MTLMNWNU
    MEMBER_MAP(INDXMEM+1) = MTLMNWNU

    INDXMEM=INDXMEM+2
    INDX_PTLWMLE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MTLWMLNU)
    MEMBER_MAP(INDXMEM) = MTLWMLNU
    MEMBER_MAP(INDXMEM+1) = MTLWMLNU

    INDXMEM=INDXMEM+2
    INDX_PTLBOTE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MTLBOTNU)
    MEMBER_MAP(INDXMEM) = MTLBOTNU
    MEMBER_MAP(INDXMEM+1) = MTLBOTNU

    INDXMEM=INDXMEM+2
    INDX_PTLSFE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MTLSFNU)
    MEMBER_MAP(INDXMEM) = MTLSFNU
    MEMBER_MAP(INDXMEM+1) = MTLSFNU

    INDXMEM=INDXMEM+2
    INDX_PHLICEE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MHLICENU)
    MEMBER_MAP(INDXMEM) = MHLICENU
    MEMBER_MAP(INDXMEM+1) = MHLICENU

    INDXMEM=INDXMEM+2
    INDX_PHLMLE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MHLMLNU)
    MEMBER_MAP(INDXMEM) = MHLMLNU
    MEMBER_MAP(INDXMEM+1) = MHLMLNU

    INDXMEM=INDXMEM+2
    INDX_PUOE1 = (INDXMEM+1)/2 !SELF%ZGPE(:,MUONU:MUONU+NCOM)
    MEMBER_MAP(INDXMEM) = MUONU
    MEMBER_MAP(INDXMEM+1) = MUONU+NCOM

    INDXMEM=INDXMEM+2
    INDX_PVOE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MVONU:MVONU+NCOM)
    MEMBER_MAP(INDXMEM) = MVONU
    MEMBER_MAP(INDXMEM+1) = MVONU+NCOM

    INDXMEM=INDXMEM+2
    INDX_PTOE1  = (INDXMEM+1)/2  !SELF%ZGPE(:,MTONU:MTONU+NCOM)
    MEMBER_MAP(INDXMEM) = MTONU
    MEMBER_MAP(INDXMEM+1) = MTONU+NCOM

    INDXMEM=INDXMEM+2
    INDX_PSOE1 = (INDXMEM+1)/2!  SELF%ZGPE(:,MSONU:MSONU+NCOM)
    MEMBER_MAP(INDXMEM) = MSONU
    MEMBER_MAP(INDXMEM+1) = MSONU+NCOM

    INDXMEM=INDXMEM+2
    INDX_PLAIE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MLAINU:MLAINU+NVHILO-1)
    MEMBER_MAP(INDXMEM) = MLAINU
    MEMBER_MAP(INDXMEM+1) = MLAINU+NVHILO-1

    INDXMEM=INDXMEM+2
    INDX_PBSTRE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MBSTRNU:MBSTRNU+NVHILO-1)
    MEMBER_MAP(INDXMEM) = MBSTRNU
    MEMBER_MAP(INDXMEM+1) = MBSTRNU+NVHILO-1

    INDXMEM=INDXMEM+2
    INDX_PBSTR2E1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MBSTR2NU:MBSTR2NU+NVHILO-1)
    MEMBER_MAP(INDXMEM) = MBSTR2NU
    MEMBER_MAP(INDXMEM+1) = MBSTR2NU+NVHILO-1

    INDXMEM=INDXMEM+2
    INDX_PTIAE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MTILNU:MTILNU+NCSS-1)
    MEMBER_MAP(INDXMEM) = MTILNU
    MEMBER_MAP(INDXMEM+1) = MTILNU+NCSS-1

    INDXMEM=INDXMEM+2
    INDX_PWSAE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MQLINU:MQLINU+NCSS-1)
    MEMBER_MAP(INDXMEM) = MQLINU
    MEMBER_MAP(INDXMEM+1) = MQLINU+NCSS-1

    INDXMEM=INDXMEM+2
    INDX_PTSAE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MTSLNU:MTSLNU+NCSS-1)
    MEMBER_MAP(INDXMEM) = MTSLNU
    MEMBER_MAP(INDXMEM+1) = MTSLNU+NCSS-1

    INDXMEM=INDXMEM+2
    INDX_PSNSE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MFSNNU:MFSNNU+NCSNEC-1)
    MEMBER_MAP(INDXMEM) = MFSNNU
    MEMBER_MAP(INDXMEM+1) = MFSNNU+NCSNEC-1

    INDXMEM=INDXMEM+2
    INDX_PTSNE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MTSNNU:MTSNNU+NCSNEC-1)
    MEMBER_MAP(INDXMEM) = MTSNNU
    MEMBER_MAP(INDXMEM+1) = MTSNNU+NCSNEC-1

    INDXMEM=INDXMEM+2
    INDX_PWSNE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MWSNNU:MWSNNU+NCSNEC-1)
    MEMBER_MAP(INDXMEM) = MWSNNU
    MEMBER_MAP(INDXMEM+1) = MWSNNU+NCSNEC-1

    INDXMEM=INDXMEM+2
    INDX_PRSNE1 = (INDXMEM+1)/2  !SELF%ZGPE(:,MRSNNU:MRSNNU+NCSNEC-1)
    MEMBER_MAP(INDXMEM) = MRSNNU
    MEMBER_MAP(INDXMEM+1) = MRSNNU+NCSNEC-1

    MEMBER_LBOUNDS = 1
    CALL FIELD_NEW(SELF%F_ZGPE_STACK, UBOUNDS=[NPROMA,NGPP,NBLOCKS], &
 &    MEMBER_LBOUNDS=MEMBER_LBOUNDS, MEMBER_MAP=MEMBER_MAP, &
 &    LSTACK=.TRUE., PERSISTENT = LLPERSIST)

    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PASNE1  ,SELF%F_PASNE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTLE1   ,SELF%F_PTLE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PWLE1   ,SELF%F_PWLE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTLICEE1,SELF%F_PTLICEE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTLMNWE1,SELF%F_PTLMNWE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTLWMLE1,SELF%F_PTLWMLE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTLBOTE1,SELF%F_PTLBOTE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTLSFE1 ,SELF%F_PTLSFE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PHLICEE1,SELF%F_PHLICEE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PHLMLE1 ,SELF%F_PHLMLE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PUOE1   ,SELF%F_PUOE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PVOE1   ,SELF%F_PVOE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTOE1   ,SELF%F_PTOE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PSOE1   ,SELF%F_PSOE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PLAIE1  ,SELF%F_PLAIE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PBSTRE1 ,SELF%F_PBSTRE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PBSTR2E1,SELF%F_PBSTR2E1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTIAE1  ,SELF%F_PTIAE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PWSAE1  ,SELF%F_PWSAE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTSAE1  ,SELF%F_PTSAE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PSNSE1  ,SELF%F_PSNSE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PTSNE1  ,SELF%F_PTSNE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PWSNE1  ,SELF%F_PWSNE1)
    CALL GET_STACK_MEMBER(SELF%F_ZGPE_STACK,INDX_PRSNE1  ,SELF%F_PRSNE1)

  END SUBROUTINE SURF_AND_MORE_TYPE_INIT

  SUBROUTINE SURF_AND_MORE_TYPE_FINAL(SELF)
    CLASS(SURF_AND_MORE_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PISOP_EP)
    NULLIFY(SELF%PISOP_EP)
    CALL FIELD_DELETE(SELF%F_PFWET)
    NULLIFY(SELF%PFWET)
    CALL FIELD_DELETE(SELF%F_ZAVGPAR)
    NULLIFY(SELF%ZAVGPAR)
    CALL FIELD_DELETE(SELF%F_PSDOR)
    NULLIFY(SELF%PSDOR)
    CALL FIELD_DELETE(SELF%F_PCIL)
    NULLIFY(SELF%PCIL)
    CALL FIELD_DELETE(SELF%F_PUSTRTI)
    NULLIFY(SELF%PUSTRTI)
    CALL FIELD_DELETE(SELF%F_PVSTRTI)
    NULLIFY(SELF%PVSTRTI)
    CALL FIELD_DELETE(SELF%F_PAHFSTI)
    NULLIFY(SELF%PAHFSTI)
    CALL FIELD_DELETE(SELF%F_PEVAPTI)
    NULLIFY(SELF%PEVAPTI)
    CALL FIELD_DELETE(SELF%F_PTSKTI)
    NULLIFY(SELF%PTSKTI)
    CALL FIELD_DELETE(SELF%F_PRESPBSTR)
    NULLIFY(SELF%PRESPBSTR)
    CALL FIELD_DELETE(SELF%F_PRESPBSTR2)
    NULLIFY(SELF%PRESPBSTR2)
    CALL FIELD_DELETE(SELF%F_PBIOMASS_LAST)
    NULLIFY(SELF%PBIOMASS_LAST)
    CALL FIELD_DELETE(SELF%F_PBIOMASSTR_LAST)
    NULLIFY(SELF%PBIOMASSTR_LAST)
    CALL FIELD_DELETE(SELF%F_PBIOMASSTR2_LAST)
    NULLIFY(SELF%PBIOMASSTR2_LAST)
    CALL FIELD_DELETE(SELF%F_PBLOSSVT)
    NULLIFY(SELF%PBLOSSVT)
    CALL FIELD_DELETE(SELF%F_PBGAINVT)
    NULLIFY(SELF%PBGAINVT)
    CALL FIELD_DELETE(SELF%GSP%F_PASN)
    NULLIFY(SELF%GSP%PASN)
    CALL FIELD_DELETE(SELF%GSP%F_PTSN)
    NULLIFY(SELF%GSP%PTSN)
    CALL FIELD_DELETE(SELF%GSP%F_PTSA)
    NULLIFY(SELF%GSP%PTSA)
    CALL FIELD_DELETE(SELF%GSP%F_PTL)
    NULLIFY(SELF%GSP%PTL)
    CALL FIELD_DELETE(SELF%GSP%F_PWSA)
    NULLIFY(SELF%GSP%PWSA)
    CALL FIELD_DELETE(SELF%GSP%F_PTIA)
    NULLIFY(SELF%GSP%PTIA)
    CALL FIELD_DELETE(SELF%GSP%F_PTLICE)
    NULLIFY(SELF%GSP%PTLICE)
    CALL FIELD_DELETE(SELF%GSP%F_PTLMNW)
    NULLIFY(SELF%GSP%PTLMNW)
    CALL FIELD_DELETE(SELF%GSP%F_PTLWML)
    NULLIFY(SELF%GSP%PTLWML)
    CALL FIELD_DELETE(SELF%GSP%F_PTLBOT)
    NULLIFY(SELF%GSP%PTLBOT)
    CALL FIELD_DELETE(SELF%GSP%F_PTLSF)
    NULLIFY(SELF%GSP%PTLSF)
    CALL FIELD_DELETE(SELF%GSP%F_PHLICE)
    NULLIFY(SELF%GSP%PHLICE)
    CALL FIELD_DELETE(SELF%GSP%F_PHLML)
    NULLIFY(SELF%GSP%PHLML)
    CALL FIELD_DELETE(SELF%GSP%F_PUO0)
    NULLIFY(SELF%GSP%PUO0)
    CALL FIELD_DELETE(SELF%GSP%F_PVO0)
    NULLIFY(SELF%GSP%PVO0)
    CALL FIELD_DELETE(SELF%GSP%F_PTO0)
    NULLIFY(SELF%GSP%PTO0)
    CALL FIELD_DELETE(SELF%GSP%F_PSO0)
    NULLIFY(SELF%GSP%PSO0)
    CALL FIELD_DELETE(SELF%GSD%F_PHO)
    NULLIFY(SELF%GSD%PHO)
    CALL FIELD_DELETE(SELF%GSD%F_PDO)
    NULLIFY(SELF%GSD%PDO)
    CALL FIELD_DELETE(SELF%GSD%F_PALBF)
    NULLIFY(SELF%GSD%PALBF)
    CALL FIELD_DELETE(SELF%GSD%F_PLAILC)
    NULLIFY(SELF%GSD%PLAILC)
    CALL FIELD_DELETE(SELF%GSD%F_PLAIHC)
    NULLIFY(SELF%GSD%PLAIHC)
    CALL FIELD_DELETE(SELF%GSD%F_PHO_INV)
    NULLIFY(SELF%GSD%PHO_INV)
    CALL FIELD_DELETE(SELF%GSD%F_POCDEPTH)
    NULLIFY(SELF%GSD%POCDEPTH)
    CALL FIELD_DELETE(SELF%GSD%F_PADVT)
    NULLIFY(SELF%GSD%PADVT)
    CALL FIELD_DELETE(SELF%GSD%F_PADVS)
    NULLIFY(SELF%GSD%PADVS)
    CALL FIELD_DELETE(SELF%GSD%F_PTRI0)
    NULLIFY(SELF%GSD%PTRI0)
    CALL FIELD_DELETE(SELF%GSD%F_PTRI1)
    NULLIFY(SELF%GSD%PTRI1)
    CALL FIELD_DELETE(SELF%GSD%F_PSWDK_SAVE)
    NULLIFY(SELF%GSD%PSWDK_SAVE)
    CALL FIELD_DELETE(SELF%F_PSRSOD)
    NULLIFY(SELF%PSRSOD)
    CALL FIELD_DELETE(SELF%F_PSRTHD)
    NULLIFY(SELF%PSRTHD)
!ZGPE pointers
    NULLIFY(SELF%PSNSE1)
    NULLIFY(SELF%PTSNE1)
    NULLIFY(SELF%PWSNE1)
    NULLIFY(SELF%PRSNE1)
    NULLIFY(SELF%PASNE1)
    NULLIFY(SELF%PTLE1)
    NULLIFY(SELF%PWLE1)
    NULLIFY(SELF%PTIAE1)
    NULLIFY(SELF%PWSAE1)
    NULLIFY(SELF%PTSAE1)
    NULLIFY(SELF%PTLICEE1)
    NULLIFY(SELF%PTLMNWE1)
    NULLIFY(SELF%PTLWMLE1)
    NULLIFY(SELF%PTLBOTE1)
    NULLIFY(SELF%PTLSFE1)
    NULLIFY(SELF%PHLICEE1)
    NULLIFY(SELF%PHLMLE1)
    NULLIFY(SELF%PUOE1)
    NULLIFY(SELF%PVOE1)
    NULLIFY(SELF%PTOE1)
    NULLIFY(SELF%PSOE1)
    NULLIFY(SELF%PLAIE1)
    NULLIFY(SELF%PBSTRE1)
    NULLIFY(SELF%PBSTR2E1)

    CALL FIELD_DELETE(SELF%F_PUSTRC)
    NULLIFY(SELF%PUSTRC)
    CALL FIELD_DELETE(SELF%F_PVSTRC)
    NULLIFY(SELF%PVSTRC)
    CALL FIELD_DELETE(SELF%F_ZCVL)
    NULLIFY(SELF%ZCVL)
    CALL FIELD_DELETE(SELF%F_ZCVH)
    NULLIFY(SELF%ZCVH)
    CALL FIELD_DELETE(SELF%F_ZCUR)
    NULLIFY(SELF%ZCUR)
    CALL FIELD_DELETE(SELF%F_PAN)
    NULLIFY(SELF%PAN)
    CALL FIELD_DELETE(SELF%F_PAG)
    NULLIFY(SELF%PAG)
    CALL FIELD_DELETE(SELF%F_PRD)
    NULLIFY(SELF%PRD)
    CALL FIELD_DELETE(SELF%F_PRSOIL_STR)
    NULLIFY(SELF%PRSOIL_STR)
    CALL FIELD_DELETE(SELF%F_PRECO)
    NULLIFY(SELF%PRECO)
    CALL FIELD_DELETE(SELF%F_PCO2FLUX)
    NULLIFY(SELF%PCO2FLUX)
    CALL FIELD_DELETE(SELF%F_PCH4FLUX)
    NULLIFY(SELF%PCH4FLUX)
    CALL FIELD_DELETE(SELF%F_PLAI)
    NULLIFY(SELF%PLAI)
    CALL FIELD_DELETE(SELF%F_ZEMIS)
    NULLIFY(SELF%ZEMIS)
    CALL FIELD_DELETE(SELF%F_ZLAILP)
    NULLIFY(SELF%ZLAILP)
    CALL FIELD_DELETE(SELF%F_ZLAIHP)
    NULLIFY(SELF%ZLAIHP)
    CALL FIELD_DELETE(SELF%F_ZCHAR)
    NULLIFY(SELF%ZCHAR)
    CALL FIELD_DELETE(SELF%F_ZCHARHQ)
    NULLIFY(SELF%ZCHARHQ)
    CALL FIELD_DELETE(SELF%F_ZUCURR)
    NULLIFY(SELF%ZUCURR)
    CALL FIELD_DELETE(SELF%F_ZVCURR)
    NULLIFY(SELF%ZVCURR)
    CALL FIELD_DELETE(SELF%F_PUSTOKES)
    NULLIFY(SELF%PUSTOKES)
    CALL FIELD_DELETE(SELF%F_PVSTOKES)
    NULLIFY(SELF%PVSTOKES)
    CALL FIELD_DELETE(SELF%GSD%F_PTAUOCX)
    NULLIFY(SELF%GSD%PTAUOCX)
    CALL FIELD_DELETE(SELF%GSD%F_PTAUOCY)
    NULLIFY(SELF%GSD%PTAUOCY)
    CALL FIELD_DELETE(SELF%F_PPHIOC)
    NULLIFY(SELF%PPHIOC)
    CALL FIELD_DELETE(SELF%F_PWSEMEAN)
    NULLIFY(SELF%PWSEMEAN)
    CALL FIELD_DELETE(SELF%F_PWSFMEAN)
    NULLIFY(SELF%PWSFMEAN)
    CALL FIELD_DELETE(SELF%F_PBIOM)
    NULLIFY(SELF%PBIOM)
    CALL FIELD_DELETE(SELF%F_PBLOSS)
    NULLIFY(SELF%PBLOSS)
    CALL FIELD_DELETE(SELF%F_PBGAIN)
    NULLIFY(SELF%PBGAIN)
    CALL FIELD_DELETE(SELF%F_PBIOMSTR)
    NULLIFY(SELF%PBIOMSTR)
    CALL FIELD_DELETE(SELF%F_PBIOMSTR2)
    NULLIFY(SELF%PBIOMSTR2)
    CALL FIELD_DELETE(SELF%F_PDIFM)
    NULLIFY(SELF%PDIFM)
    CALL FIELD_DELETE(SELF%F_PDIFT)
    NULLIFY(SELF%PDIFT)
    CALL FIELD_DELETE(SELF%F_PDIFS)
    NULLIFY(SELF%PDIFS)
    CALL FIELD_DELETE(SELF%F_ZTE)
    NULLIFY(SELF%ZTE)
    CALL FIELD_DELETE(SELF%F_ZQE)
    NULLIFY(SELF%ZQE)
    CALL FIELD_DELETE(SELF%F_ZVOM)
    NULLIFY(SELF%ZVOM)
    CALL FIELD_DELETE(SELF%F_ZVOL)
    NULLIFY(SELF%ZVOL)
    CALL FIELD_DELETE(SELF%F_ZTENC)
    NULLIFY(SELF%ZTENC)
    CALL FIELD_DELETE(SELF%F_ITVL)
    NULLIFY(SELF%ITVL)
    CALL FIELD_DELETE(SELF%F_ITVH)
    NULLIFY(SELF%ITVH)
    CALL FIELD_DELETE(SELF%F_ISOTY)
    NULLIFY(SELF%ISOTY)
    CALL FIELD_DELETE(SELF%F_ICO2TYP)
    NULLIFY(SELF%ICO2TYP)
    CALL FIELD_DELETE(SELF%F_IVEG)
    NULLIFY(SELF%IVEG)
    CALL FIELD_DELETE(SELF%GSP%F_PUOC)
    NULLIFY(SELF%GSP%PUOC)
    CALL FIELD_DELETE(SELF%GSP%F_PVOC)
    NULLIFY(SELF%GSP%PVOC)
    CALL FIELD_DELETE(SELF%GSP%F_PSST)
    NULLIFY(SELF%GSP%PSST)
    CALL FIELD_DELETE(SELF%GSP%F_ZWS1)
    NULLIFY(SELF%GSP%ZWS1)
    CALL FIELD_DELETE(SELF%GSD%F_PEVAPTIU)
    NULLIFY(SELF%GSD%PEVAPTIU)
    CALL FIELD_DELETE(SELF%GSD%F_PU10M)
    NULLIFY(SELF%GSD%PU10M)
    CALL FIELD_DELETE(SELF%GSD%F_PV10M)
    NULLIFY(SELF%GSD%PV10M)
    CALL FIELD_DELETE(SELF%GSD%F_PT2M)
    NULLIFY(SELF%GSD%PT2M)
    CALL FIELD_DELETE(SELF%GSD%F_PD2M)
    NULLIFY(SELF%GSD%PD2M)
    CALL FIELD_DELETE(SELF%GSD%F_PQ2M)
    NULLIFY(SELF%GSD%PQ2M)
    CALL FIELD_DELETE(SELF%GSD%F_POTKE)
    NULLIFY(SELF%GSD%POTKE)
    CALL FIELD_DELETE(SELF%GSD%F_ZALCOEFF)
    NULLIFY(SELF%GSD%ZALCOEFF)
    CALL FIELD_DELETE(SELF%GSD%F_PALBICEF)
    NULLIFY(SELF%GSD%PALBICEF)
    CALL FIELD_DELETE(SELF%GSD%F_ZAVGPARC)
    NULLIFY(SELF%GSD%ZAVGPARC)
    CALL FIELD_DELETE(SELF%F_ZGPE_STACK)
    NULLIFY(SELF%ZGPE_STACK)

  END SUBROUTINE SURF_AND_MORE_TYPE_FINAL

  SUBROUTINE SURFACE_PROGNOSTIC_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(SURFACE_PROGNOSTIC) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PHLICE)) SELF%PHLICE => SELF%F_PHLICE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLICE)) SELF%PTLICE => SELF%F_PTLICE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTL))    SELF%PTL    => SELF%F_PTL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLSF))  SELF%PTLSF  => SELF%F_PTLSF%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLMNW)) SELF%PTLMNW => SELF%F_PTLMNW%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLWML)) SELF%PTLWML => SELF%F_PTLWML%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLBOT)) SELF%PTLBOT => SELF%F_PTLBOT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PASN))   SELF%PASN   => SELF%F_PASN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PHLML))  SELF%PHLML  => SELF%F_PHLML%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PUO0))   SELF%PUO0   => SELF%F_PUO0%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVO0))   SELF%PVO0   => SELF%F_PVO0%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTO0))   SELF%PTO0   => SELF%F_PTO0%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSO0))   SELF%PSO0   => SELF%F_PSO0%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTSN))   SELF%PTSN   => SELF%F_PTSN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWSA))   SELF%PWSA   => SELF%F_PWSA%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTSA))   SELF%PTSA   => SELF%F_PTSA%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTIA))   SELF%PTIA   => SELF%F_PTIA%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSST))   SELF%PSST   => SELF%F_PSST%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PUOC))   SELF%PUOC   => SELF%F_PUOC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVOC))   SELF%PVOC   => SELF%F_PVOC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZWS1))   SELF%ZWS1   => SELF%F_ZWS1%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_PROGNOSTIC_UPDATE_VIEW

  SUBROUTINE SURFACE_DIAGNOSTIC_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(SURFACE_DIAGNOSTIC) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PDO))       SELF%PDO       => SELF%F_PDO%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PHO))       SELF%PHO       => SELF%F_PHO%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_POCDEPTH))  SELF%POCDEPTH  => SELF%F_POCDEPTH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PHO_INV))   SELF%PHO_INV   => SELF%F_PHO_INV%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PALBF))     SELF%PALBF     => SELF%F_PALBF%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLAILC))    SELF%PLAILC    => SELF%F_PLAILC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLAIHC))    SELF%PLAIHC    => SELF%F_PLAIHC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PADVT))     SELF%PADVT     => SELF%F_PADVT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PADVS))     SELF%PADVS     => SELF%F_PADVS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTRI0))     SELF%PTRI0     => SELF%F_PTRI0%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTRI1))     SELF%PTRI1     => SELF%F_PTRI1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSWDK_SAVE)) SELF%PSWDK_SAVE => SELF%F_PSWDK_SAVE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PEVAPTIU))  SELF%PEVAPTIU  => SELF%F_PEVAPTIU%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PU10M))     SELF%PU10M     => SELF%F_PU10M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PV10M))     SELF%PV10M     => SELF%F_PV10M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PT2M))      SELF%PT2M      => SELF%F_PT2M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PD2M))      SELF%PD2M      => SELF%F_PD2M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PQ2M))      SELF%PQ2M      => SELF%F_PQ2M%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PALBICEF))  SELF%PALBICEF  => SELF%F_PALBICEF%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZALCOEFF))  SELF%ZALCOEFF  => SELF%F_ZALCOEFF%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZAVGPARC))  SELF%ZAVGPARC  => SELF%F_ZAVGPARC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTAUOCX))   SELF%PTAUOCX   => SELF%F_PTAUOCX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTAUOCY))   SELF%PTAUOCY   => SELF%F_PTAUOCY%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_POTKE))     SELF%POTKE     => SELF%F_POTKE%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURFACE_DIAGNOSTIC_UPDATE_VIEW

  SUBROUTINE SURF_AND_MORE_TYPE_UPDATE_VIEW(SELF, NCSNEC, NCSS, NCOM, NVHILO, BLOCK_INDEX)
    CLASS(SURF_AND_MORE_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX, NCSNEC, NCSS, NCOM, NVHILO
    IF(ASSOCIATED(SELF%F_ZGPE_STACK)) SELF%ZGPE_STACK => SELF%F_ZGPE_STACK%GET_VIEW(BLOCK_INDEX)

    IF(ASSOCIATED(SELF%F_PSNSE1  ))  SELF%PSNSE1  => SELF%F_PSNSE1  %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTSNE1  ))  SELF%PTSNE1  => SELF%F_PTSNE1  %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWSNE1  ))  SELF%PWSNE1  => SELF%F_PWSNE1  %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRSNE1  ))  SELF%PRSNE1  => SELF%F_PRSNE1  %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PASNE1  ))  SELF%PASNE1  => SELF%F_PASNE1  %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLE1   ))  SELF%PTLE1   => SELF%F_PTLE1   %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWLE1   ))  SELF%PWLE1   => SELF%F_PWLE1   %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTIAE1  ))  SELF%PTIAE1  => SELF%F_PTIAE1  %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWSAE1  ))  SELF%PWSAE1  => SELF%F_PWSAE1  %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTSAE1  ))  SELF%PTSAE1  => SELF%F_PTSAE1  %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLICEE1))  SELF%PTLICEE1=> SELF%F_PTLICEE1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLMNWE1))  SELF%PTLMNWE1=> SELF%F_PTLMNWE1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLWMLE1))  SELF%PTLWMLE1=> SELF%F_PTLWMLE1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLBOTE1))  SELF%PTLBOTE1=> SELF%F_PTLBOTE1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTLSFE1 ))  SELF%PTLSFE1 => SELF%F_PTLSFE1 %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PHLICEE1))  SELF%PHLICEE1=> SELF%F_PHLICEE1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PHLMLE1 ))  SELF%PHLMLE1 => SELF%F_PHLMLE1 %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PUOE1   ))  SELF%PUOE1   => SELF%F_PUOE1   %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVOE1   ))  SELF%PVOE1   => SELF%F_PVOE1   %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTOE1   ))  SELF%PTOE1   => SELF%F_PTOE1   %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSOE1   ))  SELF%PSOE1   => SELF%F_PSOE1   %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLAIE1  ))  SELF%PLAIE1  => SELF%F_PLAIE1  %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBSTRE1 ))  SELF%PBSTRE1 => SELF%F_PBSTRE1 %GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBSTR2E1))  SELF%PBSTR2E1=> SELF%F_PBSTR2E1%GET_VIEW(BLOCK_INDEX)

    CALL SELF%GSP%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%GSD%UPDATE_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZEMIS))     SELF%ZEMIS     => SELF%F_ZEMIS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ITVH))      SELF%ITVH      => SELF%F_ITVH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ITVL))      SELF%ITVL      => SELF%F_ITVL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ICO2TYP))   SELF%ICO2TYP   => SELF%F_ICO2TYP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ISOTY))     SELF%ISOTY     => SELF%F_ISOTY%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_IVEG))      SELF%IVEG      => SELF%F_IVEG%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCVL))      SELF%ZCVL      => SELF%F_ZCVL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCVH))      SELF%ZCVH      => SELF%F_ZCVH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCUR))      SELF%ZCUR      => SELF%F_ZCUR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PPHIOC))    SELF%PPHIOC    => SELF%F_PPHIOC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRSOIL_STR)) SELF%PRSOIL_STR => SELF%F_PRSOIL_STR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCO2FLUX))  SELF%PCO2FLUX  => SELF%F_PCO2FLUX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCH4FLUX))  SELF%PCH4FLUX  => SELF%F_PCH4FLUX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PUSTOKES))  SELF%PUSTOKES  => SELF%F_PUSTOKES%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVSTOKES))  SELF%PVSTOKES  => SELF%F_PVSTOKES%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWSEMEAN))  SELF%PWSEMEAN  => SELF%F_PWSEMEAN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWSFMEAN))  SELF%PWSFMEAN  => SELF%F_PWSFMEAN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDIFM))     SELF%PDIFM     => SELF%F_PDIFM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDIFT))     SELF%PDIFT     => SELF%F_PDIFT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDIFS))     SELF%PDIFS     => SELF%F_PDIFS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PUSTRC))    SELF%PUSTRC    => SELF%F_PUSTRC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVSTRC))    SELF%PVSTRC    => SELF%F_PVSTRC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRECO))     SELF%PRECO     => SELF%F_PRECO%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PAN))       SELF%PAN       => SELF%F_PAN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PAG))       SELF%PAG       => SELF%F_PAG%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRD))       SELF%PRD       => SELF%F_PRD%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLAI))      SELF%PLAI      => SELF%F_PLAI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBIOM))     SELF%PBIOM     => SELF%F_PBIOM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBLOSS))    SELF%PBLOSS    => SELF%F_PBLOSS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBGAIN))    SELF%PBGAIN    => SELF%F_PBGAIN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBIOMSTR))  SELF%PBIOMSTR  => SELF%F_PBIOMSTR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBIOMSTR2)) SELF%PBIOMSTR2 => SELF%F_PBIOMSTR2%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAILP))    SELF%ZLAILP    => SELF%F_ZLAILP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAIHP))    SELF%ZLAIHP    => SELF%F_ZLAIHP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCHAR))     SELF%ZCHAR     => SELF%F_ZCHAR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCHARHQ))   SELF%ZCHARHQ   => SELF%F_ZCHARHQ%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZTE))       SELF%ZTE       => SELF%F_ZTE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZQE))       SELF%ZQE       => SELF%F_ZQE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZVOM))      SELF%ZVOM      => SELF%F_ZVOM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZVOL))      SELF%ZVOL      => SELF%F_ZVOL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZTENC))     SELF%ZTENC     => SELF%F_ZTENC%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZUCURR))    SELF%ZUCURR    => SELF%F_ZUCURR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZVCURR))    SELF%ZVCURR    => SELF%F_ZVCURR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PISOP_EP))  SELF%PISOP_EP  => SELF%F_PISOP_EP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PFWET))     SELF%PFWET     => SELF%F_PFWET%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZAVGPAR))   SELF%ZAVGPAR   => SELF%F_ZAVGPAR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSDOR))     SELF%PSDOR     => SELF%F_PSDOR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCIL))      SELF%PCIL      => SELF%F_PCIL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PUSTRTI))   SELF%PUSTRTI   => SELF%F_PUSTRTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PVSTRTI))   SELF%PVSTRTI   => SELF%F_PVSTRTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PAHFSTI))   SELF%PAHFSTI   => SELF%F_PAHFSTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PEVAPTI))   SELF%PEVAPTI   => SELF%F_PEVAPTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTSKTI))    SELF%PTSKTI    => SELF%F_PTSKTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRESPBSTR))  SELF%PRESPBSTR  => SELF%F_PRESPBSTR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRESPBSTR2)) SELF%PRESPBSTR2 => SELF%F_PRESPBSTR2%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBIOMASS_LAST))    SELF%PBIOMASS_LAST    => SELF%F_PBIOMASS_LAST%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBIOMASSTR_LAST))  SELF%PBIOMASSTR_LAST  => SELF%F_PBIOMASSTR_LAST%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBIOMASSTR2_LAST)) SELF%PBIOMASSTR2_LAST => SELF%F_PBIOMASSTR2_LAST%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBLOSSVT))  SELF%PBLOSSVT  => SELF%F_PBLOSSVT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PBGAINVT))  SELF%PBGAINVT  => SELF%F_PBGAINVT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSRSOD))    SELF%PSRSOD    => SELF%F_PSRSOD%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSRTHD))    SELF%PSRTHD    => SELF%F_PSRTHD%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURF_AND_MORE_TYPE_UPDATE_VIEW

END MODULE ECLAND_SURFACE_TYPE_MOD
