MODULE ECLAND_CLIMATE_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMGPD1S , ONLY : VFCLAKEF, VFTVL, VFTVH, VDALB, &
                      VFSOTY  , VFCVL, VFCVH, VFCUR, &
                      VFITM   , VFCI , VFZO ,VFCO2TYP, VFLDEPTH
USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE CLIMATE_TYPE
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PCLAKE   => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCLAKE   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PTVL     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTVL     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PTVH     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PTVH     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PALB     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PALB     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PSOTY    => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PSOTY    => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PCVL     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCVL     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PCVH     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCVH     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PCUR     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCUR     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PLSM     => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PLSM     => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PCI      => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCI      => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS, POINTER :: PZO      => NULL()
  CLASS(FIELD_3RB), POINTER :: F_PZO      => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PCO2TYP  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PCO2TYP  => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,   POINTER :: PLDEPTH  => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PLDEPTH  => NULL()
CONTAINS
  PROCEDURE :: INIT  => CLIMATE_TYPE_INIT
  PROCEDURE :: FINAL => CLIMATE_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => CLIMATE_TYPE_UPDATE_VIEW
END TYPE CLIMATE_TYPE

CONTAINS

 SUBROUTINE CLIMATE_TYPE_INIT(SELF)
    CLASS(CLIMATE_TYPE) :: SELF

    CALL FIELD_NEW(SELF%F_PCLAKE,  DATA=VFCLAKEF)
    CALL FIELD_NEW(SELF%F_PTVL,    DATA=VFTVL)
    CALL FIELD_NEW(SELF%F_PTVH,    DATA=VFTVH)
    CALL FIELD_NEW(SELF%F_PALB,    DATA=VDALB)
    CALL FIELD_NEW(SELF%F_PSOTY,   DATA=VFSOTY)
    CALL FIELD_NEW(SELF%F_PCVL,    DATA=VFCVL)
    CALL FIELD_NEW(SELF%F_PCVH,    DATA=VFCVH)
    CALL FIELD_NEW(SELF%F_PCUR,    DATA=VFCUR)
    CALL FIELD_NEW(SELF%F_PLSM,    DATA=VFITM)
    CALL FIELD_NEW(SELF%F_PCI,     DATA=VFCI)
    CALL FIELD_NEW(SELF%F_PZO,     DATA=VFZO)
    CALL FIELD_NEW(SELF%F_PCO2TYP, DATA=VFCO2TYP)
    CALL FIELD_NEW(SELF%F_PLDEPTH, DATA=VFLDEPTH)
 END SUBROUTINE CLIMATE_TYPE_INIT

 SUBROUTINE CLIMATE_TYPE_FINAL(SELF)
    CLASS(CLIMATE_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PCLAKE)
    NULLIFY(SELF%PCLAKE)
    CALL FIELD_DELETE(SELF%F_PTVL)
    NULLIFY(SELF%PTVL)
    CALL FIELD_DELETE(SELF%F_PTVH)
    NULLIFY(SELF%PTVH)
    CALL FIELD_DELETE(SELF%F_PALB)
    NULLIFY(SELF%PALB)
    CALL FIELD_DELETE(SELF%F_PSOTY)
    NULLIFY(SELF%PSOTY)
    CALL FIELD_DELETE(SELF%F_PCVL)
    NULLIFY(SELF%PCVL)
    CALL FIELD_DELETE(SELF%F_PCVH)
    NULLIFY(SELF%PCVH)
    CALL FIELD_DELETE(SELF%F_PCUR)
    NULLIFY(SELF%PCUR)
    CALL FIELD_DELETE(SELF%F_PLSM)
    NULLIFY(SELF%PLSM)
    CALL FIELD_DELETE(SELF%F_PCI)
    NULLIFY(SELF%PCI)
    CALL FIELD_DELETE(SELF%F_PZO)
    NULLIFY(SELF%PZO)
    CALL FIELD_DELETE(SELF%F_PCO2TYP)
    NULLIFY(SELF%PCO2TYP)
    CALL FIELD_DELETE(SELF%F_PLDEPTH)
    NULLIFY(SELF%PLDEPTH)
 END SUBROUTINE CLIMATE_TYPE_FINAL

 SUBROUTINE CLIMATE_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(CLIMATE_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PCLAKE))  SELF%PCLAKE  => SELF%F_PCLAKE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTVL))    SELF%PTVL    => SELF%F_PTVL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PTVH))    SELF%PTVH    => SELF%F_PTVH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PALB))    SELF%PALB    => SELF%F_PALB%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSOTY))   SELF%PSOTY   => SELF%F_PSOTY%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCVL))    SELF%PCVL    => SELF%F_PCVL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCVH))    SELF%PCVH    => SELF%F_PCVH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCUR))    SELF%PCUR    => SELF%F_PCUR%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLSM))    SELF%PLSM    => SELF%F_PLSM%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCI))     SELF%PCI     => SELF%F_PCI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PZO))     SELF%PZO     => SELF%F_PZO%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PCO2TYP)) SELF%PCO2TYP => SELF%F_PCO2TYP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLDEPTH)) SELF%PLDEPTH => SELF%F_PLDEPTH%GET_VIEW(BLOCK_INDEX)
 END SUBROUTINE CLIMATE_TYPE_UPDATE_VIEW

END MODULE ECLAND_CLIMATE_TYPE_MOD
