MODULE ECLAND_SURF_LOCAL_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1,                  ONLY : JPIM, JPRB
USE YOMCDH1S ,                 ONLY : NLEVI  , &
     &  NDHVTLS,NDHFTLS,NDHVTSS,NDHFTSS, &
     &  NDHVTTS,NDHFTTS,NDHVTIS,NDHFTIS, &
     &  NDHVSSS,NDHFSSS,NDHVIIS,NDHFIIS, &
     &  NDHVWLS,NDHFWLS,NDHVRESS,NDHFRESS, &
     &  NDHVCO2S,NDHFCO2S, &
     &  NDHVBIOS,NDHFBIOS,NDHVBVOCS,NDHVVEGS,NDHFVEGS
USE YOMGP1S0 ,                 ONLY : WRENU0, FSNNU0, RSNNU0, WSNNU0
USE YOMGPD1S , ONLY :  VDANDAYVT,VDANFMVT
USE PTRGP1S  , ONLY : MTSLNU  ,MQLINU  ,MFSNNU,         &
     &                MTSNNU  ,MASNNU  ,MWSNNU, MRSNNU, &
     &                MTRENU  ,MWRENU  ,MTILNU,         &
     &                MTLICENU,MTLMNWNU,MTLWMLNU,MTLBOTNU,MTLSFNU,& ! FLAKE
     &                MHLICENU,MHLMLNU ,                &           ! FLAKE
     &                MUONU   ,MVONU   ,MTONU   ,MSONU, &           !KPP
     &                MLAINU  ,MBSTRNU ,MBSTR2NU
USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB, FIELD_4RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

PRIVATE


TYPE, PUBLIC :: SURF_AND_MORE_LOCAL_TYPE
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: PLAILI  => NULL() !ZLAILI  ! Arrays for interactive LAI (CITESSEL option)
    CLASS(FIELD_2RB), POINTER :: F_PLAILI  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: PLAIHI  => NULL() !ZLAIHI  ! Arrays for interactive LAI (CITESSEL option)
    CLASS(FIELD_2RB), POINTER :: F_PLAIHI  => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: ZLAIL   => NULL()
    CLASS(FIELD_2RB), POINTER :: F_ZLAIL   => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: ZLAIH   => NULL()
    CLASS(FIELD_2RB), POINTER :: F_ZLAIH   => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: PWL     => NULL() !ZWLM1M
    CLASS(FIELD_2RB), POINTER :: F_PWL     => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: PZIDLWV => NULL()  
    CLASS(FIELD_2RB), POINTER :: F_PZIDLWV => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: PSNS    => NULL() !ZSNM1M  ! KLON,KLEVSN
    CLASS(FIELD_3RB), POINTER :: F_PSNS    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: PRSN    => NULL()!ZRSNM1M ! KLON,KLEVSN
    CLASS(FIELD_3RB), POINTER :: F_PRSN    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: PWSN    => NULL()
    CLASS(FIELD_3RB), POINTER :: F_PWSN    => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: ZTHKICE => NULL()! sea ice
    CLASS(FIELD_2RB), POINTER :: F_ZTHKICE => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: ZWLMX   => NULL()
    CLASS(FIELD_2RB), POINTER :: F_ZWLMX   => NULL()
    REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: ZCSN    => NULL()
    CLASS(FIELD_2RB), POINTER :: F_ZCSN    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZCVT    => NULL()
    CLASS(FIELD_3RB), POINTER :: F_ZCVT    => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZLAIVT  => NULL()
    CLASS(FIELD_3RB), POINTER :: F_ZLAIVT  => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZKH     => NULL()
    CLASS(FIELD_3RB), POINTER :: F_ZKH     => NULL()
    REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZEXDIAG => NULL()
    CLASS(FIELD_3RB), POINTER :: F_ZEXDIAG => NULL()
   ! Longwave surface spectral emissivity in two or more bands,
   ! dimensioned (KLON,NLWEMISS); note that ZEMIR and ZEMIW point to
   ! the first two columns of this matrix:
     REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZSPECTRALEMISS => NULL()
     CLASS(FIELD_3RB), POINTER :: F_ZSPECTRALEMISS => NULL()
     REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,      POINTER  :: ZEVAPSNW => NULL()
     CLASS(FIELD_2RB), POINTER :: F_ZEVAPSNW => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZFRTI    => NULL()! KLON,KTILES
     CLASS(FIELD_3RB), POINTER :: F_ZFRTI    => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZALBTI   => NULL()! KLON,KTILES
     CLASS(FIELD_3RB), POINTER :: F_ZALBTI   => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZFRSOTI  => NULL()
     CLASS(FIELD_3RB), POINTER :: F_ZFRSOTI  => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: PSLRFLTI => NULL()! ZAHFTRTI
     CLASS(FIELD_3RB), POINTER :: F_PSLRFLTI => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZALBD    => NULL()! KLON,NTSW
     CLASS(FIELD_3RB), POINTER :: F_ZALBD    => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: ZALBP    => NULL()! KLON,NTSW
     CLASS(FIELD_3RB), POINTER :: F_ZALBP    => NULL()
   !  CTESSEL: Carbon model
     REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: PANDAYVT => NULL() !ZANDAYVT
     CLASS(FIELD_3RB), POINTER :: F_PANDAYVT => NULL()
     REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,    POINTER  :: PANFMVT  => NULL()  !ZANFMVT
     CLASS(FIELD_3RB), POINTER :: F_PANFMVT  => NULL()

CONTAINS
  PROCEDURE :: INIT  => SURF_AND_MORE_LOCAL_TYPE_INIT
  PROCEDURE :: FINAL => SURF_AND_MORE_LOCAL_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => SURF_AND_MORE_LOCAL_TYPE_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => SURF_AND_MORE_LOCAL_TYPE_SYNC_HOST
END TYPE SURF_AND_MORE_LOCAL_TYPE

TYPE, PUBLIC :: DDH_SURF_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHTLS   => NULL() ! Diagnostic array for tiles (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTLS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHTSS   => NULL() ! Diagnostic array for snow T (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTSS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHTTS   => NULL() ! Diagnostic array for soil T (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTTS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHTIS   => NULL() ! Diagnostic array for ice T (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHTIS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHCO2S  => NULL()
  CLASS(FIELD_4RB), POINTER :: F_PDHCO2S  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHBVOCS => NULL()
  CLASS(FIELD_4RB), POINTER :: F_PDHBVOCS => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHBIOS  => NULL()
  CLASS(FIELD_4RB), POINTER :: F_PDHBIOS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHVEGS  => NULL()
  CLASS(FIELD_4RB), POINTER :: F_PDHVEGS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHSSS   => NULL() ! Diagnostic array for snow mass (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHSSS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,     POINTER :: PDHIIS   => NULL() ! Diagnostic array for interception layer (see module yomcdh)
  CLASS(FIELD_3RB), POINTER :: F_PDHIIS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:,:), CONTIGUOUS,   POINTER :: PDHWLS   => NULL() ! Diagnostic array for soil water (see module yomcdh)
  CLASS(FIELD_4RB), POINTER :: F_PDHWLS   => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,       POINTER :: PDHFSS   => NULL()

CONTAINS
  PROCEDURE :: INIT  => DDH_SURF_TYPE_INIT
  PROCEDURE :: FINAL => DDH_SURF_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => DDH_SURF_TYPE_UPDATE_VIEW
  PROCEDURE :: SYNC_HOST   => DDH_SURF_TYPE_SYNC_HOST
END TYPE DDH_SURF_TYPE

CONTAINS

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT(SELF,NPROMA, NBLOCKS, NLEV, NTILES, NTSW, NLWEMISS,NVHILO)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NLEV,  NBLOCKS, NTSW,NTILES, NLWEMISS,NVHILO

    CALL FIELD_NEW(SELF%F_PWL, DATA=WRENU0)
    CALL FIELD_NEW(SELF%F_PSNS, DATA=FSNNU0)
    CALL FIELD_NEW(SELF%F_PRSN, DATA=RSNNU0)
    CALL FIELD_NEW(SELF%F_PWSN, DATA=WSNNU0)
    CALL FIELD_NEW(SELF%F_PANDAYVT, DATA=VDANDAYVT)
    CALL FIELD_NEW(SELF%F_PANFMVT, DATA=VDANFMVT)
    CALL FIELD_NEW(SELF%F_PLAIHI, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PLAILI, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZLAIL, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZLAIH, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PZIDLWV, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZTHKICE, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZWLMX, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCSN, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZCVT, UBOUNDS=[NPROMA,NVHILO,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZLAIVT, UBOUNDS=[NPROMA,NVHILO,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZKH, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZEXDIAG, UBOUNDS=[NPROMA,12,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZSPECTRALEMISS, UBOUNDS=[NPROMA,NLWEMISS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZEVAPSNW, UBOUNDS=[NPROMA,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZFRTI, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZALBTI, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZFRSOTI, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PSLRFLTI, UBOUNDS=[NPROMA,NTILES,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZALBD, UBOUNDS=[NPROMA,NTSW,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_ZALBP, UBOUNDS=[NPROMA,NTSW,NBLOCKS], PERSISTENT=.TRUE.)
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_INIT

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL(SELF)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PWL)
    NULLIFY(SELF%PWL)
    CALL FIELD_DELETE(SELF%F_PSNS)
    NULLIFY(SELF%PSNS)
    CALL FIELD_DELETE(SELF%F_PRSN)
    NULLIFY(SELF%PRSN)
    CALL FIELD_DELETE(SELF%F_PWSN)
    NULLIFY(SELF%PWSN)
    CALL FIELD_DELETE(SELF%F_PANDAYVT)
    NULLIFY(SELF%PANDAYVT)
    CALL FIELD_DELETE(SELF%F_PANFMVT)
    NULLIFY(SELF%PANFMVT)

    CALL FIELD_DELETE(SELF%F_PLAIHI)
    CALL FIELD_DELETE(SELF%F_PLAILI)
    CALL FIELD_DELETE(SELF%F_ZLAIL)
    CALL FIELD_DELETE(SELF%F_ZLAIH)
    CALL FIELD_DELETE(SELF%F_PZIDLWV)
    CALL FIELD_DELETE(SELF%F_ZTHKICE)
    CALL FIELD_DELETE(SELF%F_ZWLMX)
    CALL FIELD_DELETE(SELF%F_ZCSN)
    CALL FIELD_DELETE(SELF%F_ZCVT)
    CALL FIELD_DELETE(SELF%F_ZLAIVT)
    CALL FIELD_DELETE(SELF%F_ZKH)
    CALL FIELD_DELETE(SELF%F_ZEXDIAG)
    CALL FIELD_DELETE(SELF%F_ZSPECTRALEMISS)
    CALL FIELD_DELETE(SELF%F_ZEVAPSNW)
    CALL FIELD_DELETE(SELF%F_ZFRTI)
    CALL FIELD_DELETE(SELF%F_ZALBTI)
    CALL FIELD_DELETE(SELF%F_ZFRSOTI)
    CALL FIELD_DELETE(SELF%F_PSLRFLTI)
    CALL FIELD_DELETE(SELF%F_ZALBD)
    CALL FIELD_DELETE(SELF%F_ZALBP)

    NULLIFY(SELF%PLAIHI)
    NULLIFY(SELF%PLAILI)
    NULLIFY(SELF%ZLAIL)
    NULLIFY(SELF%ZLAIH)
    NULLIFY(SELF%PZIDLWV)
    NULLIFY(SELF%ZTHKICE)
    NULLIFY(SELF%ZWLMX)
    NULLIFY(SELF%ZCSN)
    NULLIFY(SELF%ZCVT)
    NULLIFY(SELF%ZLAIVT)
    NULLIFY(SELF%ZKH)
    NULLIFY(SELF%ZEXDIAG)
    NULLIFY(SELF%ZSPECTRALEMISS)
    NULLIFY(SELF%ZEVAPSNW)
    NULLIFY(SELF%ZFRTI)
    NULLIFY(SELF%ZALBTI)
    NULLIFY(SELF%ZFRSOTI)
    NULLIFY(SELF%PSLRFLTI)
    NULLIFY(SELF%ZALBD)
    NULLIFY(SELF%ZALBP)
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_FINAL

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PLAILI))        SELF%PLAILI        => SELF%F_PLAILI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PLAIHI))        SELF%PLAIHI        => SELF%F_PLAIHI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAIL))         SELF%ZLAIL         => SELF%F_ZLAIL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAIH))         SELF%ZLAIH         => SELF%F_ZLAIH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PZIDLWV))       SELF%PZIDLWV       => SELF%F_PZIDLWV%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZTHKICE))       SELF%ZTHKICE       => SELF%F_ZTHKICE%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZWLMX))         SELF%ZWLMX         => SELF%F_ZWLMX%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCSN))          SELF%ZCSN          => SELF%F_ZCSN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZCVT))          SELF%ZCVT          => SELF%F_ZCVT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZLAIVT))        SELF%ZLAIVT        => SELF%F_ZLAIVT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZKH))           SELF%ZKH           => SELF%F_ZKH%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZEXDIAG))       SELF%ZEXDIAG       => SELF%F_ZEXDIAG%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZSPECTRALEMISS)) SELF%ZSPECTRALEMISS => SELF%F_ZSPECTRALEMISS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZEVAPSNW))      SELF%ZEVAPSNW      => SELF%F_ZEVAPSNW%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZFRTI))         SELF%ZFRTI         => SELF%F_ZFRTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZALBTI))        SELF%ZALBTI        => SELF%F_ZALBTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZFRSOTI))       SELF%ZFRSOTI       => SELF%F_ZFRSOTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSLRFLTI))      SELF%PSLRFLTI      => SELF%F_PSLRFLTI%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZALBD))         SELF%ZALBD         => SELF%F_ZALBD%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_ZALBP))         SELF%ZALBP         => SELF%F_ZALBP%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWL))           SELF%PWL           => SELF%F_PWL%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PSNS))          SELF%PSNS          => SELF%F_PSNS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PRSN))          SELF%PRSN          => SELF%F_PRSN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PWSN))          SELF%PWSN          => SELF%F_PWSN%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PANDAYVT))      SELF%PANDAYVT      => SELF%F_PANDAYVT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PANFMVT))       SELF%PANFMVT       => SELF%F_PANFMVT%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_UPDATE_VIEW

  SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_SYNC_HOST(SELF)
    CLASS(SURF_AND_MORE_LOCAL_TYPE) :: SELF
    CALL SELF%F_PLAILI%SYNC_HOST_RDWR()
    CALL SELF%F_PLAIHI%SYNC_HOST_RDWR()
    CALL SELF%F_ZLAIL%SYNC_HOST_RDWR()
    CALL SELF%F_ZLAIH%SYNC_HOST_RDWR()
    CALL SELF%F_PZIDLWV%SYNC_HOST_RDWR()
    CALL SELF%F_ZTHKICE%SYNC_HOST_RDWR()
    CALL SELF%F_ZWLMX%SYNC_HOST_RDWR()
    CALL SELF%F_ZCSN%SYNC_HOST_RDWR()
    CALL SELF%F_ZCVT%SYNC_HOST_RDWR()
    CALL SELF%F_ZLAIVT%SYNC_HOST_RDWR()
    CALL SELF%F_ZKH%SYNC_HOST_RDWR()
    CALL SELF%F_ZEXDIAG%SYNC_HOST_RDWR()
    CALL SELF%F_ZSPECTRALEMISS%SYNC_HOST_RDWR()
    CALL SELF%F_ZEVAPSNW%SYNC_HOST_RDWR()
    CALL SELF%F_ZFRTI%SYNC_HOST_RDWR()
    CALL SELF%F_ZALBTI%SYNC_HOST_RDWR()
    CALL SELF%F_ZFRSOTI%SYNC_HOST_RDWR()
    CALL SELF%F_PSLRFLTI%SYNC_HOST_RDWR()
    CALL SELF%F_ZALBD%SYNC_HOST_RDWR()
    CALL SELF%F_ZALBP%SYNC_HOST_RDWR()
    CALL SELF%F_PWL%SYNC_HOST_RDWR()
    CALL SELF%F_PSNS%SYNC_HOST_RDWR()
    CALL SELF%F_PRSN%SYNC_HOST_RDWR()
    CALL SELF%F_PWSN%SYNC_HOST_RDWR()
    CALL SELF%F_PANDAYVT%SYNC_HOST_RDWR()
    CALL SELF%F_PANFMVT%SYNC_HOST_RDWR()
  END SUBROUTINE SURF_AND_MORE_LOCAL_TYPE_SYNC_HOST

  SUBROUTINE DDH_SURF_TYPE_INIT(SELF, NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO )
    CLASS(DDH_SURF_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA, NBLOCKS, NCSS, NCSNEC, NTILES, NVHILO
    CALL FIELD_NEW(SELF%F_PDHBVOCS, UBOUNDS=[NPROMA,NVHILO,NDHVBVOCS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHTLS, UBOUNDS=[NPROMA,NTILES,NDHVTLS+NDHFTLS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHTSS, UBOUNDS=[NPROMA,NCSNEC,NDHVTSS+NDHFTSS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHSSS, UBOUNDS=[NPROMA,NCSNEC,NDHVSSS+NDHFSSS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHTTS, UBOUNDS=[NPROMA,NCSS  ,NDHVTTS+NDHFTTS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHWLS, UBOUNDS=[NPROMA,NCSS  ,NDHVWLS+NDHFWLS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHTIS, UBOUNDS=[NPROMA,NLEVI ,NDHVTIS+NDHFTIS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHIIS, UBOUNDS=[NPROMA,       NDHVIIS+NDHFIIS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHCO2S, UBOUNDS=[NPROMA,NVHILO,NDHVCO2S+NDHFCO2S,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHBIOS, UBOUNDS=[NPROMA,NVHILO,NDHVBIOS+NDHFBIOS,NBLOCKS], PERSISTENT=.TRUE.)
    CALL FIELD_NEW(SELF%F_PDHVEGS, UBOUNDS=[NPROMA,NVHILO,NDHVVEGS+NDHFVEGS,NBLOCKS], PERSISTENT=.TRUE.)

    BLOCK
      INTEGER(KIND=JPIM) :: JIBL
      REAL(KIND=JPRB), POINTER :: ZPDHTTS(:,:,:)
      REAL(KIND=JPRB), POINTER :: ZPDHVEGS(:,:,:)
      DO JIBL = 1, NBLOCKS
        ZPDHTTS  => SELF%F_PDHTTS%GET_VIEW(JIBL)
        ZPDHVEGS => SELF%F_PDHVEGS%GET_VIEW(JIBL)
        ZPDHTTS  = 0._JPRB
        ZPDHVEGS = 0._JPRB
      ENDDO
    END BLOCK
  END SUBROUTINE DDH_SURF_TYPE_INIT

  SUBROUTINE DDH_SURF_TYPE_FINAL(SELF)
    CLASS(DDH_SURF_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PDHTLS)
    CALL FIELD_DELETE(SELF%F_PDHTSS)
    CALL FIELD_DELETE(SELF%F_PDHSSS)
    CALL FIELD_DELETE(SELF%F_PDHTTS)
    CALL FIELD_DELETE(SELF%F_PDHWLS)
    CALL FIELD_DELETE(SELF%F_PDHTIS)
    CALL FIELD_DELETE(SELF%F_PDHIIS)
    CALL FIELD_DELETE(SELF%F_PDHCO2S)
    CALL FIELD_DELETE(SELF%F_PDHBIOS)
    CALL FIELD_DELETE(SELF%F_PDHBVOCS)
    CALL FIELD_DELETE(SELF%F_PDHVEGS)

    NULLIFY( SELF%PDHTLS)
    NULLIFY( SELF%PDHTSS)
    NULLIFY( SELF%PDHSSS)
    NULLIFY( SELF%PDHTTS)
    NULLIFY( SELF%PDHWLS)
    NULLIFY( SELF%PDHTIS)
    NULLIFY( SELF%PDHIIS)
    NULLIFY( SELF%PDHCO2S)
    NULLIFY( SELF%PDHBIOS)
    NULLIFY( SELF%PDHBVOCS)
    NULLIFY( SELF%PDHVEGS)
  END SUBROUTINE DDH_SURF_TYPE_FINAL

  SUBROUTINE DDH_SURF_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(DDH_SURF_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    IF(ASSOCIATED(SELF%F_PDHTLS))   SELF%PDHTLS   => SELF%F_PDHTLS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHTSS))   SELF%PDHTSS   => SELF%F_PDHTSS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHTTS))   SELF%PDHTTS   => SELF%F_PDHTTS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHTIS))   SELF%PDHTIS   => SELF%F_PDHTIS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHCO2S))  SELF%PDHCO2S  => SELF%F_PDHCO2S%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHBVOCS)) SELF%PDHBVOCS => SELF%F_PDHBVOCS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHBIOS))  SELF%PDHBIOS  => SELF%F_PDHBIOS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHVEGS))  SELF%PDHVEGS  => SELF%F_PDHVEGS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHSSS))   SELF%PDHSSS   => SELF%F_PDHSSS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHIIS))   SELF%PDHIIS   => SELF%F_PDHIIS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PDHWLS))   SELF%PDHWLS   => SELF%F_PDHWLS%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE DDH_SURF_TYPE_UPDATE_VIEW

  SUBROUTINE DDH_SURF_TYPE_SYNC_HOST(SELF)
    CLASS(DDH_SURF_TYPE) :: SELF
    CALL SELF%F_PDHTLS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHTSS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHTTS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHTIS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHCO2S%SYNC_HOST_RDWR()
    CALL SELF%F_PDHBVOCS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHBIOS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHVEGS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHSSS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHIIS%SYNC_HOST_RDWR()
    CALL SELF%F_PDHWLS%SYNC_HOST_RDWR()
  END SUBROUTINE DDH_SURF_TYPE_SYNC_HOST

END MODULE ECLAND_SURF_LOCAL_TYPE_MOD
