MODULE ECLAND_ATMO_TYPE_MOD
! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMGF1S , ONLY: UNLEV0   ,VNLEV0   ,TNLEV0   ,QNLEV0   ,&
     &              PNLP0    ,UNLEV1   ,VNLEV1   ,TNLEV1   ,QNLEV1
USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE

TYPE ATMO_TYPE
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PU => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PU  => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PV => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PV  => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PT => NULL()
  CLASS(FIELD_2RB), POINTER :: F_PT  => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PU1=> NULL() ! GMV fields
  CLASS(FIELD_2RB), POINTER :: F_PU1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PV1=> NULL() ! GMV fields
  CLASS(FIELD_2RB), POINTER :: F_PV1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PT1=> NULL() ! GMV fields
  CLASS(FIELD_2RB), POINTER :: F_PT1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PQ  => NULL() ! GFL fields
  CLASS(FIELD_2RB), POINTER :: F_PQ  => NULL()
  REAL(KIND=JPRB), DIMENSION(:), CONTIGUOUS,     POINTER :: PQ1 => NULL() ! GFL fields
  CLASS(FIELD_2RB), POINTER :: F_PQ1 => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PAPRS  => NULL()  ! PRESSURE ON HALF-LEVELS
  CLASS(FIELD_3RB), POINTER :: F_PAPRS  => NULL()
  REAL(KIND=JPRB), DIMENSION(:,:), CONTIGUOUS,   POINTER :: PGEOM1 => NULL()  ! GEOPOTENTIAL ON FULL LEVELS
  CLASS(FIELD_3RB), POINTER :: F_PGEOM1 => NULL()

CONTAINS
  PROCEDURE :: INIT  => ATMO_TYPE_INIT
  PROCEDURE :: FINAL => ATMO_TYPE_FINAL
  PROCEDURE :: UPDATE_VIEW => ATMO_TYPE_UPDATE_VIEW
END TYPE ATMO_TYPE

CONTAINS

  SUBROUTINE ATMO_TYPE_INIT(SELF, NPROMA, NLEV, NBLOCKS, PERSISTENT)
    CLASS(ATMO_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: NPROMA,NLEV,NBLOCKS
    LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
    LOGICAL :: LLPERSIST

    LLPERSIST = .FALSE.
    IF (PRESENT(PERSISTENT)) LLPERSIST = PERSISTENT

    CALL FIELD_NEW(SELF%F_PU, DATA=UNLEV0)
    CALL FIELD_NEW(SELF%F_PV, DATA=VNLEV0)
    CALL FIELD_NEW(SELF%F_PT, DATA=TNLEV0)
    CALL FIELD_NEW(SELF%F_PQ, DATA=QNLEV0)
    CALL FIELD_NEW(SELF%F_PU1, DATA=UNLEV1)
    CALL FIELD_NEW(SELF%F_PV1, DATA=VNLEV1)
    CALL FIELD_NEW(SELF%F_PT1, DATA=TNLEV1)
    CALL FIELD_NEW(SELF%F_PQ1, DATA=QNLEV1)

    CALL FIELD_NEW(SELF%F_PAPRS, LBOUNDS=[1,0,1], UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT = LLPERSIST)
    CALL FIELD_NEW(SELF%F_PGEOM1, UBOUNDS=[NPROMA,NLEV,NBLOCKS], PERSISTENT = LLPERSIST)
  END SUBROUTINE ATMO_TYPE_INIT

  SUBROUTINE ATMO_TYPE_FINAL(SELF)
    CLASS(ATMO_TYPE) :: SELF

    CALL FIELD_DELETE(SELF%F_PU)
    NULLIFY(SELF%PU)
    CALL FIELD_DELETE(SELF%F_PV)
    NULLIFY(SELF%PV)
    CALL FIELD_DELETE(SELF%F_PT)
    NULLIFY(SELF%PT)
    CALL FIELD_DELETE(SELF%F_PQ)
    NULLIFY(SELF%PQ)
    CALL FIELD_DELETE(SELF%F_PU1)
    NULLIFY(SELF%PU1)
    CALL FIELD_DELETE(SELF%F_PV1)
    NULLIFY(SELF%PV1)
    CALL FIELD_DELETE(SELF%F_PT1)
    NULLIFY(SELF%PT1)
    CALL FIELD_DELETE(SELF%F_PQ1)
    NULLIFY(SELF%PQ1)
    CALL FIELD_DELETE(SELF%F_PAPRS)
    NULLIFY(SELF%PAPRS)
    CALL FIELD_DELETE(SELF%F_PGEOM1)
    NULLIFY(SELF%PGEOM1)
  END SUBROUTINE ATMO_TYPE_FINAL

  SUBROUTINE ATMO_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
    CLASS(ATMO_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX

    IF(ASSOCIATED(SELF%F_PU))      SELF%PU      => SELF%F_PU%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PV))      SELF%PV      => SELF%F_PV%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PT))      SELF%PT      => SELF%F_PT%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PQ))      SELF%PQ      => SELF%F_PQ%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PU1))     SELF%PU1     => SELF%F_PU1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PV1))     SELF%PV1     => SELF%F_PV1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PT1))     SELF%PT1     => SELF%F_PT1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PQ1))     SELF%PQ1     => SELF%F_PQ1%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PAPRS))  SELF%PAPRS    => SELF%F_PAPRS%GET_VIEW(BLOCK_INDEX)
    IF(ASSOCIATED(SELF%F_PGEOM1)) SELF%PGEOM1   => SELF%F_PGEOM1%GET_VIEW(BLOCK_INDEX)
  END SUBROUTINE ATMO_TYPE_UPDATE_VIEW

END MODULE ECLAND_ATMO_TYPE_MOD
