SUBROUTINE UPDDIAG( &
 &  IBL &
 & ,KIDIA,KFDIA,KLON,KLEV,KLEVS,KLEVSN,KTILES &
 & ,PTSPHY &
 & ,PPSURF &
 & ,PSURF, PSURFL, PAUX, PAUXL, PCLIM, PFLUX, PDIAG, STATE, GEMSL, PDDHS)

! (C) Copyright 2010- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
!**** UPDDIAG - INTERFACE ROUTINE TO COPY IFS VARIABLES TO
!		OFFLINE CODE DIAGNOSTICS BUFFERS

!     S. Boussetta/G.Balsamo May 2010 Add CTESSEL based on:
!        Marita Voogt (KNMI) "C-Tessel" 09/2005
!        Sebastien Lafont (ECMWF) "C-TESSEL"

!     E. Dutra May 2014, add KIDIAF,KFDIAF for NPROMA implementation

!
! INTERFACE
!
!    *KLON*         NUMBER OF GRID POINTS PER PACKET
!    *KIDIA*        FIRST POINT
!    *KFDIA*        LAST POINT
!    *KLEV*         NUMBER OF LOWEST LEVEL
!    *KLEVS*        SOIL LAYERS
!    *KLEVSN*       SNOW LAYERS
!    *KTILES*       NUMBER OF TILES (I.E. SUBGRID AREAS WITH DIFFERENT
!                   OF SURFACE BOUNDARY CONDITION)

!    *KVTYPES*      NUMBER OF VEGETATION TYPES

!    *KDHVTLS*      Number of variables for individual tiles
!    *KDHFTLS*      Number of fluxes for individual tiles
!    *KDHVTSS*      Number of variables for snow energy budget
!    *KDHFTSS*      Number of fluxes for snow energy budget
!    *KDHVTTS*      Number of variables for soil energy budget
!    *KDHFTTS*      Number of fluxes for soil energy budget
!    *KDHVIIS*      Number of variables for interception water budget
!    *KDHFIIS*      Number of fluxes for interception water budget
!    *KDHVSSS*      Number of variables for snow water budget
!    *KDHFSSS*      Number of fluxes for snow water budget
!    *KDHVWLS*      Number of variables for soil water budget
!    *KDHFWLS*      Number of fluxes for soil water budget
!    *KDHVRESS*     Number of variables for resistances
!    *KDHFRESS*     Number of fluxes for resistances

!    *KDHVCO2S*     Number of variables for CO2
!    *KDHFCO2S*     Number of fluxes for CO2
!    *KDHVBIOS*     Number of variables for biomass
!    *KDHFBIOS*     Number of fluxes for biomass
!    *KDHVVEGS*     Number of variables for vegetation
!    *KDHFVEGS*     Number of fluxes for vegetation


!
!    *PTSPHY*       time step length
!    *PDHTLS*	    surface fluxes
!    *PDHTSS*	    snow fluxes
!    *PDHTTS*	    soil T fluxes
!    *PDHSSS*	    snow mass fluxes
!    *PDHIIS*	    interception mass fluxes
!    *PDHWLS*	    soil water fluxes
!    *PDHRESS*      resistances
!
!    *PT2M*         Screen-level air temperature
!    *PD2M*         Screen-level air dew point temperature
!
!     PWSAE1	 : tendency of soil water content
!     PWLE1	 : tendency of interception reservoir content
!     PSNSE1	 : tendency of snow mass

!    *PDHCO2S*      CO2 fluxes per vegetation type
!    *PDHBIOS*      biomass per vegetation type
!    *PDHVEGS*      vegetation variables per vegetation type



!     PSRSOD     : SURFACE SHORTWAVE RADIATIVE FLUX DOWNWARDS.
!     PSRTHD     : SURFACE LONGWAVE RADIATIVE FLUX DOWNWARDS.
!     PFRSO      : SHORTWAVE RADIATIVE FLUX.
!     PFRTH      : LONGWAVE RADIATIVE FLUX.
!     PALB       : MODEL SURFACE SHORTWAVE ALBEDO.
!     PFTLHEV    : SURFACE LATENT HEAT FLUX (SNOW FREE FRACTION)
!     PFTLHSB    : SURFACE LATENT HEAT FLUX (SNOW COVERED FRACTION)
!     PDIFTQ     : TURBULENT FLUX OF MOISTURE
!     PDIFTS     : TURBULENT FLUX OF ENTHALPY (OR DRY STATIC ENERGY).
!     PSTRTU     : TURBULENT MOMENTUM FLUX
!     PSTRTV     : TURBULENT MOMENTUM FLUX
!     PLSRF      : LARGE SCALE RAINFALL
!     PCRF       : CONVECTIVE RAINFALL
!     PLSSF      : LARGE SCALE SNOWFALL
!     PCSF       : CONVECTIVE SNOWFALL
!     PFWRO1     : SURFACE RUNOFF
!     PFWROD     : DEEP RUNOFF
!     PFWMLT     : SNOW MELT

!     PAN        : NET CO2 ASSIMILATION OVER CANOPY
!     PAG        : GROSS CO2 ASSIMILATION OVER CANOPY
!     PRD        : DARK RESPIRATION
!     PRSOIL_STR : RESPIRATION FROM SOIL AND STRUCTURAL BIOMASS
!     PRECO      : ECOSYSTEM RESPIRATION
!     PCO2FLUX   : CO2 FLUX
!     PCH4FLUX   : CH4 FLUX
!     PBVOCFLUX  : BVOC FLUX
!     PLAI       : LAI (M2/M2)
!     PBIOM      : BIOMASS (KG/M2)
!     PBLOSS     : BIOMASS LOSS (KG/M2)
!     PBGAIN     : BIOMASS GAIN (KG/M2)
!     PBIOMSTR   : ABOVE GROUND STRUCTURAL BIOMASS (KG/M2)
!     PBIOMSTR2  : BELOW GROUND STRUCTURAL BIOMASS (KG/M2)
!     PWSAE1	 : tendency of soil water content
!     PWLE1	 : tendency of interception reservoir content
!     PSNSE1	 : tendency of snow mass
!     PTAIR      : AIR TEMPERATURE (forcing T+1, end of timestep)
!     PQAIR      : AIR SPECIFIC HUMIDITY (forcing T+1, end of timestep)
!     PUWIND     : U WIND SPEED (forcing T+1, end of timestep)
!     PVWIND     : V WIND SPEED (forcing T+1, end of timestep)
!
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOETHF   , ONLY : RHOH2O
USE YOESOIL1S, ONLY : RDAW
USE YOMGPD1S , ONLY : VDIEWSS  ,VDINSSS  ,VDISSHF
USE YOMGDI1S , ONLY : D1STISRD ,D1STISRU ,D1STITRD ,D1STITRU ,&
            &D1STIH   ,D1STILE  ,D1STIGFL ,D1STII   ,D1STIEVAP,&
            &D1SNFR   ,D1SNTFR  ,D1SNAFR  ,&
            &D1SRFLD  ,D1SRFLU  ,D1TRFLD  ,D1TRFLU  ,&
            &D1AHFS   ,D1AHFL   ,D1MOMU   ,D1MOMV   ,&
            &D1STNSRD ,D1STNSRU ,D1STNTRD ,D1STNTRU ,&
            &D1STNGFL ,D1STNDH  ,D1STNM   ,&
            &D1ST1SRD ,D1ST1SRU ,D1ST1TRD ,D1ST1TRU ,&
            &D1ST1H   ,D1ST1LE  ,D1STAGFL ,D1STASF  ,&
            &D1SSFL   ,D1SSFC   ,D1SWNJQ  ,D1SWNM   ,&
            &D1SWLIT  ,D1SWLJQ  ,&
            &D1SW1JBG ,D1SW1TF  ,D1SWAGFL ,D1SW1RI  ,&
            &D1SWARS  ,D1SWAEXT ,D1SW1M   ,D1SWAC   ,&
            &D1SW1C   ,D1STIFR  ,D1STITK  ,D1STIALB ,&
            &D1SVTAN  ,D1SVTAG  ,D1SVTRD  ,D1SVTRSOIL_STR,D1SVTRECO,&
            &D1SVTCO2FLUX,D1SVTRNOQ10,&
            &D1SAN    ,D1SAG    ,D1SRD    ,D1SRSOIL_STR ,D1SRECO,&
            &D1SCO2FLUX,D1SCH4FLUX, D1SBVOCFLUX, &
            &D1SLAI   ,D1SBIOM  ,D1SBLOSS ,D1SBGAIN ,D1SBIOMSTR,&
            &D1SBIOMSTRB,&
            &D1SVTLAI ,D1SVTBIOM,D1SVTBLOSS,D1SVTBGAIN,&
            &D1SVTBIOMSTR,D1SVTBIOMSTRB,&
            &D1SVTGC  ,D1SVTGA  ,D1SVTF2  ,D1SVTDS,D1SVTDMAX,&
            &D1SVTLE  ,D1SVTFR  ,D1SWFR    ,&
            &D1STAIR  ,D1SQAIR  ,D1SUWIND  ,D1SVWIND,&
            &D1SNDEPTH,D1SWAFR  ,D1SRADTK ,&
            &D1SAVTK  ,D1SVEGTK ,&
            &D1SGHF   ,D1SALB   ,&
            &D1SVEGEV ,D1SDSH   ,&
            &D1SWDS   ,&
            &D1SSDS   ,D1SWLDS  ,&
            &D1SLSRF  ,D1SCRF   ,D1SLSSF  ,D1SCSF   ,&
            &D1STE    ,D1STRO   ,D1STSRO  ,D1SMLT  ,&
            &D1SSDSSL,&
            &D1SVTRC  ,D1SVTRA ,&
            &D1T2M    ,D1D2M,&
            &D1WFLUXRF,D1HFLUXRF,D1WSN,&
            &D1STIEVAPU,D1STISKC,D1SPSURF, &
            &D1SBVOCST1,D1SBVOCST2
USE YOMDPHY , ONLY: NPOI, NBLOCKS
USE YOMDIM1S, ONLY: NPROMA
USE ECLAND_ATMO_TYPE_MOD, ONLY: ATMO_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD, ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECLAND_AUX_TYPE_MOD, ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_DDH_TYPE_MOD, ONLY: DDH_SURF_TYPE
USE ECLAND_CLIMATE_TYPE_MOD, ONLY: CLIMATE_TYPE
USE ECLAND_FLUX_TYPE_MOD, ONLY: FLUX_TYPE
USE ECLAND_GEMS_TYPE_MOD, ONLY: GEMS_LOCAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD, ONLY: SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY: SURF_AND_MORE_LOCAL_TYPE

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVS
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVSN
INTEGER(KIND=JPIM),INTENT(IN)    :: KTILES

REAL(KIND=JPRB),INTENT(IN)       :: PTSPHY

TYPE(SURF_AND_MORE_TYPE)       , INTENT(IN) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE) , INTENT(IN) :: PSURFL
TYPE(AUX_DIAG_TYPE)            , INTENT(IN) :: PDIAG
TYPE(AUX_DIAG_LOCAL_TYPE)      , INTENT(IN) :: PAUXL
TYPE(AUX_TYPE)                 , INTENT(IN) :: PAUX
TYPE(FLUX_TYPE)                , INTENT(IN) :: PFLUX
TYPE(CLIMATE_TYPE)             , INTENT(IN) :: PCLIM
TYPE(ATMO_TYPE)                , INTENT(IN) :: STATE
TYPE(GEMS_LOCAL_TYPE)          , INTENT(IN) :: GEMSL
TYPE(DDH_SURF_TYPE)            , INTENT(IN) :: PDDHS

REAL(KIND=JPRB)   ,INTENT(IN)    :: PPSURF(KLON,NBLOCKS)
INTEGER(KIND=JPIM),INTENT(IN)    :: IBL

INTEGER(KIND=JPIM) :: JTILE,JL,JK,JLK
REAL(KIND=JPRB) :: ZEPS
REAL(KIND=JPRB) :: ZEPSILON

! balans sluitingen
INTEGER(KIND=JPIM)   :: I1

!* ==============================================================
!* ==============================================================
!*           IMPORTANT
!* Use KIDIA,KFDIA for input array P* that are defined over KLON points
!* Use KIDIAF:KFDIAF  for module D* arrays that are defined over all NPOINTS
!* Be carafull when using the D* in calculations for other D* arrays
!* ==============================================================
!* ==============================================================

ZEPS=1.E-5_JPRB
ZEPSILON=EPSILON(ZEPS)
!* calculations on JL
DO JL=KIDIA,KFDIA
  D1SWDS(JL,IBL)=PTSPHY*RHOH2O*DOT_PRODUCT(PSURF%PWSAE1(JL,:),RDAW(:))
  DO JK=1,KLEVS
    D1SSDSSL(JL,JK,IBL)=PTSPHY*RHOH2O*PSURF%PWSAE1(JL,JK)*RDAW(JK)
  ENDDO
ENDDO

!*  -- no calculations just memory swap

VDISSHF(KIDIA:KFDIA,IBL) = PFLUX%PDIFTS(KIDIA:KFDIA,KLEV)
VDIEWSS(KIDIA:KFDIA,IBL) = PFLUX%PSTRTU(KIDIA:KFDIA,KLEV)
VDINSSS(KIDIA:KFDIA,IBL) = PFLUX%PSTRTV(KIDIA:KFDIA,KLEV)


! Tile energy fluxes
D1STISRD(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHTLS(KIDIA:KFDIA,:,4)
D1STISRU(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHTLS(KIDIA:KFDIA,:,5)
D1STITRD(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHTLS(KIDIA:KFDIA,:,6)
D1STITRU(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHTLS(KIDIA:KFDIA,:,7)
D1STIH(KIDIA:KFDIA,:,IBL)     = PDDHS%PDHTLS(KIDIA:KFDIA,:,8)
D1STILE(KIDIA:KFDIA,:,IBL)    = PDDHS%PDHTLS(KIDIA:KFDIA,:,9)
D1STIGFL(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHTLS(KIDIA:KFDIA,:,10)
D1STII(KIDIA:KFDIA,:,IBL)     = 0._JPRB
D1STIEVAP(KIDIA:KFDIA,:,IBL)  = PDDHS%PDHTLS(KIDIA:KFDIA,:,11)
D1STISKC(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHTLS(KIDIA:KFDIA,:,12)
D1STIEVAPU(KIDIA:KFDIA,:,IBL) = PSURF%GSD%PEVAPTIU(KIDIA:KFDIA,:)

! Average energy fluxes
D1SRFLD(KIDIA:KFDIA,IBL) = PSURF%PSRSOD(KIDIA:KFDIA)
D1SRFLU(KIDIA:KFDIA,IBL) = PFLUX%PFRSO(KIDIA:KFDIA,KLEV)-PSURF%PSRSOD(KIDIA:KFDIA)
D1TRFLD(KIDIA:KFDIA,IBL) = PSURF%PSRTHD(KIDIA:KFDIA)
D1TRFLU(KIDIA:KFDIA,IBL) = PFLUX%PFRTH(KIDIA:KFDIA,KLEV)-PSURF%PSRTHD(KIDIA:KFDIA)
D1AHFS(KIDIA:KFDIA,IBL)  = PFLUX%PDIFTS(KIDIA:KFDIA,KLEV)
D1AHFL(KIDIA:KFDIA,IBL)  = PFLUX%PFTLHEV(KIDIA:KFDIA)+PFLUX%PFTLHSB(KIDIA:KFDIA)
D1MOMU(KIDIA:KFDIA,IBL)  = PFLUX%PSTRTU(KIDIA:KFDIA,KLEV)
D1MOMV(KIDIA:KFDIA,IBL)  = PFLUX%PSTRTV(KIDIA:KFDIA,KLEV)

! Snow energy fluxes
D1STNSRD(KIDIA:KFDIA,IBL) = PDDHS%PDHTSS(KIDIA:KFDIA,1,7)
D1STNSRU(KIDIA:KFDIA,IBL) = PDDHS%PDHTSS(KIDIA:KFDIA,1,8)
D1STNTRD(KIDIA:KFDIA,IBL) = PDDHS%PDHTSS(KIDIA:KFDIA,1,9)
D1STNTRU(KIDIA:KFDIA,IBL) = PDDHS%PDHTSS(KIDIA:KFDIA,1,10)
D1STNGFL(KIDIA:KFDIA,IBL) = PDDHS%PDHTSS(KIDIA:KFDIA,1,13)
D1STNM(KIDIA:KFDIA,IBL)   = PDDHS%PDHTSS(KIDIA:KFDIA,1,14)
D1HFLUXRF(KIDIA:KFDIA,IBL) = 0._JPRB ! PDHTSS(KIDIA:KFDIA,1,16) Not available in surf

! Soil energy fluxes
D1ST1SRD(KIDIA:KFDIA,IBL) = PDDHS%PDHTTS(KIDIA:KFDIA,1,5)
D1ST1SRU(KIDIA:KFDIA,IBL) = PDDHS%PDHTTS(KIDIA:KFDIA,1,6)
D1ST1TRD(KIDIA:KFDIA,IBL) = PDDHS%PDHTTS(KIDIA:KFDIA,1,7)
D1ST1TRU(KIDIA:KFDIA,IBL) = PDDHS%PDHTTS(KIDIA:KFDIA,1,8)
D1ST1H(KIDIA:KFDIA,IBL)   = PDDHS%PDHTTS(KIDIA:KFDIA,1,9)
D1ST1LE(KIDIA:KFDIA,IBL)  = PDDHS%PDHTTS(KIDIA:KFDIA,1,10)
D1STAGFL(KIDIA:KFDIA,:,IBL) = PDDHS%PDHTTS(KIDIA:KFDIA,:,11)
D1STASF(KIDIA:KFDIA,:,IBL)  = PDDHS%PDHTTS(KIDIA:KFDIA,:,12)

! Snow water fluxes
D1SSFL(KIDIA:KFDIA,IBL)  = PDDHS%PDHSSS(KIDIA:KFDIA,1,2)
D1SSFC(KIDIA:KFDIA,IBL)  = PDDHS%PDHSSS(KIDIA:KFDIA,1,3)
D1SWNJQ(KIDIA:KFDIA,IBL) = PDDHS%PDHSSS(KIDIA:KFDIA,1,4)
D1SWNM(KIDIA:KFDIA,IBL)  = PDDHS%PDHSSS(KIDIA:KFDIA,1,5)
D1WFLUXRF(KIDIA:KFDIA,IBL) = 0._JPRB ! PDHSSS(KIDIA:KFDIA,1,6) Not available in surf
D1WSN(KIDIA:KFDIA,IBL) = 0._JPRB ! PDHSSS(KIDIA:KFDIA,1,7) Not available in surf

! Interception water fluxes
D1SWLIT(KIDIA:KFDIA,IBL) = PDDHS%PDHIIS(KIDIA:KFDIA,2)+PDDHS%PDHIIS(KIDIA:KFDIA,3)
D1SWLJQ(KIDIA:KFDIA,IBL) = PDDHS%PDHIIS(KIDIA:KFDIA,4)
!write(6,*) 'upddiag chech interceptie balans'
!write(6,*) 'interceptie',D1SWLIT
!write(6,*) 'evaporatie',D1SWLjq

! Soil water fluxes
D1SW1JBG(KIDIA:KFDIA,IBL) = PDDHS%PDHWLS(KIDIA:KFDIA,1,9)! bare ground evaporation
                                                   ! with mismatches from
                                                   ! intercep & snow tiles
D1SW1TF(KIDIA:KFDIA,IBL)  = PDDHS%PDHWLS(KIDIA:KFDIA,1,3)+PDDHS%PDHWLS(KIDIA:KFDIA,1,4)
D1SWAGFL(KIDIA:KFDIA,:,IBL) = PDDHS%PDHWLS(KIDIA:KFDIA,:,8)

D1SW1RI(KIDIA:KFDIA,IBL) = PDDHS%PDHWLS(KIDIA:KFDIA,1,6) ! surface runoff
D1SWARS(KIDIA:KFDIA,:,IBL) = 0._JPRB ! excess runoff
D1SWAEXT(KIDIA:KFDIA,:,IBL) = PDDHS%PDHWLS(KIDIA:KFDIA,:,7)
D1SW1M(KIDIA:KFDIA,IBL) = PDDHS%PDHSSS(KIDIA:KFDIA,1,5)
D1SW1C(KIDIA:KFDIA,IBL) = PDDHS%PDHWLS(KIDIA:KFDIA,1,10)
D1SWAC(KIDIA:KFDIA,:,IBL) = 0._JPRB ! clipping

! Resistances for low and high vegetation type
! D1SVTRC(KIDIAF:KFDIAF,:) = PDHRESS(KIDIA:KFDIA,:,1)  PDHRESS  not used in surf...
! D1SVTRA(KIDIAF:KFDIAF,:) = PDHRESS(KIDIA:KFDIA,:,2)  PDHRESS  not used in surf...

! CO2 fluxes per vegetation type (normalized to grid)
D1SVTAG(KIDIA:KFDIA,:,IBL) =        PDDHS%PDHCO2S(KIDIA:KFDIA,:,1)
D1SVTRD(KIDIA:KFDIA,:,IBL) =        PDDHS%PDHCO2S(KIDIA:KFDIA,:,2)
D1SVTAN(KIDIA:KFDIA,:,IBL) =        PDDHS%PDHCO2S(KIDIA:KFDIA,:,3)
D1SVTRSOIL_STR(KIDIA:KFDIA,:,IBL) = PDDHS%PDHCO2S(KIDIA:KFDIA,:,4)
D1SVTRECO(KIDIA:KFDIA,:,IBL) =      PDDHS%PDHCO2S(KIDIA:KFDIA,:,5)
D1SVTCO2FLUX(KIDIA:KFDIA,:,IBL) =   PDDHS%PDHCO2S(KIDIA:KFDIA,:,6)
D1SVTRNOQ10(KIDIA:KFDIA,:,IBL) =    PDDHS%PDHCO2S(KIDIA:KFDIA,:,7)
! CO2 flux per grid
D1SAN(KIDIA:KFDIA,IBL)=PSURF%PAN(KIDIA:KFDIA)
D1SAG(KIDIA:KFDIA,IBL)=PSURF%PAG(KIDIA:KFDIA)
D1SRD(KIDIA:KFDIA,IBL)=PSURF%PRD(KIDIA:KFDIA)
D1SRSOIL_STR(KIDIA:KFDIA,IBL)=PSURF%PRSOIL_STR(KIDIA:KFDIA)
D1SRECO(KIDIA:KFDIA,IBL)     =PSURF%PRECO(KIDIA:KFDIA)
D1SCO2FLUX(KIDIA:KFDIA,IBL)  =PSURF%PCO2FLUX(KIDIA:KFDIA)
D1SCH4FLUX(KIDIA:KFDIA,IBL)  =PSURF%PCH4FLUX(KIDIA:KFDIA)
D1SBVOCFLUX(KIDIA:KFDIA,IBL) =GEMSL%PBVOCFLUX(KIDIA:KFDIA,1)

! Biomass per vegetation type
D1SVTBIOM(KIDIA:KFDIA,:,IBL)     = PDDHS%PDHBIOS(KIDIA:KFDIA,:,1)
D1SVTBLOSS(KIDIA:KFDIA,:,IBL)    = PDDHS%PDHBIOS(KIDIA:KFDIA,:,2)
D1SVTBGAIN(KIDIA:KFDIA,:,IBL)    = PDDHS%PDHBIOS(KIDIA:KFDIA,:,3)
D1SVTBIOMSTR(KIDIA:KFDIA,:,IBL)  = PDDHS%PDHBIOS(KIDIA:KFDIA,:,4)
D1SVTBIOMSTRB(KIDIA:KFDIA,:,IBL) = PDDHS%PDHBIOS(KIDIA:KFDIA,:,5)
! Biomass per grid
D1SBIOM(KIDIA:KFDIA,IBL)    =PSURF%PBIOM(KIDIA:KFDIA)
D1SBLOSS(KIDIA:KFDIA,IBL)   =PSURF%PBLOSS(KIDIA:KFDIA)
D1SBGAIN(KIDIA:KFDIA,IBL)   =PSURF%PBGAIN(KIDIA:KFDIA)
D1SBIOMSTR(KIDIA:KFDIA,IBL) =PSURF%PBIOMSTR(KIDIA:KFDIA)
D1SBIOMSTRB(KIDIA:KFDIA,IBL)=PSURF%PBIOMSTR2(KIDIA:KFDIA)

! LAI per grid
D1SLAI(KIDIA:KFDIA,IBL)=PSURF%PLAI(KIDIA:KFDIA)

! Variables per vegetation type
D1SVTFR(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHVEGS(KIDIA:KFDIA,:,1)
D1SVTLAI(KIDIA:KFDIA,:,IBL)  = PDDHS%PDHVEGS(KIDIA:KFDIA,:,2)
D1SVTGC(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHVEGS(KIDIA:KFDIA,:,3)
D1SVTGA(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHVEGS(KIDIA:KFDIA,:,4)
D1SVTF2(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHVEGS(KIDIA:KFDIA,:,5)
D1SVTDS(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHVEGS(KIDIA:KFDIA,:,6)
D1SVTDMAX(KIDIA:KFDIA,:,IBL) = PDDHS%PDHVEGS(KIDIA:KFDIA,:,7)
D1SVTLE(KIDIA:KFDIA,:,IBL)   = PDDHS%PDHVEGS(KIDIA:KFDIA,:,8)

! Tile values
D1STIFR(KIDIA:KFDIA,:,IBL)  = PDDHS%PDHTLS(KIDIA:KFDIA,:,1)
D1STITK(KIDIA:KFDIA,:,IBL)  = PDDHS%PDHTLS(KIDIA:KFDIA,:,2)
D1STIALB(KIDIA:KFDIA,:,IBL) = PDDHS%PDHTLS(KIDIA:KFDIA,:,3)

!AuxSN
D1SNDEPTH(KIDIA:KFDIA,IBL) = PDDHS%PDHSSS(KIDIA:KFDIA,1,1)
D1SNFR(KIDIA:KFDIA,IBL) = PDDHS%PDHTLS(KIDIA:KFDIA,5,1)+PDDHS%PDHTLS(KIDIA:KFDIA,7,1)
D1SNTFR(KIDIA:KFDIA,IBL) = D1SNFR(KIDIA:KFDIA,IBL)*PDDHS%PDHTSS(KIDIA:KFDIA,1,2)
D1SNAFR(KIDIA:KFDIA,IBL) = D1SNFR(KIDIA:KFDIA,IBL)*PDDHS%PDHTSS(KIDIA:KFDIA,1,6)
!AuxW
WHERE (PDDHS%PDHTLS(KIDIA:KFDIA,3,1) > ZEPSILON )
  D1SWFR(KIDIA:KFDIA,IBL) = PDDHS%PDHTLS(KIDIA:KFDIA,3,1)/  &
   & MAX(ZEPSILON, 1._JPRB-(PDDHS%PDHTLS(KIDIA:KFDIA,5,1)+PDDHS%PDHTLS(KIDIA:KFDIA,7,1)))
ELSEWHERE
  D1SWFR(KIDIA:KFDIA,IBL) = 0._JPRB
ENDWHERE
D1SWAFR(KIDIA:KFDIA,:,IBL) = PDDHS%PDHWLS(KIDIA:KFDIA,:,1)-PDDHS%PDHWLS(KIDIA:KFDIA,:,2) ! liquid water (kg m-2)
!AuxT
D1SAVTK(KIDIA:KFDIA,IBL) = 0._JPRB
DO JTILE=1,KTILES
  D1SAVTK(KIDIA:KFDIA,IBL)=D1SAVTK(KIDIA:KFDIA,IBL)+PDDHS%PDHTLS(KIDIA:KFDIA,JTILE,1)*PDDHS%PDHTLS(KIDIA:KFDIA,JTILE,2)
ENDDO
D1SVEGTK(KIDIA:KFDIA,IBL) = (MAX(ZEPS,PDDHS%PDHTLS(KIDIA:KFDIA,4,1))*PDDHS%PDHTLS(KIDIA:KFDIA,4, 2)+ &
     &      PDDHS%PDHTLS(KIDIA:KFDIA,6,1)*PDDHS%PDHTLS(KIDIA:KFDIA,6,2))/  &
     &     (MAX(ZEPS,PDDHS%PDHTLS(KIDIA:KFDIA,4,1))+PDDHS%PDHTLS(KIDIA:KFDIA,6,1))
D1SGHF(KIDIA:KFDIA,IBL) = PDDHS%PDHTTS(KIDIA:KFDIA,1,14)
D1SRADTK(KIDIA:KFDIA,IBL) = 0._JPRB ! not calculated in vdfmain
D1SRADTK(KIDIA:KFDIA,IBL) =(PDDHS%PDHTLS(KIDIA:KFDIA,1,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,1, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,2,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,2, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,3,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,3, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,4,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,4, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,5,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,5, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,6,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,6, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,7,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,7, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,8,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,8, 2))**4)**(0.25_JPRB)
IF (KTILES > 9) THEN
 D1SRADTK(KIDIA:KFDIA,IBL) =(PDDHS%PDHTLS(KIDIA:KFDIA,1,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,1, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,2,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,2, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,3,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,3, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,4,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,4, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,5,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,5, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,6,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,6, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,7,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,7, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,8,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,8, 2))**4+ &
     &     PDDHS%PDHTLS(KIDIA:KFDIA,10,1)*(PDDHS%PDHTLS(KIDIA:KFDIA,10, 2))**4)**(0.25_JPRB)
ENDIF
D1SALB(KIDIA:KFDIA,IBL) = PCLIM%PALB(KIDIA:KFDIA)
D1SVEGEV(KIDIA:KFDIA,IBL) = 0._JPRB ! not used
D1SDSH(KIDIA:KFDIA,IBL) = 0._JPRB ! DelSoilHeat of skin layer (0)
D1STNDH(KIDIA:KFDIA,IBL) = PDDHS%PDHTSS(KIDIA:KFDIA,1,15)     ! DelColdCont

D1SSDS(KIDIA:KFDIA,IBL)=PTSPHY*PSURF%PSNSE1(KIDIA:KFDIA,1)
D1SWLDS(KIDIA:KFDIA,IBL)=PTSPHY*PSURF%PWLE1(KIDIA:KFDIA)
!write(6,*) 'delint',D1SWLDS

! Water budgets
D1SLSRF(KIDIA:KFDIA,IBL) =  PFLUX%PFPLSL(KIDIA:KFDIA) ! PLSRF(KIDIA:KFDIA)
D1SCRF(KIDIA:KFDIA,IBL)  =  PFLUX%PFPLCL(KIDIA:KFDIA) ! PCRF(KIDIA:KFDIA)
D1SLSSF(KIDIA:KFDIA,IBL) =  PFLUX%PFPLSN(KIDIA:KFDIA) ! PLSSF(KIDIA:KFDIA)
D1SCSF(KIDIA:KFDIA,IBL)  =  PFLUX%PFPLCN(KIDIA:KFDIA) ! PCSF(KIDIA:KFDIA)
D1STE(KIDIA:KFDIA,IBL)   =  PFLUX%PDIFTQ(KIDIA:KFDIA,KLEV)
D1STSRO(KIDIA:KFDIA,IBL) =  PFLUX%PFWRO1(KIDIA:KFDIA)
D1STRO(KIDIA:KFDIA,IBL)  =  PFLUX%PFWRO1(KIDIA:KFDIA) + PFLUX%PFWROD(KIDIA:KFDIA)
D1SMLT(KIDIA:KFDIA,IBL)  =  PFLUX%PFWMLT(KIDIA:KFDIA)

! Screen level
D1T2M(KIDIA:KFDIA,IBL) = PSURF%GSD%PT2M(KIDIA:KFDIA)
D1D2M(KIDIA:KFDIA,IBL) = PSURF%GSD%PD2M(KIDIA:KFDIA)
! forcing (end of timestep)

D1STAIR(KIDIA:KFDIA,IBL)  = STATE%PT1(KIDIA:KFDIA) ! PTAIR(KIDIA:KFDIA)
D1SQAIR(KIDIA:KFDIA,IBL)  = STATE%PQ1(KIDIA:KFDIA) ! PQAIR(KIDIA:KFDIA)
D1SUWIND(KIDIA:KFDIA,IBL) = STATE%PU1(KIDIA:KFDIA) !PUWIND(KIDIA:KFDIA)
D1SVWIND(KIDIA:KFDIA,IBL) = STATE%PV1(KIDIA:KFDIA) !PVWIND(KIDIA:KFDIA)
D1SPSURF(KIDIA:KFDIA,IBL) = PPSURF(KIDIA:KFDIA,IBL)
! Biogenic VOC emission diagnostics per vegetation type. Check how this is computed!
D1SBVOCST1(KIDIA:KFDIA,:,IBL) = PDDHS%PDHBVOCS(KIDIA:KFDIA,:,1)
D1SBVOCST2(KIDIA:KFDIA,:,IBL) = PDDHS%PDHBVOCS(KIDIA:KFDIA,:,2)

END SUBROUTINE UPDDIAG
