SUBROUTINE UPDDIAG( &
 & IST,IEND,IBL,IPROMA &
 & ,KIDIA,KFDIA,KLON,KLEV,KLEVS,KLEVSN,KTILES &
 & ,PTSPHY &
 & ,PPSURF &
 & ,PSURF, PSURFL, PAUX, PAUXL, PCLIM, PFLUX, PDIAG, STATE, GEMSL, PDDHS)

! (C) Copyright 2010- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
!**** UPDDIAG - INTERFACE ROUTINE TO COPY IFS VARIABLES TO
!		OFFLINE CODE DIAGNOSTICS BUFFERS

!     S. Boussetta/G.Balsamo May 2010 Add CTESSEL based on:
!        Marita Voogt (KNMI) "C-Tessel" 09/2005
!        Sebastien Lafont (ECMWF) "C-TESSEL"

!     E. Dutra May 2014, add KIDIAF,KFDIAF for NPROMA implementation 

!
! INTERFACE
!
!    *KLON*         NUMBER OF GRID POINTS PER PACKET
!    *KIDIA*        FIRST POINT
!    *KFDIA*        LAST POINT
!    *KLEV*         NUMBER OF LOWEST LEVEL
!    *KLEVS*        SOIL LAYERS
!    *KLEVSN*       SNOW LAYERS
!    *KTILES*       NUMBER OF TILES (I.E. SUBGRID AREAS WITH DIFFERENT 
!                   OF SURFACE BOUNDARY CONDITION)

!    *KVTYPES*      NUMBER OF VEGETATION TYPES

!    *KDHVTLS*      Number of variables for individual tiles
!    *KDHFTLS*      Number of fluxes for individual tiles
!    *KDHVTSS*      Number of variables for snow energy budget
!    *KDHFTSS*      Number of fluxes for snow energy budget
!    *KDHVTTS*      Number of variables for soil energy budget
!    *KDHFTTS*      Number of fluxes for soil energy budget
!    *KDHVIIS*      Number of variables for interception water budget
!    *KDHFIIS*      Number of fluxes for interception water budget
!    *KDHVSSS*      Number of variables for snow water budget
!    *KDHFSSS*      Number of fluxes for snow water budget
!    *KDHVWLS*      Number of variables for soil water budget
!    *KDHFWLS*      Number of fluxes for soil water budget
!    *KDHVRESS*     Number of variables for resistances 
!    *KDHFRESS*     Number of fluxes for resistances

!    *KDHVCO2S*     Number of variables for CO2
!    *KDHFCO2S*     Number of fluxes for CO2
!    *KDHVBIOS*     Number of variables for biomass
!    *KDHFBIOS*     Number of fluxes for biomass
!    *KDHVVEGS*     Number of variables for vegetation
!    *KDHFVEGS*     Number of fluxes for vegetation


!
!    *PTSPHY*       time step length
!    *PDHTLS*	    surface fluxes
!    *PDHTSS*	    snow fluxes
!    *PDHTTS*	    soil T fluxes
!    *PDHSSS*	    snow mass fluxes
!    *PDHIIS*	    interception mass fluxes
!    *PDHWLS*	    soil water fluxes
!    *PDHRESS*      resistances 
!
!    *PT2M*         Screen-level air temperature  
!    *PD2M*         Screen-level air dew point temperature 
!
!     PWSAE1	 : tendency of soil water content
!     PWLE1	 : tendency of interception reservoir content
!     PSNSE1	 : tendency of snow mass

!    *PDHCO2S*      CO2 fluxes per vegetation type
!    *PDHBIOS*      biomass per vegetation type
!    *PDHVEGS*      vegetation variables per vegetation type



!     PSRSOD     : SURFACE SHORTWAVE RADIATIVE FLUX DOWNWARDS.
!     PSRTHD     : SURFACE LONGWAVE RADIATIVE FLUX DOWNWARDS.
!     PFRSO      : SHORTWAVE RADIATIVE FLUX.
!     PFRTH      : LONGWAVE RADIATIVE FLUX.
!     PALB       : MODEL SURFACE SHORTWAVE ALBEDO.
!     PFTLHEV    : SURFACE LATENT HEAT FLUX (SNOW FREE FRACTION)
!     PFTLHSB    : SURFACE LATENT HEAT FLUX (SNOW COVERED FRACTION)
!     PDIFTQ     : TURBULENT FLUX OF MOISTURE
!     PDIFTS     : TURBULENT FLUX OF ENTHALPY (OR DRY STATIC ENERGY).
!     PSTRTU     : TURBULENT MOMENTUM FLUX 
!     PSTRTV     : TURBULENT MOMENTUM FLUX 
!     PLSRF      : LARGE SCALE RAINFALL
!     PCRF       : CONVECTIVE RAINFALL
!     PLSSF      : LARGE SCALE SNOWFALL
!     PCSF       : CONVECTIVE SNOWFALL
!     PFWRO1     : SURFACE RUNOFF
!     PFWROD     : DEEP RUNOFF
!     PFWMLT     : SNOW MELT

!     PAN        : NET CO2 ASSIMILATION OVER CANOPY         
!     PAG        : GROSS CO2 ASSIMILATION OVER CANOPY   
!     PRD        : DARK RESPIRATION                         
!     PRSOIL_STR : RESPIRATION FROM SOIL AND STRUCTURAL BIOMASS
!     PRECO      : ECOSYSTEM RESPIRATION 
!     PCO2FLUX   : CO2 FLUX
!     PCH4FLUX   : CH4 FLUX
!     PBVOCFLUX  : BVOC FLUX
!     PLAI       : LAI (M2/M2)
!     PBIOM      : BIOMASS (KG/M2)
!     PBLOSS     : BIOMASS LOSS (KG/M2)
!     PBGAIN     : BIOMASS GAIN (KG/M2)
!     PBIOMSTR   : ABOVE GROUND STRUCTURAL BIOMASS (KG/M2)
!     PBIOMSTR2  : BELOW GROUND STRUCTURAL BIOMASS (KG/M2)
!     PWSAE1	 : tendency of soil water content
!     PWLE1	 : tendency of interception reservoir content
!     PSNSE1	 : tendency of snow mass
!     PTAIR      : AIR TEMPERATURE (forcing T+1, end of timestep)
!     PQAIR      : AIR SPECIFIC HUMIDITY (forcing T+1, end of timestep)
!     PUWIND     : U WIND SPEED (forcing T+1, end of timestep)
!     PVWIND     : V WIND SPEED (forcing T+1, end of timestep)



!
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOETHF   , ONLY : RHOH2O
USE YOESOIL1S, ONLY : RDAW
USE YOMGPD1S , ONLY : VDIEWSS  ,VDINSSS  ,VDISSHF 
USE YOMGDI1S , ONLY : D1STISRD ,D1STISRU ,D1STITRD ,D1STITRU ,&
            &D1STIH   ,D1STILE  ,D1STIGFL ,D1STII   ,D1STIEVAP,&
            &D1SNFR   ,D1SNTFR  ,D1SNAFR  ,&
            &D1SRFLD  ,D1SRFLU  ,D1TRFLD  ,D1TRFLU  ,&
            &D1AHFS   ,D1AHFL   ,D1MOMU   ,D1MOMV   ,&
            &D1STNSRD ,D1STNSRU ,D1STNTRD ,D1STNTRU ,&
            &D1STNGFL ,D1STNDH  ,D1STNM   ,&
            &D1ST1SRD ,D1ST1SRU ,D1ST1TRD ,D1ST1TRU ,&
            &D1ST1H   ,D1ST1LE  ,D1STAGFL ,D1STASF  ,&
            &D1SSFL   ,D1SSFC   ,D1SWNJQ  ,D1SWNM   ,&
            &D1SWLIT  ,D1SWLJQ  ,&
            &D1SW1JBG ,D1SW1TF  ,D1SWAGFL ,D1SW1RI  ,&
            &D1SWARS  ,D1SWAEXT ,D1SW1M   ,D1SWAC   ,&
            &D1SW1C   ,D1STIFR  ,D1STITK  ,D1STIALB ,&
            &D1SVTAN  ,D1SVTAG  ,D1SVTRD  ,D1SVTRSOIL_STR,D1SVTRECO,&
            &D1SVTCO2FLUX,D1SVTRNOQ10,&
            &D1SAN    ,D1SAG    ,D1SRD    ,D1SRSOIL_STR ,D1SRECO,&
            &D1SCO2FLUX,D1SCH4FLUX, D1SBVOCFLUX, &
            &D1SLAI   ,D1SBIOM  ,D1SBLOSS ,D1SBGAIN ,D1SBIOMSTR,&
            &D1SBIOMSTRB,&
            &D1SVTLAI ,D1SVTBIOM,D1SVTBLOSS,D1SVTBGAIN,&
            &D1SVTBIOMSTR,D1SVTBIOMSTRB,&
            &D1SVTGC  ,D1SVTGA  ,D1SVTF2  ,D1SVTDS,D1SVTDMAX,&
            &D1SVTLE  ,D1SVTFR  ,D1SWFR    ,&
            &D1STAIR  ,D1SQAIR  ,D1SUWIND  ,D1SVWIND,&
            &D1SNDEPTH,D1SWAFR  ,D1SRADTK ,&
            &D1SAVTK  ,D1SVEGTK ,&
            &D1SGHF   ,D1SALB   ,&
            &D1SVEGEV ,D1SDSH   ,&
            &D1SWDS   ,&
            &D1SSDS   ,D1SWLDS  ,&
            &D1SLSRF  ,D1SCRF   ,D1SLSSF  ,D1SCSF   ,&
            &D1STE    ,D1STRO   ,D1STSRO  ,D1SMLT  ,&
            &D1SSDSSL,&
            &D1SVTRC  ,D1SVTRA ,&
            &D1T2M    ,D1D2M,&
            &D1WFLUXRF,D1HFLUXRF,D1WSN,&
            &D1STIEVAPU,D1STISKC,D1SPSURF, &
            &D1SBVOCST1,D1SBVOCST2
USE YOMDPHY  ,  ONLY : NPOI, NBLOCKS 
USE YOMDIM1S , ONLY : NPROMA
USE ECLAND_SURFACE_TYPE_MOD, ONLY: SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY: SURF_AND_MORE_LOCAL_TYPE, DDH_SURF_TYPE 
USE ECLAND_AUX_DIAG_TYPE_MOD, ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECLAND_AUX_TYPE_MOD, ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD, ONLY: CLIMATE_TYPE
USE ECLAND_FLUX_TYPE_MOD, ONLY: FLUX_TYPE
USE ECLAND_ATMO_TYPE_MOD, ONLY: ATMO_TYPE
USE ECLAND_GEMS_TYPE_MOD, ONLY: GEMS_LOCAL_TYPE

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVS
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVSN
INTEGER(KIND=JPIM),INTENT(IN)    :: KTILES 

REAL(KIND=JPRB),INTENT(IN)       :: PTSPHY

TYPE(SURF_AND_MORE_TYPE)       , INTENT(IN) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE) , INTENT(IN) :: PSURFL
TYPE(AUX_DIAG_TYPE)            , INTENT(IN) :: PDIAG
TYPE(AUX_DIAG_LOCAL_TYPE)      , INTENT(IN) :: PAUXL
TYPE(AUX_TYPE)                 , INTENT(IN) :: PAUX
TYPE(FLUX_TYPE)                , INTENT(IN) :: PFLUX
TYPE(CLIMATE_TYPE)             , INTENT(IN) :: PCLIM
TYPE(ATMO_TYPE)                , INTENT(IN) :: STATE
TYPE(GEMS_LOCAL_TYPE)          , INTENT(IN) :: GEMSL 
TYPE(DDH_SURF_TYPE)            , INTENT(IN) :: PDDHS

REAL(KIND=JPRB)   ,INTENT(IN)    :: PPSURF(KLON,NBLOCKS)
INTEGER(KIND=JPIM),INTENT(IN)    :: IST,IEND,IBL,IPROMA

INTEGER(KIND=JPIM) :: JTILE,JL,JK,JLK
REAL(KIND=JPRB) :: ZEPS
REAL(KIND=JPRB) :: ZEPSILON

! balans sluitingen
INTEGER(KIND=JPIM)   :: I1


!* ==============================================================
!* ==============================================================
!*           IMPORTANT 
!* Use KIDIA,KFDIA for input array P* that are defined over KLON points 
!* Use KIDIAF:KFDIAF  for module D* arrays that are defined over all NPOINTS 
!* Be carafull when using the D* in calculations for other D* arrays 
!* ==============================================================
!* ==============================================================

ZEPS=1.E-5_JPRB
ZEPSILON=EPSILON(ZEPS)
!* calculations on JL 
DO JL=1,IPROMA
  D1SWDS(JL,IBL)=PTSPHY*RHOH2O*DOT_PRODUCT(PSURF%PWSAE1(JL,:),RDAW(:))
  DO JK=1,KLEVS
    D1SSDSSL(JL,JK,IBL)=PTSPHY*RHOH2O*PSURF%PWSAE1(JL,JK)*RDAW(JK)
  ENDDO
ENDDO

!*  -- no calculations just memory swap 

VDISSHF(1:IPROMA,IBL) = PFLUX%PDIFTS(1:IPROMA,KLEV)
VDIEWSS(1:IPROMA,IBL) = PFLUX%PSTRTU(1:IPROMA,KLEV)
VDINSSS(1:IPROMA,IBL) = PFLUX%PSTRTV(1:IPROMA,KLEV)


! Tile energy fluxes
D1STISRD(1:IPROMA,:,IBL)   = PDDHS%PDHTLS(1:IPROMA,:,4)
D1STISRU(1:IPROMA,:,IBL)   = PDDHS%PDHTLS(1:IPROMA,:,5)
D1STITRD(1:IPROMA,:,IBL)   = PDDHS%PDHTLS(1:IPROMA,:,6)
D1STITRU(1:IPROMA,:,IBL)   = PDDHS%PDHTLS(1:IPROMA,:,7)
D1STIH(1:IPROMA,:,IBL)     = PDDHS%PDHTLS(1:IPROMA,:,8)
D1STILE(1:IPROMA,:,IBL)    = PDDHS%PDHTLS(1:IPROMA,:,9)
D1STIGFL(1:IPROMA,:,IBL)   = PDDHS%PDHTLS(1:IPROMA,:,10)
D1STII(1:IPROMA,:,IBL)     = 0.
D1STIEVAP(1:IPROMA,:,IBL)  = PDDHS%PDHTLS(1:IPROMA,:,11)
D1STISKC(1:IPROMA,:,IBL)   = PDDHS%PDHTLS(1:IPROMA,:,12)
D1STIEVAPU(1:IPROMA,:,IBL) = PSURF%GSD%PEVAPTIU(1:IPROMA,:)

! Average energy fluxes
D1SRFLD(1:IPROMA,IBL) = PSURF%PSRSOD(1:IPROMA)
D1SRFLU(1:IPROMA,IBL) = PFLUX%PFRSO(1:IPROMA,KLEV)-PSURF%PSRSOD(1:IPROMA)
D1TRFLD(1:IPROMA,IBL) = PSURF%PSRTHD(1:IPROMA)
D1TRFLU(1:IPROMA,IBL) = PFLUX%PFRTH(1:IPROMA,KLEV)-PSURF%PSRTHD(1:IPROMA)
D1AHFS(1:IPROMA,IBL)  = PFLUX%PDIFTS(1:IPROMA,KLEV)
D1AHFL(1:IPROMA,IBL)  = PFLUX%PFTLHEV(1:IPROMA)+PFLUX%PFTLHSB(1:IPROMA)
D1MOMU(1:IPROMA,IBL)  = PFLUX%PSTRTU(1:IPROMA,KLEV)
D1MOMV(1:IPROMA,IBL)  = PFLUX%PSTRTV(1:IPROMA,KLEV)

! Snow energy fluxes
D1STNSRD(1:IPROMA,IBL) = PDDHS%PDHTSS(1:IPROMA,1,7)
D1STNSRU(1:IPROMA,IBL) = PDDHS%PDHTSS(1:IPROMA,1,8)
D1STNTRD(1:IPROMA,IBL) = PDDHS%PDHTSS(1:IPROMA,1,9)
D1STNTRU(1:IPROMA,IBL) = PDDHS%PDHTSS(1:IPROMA,1,10)
D1STNGFL(1:IPROMA,IBL) = PDDHS%PDHTSS(1:IPROMA,1,13)
D1STNM(1:IPROMA,IBL)   = PDDHS%PDHTSS(1:IPROMA,1,14)
D1HFLUXRF(1:IPROMA,IBL) = 0._JPRB ! PDHTSS(1:IPROMA,1,16) Not available in surf 

! Soil energy fluxes
D1ST1SRD(1:IPROMA,IBL) = PDDHS%PDHTTS(1:IPROMA,1,5)
D1ST1SRU(1:IPROMA,IBL) = PDDHS%PDHTTS(1:IPROMA,1,6)
D1ST1TRD(1:IPROMA,IBL) = PDDHS%PDHTTS(1:IPROMA,1,7)
D1ST1TRU(1:IPROMA,IBL) = PDDHS%PDHTTS(1:IPROMA,1,8)
D1ST1H(1:IPROMA,IBL)   = PDDHS%PDHTTS(1:IPROMA,1,9)
D1ST1LE(1:IPROMA,IBL)  = PDDHS%PDHTTS(1:IPROMA,1,10)
D1STAGFL(1:IPROMA,:,IBL) = PDDHS%PDHTTS(1:IPROMA,:,11)
D1STASF(1:IPROMA,:,IBL)  = PDDHS%PDHTTS(1:IPROMA,:,12)

! Snow water fluxes
D1SSFL(1:IPROMA,IBL)  = PDDHS%PDHSSS(1:IPROMA,1,2)
D1SSFC(1:IPROMA,IBL)  = PDDHS%PDHSSS(1:IPROMA,1,3)
D1SWNJQ(1:IPROMA,IBL) = PDDHS%PDHSSS(1:IPROMA,1,4)
D1SWNM(1:IPROMA,IBL)  = PDDHS%PDHSSS(1:IPROMA,1,5)
D1WFLUXRF(1:IPROMA,IBL) = 0._JPRB ! PDHSSS(1:IPROMA,1,6) Not available in surf 
D1WSN(1:IPROMA,IBL) = 0._JPRB ! PDHSSS(1:IPROMA,1,7) Not available in surf 

! Interception water fluxes
D1SWLIT(1:IPROMA,IBL) = PDDHS%PDHIIS(1:IPROMA,2)+PDDHS%PDHIIS(1:IPROMA,3)
D1SWLJQ(1:IPROMA,IBL) = PDDHS%PDHIIS(1:IPROMA,4)
!write(6,*) 'upddiag chech interceptie balans'
!write(6,*) 'interceptie',D1SWLIT
!write(6,*) 'evaporatie',D1SWLjq

! Soil water fluxes
D1SW1JBG(1:IPROMA,IBL) = PDDHS%PDHWLS(1:IPROMA,1,9)! bare ground evaporation 
                                                   ! with mismatches from 
                                                   ! intercep & snow tiles
D1SW1TF(1:IPROMA,IBL)  = PDDHS%PDHWLS(1:IPROMA,1,3)+PDDHS%PDHWLS(1:IPROMA,1,4)
D1SWAGFL(1:IPROMA,:,IBL) = PDDHS%PDHWLS(1:IPROMA,:,8)

D1SW1RI(1:IPROMA,IBL) = PDDHS%PDHWLS(1:IPROMA,1,6) ! surface runoff
D1SWARS(1:IPROMA,:,IBL) = 0. ! excess runoff
D1SWAEXT(1:IPROMA,:,IBL) = PDDHS%PDHWLS(1:IPROMA,:,7)
D1SW1M(1:IPROMA,IBL) = PDDHS%PDHSSS(1:IPROMA,1,5)
D1SW1C(1:IPROMA,IBL) = PDDHS%PDHWLS(1:IPROMA,1,10)
D1SWAC(1:IPROMA,:,IBL) = 0. ! clipping

! Resistances for low and high vegetation type
! D1SVTRC(KIDIAF:KFDIAF,:) = PDHRESS(1:IPROMA,:,1)  PDHRESS  not used in surf...
! D1SVTRA(KIDIAF:KFDIAF,:) = PDHRESS(1:IPROMA,:,2)  PDHRESS  not used in surf...

! CO2 fluxes per vegetation type (normalized to grid)
D1SVTAG(1:IPROMA,:,IBL) =        PDDHS%PDHCO2S(1:IPROMA,:,1)
D1SVTRD(1:IPROMA,:,IBL) =        PDDHS%PDHCO2S(1:IPROMA,:,2)
D1SVTAN(1:IPROMA,:,IBL) =        PDDHS%PDHCO2S(1:IPROMA,:,3)
D1SVTRSOIL_STR(1:IPROMA,:,IBL) = PDDHS%PDHCO2S(1:IPROMA,:,4)
D1SVTRECO(1:IPROMA,:,IBL) =      PDDHS%PDHCO2S(1:IPROMA,:,5)
D1SVTCO2FLUX(1:IPROMA,:,IBL) =   PDDHS%PDHCO2S(1:IPROMA,:,6)
D1SVTRNOQ10(1:IPROMA,:,IBL) =    PDDHS%PDHCO2S(1:IPROMA,:,7)
! CO2 flux per grid
D1SAN(1:IPROMA,IBL)=PSURF%PAN(1:IPROMA)
D1SAG(1:IPROMA,IBL)=PSURF%PAG(1:IPROMA)
D1SRD(1:IPROMA,IBL)=PSURF%PRD(1:IPROMA)
D1SRSOIL_STR(1:IPROMA,IBL)=PSURF%PRSOIL_STR(1:IPROMA)
D1SRECO(1:IPROMA,IBL)     =PSURF%PRECO(1:IPROMA)
D1SCO2FLUX(1:IPROMA,IBL)  =PSURF%PCO2FLUX(1:IPROMA)
D1SCH4FLUX(1:IPROMA,IBL)  =PSURF%PCH4FLUX(1:IPROMA)
D1SBVOCFLUX(1:IPROMA,IBL) =GEMSL%PBVOCFLUX(1:IPROMA,1)

! Biomass per vegetation type
D1SVTBIOM(1:IPROMA,:,IBL)     = PDDHS%PDHBIOS(1:IPROMA,:,1)
D1SVTBLOSS(1:IPROMA,:,IBL)    = PDDHS%PDHBIOS(1:IPROMA,:,2)
D1SVTBGAIN(1:IPROMA,:,IBL)    = PDDHS%PDHBIOS(1:IPROMA,:,3) 
D1SVTBIOMSTR(1:IPROMA,:,IBL)  = PDDHS%PDHBIOS(1:IPROMA,:,4)
D1SVTBIOMSTRB(1:IPROMA,:,IBL) = PDDHS%PDHBIOS(1:IPROMA,:,5)
! Biomass per grid
D1SBIOM(1:IPROMA,IBL)    =PSURF%PBIOM(1:IPROMA)
D1SBLOSS(1:IPROMA,IBL)   =PSURF%PBLOSS(1:IPROMA)
D1SBGAIN(1:IPROMA,IBL)   =PSURF%PBGAIN(1:IPROMA)
D1SBIOMSTR(1:IPROMA,IBL) =PSURF%PBIOMSTR(1:IPROMA)
D1SBIOMSTRB(1:IPROMA,IBL)=PSURF%PBIOMSTR2(1:IPROMA)

! LAI per grid
D1SLAI(1:IPROMA,IBL)=PSURF%PLAI(1:IPROMA)

! Variables per vegetation type
D1SVTFR(1:IPROMA,:,IBL)   = PDDHS%PDHVEGS(1:IPROMA,:,1)
D1SVTLAI(1:IPROMA,:,IBL)  = PDDHS%PDHVEGS(1:IPROMA,:,2)
D1SVTGC(1:IPROMA,:,IBL)   = PDDHS%PDHVEGS(1:IPROMA,:,3)
D1SVTGA(1:IPROMA,:,IBL)   = PDDHS%PDHVEGS(1:IPROMA,:,4)
D1SVTF2(1:IPROMA,:,IBL)   = PDDHS%PDHVEGS(1:IPROMA,:,5)
D1SVTDS(1:IPROMA,:,IBL)   = PDDHS%PDHVEGS(1:IPROMA,:,6)
D1SVTDMAX(1:IPROMA,:,IBL) = PDDHS%PDHVEGS(1:IPROMA,:,7)
D1SVTLE(1:IPROMA,:,IBL)   = PDDHS%PDHVEGS(1:IPROMA,:,8)

! Tile values
D1STIFR(1:IPROMA,:,IBL)  = PDDHS%PDHTLS(1:IPROMA,:,1)
D1STITK(1:IPROMA,:,IBL)  = PDDHS%PDHTLS(1:IPROMA,:,2)
D1STIALB(1:IPROMA,:,IBL) = PDDHS%PDHTLS(1:IPROMA,:,3)

!AuxSN
D1SNDEPTH(1:IPROMA,IBL) = PDDHS%PDHSSS(1:IPROMA,1,1)
D1SNFR(1:IPROMA,IBL) = PDDHS%PDHTLS(1:IPROMA,5,1)+PDDHS%PDHTLS(1:IPROMA,7,1)
D1SNTFR(1:IPROMA,IBL) = D1SNFR(1:IPROMA,IBL)*PDDHS%PDHTSS(1:IPROMA,1,2)
D1SNAFR(1:IPROMA,IBL) = D1SNFR(1:IPROMA,IBL)*PDDHS%PDHTSS(1:IPROMA,1,6)
!AuxW
WHERE (PDDHS%PDHTLS(1:IPROMA,3,1) > ZEPSILON )
  D1SWFR(1:IPROMA,IBL) = PDDHS%PDHTLS(1:IPROMA,3,1)/  &
   & MAX(ZEPSILON, 1._JPRB-(PDDHS%PDHTLS(1:IPROMA,5,1)+PDDHS%PDHTLS(1:IPROMA,7,1)))
ELSEWHERE
  D1SWFR(1:IPROMA,IBL) = 0._JPRB
ENDWHERE
D1SWAFR(1:IPROMA,:,IBL) = PDDHS%PDHWLS(1:IPROMA,:,1)-PDDHS%PDHWLS(1:IPROMA,:,2) ! liquid water (kg m-2)
!AuxT
D1SAVTK(1:IPROMA,IBL) = 0.
DO JTILE=1,KTILES
  D1SAVTK(1:IPROMA,IBL)=D1SAVTK(1:IPROMA,IBL)+PDDHS%PDHTLS(1:IPROMA,JTILE,1)*PDDHS%PDHTLS(1:IPROMA,JTILE,2)
ENDDO
D1SVEGTK(1:IPROMA,IBL) = (MAX(ZEPS,PDDHS%PDHTLS(1:IPROMA,4,1))*PDDHS%PDHTLS(1:IPROMA,4, 2)+ &
     &      PDDHS%PDHTLS(1:IPROMA,6,1)*PDDHS%PDHTLS(1:IPROMA,6,2))/  &
     &     (MAX(ZEPS,PDDHS%PDHTLS(1:IPROMA,4,1))+PDDHS%PDHTLS(1:IPROMA,6,1))
D1SGHF(1:IPROMA,IBL) = PDDHS%PDHTTS(1:IPROMA,1,14)
D1SRADTK(1:IPROMA,IBL) = 0. ! not calculated in vdfmain
D1SRADTK(1:IPROMA,IBL) =(PDDHS%PDHTLS(1:IPROMA,1,1)*(PDDHS%PDHTLS(1:IPROMA,1, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,2,1)*(PDDHS%PDHTLS(1:IPROMA,2, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,3,1)*(PDDHS%PDHTLS(1:IPROMA,3, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,4,1)*(PDDHS%PDHTLS(1:IPROMA,4, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,5,1)*(PDDHS%PDHTLS(1:IPROMA,5, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,6,1)*(PDDHS%PDHTLS(1:IPROMA,6, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,7,1)*(PDDHS%PDHTLS(1:IPROMA,7, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,8,1)*(PDDHS%PDHTLS(1:IPROMA,8, 2))**4)**(0.25_JPRB) 
IF (KTILES > 9) THEN
 D1SRADTK(1:IPROMA,IBL) =(PDDHS%PDHTLS(1:IPROMA,1,1)*(PDDHS%PDHTLS(1:IPROMA,1, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,2,1)*(PDDHS%PDHTLS(1:IPROMA,2, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,3,1)*(PDDHS%PDHTLS(1:IPROMA,3, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,4,1)*(PDDHS%PDHTLS(1:IPROMA,4, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,5,1)*(PDDHS%PDHTLS(1:IPROMA,5, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,6,1)*(PDDHS%PDHTLS(1:IPROMA,6, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,7,1)*(PDDHS%PDHTLS(1:IPROMA,7, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,8,1)*(PDDHS%PDHTLS(1:IPROMA,8, 2))**4+ &
     &     PDDHS%PDHTLS(1:IPROMA,10,1)*(PDDHS%PDHTLS(1:IPROMA,10, 2))**4)**(0.25_JPRB)
ENDIF
D1SALB(1:IPROMA,IBL) = PCLIM%PALB(1:IPROMA)
D1SVEGEV(1:IPROMA,IBL) = 0. ! not used
D1SDSH(1:IPROMA,IBL) = 0. ! DelSoilHeat of skin layer (0)
D1STNDH(1:IPROMA,IBL) = PDDHS%PDHTSS(1:IPROMA,1,15)     ! DelColdCont

D1SSDS(1:IPROMA,IBL)=PTSPHY*PSURF%PSNSE1(1:IPROMA,1)
D1SWLDS(1:IPROMA,IBL)=PTSPHY*PSURF%PWLE1(1:IPROMA)
!write(6,*) 'delint',D1SWLDS

! Water budgets
D1SLSRF(1:IPROMA,IBL) =  PFLUX%PFPLSL(1:IPROMA) ! PLSRF(1:IPROMA)
D1SCRF(1:IPROMA,IBL)  =  PFLUX%PFPLCL(1:IPROMA) ! PCRF(1:IPROMA)
D1SLSSF(1:IPROMA,IBL) =  PFLUX%PFPLSN(1:IPROMA) ! PLSSF(1:IPROMA) 
D1SCSF(1:IPROMA,IBL)  =  PFLUX%PFPLCN(1:IPROMA) ! PCSF(1:IPROMA)
D1STE(1:IPROMA,IBL)   =  PFLUX%PDIFTQ(1:IPROMA,KLEV)
D1STSRO(1:IPROMA,IBL) =  PFLUX%PFWRO1(1:IPROMA)
D1STRO(1:IPROMA,IBL)  =  PFLUX%PFWRO1(1:IPROMA) + PFLUX%PFWROD(1:IPROMA)
D1SMLT(1:IPROMA,IBL)  =  PFLUX%PFWMLT(1:IPROMA)

! Screen level 
D1T2M(1:IPROMA,IBL) = PSURF%GSD%PT2M(1:IPROMA)
D1D2M(1:IPROMA,IBL) = PSURF%GSD%PD2M(1:IPROMA)
! forcing (end of timestep)

D1STAIR(1:IPROMA,IBL)  = STATE%PT1(1:IPROMA) ! PTAIR(1:IPROMA)
D1SQAIR(1:IPROMA,IBL)  = STATE%PQ1(1:IPROMA) ! PQAIR(1:IPROMA)
D1SUWIND(1:IPROMA,IBL) = STATE%PU1(1:IPROMA) !PUWIND(1:IPROMA)
D1SVWIND(1:IPROMA,IBL) = STATE%PV1(1:IPROMA) !PVWIND(1:IPROMA)
D1SPSURF(1:IPROMA,IBL) = PPSURF(1:IPROMA,IBL)
! Biogenic VOC emission diagnostics per vegetation type. Check how this is computed!
D1SBVOCST1(1:IPROMA,:,IBL) = PDDHS%PDHBVOCS(1:IPROMA,:,1)
D1SBVOCST2(1:IPROMA,:,IBL) = PDDHS%PDHBVOCS(1:IPROMA,:,2)

END SUBROUTINE UPDDIAG
